### ISSUE TITLE
TSO function is abnormal

### ISSUE THREAD

**Issue by liupf-fj** [F-Stack/f-stack#100]
when set "tso=1" in the conf file, packets larger than MTU are divided into several packets by the network device. the first packet is right, but from the second packet, the 12-byte data is placed in the tcp options field. the client does not consider the data in the options field as payload, so do not send ack to the server.  
packets at [https://pan.baidu.com/s/1i4I8q3b](url)

**Comment by liupf-fj** [comment]
The code in the function “ff_dpdk_if_send" @ file "lib\ff_dpdk_if.c":
<table><tr><td>if (offload.tcp_csum) {</br>
&nbsp;&nbsp;head->ol_flags |= PKT_TX_TCP_CKSUM;</br>
&nbsp;&nbsp;head->l2_len = sizeof(struct ether_hdr);</br>
&nbsp;&nbsp;<b>head->l3_len = sizeof(struct ipv4_hdr);</b></br>
}
if (offload.tso_seg_size) {</br>
&nbsp;&nbsp;head->ol_flags |= PKT_TX_TCP_SEG;</br>
&nbsp;&nbsp;<b>head->l4_len = sizeof(struct tcp_hdr);</b></br>
&nbsp;&nbsp;head->tso_segsz = offload.tso_seg_size;</br>
}</td></tr></table>
<p>“l3_len” and "l4_len" does not calculate the length of the options field.
</p>
Reference the code in the function "ixgbe_tso" @ linux(2.6.32) source code(file "drivers\net\ixgbe\ixgbe_main.c"):
<table><tr><td>/* compute header lengths */</br>
l4len = tcp_hdrlen(skb);</br>
*hdr_len = skb_transport_offset(skb) + l4len;</td></tr></table>

**Comment by whl739** [comment]
Well, this is really a mistake. Thanks for your help. I'll fix it soon.

**Comment by liupf-fj** [comment]
you can reference " f-stack/dpdk/doc/guides/prog_guide/mbuf_lib.rst", line 145~232.
i modified the function "ff_dpdk_if_send" in file "f-stack/lib/ff_dpdk_if.c":
<table><tr><td>
struct ff_tx_offload offload = {0};</br>
ff_mbuf_tx_offload(m, &offload);</br>
<b>unsigned char * pkt_data = ((unsigned char *)rte_pktmbuf_mtod(head, void*)) + 14;  <i>// 14 = dst_mac[6] + src_mac[6] + type[2]; pointer to ip_head</i></br>
unsigned int l3len = (pkt_data[0] & 0x0F) << 2;</b></br>

if (offload.ip_csum) {
&nbsp;&nbsp;head->ol_flags |= PKT_TX_IP_CKSUM <b>| PKT_TX_IPV4</b>;
&nbsp;&nbsp;head->l2_len = sizeof(struct ether_hdr);
<b>//&nbsp;&nbsp;head->l3_len = sizeof(struct ipv4_hdr);
&nbsp;&nbsp;head->l3_len = l3len;</b>
}

if (ctx->hw_features.tx_csum_l4) {
&nbsp;&nbsp;if (offload.tcp_csum) {
&nbsp;&nbsp;&nbsp;&nbsp;head->ol_flags |= PKT_TX_TCP_CKSUM;
&nbsp;&nbsp;&nbsp;&nbsp;head->l2_len = sizeof(struct ether_hdr);
<b>//&nbsp;&nbsp;&nbsp;&nbsp;head->l3_len = sizeof(struct ipv4_hdr);
&nbsp;&nbsp;&nbsp;&nbsp;head->l3_len = l3len;</b>
&nbsp;&nbsp;}

&nbsp;&nbsp;if (offload.tso_seg_size) {
<b>&nbsp;&nbsp;&nbsp;&nbsp;uint16_t tcp_cs = rte_ipv4_phdr_cksum((const struct ipv4_hdr *)pkt_data, PKT_TX_TCP_SEG);
&nbsp;&nbsp;&nbsp;&nbsp;pkt_data += l3len;   <i>// pointer to tcp_head;</i>
&nbsp;&nbsp;&nbsp;&nbsp;pkt_data[17] = (tcp_cs >> 8) & 0xFF;
&nbsp;&nbsp;&nbsp;&nbsp;pkt_data[16] = tcp_cs & 0xFF;</b>

&nbsp;&nbsp;&nbsp;&nbsp;head->ol_flags |= PKT_TX_TCP_SEG;
<b>//&nbsp;&nbsp;&nbsp;&nbsp;head->l4_len = sizeof(struct tcp_hdr);
&nbsp;&nbsp;&nbsp;&nbsp;head->l4_len = pkt_data[12] >> 2;  <i>// (x >> 4) << 2</i></b>
&nbsp;&nbsp;&nbsp;&nbsp;head->tso_segsz = offload.tso_seg_size;
&nbsp;&nbsp;}
&nbsp;&nbsp;...
<i>//i did not deal with "offload.udp_csum"</i>
}</td></tr></table>
then tso function works well.
test: "tso=1", 2 worker_processes, 10G NIC, 50KB HTML file, the bandwidth is about 9.8G.
if "tso=0", the bandwidth is 8.86G.
