### ISSUE TITLE
compile error in kernel 3.10.0-693.5.2.el7.x86_64 from centos 7.2

### ISSUE THREAD

**Issue by liwanfei999** [F-Stack/f-stack#101]
# cat /proc/version 
Linux version 3.10.0-693.5.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Fri Oct 20 20:32:50 UTC 2017

======
[root@VM_0_8_centos dpdk]# cat ./lib/librte_eal/common/include/rte_version.h 

#define RTE_VER_PREFIX "DPDK"

/**
 * Major version/year number i.e. the yy in yy.mm.z
 */
#define RTE_VER_YEAR 16

/**
 * Minor version/month number i.e. the mm in yy.mm.z
 */
#define RTE_VER_MONTH 7

/**
 * Patch level number i.e. the z in yy.mm.z
 */
#define RTE_VER_MINOR 2

======
PROBLEM:

 cat /usr/src/kernels/3.10.0-693.5.2.el7.x86_64/include/linux/rtnetlink.h

extern int ndo_dflt_bridge_getlink(struct sk_buff *skb, u32 pid, u32 seq,
				   struct net_device *dev, u16 mode,
				   u32 flags, u32 mask, int nlflags,
				   u32 filter_mask,
				   int (*vlan_fill)(struct sk_buff *skb,
						    struct net_device *dev,
						    u32 filter_mask));

======

/data/f-stack/dpdk/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c: In function ‘igb_ndo_bridge_getlink’:
/data/f-stack/dpdk/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c:2287:2: error: too few arguments to function ‘ndo_dflt_bridge_getlink’
  return ndo_dflt_bridge_getlink(skb, pid, seq, dev, mode, 0, 0, nlflags);
  ^
In file included from /usr/src/kernels/3.10.0-693.5.2.el7.x86_64/include/net/dst.h:13:0,
                 from /usr/src/kernels/3.10.0-693.5.2.el7.x86_64/include/net/sock.h:72,
                 from /usr/src/kernels/3.10.0-693.5.2.el7.x86_64/include/linux/tcp.h:23,
                 from /data/f-stack/dpdk/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c:34:
/usr/src/kernels/3.10.0-693.5.2.el7.x86_64/include/linux/rtnetlink.h:115:12: note: declared here
 extern int ndo_dflt_bridge_getlink(struct sk_buff *skb, u32 pid, u32 seq,
            ^
/data/f-stack/dpdk/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c: At top level:
/data/f-stack/dpdk/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c:2316:2: error: unknown field ‘ndo_set_vf_vlan’ specified in initializer
  .ndo_set_vf_vlan = igb_ndo_set_vf_vlan,
  ^
/data/f-stack/dpdk/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c: In function ‘igb_ndo_bridge_getlink’:
/data/f-stack/dpdk/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.c:2295:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
make[10]: *** [/data/f-stack/dpdk/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni/igb_main.o] Error 1
make[9]: *** [_module_/data/f-stack/dpdk/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/kni] Error 2

**Comment by whl739** [comment]
This dpdk version(16.07) is not suitable for centos 7.2+, related to #91 .
I'll upgrade dpdk to newer version in the future.
But for now you can just use a recent dpdk version(16.11+),  compile it and `export FF_DPDK=/your/dpdk/build/path`, then compile f-stack.

**Comment by helloworld77** [comment]
I recommend to install the correct kernel packages by this: yum install "kernel-devel-uname-r == $(uname -r)”

**Comment by Winters123** [comment]
I met the same problem while compiling dpdk-17.08 on CentOS 7.  Still have no idea how to deal with it.

**Comment by whl739** [comment]
Just google it.

**Comment by Winters123** [comment]
Thx, I solved it by update the kernel version with a newer one.

**Comment by liwanfei999** [comment]
Thanks a lot.
