### ISSUE TITLE
ipfw: don't call ff_ipc_init function

### ISSUE THREAD

**Issue by tigerjibo** [F-Stack/f-stack#102]
Hi :
  In tools/ipfw/main.c file. Don't call the **ff_ipc_init** in main function?
  when use the fstack, we must use the ff_ipc_init function initailization.

**Comment by whl739** [comment]
`ff_ipc_init` will be called automatically if it hasn't been initialized.
But call `ff_ipc_init` in main before any other mallocs is more safer than automatical.
See [this commit](https://github.com/F-Stack/f-stack/commit/85eb2ae96a9269e6e5f3f92b072a1717d8a76eee).
I'll fix it later.

**Comment by tigerjibo** [comment]
OK. I get it.
