### ISSUE TITLE
ff_connect not work

### ISSUE THREAD

**Issue by qiuyi21** [F-Stack/f-stack#104]
Edit file f-stack/example/main.c with following code:
`#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include "ff_api.h"

int main(int argc, char * argv[]) {
    ff_init(argc, argv);

    int sockfd = ff_socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    printf("sockfd:%d\n", sockfd);
    if (sockfd < 0) {
        printf("ff_socket failed\n");
        exit(1);
    }

    struct sockaddr_in my_addr;
    bzero(&my_addr, sizeof(my_addr));
    my_addr.sin_family = AF_INET;
    my_addr.sin_port = htons(80);
    my_addr.sin_addr.s_addr = inet_addr("10.0.0.2");

    if (ff_connect(sockfd, (struct linux_sockaddr *)&my_addr, sizeof(my_addr)) == -1) {
        perror("ff_connect failed");
        exit(1);
    } else {
        printf("ff_connect OK\n");
    }

    return 0;
}`

`make` it and run `./helloworld --conf f-stack.conf --proc-type=primary --proc-id=0` will failed always: Operation not permitted

Why ff_connect doesn't work correctly?

**Comment by whl739** [comment]
Because f-stack was not running, f-stack is a server-side library, you must call `ff_run` with your callback function. In the callback, you can call `ff_connect`.

**Comment by qiuyi21** [comment]
@whl739
I use these code and the same result: Operation not permitted

`#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <errno.h>
#include "ff_api.h"

int sockfd = -1;

int loop(void *arg) {
    struct sockaddr_in my_addr;
    bzero(&my_addr, sizeof(my_addr));
    my_addr.sin_family = AF_INET;
    my_addr.sin_port = htons(80);
    my_addr.sin_addr.s_addr = inet_addr("10.0.0.2");

    if (ff_connect(sockfd, (struct linux_sockaddr *)&my_addr, sizeof(my_addr)) == -1) {
        printf("ff_connect failed %d: %s\n", errno, strerror(errno));
    } else {
        printf("ff_connect OK\n");
        exit(0);
    }

    return 0;
}

int main(int argc, char * argv[]) {
    ff_init(argc, argv);

    sockfd = ff_socket(AF_INET, SOCK_STREAM, 0);
    printf("sockfd:%d\n", sockfd);
    if (sockfd < 0) {
        printf("ff_socket failed\n");
        exit(1);
    }

    ff_run(loop, NULL);
    return 0;
}`

**Comment by qiuyi21** [comment]
It is very strange, if does not `exit` in `loop`, it will print:

`...

Timecounters tick every 10.000 msec
Timecounter "ff_clock" frequency 100 Hz quality 1
f-stack-0: Ethernet address: 00:1b:51:9b:86:bd
sockfd:1024
ff_connect failed 1: Operation not permitted
ff_connect failed 98: Address already in use
ff_connect failed 98: Address already in use
ff_connect failed 98: Address already in use
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
...`

**Comment by whl739** [comment]
F-Stack runs with polling mode, callback `loop` will be called every loop, it won't exit.
The reason of first error EPERM is that socket is not nonblock. The others are that the address has been binded.

**Comment by qiuyi21** [comment]
@whl739 
Execute `ff_fcntl(sockfd, F_SETFL, ff_fcntl(sockfd, F_GETFL, 0) | O_NONBLOCK)` before ff_connect and still failed always, ff_connect always return -1 and errno isn't EINPROGRESS forever. It is illogical with `man 2 connect` description.

output like:
Timecounters tick every 10.000 msec
Timecounter "ff_clock" frequency 100 Hz quality 1
f-stack-0: Ethernet address: 00:1b:51:9b:86:bd
sockfd:1024
ff_connect failed 1: Operation not permitted
ff_connect failed 98: Address already in use
... (repeat 98)
ff_connect failed 106: Transport endpoint is already connected
... (repeat 106)

**Comment by whl739** [comment]
There's a bug with `ff_fcntl`.  Use `int on = 1;ff_ioctl(sockfd, FIONBIO, &on);` instead.
Related #50 .

**Comment by qiuyi21** [comment]
Thank you very much. It is work.

**Comment by trojanets** [comment]
I use ff_ioctl, but effect same.

**Comment by SUDOsarvesh** [comment]
Hi @qiuyi21 hope you are well!. I am new to F-stack. I am trying to connect my client to F-stack helloworld server, but it is not working can you please explain your client code. I changed my code according to yours (https://github.com/F-Stack/f-stack/issues/104#issuecomment-346313819). In my case I have one more error for **int on = 1;ff_ioctl(sockfd, FIONBIO, &on);** saying FIONBIO not declared.

**Comment by qiuyi21** [comment]
@SUDOsarvesh You need #include <sys/ioctl.h>
