### ISSUE TITLE
Compile error for x86-64 with today's code

### ISSUE THREAD

**Issue by joshli2016** [F-Stack/f-stack#105]
Hi, 

I pulled out the code this afternoon, DPDK and libfstack can be compiled successfully, it looks no compiling error for nginx, but linked failed. I try fo find the root cause:
1. The MACHINE_CPUARCH is x86_64, which is conver to amd64 in kern.pre.mk.
2. Then the code will use freebsd/amd64/include/counter.h
3. Then the counter_u64_zero_inline function calls smp_rendezvous and smp_no_rendevous_barrier, those two functions are defined in freebsd/kern/subr_smp.c, but in lib/Makefile, subr_smp.c is not added to KERN_SRC, that smp_rendezvous and smp_no_rendevous was not defined, nginx was linked failed.

And I trie'd to add subr_smp.c to KERN_SRC in lib/Makefile, but mp_ncpus and mp_maxcpus are redefined in lib/ff_glue.c and subr_smp.c.

Expect your reply, thanks!
Josh

**Comment by whl739** [comment]
See #99 , is it your issue?

**Comment by joshli2016** [comment]
Thanks your response, exactly the same issue with #99

**Comment by joshli2016** [comment]
I got you! Thanks your information.
