### ISSUE TITLE
ff_socketpair don't work

### ISSUE THREAD

**Issue by git-littlezhou** [F-Stack/f-stack#106]
why ff_socketpair(AF_UNIX, SOCK_STREAM, 0, fd) return “Address family not supported by protocol”？I make some mistakes？

**Comment by whl739** [comment]
F-Stack doesn't support AF_UNIX. `ff_socketpair` couldn't work and should be removed.

**Comment by git-littlezhou** [comment]
Ok，thank you. And is there any other methods to implement function like socketpair or pipe？I need to notify epoll like what libevent does

**Comment by whl739** [comment]
Create a new thread, use epoll to wait events, just like what we do in nginx-fstack.

**Comment by whl739** [comment]
`ngx_channel` is created by the orginal `socketpair` in master, and forked to worker, we just create a thread and use epoll to wait channel events in worker. The main thread in worker handles network IO events with F-Stack library.

**Comment by git-littlezhou** [comment]
I want to make libevent support f-stack，because my project is based on libevent，i change libevent's epoll to ff_epoll，but libevent use pipe or socketpait to wake up epoll to implement some notification internally，orginal socketpair or pipe can not use ff_epoll.

**Comment by whl739** [comment]
`ff_epoll` only supports network IO events, it couldn't handle `pipe`/`unix domain` events.
You can only create another thread to use original `epoll` to handle these events.

**Comment by git-littlezhou** [comment]
Yes, i know, thank you very much. I'll think about some other ways.
