### ISSUE TITLE
Multi thread problem

### ISSUE THREAD

**Issue by zER0pAGe-1** [F-Stack/f-stack#110]
Hi,
I have an epoll loop working as the main thread using `ff_run()`, and another thread working as the control thread. The control thread runs on a separate CPU and is responsible for adding new event listener to the loop using `ff_epoll_ctl()`.
However, the call of `ff_epoll_ctl` always results in segment fault.
So how does F-stack work in multi-thread mode?

**Comment by whl739** [comment]
The f-stack environment is only initialized in main thread, so you couldn't use `ff_api` in the other threads, and network IO event can only be handled by main thread.
The control thread can use the real `epoll` to handle other events, for example pipe/unix domain socket.
