### ISSUE TITLE
Can't run multiple process on VM

### ISSUE THREAD

**Issue by qiuyi21** [F-Stack/f-stack#113]
I use version at 48b700b73c4ae5df29b8b0c7c7bf4e00f849da50.

I follow [Launch_F-Stack_on_AWS_EC2_in_one_minute](https://github.com/F-Stack/f-stack/blob/master/doc/Launch_F-Stack_on_AWS_EC2_in_one_minute.md), it is OK when using one Nginx process, then I configure `lcore_mask=1E` in `f-stack.conf` use 4 cores, `worker_processes 4` in `nginx.conf` use 4 workers. When I start nginx, it is just print `KNI: Creating kni...` repeatedly, no veth0 appear. What is the problem?

**Comment by whl739** [comment]
Plz paste the `f-stack.conf` and startup log.
And the hardware information, such as cpus, nics.

**Comment by qiuyi21** [comment]
Thank you for reply. I already know what the problem is. Virtual network interface need to enable multiqueue.
