### ISSUE TITLE
ff_kevent is non-blocking?

### ISSUE THREAD

**Issue by shockx2** [F-Stack/f-stack#116]
Hi f-stack team,
I'm trying helloworld and making simple UDP server.
I wonder the ff_kevents is always non-blocking? 
Can I make the ff_kevents blocking?
Thank you

**Comment by whl739** [comment]
No, you couldn't use blocking sockets, it will cause errors.

**Comment by shockx2** [comment]
Original freebsd kevents is blocking with timeout or not(infinitely), isn't it?
But, ff_kevents is always non-blocking, you mentioned.
in ff_kevent_do_each at ff_syscall_wrapper.c
struct timespec ts:
ts.tv_sec = 0;
ts.tv_nsec = 0;
I think that code is making non-blocking, right?

I think that there are some config for blocking but it is not possible.
Do you have any plan to support blocking with timeout?
Thank you

**Comment by whl739** [comment]
F-Stack is running on polling mode with single thread, so it coudn't be blocked.
And interrupt mode is in our roadmap, but it's not in the near future.

**Comment by shockx2** [comment]
Thank you
