### ISSUE TITLE
f-stack can build and run on Ali ECS or Tecent CVM ？ 

### ISSUE THREAD

**Issue by codecat007** [F-Stack/f-stack#118]
Hi
I have a cloud service, I want to ask if f-stack can build and run on  Ali ECS or Tecent CVM ？ 
Thanks

**Comment by whl739** [comment]
Yes. See this [doc](https://github.com/F-Stack/f-stack/blob/master/doc/Launch_F-Stack_on_AWS_EC2_in_one_minute.md).
