### ISSUE TITLE
ipfw: setsockopt(IP_FW_XDEL): Operation not supported

### ISSUE THREAD

**Issue by TimeYang** [F-Stack/f-stack#120]
Hi f-stack teams:
Error, when use ipfw tools in CentOS, The nginx is running.
Is it a problem of configuration?

##Steps to reproduce
[root@localhost ipfw]# ./ipfw -q -f flush
ipfw: setsockopt(IP_FW_XDEL): Operation not supported
[root@localhost ipfw]# ./ipfw list
ipfw: retrieving config failed: Operation not supported

**Comment by whl739** [comment]
`ipfw` is not enabled by default, modify lib/Makefile and recompile.
```
diff --git a/lib/Makefile b/lib/Makefile
index be1e91b..aa4e841 100644
--- a/lib/Makefile
+++ b/lib/Makefile
@@ -18,7 +18,7 @@ X86_INCLUDES=0
 HOST_OS:=$(shell uname -s)
 #DEBUG=-O0 -gdwarf-2 -g3
 #FF_NETGRAPH=1
-#FF_IPFW=1
+FF_IPFW=1

 ifeq ($(FF_DPDK),)
     FF_DPDK=${TOPDIR}/dpdk/x86_64-native-linuxapp-gcc

```

**Comment by TimeYang** [comment]
It works great!
Thank you!
