### ISSUE TITLE
ipfw: mac filtering is not supported?

### ISSUE THREAD

**Issue by TimeYang** [F-Stack/f-stack#121]
MAC address filtering is invalid.
Using FreeBSD test is ok, it must be set to "sysctl net.link.ehter.ipfw=1"
So I modify /data/f-stack/config.ini: 
net.link.ether.ipfw=1

I recompiled, still the same problem.

--------------------
F-Stack address: 192.168.1.2 00:0c:29:24:a8:e3
Host address: 192.168.1.3 2c:56:dc:94:23:45
/usr/local/etc/ipfw.rules:
IPF="/data/f-stack/tools/ipfw/ipfw -q add"
/data/f-stack/tools/ipfw/ipfw -q -f flush

#loopback
$IPF 10 allow all from any to any via lo0
$IPF 20 deny all from any to 127.0.0.0/8
$IPF 30 deny all from 127.0.0.0/8 to any

$IPF 50 check-state
$IPF 60 allow tcp from any to any established
$IPF 70 allow all from any to any out keep-state
$IPF 80 allow icmp from any to any

$IPF 300 allow ip from any to any MAC any 2c:56:dc:94:23:45
$IPF 310 allow ip from any to any MAC 00:0c:29:24:a8:e3 any
$IPF 400 deny all from any to any

$IPF 500 deny log all from any to any
$IPF 65534 deny all from any to any

**Comment by whl739** [comment]
> MAC address filtering is invalid.

What's your expect behavior and what's the actual behavior ?

**Comment by TimeYang** [comment]
The host (address: 192.168.1.3 2c:56:dc:94:23:45) can ping  192.168.1.2, but it's failed

**Comment by whl739** [comment]
I just tested it, it could work.

f-stack: 192.168.1.2  00:1b:21:ba:81:b4
host:  192.168.1.1  00:1b:21:ba:7f:8c

f-stack ipfw configurations:
```
$ ./ipfw/ipfw  list
00010 allow ip from any to any via lo0
00020 deny ip from any to 127.0.0.0/8
00030 deny ip from 127.0.0.0/8 to any
00050 check-state
00060 allow tcp from any to any established
00070 allow ip from any to any out keep-state
00080 allow icmp from any to any
00300 allow ip from any to any MAC any 00:1b:21:ba:7f:8c
00310 allow ip from any to any MAC 00:1b:21:ba:81:b4 any
00400 deny ip from any to any
00500 deny log ip from any to any
65534 deny ip from any to any
65535 allow ip from any to any
```
and ping from host:
```
$ ping 192.168.1.2
PING 192.168.1.2 (192.168.1.2) 56(84) bytes of data.
64 bytes from 192.168.1.2: icmp_seq=1 ttl=64 time=0.158 ms
64 bytes from 192.168.1.2: icmp_seq=2 ttl=64 time=0.125 ms
64 bytes from 192.168.1.2: icmp_seq=3 ttl=64 time=0.185 ms
64 bytes from 192.168.1.2: icmp_seq=4 ttl=64 time=0.186 ms
```

**Comment by TimeYang** [comment]
oh sorry, need delete a rule:
0080 allow icmp from any to any

or modify：
#$IPF 80 allow icmp from any to any

you can try it again

**Comment by whl739** [comment]
I traced it, and found where packets are dropped.

When enable `net.link.ether.ipfw`, the pfil hook `ipfw_check_frame` will be called in `ether_input` and `ifpw_check_packet` will be called in `ip_input` after ether header is stripped. This means the ipfw rules will be checked twice.

In `ether_input`, packets were accepted by rule `00300 allow ip from any to any MAC any 00:1b:21:ba:7f:8c`, and in `ip_input`, packets were dropped by rule `00400 deny ip from any to any`.

Maybe the rules are unreasonable.
So i add rule `00320 allow icmp from any to any`, it works fine.
