### ISSUE TITLE
ipfw: running error

### ISSUE THREAD

**Issue by NicoSpec** [F-Stack/f-stack#122]
PANIC in rte_eal_config_reattach():
Cannot mmap memory for rte_config
7: [./ipfw() [0x40419d]]
6: [/lib64/libc.so.6(__libc_start_main+0xf5) [0x7ffff6d2ab15]]
5: [./ipfw() [0x412a48]]
4: [./ipfw() [0x419792]]
3: [./ipfw() [0x42445d]]
2: [./ipfw() [0x403eb6]]
1: [./ipfw() [0x42b3aa]]
Aborted

This is my environment config:
export RTE_SDK=/root/f-stack/dpdk
export RTE_TARGET=x86_64-native-linuxapp-gcc
export DESTDIR=/root/f-stack/dpdk
export FF_PATH=/root/f-stack
export FF_DPDK=/root/f-stack/dpdk/x86_64-native-linuxapp-gcc

**Comment by whl739** [comment]
`echo 0 > /proc/sys/kernel/randomize_va_space`

**Comment by NicoSpec** [comment]
Thank you!
I have solved this problem, because dpdk environment variables lead to the running error.
