### ISSUE TITLE
f-stack tools runing errors

### ISSUE THREAD

**Issue by Apollsun** [F-Stack/f-stack#123]
hi,f-stack team!
I setup f-stack with f-stack's Quick Start,but when I runing ifconfig,ipfw ect.These tools apeared similar errors.
For example:
./arp 
PANIC in rte_eal_config_attach():
Cannot open '/var/run/.rte_config' for rte_mem_config
7: [./arp() [0x4037ed]]
6: [/lib64/libc.so.6(__libc_start_main+0xf5) [0x7ffff6d2ab15]]
5: [./arp() [0x4038d9]]
4: [./arp() [0x4057fe]]
3: [./arp() [0x410470]]
2: [./arp() [0x403506]]
1: [./arp() [0x41741a]]
Aborted

**Comment by whl739** [comment]
Is any f-stack process running?

**Comment by Apollsun** [comment]
Yean,you are right,but I only use ipfw's nat to replace linux's iptables fowarding package.
Need I also start a process that is not necessary?

**Comment by whl739** [comment]
Yes, because f-stack is only a library, you still need to link it to a program.
But it is very easy to use, for your case, just  like this:

main.c
```
#include "ff_api.h"
int main(int argc, char * argv[])
{
    int ret = ff_init(argc, argv);
    assert(ret == 0);
    ff_run(NULL, NULL);
    return 0;
}
```
and refer `example/Makefile` to compile it.

You can use `start.sh` to run it, or do it yourself:
```
./app --conf=config.ini --proc-type=primary --proc-id=0
./app --conf=config.ini --proc-type=secondary --proc-id=1
./app --conf=config.ini --proc-type=secondary --proc-id=2
....
```
note that, the number of processes should be equal to the lcore count of `dpdk.lcore_mask` in config.ini.

**Comment by Apollsun** [comment]
Yea,I know.f-stack tools depend on ff_init and ff_run initializing f-stack.
Thank you for your kind reply.

**Comment by whl739** [comment]
We didn't test nat before, if you have any issue about nat, let me know.

**Comment by Apollsun** [comment]
OK
