### ISSUE TITLE
ipfw: getsockopt(IP_FW_XADD): Operation not supported

### ISSUE THREAD

**Issue by NicoSpec** [F-Stack/f-stack#126]
hi.
when I setup ipfw rules appearing erros.I have modified lib/Makefile with "FF_IPFW=1" and nginx is runing.
Need I modified other configure files?

**Comment by whl739** [comment]
Is nginx re-compiled?

**Comment by NicoSpec** [comment]
Yes,I have re-compiled nginx.

**Comment by whl739** [comment]
It doesn't make sense.
It's best to clean all, re-compile, and install again.

**Comment by NicoSpec** [comment]
I tried to clean all,re-compled ,now I have resolved the problem.
thank you!
