### ISSUE TITLE
How to improve f-stack/nginx concurrency?

### ISSUE THREAD

**Issue by NicoSpec** [F-Stack/f-stack#128]
When I used wrk to test nginx, there is nothing wrong with the concurrency of 1024.
there are a lot of errors when the concurrency is over 50000, and the performance is reduced.
Does f-stack/nginx not support high concurrency?

This is my configuration files.
[dpdk]

lcore_mask=ff
channel=4
promiscuous=1
numa_on=1

tso=0

vlan_strip=1

port_list=0

[port0]
addr=10.16.20.16
netmask=255.255.255.0
broadcast=10.16.20.255
gateway=10.16.20.254

[freebsd.boot]
hz=100

fd_reserve=1024

kern.ipc.maxsockets=262144

net.inet.tcp.syncache.hashsize=65536
net.inet.tcp.syncache.bucketlimit=1000

net.inet.tcp.tcbhashsize=786432

[freebsd.sysctl]
kern.ipc.somaxconn=65536
kern.ipc.maxsockbuf=16777216

net.link.ether.inet.maxhold=5

net.inet.tcp.fast_finwait2_recycle=1
net.inet.tcp.sendspace=65536
net.inet.tcp.recvspace=65536
net.inet.tcp.nolocaltimewait=1
net.inet.tcp.cc.algorithm=cubic
net.inet.tcp.sendbuf_max=167772160
net.inet.tcp.recvbuf_max=167772160
net.inet.tcp.sendbuf_auto=1
net.inet.tcp.recvbuf_auto=1
net.inet.tcp.sendbuf_inc=524288
net.inet.tcp.recvbuf_inc=524288
net.inet.tcp.sack.enable=1
net.inet.tcp.blackhole=1
net.inet.tcp.msl=2000
net.inet.tcp.delayed_ack=0

net.inet.udp.blackhole=1
net.inet.ip.redirect=0

**Comment by whl739** [comment]
1.What tool do you use to test?
2.Paste the `nginx.conf`.
3."there are a lot of errors when the concurrency is over 50000", where did errors come from? nginx error log or the test client?
4.You can use `tools/top` to see  the real cpu usage.

**Comment by NicoSpec** [comment]
1.The test tool is wrk
2.errors comes form wrk,apearring timeout errors and connection errors.
For example:
./wrk -c50000 -t20 -d30s http://10.16.20.16
Running 30s test @ http://10.16.20.16
  20 threads and 50000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    79.56ms  197.78ms   2.00s    90.15%
    Req/Sec    14.23k     6.43k   88.57k    83.25%
  5629614 requests in 30.12s, 1.23GB read
  Socket errors: connect 25187, read 0, write 0, timeout 30606
Requests/sec: 186900.31
Transfer/sec:     41.88MB

3.cpu usage is normal

This is my nginx conf:

user  root;
worker_processes  8;
fstack_conf f-stack.conf;
events {
    worker_connections  102400;
    use kqueue;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        off;
    keepalive_timeout  65;
    server {
        listen       80;
        server_name  localhost;
        access_log /dev/null;
        location / {
            root   html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }




}

**Comment by whl739** [comment]
This probably because of the port limit of client.
`cat /proc/sys/net/ipv4/ip_local_port_range`, in my case, it's '32768   61000', it means the client can only establish at most 28232 connections, and also harm performance.
You'd better use multiple clients to test.

**Comment by NicoSpec** [comment]
Yea,I modified /proc/sys/net/ipv4/ip_local_port_range.Now there is not connection errors when we used wrk to test f-stack/nginx,and nginx also has no error log.
By the way,how much is the default concurrency limit for f-stack/nginx , because my colleague uses tsung as a test tool, when concurrent 50,000 will appear a lot of error.I doesn't understand why appearing the result.And using tsung to test Linux-based nginx, the same amount of concurrency don't have a lot of erros.
This is tsung testing reports(f-stack):
![default](https://user-images.githubusercontent.com/19813367/34436168-148a36d6-ecce-11e7-84ec-86a7eb09b82e.png)
![default](https://user-images.githubusercontent.com/19813367/34436176-22f49d38-ecce-11e7-8a98-336d32a2a220.png)

**Comment by whl739** [comment]
F-Stack itself doesn't have a limit, the limit is cpu/memory, and you can tuning the performance by `tools/sysctl`.
It seems you still use one test client, i recomend you use multiple clients.

**Comment by NicoSpec** [comment]
Tsung is a distributed test tools.We test a total of 5000 concurrent.
I know how to tune the performance.Thank you very much.
