### ISSUE TITLE
compile method error

### ISSUE THREAD

**Issue by aguaiyoung** [F-Stack/f-stack#13]
in README.md just like as
# Compile F-Stack
cd ../../lib/
make
export FF_PATH=/data/f-stack
export FF_DPDK=/data/f-stack/dpdk/x86_64-native-linuxapp-gcc
I think compile like this:
# Compile F-Stack
cd ../../lib/
export FF_PATH=/data/f-stack
export FF_DPDK=/data/f-stack/dpdk/x86_64-native-linuxapp-gcc
make

**Comment by aguaiyoung** [comment]
make 
cc -c -O2 -fno-strict-aliasing -frename-registers -pipe -Wno-maybe-uninitialized   -std=c99  -Wall -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wno-inline -Wcast-qual -Wno-pointer-sign -Wmissing-include-dirs -fdiagnostics-show-option -Wno-unused-but-set-variable -fno-common -finline-limit=8000 --param inline-unit-growth=100 --param large-function-growth=1000  -DFSTACK  -fstack-protector -D__FreeBSD__ -D_KERNEL -DHAVE_KERNEL_OPTION_HEADERS -include opt_global.h -fno-builtin -I/home/work/code/f-stack/lib/include -undef -imacros filtered_predefined_macros.h -nostdinc  -I. -I/home/work/code/f-stack/lib/../freebsd -I./machine_include -I./opt -Werror -Wno-unused-variable  ff_glue.c
cc1: warnings being treated as errors
In file included from ff_glue.c:50:
/home/work/code/f-stack/lib/../freebsd/sys/buf.h:130: 错误：没有声明任何东西
/home/work/code/f-stack/lib/../freebsd/sys/buf.h:131: 错误：没有声明任何东西
In file included from ff_glue.c:53:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:192: 错误：没有声明任何东西
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:219: 错误：没有声明任何东西
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:224: 错误：没有声明任何东西
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:246: 错误：没有声明任何东西
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:247: 错误：没有声明任何东西
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:249: 错误：没有声明任何东西
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘m_extaddref’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:659: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:660: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:661: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:662: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:663: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:664: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:665: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:666: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:667: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘m_init’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:709: 错误：‘struct mbuf’没有名为‘m_next’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:710: 错误：‘struct mbuf’没有名为‘m_nextpkt’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:711: 错误：‘struct mbuf’没有名为‘m_dat’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘m_cljset’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:793: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:794: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:794: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:794: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:795: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:796: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:797: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:798: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘m_clrprotoflags’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:816: 错误：‘struct mbuf’没有名为‘m_next’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘m_last’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:824: 错误：‘struct mbuf’没有名为‘m_next’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:825: 错误：‘struct mbuf’没有名为‘m_next’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘m_extrefcnt’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:835: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:835: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:836: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘m_align’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:914: 错误：‘struct mbuf’没有名为‘m_ext’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:914: 错误：‘struct mbuf’没有名为‘m_pktdat’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:914: 错误：‘struct mbuf’没有名为‘m_dat’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘m_tag_init’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1087: 错误：‘struct mbuf’没有名为‘m_pkthdr’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘m_tag_first’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1122: 错误：‘struct mbuf’没有名为‘m_pkthdr’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘m_tag_prepend’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1142: 错误：‘struct mbuf’没有名为‘m_pkthdr’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1142: 错误：‘struct mbuf’没有名为‘m_pkthdr’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘m_tag_unlink’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1152: 错误：‘struct mbuf’没有名为‘m_pkthdr’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1152: 错误：‘struct mbuf’没有名为‘m_pkthdr’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1152: 错误：‘struct mbuf’没有名为‘m_pkthdr’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1152: 错误：‘struct mbuf’没有名为‘m_pkthdr’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘m_tag_find’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1167: 错误：‘struct mbuf’没有名为‘m_pkthdr’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘m_free’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1174: 错误：‘struct mbuf’没有名为‘m_next’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘rt_m_getfib’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1190: 错误：‘struct mbuf’没有名为‘m_pkthdr’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘mbufq_drain’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1249: 错误：‘struct mbuf’没有名为‘m_stailqpkt’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘mbufq_last’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1265: 错误：‘struct mbuf’没有名为‘m_stailqpkt’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1265: 错误：在‘__x’的声明中，类型默认为‘int’
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1265: 错误：从不兼容的指针类型初始化
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1265: 错误：‘struct mbuf’没有名为‘m_stailqpkt’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘mbufq_enqueue’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1288: 错误：‘struct mbuf’没有名为‘m_stailqpkt’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1288: 错误：‘struct mbuf’没有名为‘m_stailqpkt’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘mbufq_dequeue’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1300: 错误：‘struct mbuf’没有名为‘m_stailqpkt’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1301: 错误：‘struct mbuf’没有名为‘m_nextpkt’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h: 在函数‘mbufq_prepend’中:
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1311: 错误：‘struct mbuf’没有名为‘m_stailqpkt’的成员
/home/work/code/f-stack/lib/../freebsd/sys/mbuf.h:1311: 错误：‘struct mbuf’没有名为‘m_stailqpkt’的成员
在文件层：
cc1: 错误：无法识别的命令行选项“-Wno-maybe-uninitialized”
make: *** [ff_glue.o] 错误 1

 gcc -v
使用内建 specs。
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC)

**Comment by whl739** [comment]
For question 1:
The two `export` commands are used for apps.
But if you has another dpdk dirictory, `export FF_DPDK` command can be excuted first, because in lib/Makefile:
`ifeq ($(FF_DPDK),)`
`FF_DPDK=${TOPDIR}/dpdk/x86_64-native-linuxapp-gcc`
`endif`
Overall, `export` commands are better excuted first. I'll update the README.

For question 2:
Upgrade gcc to 4.5+.

**Comment by aguaiyoung** [comment]
ok ,3q！
f-stack maybe add some requirement like as hardware and software configuration like as:
hardware configuration:
CPUs - As much as you need. SeaStar is highly friendly for multi-core and NUMA
NICs - As fast as possible, we recommend 10G or 40G cards. It's possible to use 1G too but you may be limited by their capacity. In addition, the more hardware queue per cpu the better for SeaStar. 
software configuration:
gcc --version 
uio
 gawk

**Comment by whl739** [comment]
Thank you for your feedback. It's very useful.I'll add a requirement doc.
