### ISSUE TITLE
Nginx Integration error

### ISSUE THREAD

**Issue by arjitAgarwal** [F-Stack/f-stack#130]
I have added your changes that you did for nginx 1.11.10 in latest version of nginx 
Its compiling fine but while running make its showing following error on running make.

/usr/bin/ld: /data/f-stack/lib/libfstack.a(libfstack.ro): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/data/f-stack/lib/libfstack.a(libfstack.ro): error adding symbols: Bad value
collect2: error: ld returned 1 exit status
objs/Makefile:379: recipe for target 'objs/nginx' failed

**Comment by whl739** [comment]
Did you compile f-stack to a shared library?
Refer to #84.

**Comment by arjitAgarwal** [comment]
I made the following changes to the Makefile
#ar -cqs $@ $*.ro ${HOST_OBJS}
${CC} -shared -o libfstack.so $*.ro -fPIC ${HOST_OBJS}

on compiling fstack now i am getting
export CONF_CFLAGS=-fPIC
make



ld -d -r -o libfstack.ro  ff_compat.o ff_glue.o ff_freebsd_init.o ff_init_main.o ff_kern_condvar.o ff_kern_environment.o ff_kern_intr.o ff_kern_subr.o ff_kern_synch.o ff_kern_timeout.o ff_lock.o ff_syscall_wrapper.o ff_subr_prf.o ff_vfs_ops.o ff_veth.o ff_route.o sha1.o siphash.o kern_descrip.o kern_event.o kern_fail.o kern_khelp.o kern_hhook.o kern_linker.o kern_mbuf.o kern_module.o kern_mtxpool.o kern_ntptime.o kern_osd.o kern_sysctl.o kern_tc.o kern_uuid.o link_elf.o md5c.o subr_capability.o subr_counter.o subr_eventhandler.o subr_kobj.o subr_lock.o subr_module.o subr_param.o subr_pcpu.o subr_sbuf.o subr_taskqueue.o subr_unit.o sys_capability.o sys_generic.o sys_socket.o uipc_accf.o uipc_mbuf.o uipc_mbuf2.o uipc_domain.o uipc_sockbuf.o uipc_socket.o uipc_syscalls.o bcd.o crc32.o inet_ntoa.o jenkins_hash.o strlcpy.o strnlen.o zlib.o in_cksum.o linker_if.o cryptodev_if.o bpf.o bridgestp.o if.o if_bridge.o if_clone.o if_dead.o if_ethersubr.o if_loop.o if_llatbl.o if_media.o if_spppfr.o if_spppsubr.o if_vlan.o if_vxlan.o in_fib.o in_gif.o ip_reass.o netisr.o pfil.o radix.o raw_cb.o raw_usrreq.o route.o rtsock.o slcompress.o if_ether.o if_gif.o igmp.o in.o in_mcast.o in_pcb.o in_proto.o in_rmx.o ip_carp.o ip_ecn.o ip_encap.o ip_fastfwd.o ip_icmp.o ip_id.o ip_input.o ip_mroute.o ip_options.o ip_output.o raw_ip.o tcp_debug.o tcp_fastopen.o tcp_hostcache.o tcp_input.o tcp_lro.o tcp_offload.o tcp_output.o tcp_reass.o tcp_sack.o tcp_subr.o tcp_syncache.o tcp_timer.o tcp_timewait.o tcp_usrreq.o udp_usrreq.o cc.o cc_newreno.o cc_htcp.o cc_cubic.o alias.o alias_db.o alias_mod.o alias_proxy.o alias_sctp.o alias_util.o uma_core.o
nm libfstack.ro  | grep -v ' U ' | cut -d ' ' -f 3 > libfstack_localize_list.tmp
objcopy --localize-symbols=libfstack_localize_list.tmp libfstack.ro 
rm libfstack_localize_list.tmp
objcopy --globalize-symbols=ff_api.symlist libfstack.ro
rm -f libfstack.a
#ar -cqs libfstack.a libfstack.ro ff_host_interface.o ff_config.o ff_ini_parser.o ff_dpdk_if.o ff_dpdk_kni.o ff_dpdk_pcap.o ff_epoll.o ff_init.o
cc -shared -o libfstack.so libfstack.ro -fPIC ff_host_interface.o ff_config.o ff_ini_parser.o ff_dpdk_if.o ff_dpdk_kni.o ff_dpdk_pcap.o ff_epoll.o ff_init.o
/usr/bin/ld: libfstack.ro: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
libfstack.ro: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:483: recipe for target 'libfstack.a' failed
make: *** [libfstack.a] Error 1

**Comment by whl739** [comment]
Did you do `make clean`?

**Comment by arjitAgarwal** [comment]
Yes I did make clean then run make again and got the same issue in the end.

**Comment by whl739** [comment]
I just tested it, it could be compiled.
Do you make sure all `cc` commands have `-fPIC`?
And the last command is `${CC} -shared -o libfstack.so $*.ro -fPIC ${HOST_OBJS}`.

**Comment by arjitAgarwal** [comment]
Did you also compiled dpdk with fPIC flag?
Yes I have run "export CONF_CFLAGS=-fPIC" which before make.
Which cc comands are you refering to ??

**Comment by whl739** [comment]
I didn't compile dpdk to a shared library.
It's my output:
```
cc -c -O2 -Wall -Werror
-include /root/f-stack/lib/../dpdk/x86_64-native-linuxapp-gcc/include/rte_config.h
-march=native -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2
-DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3
-DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2
-DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,
RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2
-I/root/f-stack/lib/../dpdk/x86_64-native-linuxapp-gcc/include
-fPIC -DFF_IPFW -I. -Werror -Wno-unused-variable  ff_host_interface.c
```

**Comment by arjitAgarwal** [comment]
If am running make it is showing no compilation errors while running with sudo make I am getting the same above error.

When I compiled with just make without sudo  and then when I am compiling my nginx i am getting a diffrent error:-
/usr/bin/ld: /data/f-stack/dpdk/x86_64-native-linuxapp-gcc/lib/librte_pmd_vmxnet3_uio.a(vmxnet3_rxtx.o): relocation R_X86_64_32S against `rte_mempool_ops_table' can not be used when making a shared object; recompile with -fPIC
/data/f-stack/dpdk/x86_64-native-linuxapp-gcc/lib/librte_pmd_vmxnet3_uio.a(vmxnet3_rxtx.o): error adding symbols: Bad value
collect2: error: ld returned 1 exit status
objs/Makefile:382: recipe for target 'objs/nginx' failed

**Comment by whl739** [comment]
I just tested nginx, and also got no errors.
I have no idea with your issue.
All my changes are
```
diff --git a/lib/Makefile b/lib/Makefile
index 4f35cf0..79a8e25 100644
--- a/lib/Makefile
+++ b/lib/Makefile
@@ -382,7 +382,8 @@ libfstack.a: machine_includes ff_api.symlist ${MHEADERS} ${MSRCS} ${HOST_OBJS} $
        rm $*_localize_list.tmp
        objcopy --globalize-symbols=ff_api.symlist $*.ro
        rm -f $@
-       ar -cqs $@ $*.ro ${HOST_OBJS}
+       #ar -cqs $@ $*.ro ${HOST_OBJS}
+       ${CC} -shared -o libfstack.so $*.ro -fPIC ${HOST_OBJS}
        rm -f $*.ro
```
and `export CONF_CFLAGS=-fPIC`.

**Comment by ghost** [comment]
Compiled as a shared library libfstack.so but get 
`OSError: ./libfstack.so: undefined symbol: rte_cycles_vmware_tsc_map`
when loading

**Comment by HREOLIN** [comment]
> Compiled as a shared library libfstack.so but get `OSError: ./libfstack.so: undefined symbol: rte_cycles_vmware_tsc_map` when loading

Has your problem been solved? Can you announce your solution
