### ISSUE TITLE
Why use rte_kni.ko if it is userspace stack?

### ISSUE THREAD

**Issue by SungHoHong2** [F-Stack/f-stack#131]
Hello I'am trying to use the f-stack for using DPDK as a TCP protocol 
however, when I read your instruction README.md 
I found that you already use `rte_kni.ko` which already allows TCP communication with DPDK. 

My First question is ...
what is reason for using f-stack in this case? when we already can use TCP transaction with the KNI? 

My Second question is ... 
I was looking for libraries that will create the TCP stack within the userspace and don't touch any kernel module, and thought this was a good example that I was looking for. 
Is this type of feature also possible in f-stack?

**Comment by whl739** [comment]
It's up to you to enable or disable kni in `config.ini`.
If you have only one nic, and want to manage it, you need to enable kni, if not, you don't need to do that.
By default, f-stack doesn't touch any kernel module, all our stack is userspace.
