### ISSUE TITLE
Are there any examples of sending packets to other server? 

### ISSUE THREAD

**Issue by SungHoHong2** [F-Stack/f-stack#132]
I have ran the example functions in the f-stack project. 
However the examples are related to displaying the html text file for the designated ip address. 

Would there be a way to check the rest of functions of f-stack work well? 
It would be great if there are more examples

**Comment by whl739** [comment]
Sorry, we didn't write more examples.
We have ported nginx to f-stack, you can use it to do some tests.
`app/nginx-1.11.10/src/event/modules/ngx_ff_module.c` has some hook funtions, these can be tested.
