### ISSUE TITLE
Correct way of using ff_connect function

### ISSUE THREAD

**Issue by SungHoHong2** [F-Stack/f-stack#135]
Hello I am trying to use the `ff_connect function` but the function keep returns `114 Operation now in progress` and then `106 Transport endpoint is already connected` 

Currently I'am sending from `client integrated with f-stack` to `server integrated with f-stack`
If I try to connect the `server with normal TCP ip address` then it return `106: Transport endpoint is already connected`

The functions that are in the example works fine. but beyond that I have no clue of using it. 
I have referred the nignx module in this [page](https://github.com/F-Stack/f-stack/blob/master/app/nginx-1.11.10/src/event/modules/ngx_ff_module.c) but it seems that it needs something more 

I have ran this code below and cannot run the `ff_connect`
the code below connects fine when I use normal function `connect function`

```c 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <errno.h>
#include <sys/ioctl.h>
#include "ff_api.h"

int sockfd = -1;

int loop(void *arg) {
    struct sockaddr_in my_addr;
    bzero(&my_addr, sizeof(my_addr));
    my_addr.sin_family = AF_INET;
    my_addr.sin_port = htons(80);
    my_addr.sin_addr.s_addr = inet_addr("10.218.111.254");

    int on = 1;
    ff_ioctl(sockfd, FIONBIO, &on);
    if (ff_connect(sockfd, (struct linux_sockaddr *)&my_addr, sizeof(my_addr)) == -1) {
        printf("ff_connect failed %d: %s\n", errno, strerror(errno));
    } else {
        printf("ff_connect OK\n");
        return -1;
    }

}

int main(int argc, char * argv[]) {
    ff_init(argc, argv);

    sockfd = ff_socket(AF_INET, SOCK_STREAM, 0);
    printf("sockfd:%d\n", sockfd);
    if (sockfd < 0) {
        printf("ff_socket failed\n");
        exit(1);
    }

    ff_run(loop, NULL);
    return 0;
}
``` 

here is the result console below 

```
ff_connect failed 115: Operation now in progress              
ff_connect failed 114: Operation already in progress          
ff_connect failed 114: Operation already in progress          
ff_connect failed 114: Operation already in progress          
ff_connect failed 114: Operation already in progress          
ff_connect failed 114: Operation already in progress          
ff_connect failed 114: Operation already in progress          
ff_connect failed 114: Operation already in progress          
ff_connect failed 114: Operation already in progress          
ff_connect failed 114: Operation already in progress          
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
```

**Comment by whl739** [comment]
These two errors `Operation already in progress` and `Transport endpoint is already connected` are due to that you used the same socket/fd to connect.
Error `Operation now in progress` is due to that the socket is nonblock, and it returns `EINPROGRESS`, this is an async connection, you should add this socket to select/poll/kqueue/epoll, and wait a writable event, when this event is reaching, call `getsockopt(sockfd, SOL_SOCKET, SO_ERROR, &error, sizeof(int));` to check whether the connection is success or not.

> The functions that are in the example works fine. but beyond that I have no clue of using it.
I have referred the nignx module in this page but it seems that it needs something more

All f-stack APIs are POSIX-like and have the same usage with the host APIs, but we only support async I/O.

**Comment by SungHoHong2** [comment]
Thanks for the reply 
In that case, are you referring to this code in the example folder? 
Can you check whether I am on the right track? 
here is the example code of `ff_run`'s loop function below

```
  int loop ( 
    for (i = 0; i < nevents; ++i) {
        struct kevent event = events[i];
        int clientfd = (int)event.ident;

        /* Handle disconnect */
        if (event.flags & EV_EOF) {
            /* Simply close socket */
            ff_close(clientfd);
        } else if (clientfd == sockfd) {
                    int available = (int)event.data;
            do {

                   // add connection here?                        

            } while (available);

         } else if (event.filter == EVFILT_READ) {
         
                 // add send and receive function here 
         }
   }
}
``` 

I am planning to implement connection and send and recv messages. 
Would this be the right way of implementing it?

**Comment by whl739** [comment]
The example is server-side, what you need is client-side.
Google a normal epoll client demo, and use ff_api instead of the host api.
