### ISSUE TITLE
ipfw: getsockopt(IP_FW_XADD): Invalid argument

### ISSUE THREAD

**Issue by mk-z** [F-Stack/f-stack#136]
This is the error message:

[root@localhost ffbin]# ./ipfw show
65535 5554 629836 allow ip from any to any
[root@localhost ffbin]# ./ipfw add 100 divert 8000 ip from any to any
ipfw: getsockopt(IP_FW_XADD): Invalid argument

**Comment by whl739** [comment]
I just tested it, got no errors.

**Comment by mk-z** [comment]
What needs to be set?

**Comment by whl739** [comment]
I didn't do anything more. What i did is that start the f-stack process, and execute the two commands.

**Comment by tigerjibo** [comment]
Hi all:
    For now ,freebsd  of f-stack does not supoort divert function .

**Comment by tigerjibo** [comment]
In general, ipfw and natd tools are used in combination.

**Comment by whl739** [comment]
`ipfw` had no built-in NAT function before FreeBSD-7, so it needs `divert` to divert packets to `natd`. But now `ipfw` has built-in NAT, it needn't `divert` any more to support NAT.

**Comment by tigerjibo** [comment]
Hi whl739:
   Yes,you are right. But if you want to ipfw divert function to releasize nat function, then must use the natd tools in combination.

**Comment by whl739** [comment]
You are right too, but it is nothing to do with this issue.

**Comment by tigerjibo** [comment]
meet "/ipfw add 100 divert 8000 ip from any to any" rules,the l3 layer packet  will divert to the 8000 (socket port ) process to deal with the packet. For now . the freebsd protocol stack is in user level, so we don't use this way to divert l3 layer packet to another progress. we can realize the core business in the ipfil hook(ipfw_chk function), which is  more efficient by this way.

**Comment by NicoSpec** [comment]
Hi whl739:
In the future, is there a plan to integrate natd into f-stack?

**Comment by whl739** [comment]
@NicoSpec 
No. Does the in-kernel nat not suit your case?

**Comment by NicoSpec** [comment]
@whl739 
when I use ipfw apearing this error.6946 is f-stack/nginx pid.
/data/f-stack/tools/ipfw/ipfw -P 6946 add 100 divert 8000 ip from any to any
lookup message ring:ff_msg_ring_in_6946 failed!
ipfw: getsockopt(IP_FW_XADD): Broken pipe

**Comment by whl739** [comment]
`-p` is not the PID of process, it's the `proc-id` which is the f-stack's launching argument.
Its range is from 0 to (number of processes - 1).

**Comment by NicoSpec** [comment]
There is an error still.
/data/f-stack/tools/ipfw/ipfw -p 0 add 100 divert 8000 ip from any to any
ipfw: An absolute pathname must be used with -p option.

**Comment by whl739** [comment]
It should be `-P`.
The error `ipfw: getsockopt(IP_FW_XADD): Invalid argument` is because of the missing of `ip_divert` module.
Apply this patch:
```
diff --git a/lib/Makefile b/lib/Makefile
index be1e91b..8166ba7 100644
--- a/lib/Makefile
+++ b/lib/Makefile
@@ -346,6 +346,7 @@ NETINET_SRCS+=              \
        in_proto.c      \
        in_rmx.c        \
        ip_carp.c       \
+       ip_divert.c     \
        ip_ecn.c        \
        ip_encap.c      \
        ip_fastfwd.c    \
```

And even though, `divert` is still not usable, as @tigerjibo says, it needs `natd`.
But you can use the built-in NAT: `ipfw nat`.
