### ISSUE TITLE
Performance decrease when using packets size of more than 1512 bytes 

### ISSUE THREAD

**Issue by SungHoHong2** [F-Stack/f-stack#137]
Hello I have been testing the f-stack 
and the f-stack performs really well when the packet size is small. 64 ~ 1024 bytes 
however, when the packet size increase up to certain point. I have noticed that it is worse than original TCP epolling 

I have been testing both latency and the throughput using client and server pingpong implemented with the f-stack. 

I am suspecting that the current NIC's MTU speed has to do with something 
since when I type like this below, I get ..  
```
ifconfig| grep MTU 
UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
UP BROADCAST MULTICAST  MTU:1500  Metric:1        
UP BROADCAST MULTICAST  MTU:1500  Metric:1        
UP LOOPBACK RUNNING  MTU:65536  Metric:1          
```

<br>

**Here is the result graph of latency**
as you can see the f-stack performance decreases when the packet size is more than 1500 

![image](http://postfiles9.naver.net/MjAxODAxMDVfMTMz/MDAxNTE1MDkzNzI2MzMy.L0vVLdMR5soj-nL9Zl5mJKXioEFUIog99O2Vsav0JEcg.iNDYuYIG_5C3xbv_6Yn8ofmuTiJWfZBDy1JHPGzCi-wg.JPEG.maverickjin8/Screen_Shot_2018-01-04_at_12.18.42_PM.png?type=w2)

**Here is the result graph of throughtput**
![image](http://postfiles12.naver.net/MjAxODAxMDVfMTcg/MDAxNTE1MDkzNzA2MzU5.gk1c7iGp9a71deAYE6nN7QgVbDt90JNZDMomaiHYHFUg.OKC915o5EbGj6C7GGCyyyYoALULxYPYdfy5p7PRX9fIg.PNG.maverickjin8/Screen_Shot_2018-01-04_at_12.18.51_PM.png?type=w2)

Is there a way to increase the f-stack performance with the big packets?

**Comment by whl739** [comment]
You have only two results, how can i analysis?
Give me more information:
- how did you test? test environment, hardware, tool, etc..
- how many f-stack processes did you start? f-stack configuration.
- how did the original TCP work? single/multi - thread/process?
- etc..

**Comment by SungHoHong2** [comment]
- I tested pingpong (originally made with simple send and recv) and counted the round trips of each packets between `workstation 1` and `workstation 2` 
- the `environment` of the workstation and the `f-stack configuration etc` are all the same 
```
4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_6
```

<br>

- The NICs that are bounded for both workstations are identical `e1000` intel product 

```
0000:04:00.0 'I350 Gigabit Network Connection 1521' drv=igb_uio unused=
speed 100 Mbps - full-duplex   

flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500                  
inet 10.218.111.252  netmask 255.255.248.0  broadcast 10.218.111.255
inet6 fe80::b30a:eb7d:2e84:8f6d  prefixlen 64  scopeid 0x20<link>   
ether 64:00:6a:5a:21:5b  txqueuelen 1000  (Ethernet)                
RX packets 30154962  bytes 7830560058 (7.8 GB)                      
RX errors 0  dropped 0  overruns 0  frame 0                         
TX packets 2513760  bytes 2069747020 (2.0 GB)                       
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0          
device interrupt 20  memory 0xf7d00000-f7d20000                     
```

<br>

-  all the pingpong was run by a `single process`, and here is the f-stack configuration. 

```
[dpdk]
## Hexadecimal bitmask of cores to run on.
lcore_mask=2
channel=4
promiscuous=1
numa_on=1
## TCP segment offload, default: disabled.
tso=0
## HW vlan strip, default: enabled.
vlan_strip=1

# enabled port list
#
# EBNF grammar:
#
#    exp      ::= num_list {"," num_list}
#    num_list ::= <num> | <range>
#    range    ::= <num>"-"<num>
#    num      ::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
#
# examples
#    0-3       ports 0, 1,2,3 are enabled
#    1-3,4,7   ports 1,2,3,4,7 are enabled
port_list=1

## Port config section
## Correspond to dpdk.port_list's index: port0, port1...
[port1]
addr=10.218.111.254
netmask=255.255.248.0
broadcast=10.218.111.255
gateway=10.218.111.1

## lcore list used to handle this port
## the format is same as port_list
# lcore_list= 0

## Packet capture path, this will hurt performance
#pcap=./a.pcap

## Kni config: if enabled and method=reject,
## all packets that do not belong to the following tcp_port and udp_port
## will transmit to kernel; if method=accept, all packets that belong to
## the following tcp_port and udp_port will transmit to kernel.
#[kni]
#enable=1
#method=reject
## The format is same as port_list
#tcp_port=80,443
#udp_port=53

## FreeBSD network performance tuning configurations.
## Most native FreeBSD configurations are supported.
[freebsd.boot]
hz=100

## Block out a range of descriptors to avoid overlap
## with the kernel's descriptor space.
## You can increase this value according to your app.
fd_reserve=1024

kern.ipc.maxsockets=262144
net.inet.tcp.syncache.hashsize=4096
net.inet.tcp.syncache.bucketlimit=100
net.inet.tcp.tcbhashsize=65536

[freebsd.sysctl]
kern.ipc.somaxconn=32768
kern.ipc.maxsockbuf=16777216
net.link.ether.inet.maxhold=5

net.inet.tcp.fast_finwait2_recycle=1
net.inet.tcp.sendspace=16384
net.inet.tcp.recvspace=8192
net.inet.tcp.nolocaltimewait=1
net.inet.tcp.cc.algorithm=cubic
net.inet.tcp.sendbuf_max=16777216
net.inet.tcp.recvbuf_max=16777216
net.inet.tcp.sendbuf_auto=1
net.inet.tcp.recvbuf_auto=1
net.inet.tcp.sendbuf_inc=16384
net.inet.tcp.recvbuf_inc=524288
net.inet.tcp.sack.enable=1
net.inet.tcp.blackhole=1
net.inet.tcp.msl=2000
net.inet.tcp.delayed_ack=0

net.inet.udp.blackhole=1
net.inet.ip.redirect=0
```

**Comment by whl739** [comment]
Could you show me the source code of `pingpong`? Then i'll test it in my environment .

**Comment by SungHoHong2** [comment]
Here is the link to the [server](https://github.com/SungHoHong2/DPDK-Experiment/blob/master/latency-experiment/f-stack-tcp/fstack-server.c)

and here is the link to the [client](https://github.com/SungHoHong2/DPDK-Experiment/blob/master/latency-experiment/f-stack-tcp/fstack-client.c)
  
I suppose this has to do with the DPDK because when I increased the packet size in DPDK l2forwarding the performance degraded in that case too.

**Comment by whl739** [comment]
I consider that there's something wrong with your code.
For the first picture, when packet size > 1024, "tcp" latency is much smaller than packet size < 1024, it's strange, if your code is no error, maybe it relates to `TCP_NODELAY`.

And the f-stack client code:
```
int nrecv = ff_recv(events[i].data.fd, buffer, PKT_SIZE, 0) ;
if(nrecv == -1 && errno != EAGAIN)
    perror("read error");
if((nrecv == -1 && errno == EAGAIN) || nrecv == 0)
    break;
if (nrecv > 0) succ++;

curr_bytes+=strlen(buffer);
```
this should be `curr_bytes += nrecv`.


According to the below code,  the `latency` means the latency of receiving PKT_SIZE bytes.
this is inaccurate, see the above code `ff_recv(events[i].data.fd, buffer, PKT_SIZE, 0) ;`, 
you recveive PKT_SIZE bytes every time, and then modify the event, so if the readable buffers are
more than PKT_SIZE, the `curr_bytes` gets the error result.
```
if(curr_bytes>=limit_bytes){
    printf("latency results\n");
    gettimeofday(&t2, NULL);
    printf("curr_bytes: %ld\n", curr_bytes);
    printf("limit_bytes: %ld\n", limit_bytes);

    // elapsedTime = (t2.tv_sec - t1.tv_sec) * 1000.0;      // sec to ms
    // elapsedTime += (t2.tv_usec - t1.tv_usec) / 1000.0;   // us to ms
    latency = (t2.tv_sec - t1.tv_sec) * 1000000.0;      // sec to us
    latency += (t2.tv_usec - t1.tv_usec);   // us

    latency/=MAXIMUM_RUN;
    printf("latency: %f us\n", latency);
    exit(1);
}
```

**Comment by jfb8856606** [comment]
Update: The performance degradation with large packets was partly due to the MTU 1500 limitation causing IP fragmentation. F-Stack now supports jumbo frames (MTU up to 9000) on the `dev` branch via `mtu_enable=1` configuration, which should significantly improve large-packet throughput. See #490 and #720 for details.
