### ISSUE TITLE
how to: guideline to patch latest nginx release that can be compiled with latest f-stack

### ISSUE THREAD

**Issue by progamer71** [F-Stack/f-stack#141]
I would like to use latest nginx release (version 1.13.8 at this time) with latest f-stack.
I don't know where to start.
I have tried to look at app/nginx-1.11.10 and feel lost.

Do you have any suggestions?

I also try to combine openresty and f-stack in the future if nobody do it :).
I will be a great speedy web framework.

Thanks you.

**Comment by whl739** [comment]
I made a patch before, but it's based on 20be49f6081d28328832b3bcfef59f5218385398, you can refer to the following patch and upgrade it. 
[f-stack-openresty-patch.txt](https://github.com/F-Stack/f-stack/files/1610844/f-stack-openresty-patch.txt)

All the changed codes are wrapped with macro `NGX_HAVE_FSTACK`,  some new files are added in `app/nginx-1.11.10/src/event/modules`, and `app/nginx-1.11.10/auto` are modified for compiling.

**Comment by progamer71** [comment]
Thanks you so much
