### ISSUE TITLE
Can't start proxy_cache

### ISSUE THREAD

**Issue by T142857** [F-Stack/f-stack#142]
Hi F-stack Team,
I'm build F-stack solution on CentOS Linux release 7.4.1708 (Core) , kernel 3.10.0-514.el7.x86_64
My problem, I can't start proxy cache
This is log in /usr/local/nginx_fstack/logs/error.log:
2018/01/08 12:00:14 [alert] 3799#0: cache manager process 17762 exited on signal 11
2018/01/08 12:00:14 [alert] 3799#0: cache manager process 17764 exited on signal 11
2018/01/08 12:00:14 [alert] 3799#0: cache manager process 17765 exited on signal 11
2018/01/08 12:00:14 [alert] 3799#0: cache manager process 17767 exited on signal 11

This is my config 
proxy_cache_path levels=2 keys_zone=my_cache:16m inactive=10m max_size=512m;
server {
location / {
    proxy_pass http://171.xx.xx.xx;
    proxy_cache my_cache;
}
}

Plz help me, fix problem

Thank Team

**Comment by whl739** [comment]
`proxy_cache` is not supported for now.
I'll fix it in the near future.

**Comment by T142857** [comment]
thank you.
