### ISSUE TITLE
`ff_connect` failed 

### ISSUE THREAD

**Issue by gpfei** [F-Stack/f-stack#146]
### Environments
- Centos 7.4.1708
- DPDK 17.08.1
- f-stack b2dbf8fd04cb3755ef1592d3b65b3b4d61c00527 (modified to using DPDK 17.08.1)

Hi f-stack team,

I am trying to adopt f-stack with Golang to implement tcp client, but confront a problem:
`ff_connect` always failed, because of that `kern_connectat` returns `EPERM`.

After inspecting the source code, I found that `EPERM` is returned by `_sleep()` defined in `ff_kern_synch.c`.

Could you please explain why overwriting the `_sleep()` in `freebsd/kern/kern_synch.c`?

Thanks!

**Comment by whl739** [comment]
`ff_connect ` must be nonblock.

**Comment by gpfei** [comment]
So should I ignore the failure of `ff_connect` and use `ff_select/ff_poll` to monitor the socket fd?

**Comment by whl739** [comment]
Yes, first set the fd noblock, then call `ff_connect`, and ignore the failure if errno is `EINPROGRESS`, add the fd to `ff_epoll`/`ff_kqueue`/`ff_select`/`ff_poll`.
Refer to #135.

**Comment by gpfei** [comment]
Thanks, I will try it.

**Comment by gpfei** [comment]
After calling `ff_connect`, the `errno` is `EPERM`, instead of `EINPROGRESS`.

The procedure is:
1. create socket `ff_socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);`
2. set nonblock `ff_fcntl(sockfd, F_SETFL, flag | O_NONBLOCK );`
3. call `ff_connect`
4. add to `ff_epoll`

**Comment by whl739** [comment]
> set nonblock ff_fcntl(sockfd, F_SETFL, flag | O_NONBLOCK );

There's bug of `ff_fcntl`, use `int on = 1;ff_ioctl(sockfd, FIONBIO, &on);` instead.

**Comment by gpfei** [comment]
Thanks, `ff_ioctl` works. But `ff_epoll_wait` always return 0.

My process contains multi threads, and run `ff_init_thread0` twice. The tid of thread which is running `ff_epoll_wait` is same with the `ff_socket` one.

**Comment by whl739** [comment]
`ff_api` couldn't be used in multi threads.

**Comment by gpfei** [comment]
> `ff_api` couldn't be used in multi threads.

Even if all codes using `ff_api` are in one single thread, while other codes in another thread?

**Comment by whl739** [comment]
> Even if all codes using ff_api are in one single thread, while other codes in another thread?

It's ok in this case.

It's better to paste your codes or show an example that can be reproduced.

**Comment by gpfei** [comment]
I would like to paste the code, but it is written in Golang.

**Comment by whl739** [comment]
Did your `ff_epoll_wait` run in `ff_run`?

**Comment by gpfei** [comment]
No, `ff_run` is not used. `ff_epoll_wait` is called in an infinite `while-loop`.

**Comment by gpfei** [comment]
BTW, the args are `-c f -n 2 -- -q 1 -p 0x3`

**Comment by whl739** [comment]
All the apis must be run in `ff_run`.
See the example.

**Comment by gpfei** [comment]
Does that mean `f-stack` is not suitable for developing client, which requests multi servers, such as website crawler?

**Comment by whl739** [comment]
F-Stack is designed as a server-side development kit. But it also can be used in client-side.
See `ff_run`, it needs a `loop` callback function, it means you should put your logics in the `loop` function, for your case, logics in the infinite `while-loop` should be moved to a single functin, and pass the function to `ff_run`.

**Comment by gpfei** [comment]
I see. I have to re-organize the code. Thanks very much!

**Comment by trojanets** [comment]
Can anyone rewrite my example to work with ff_poll ?
I am not understand why it's not working.
Is it possible to change loop fucntion?
ff_run(loop1,NULL);
//code
ff_run(loop2,NULL);

`#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <arpa/inet.h>

#include <errno.h>
#include "ff_api.h"
#define BUF_SIZE 4096
int sockfd = -1;

int loop(void *arg) {
    char buf[BUF_SIZE];
    struct pollfd fdset;
    memset(&fdset, 0, sizeof(fdset));
    printf("Loop..OK\n");
    fdset.fd = sockfd;
    printf("Socket id: %d.\n", sockfd);
    fdset.events = POLLIN;
    int len,error;
    sleep(5);
    if (getsockopt(sockfd, SOL_SOCKET, SO_ERROR, &error, &len) < 0)
            {
                printf("Еще не установлено соединение\n"); 
                sleep(1);
            }
            else
            {
                printf("Установлено соединение\n");
                ff_read(sockfd,buf,BUF_SIZE);
                printf("%s\n");
            }
    while (1)
    {
        int nready = ff_poll(&fdset, 1, 0);
        if (nready == 0)
        {
            continue; /* no fd ready */
        }
        int revents = fdset.revents;
        if (revents !=0)
        {
            len = sizeof(error);
            error = 0;
            if (getsockopt(sockfd, SOL_SOCKET, SO_ERROR, &error, &len) < 0)
            {
                printf("Еще не установлено соединение\n"); 
                sleep(1);
            }
            else
            {
                printf("Установлено соединение\n");
                ff_read(sockfd,buf,BUF_SIZE);
                printf("%s\n");
            }
        }    
        // if (revents & POLLOUT)
        //     do_sock_write();
        // i += 1;
    }
    return 0;
}

int main(int argc, char * argv[]) {
    ff_init(argc, argv);

    sockfd = ff_socket(AF_INET, SOCK_STREAM, 0);
    printf("sockfd:%d\n", sockfd);
    if (sockfd < 0) {
        printf("ff_socket failed\n");
        exit(1);
    }
    struct sockaddr_in my_addr;
        bzero(&my_addr, sizeof(my_addr));
        my_addr.sin_family = AF_INET;
        my_addr.sin_port = htons(5672);
        my_addr.sin_addr.s_addr = inet_addr("10.10.10.60");
        int on = 1;
        ff_ioctl(sockfd, FIONBIO, &on);
        if (ff_connect(sockfd, (struct linux_sockaddr *)&my_addr, sizeof(my_addr)) == -1) {
            printf("ff_connect failed %d: %s\n", errno, strerror(errno));
        } else {
            printf("ff_connect OK\n");
        }
    ff_run(loop, NULL);
    return 0;
}`
