### ISSUE TITLE
f-stack/nginx configuration two NIC can not ping.

### ISSUE THREAD

**Issue by NicoSpec** [F-Stack/f-stack#147]
When I start up f-stack/nginx ,I couldn't ping these two ip address.
This my f-stack.conf.
[dpdk]
** Hexadecimal bitmask of cores to run on.
lcore_mask=ff
channel=4
promiscuous=1
numa_on=1
** TCP segment offload, default: disabled.
tso=0
** HW vlan strip, default: enabled.
vlan_strip=1

* enabled port list
*
* EBNF grammar:
*
*    exp      ::= num_list {"," num_list}
*    num_list ::= <num> | <range>
*    range    ::= <num>"-"<num>
*    num      ::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
*
* examples
*    0-3       ports 0, 1,2,3 are enabled
*    1-3,4,7   ports 1,2,3,4,7 are enabled
port_list=0,1

 Port config section
** Correspond to dpdk.port_list's index: port0, port1...
[port0]
addr=公网IP
netmask=255.255.255.0
broadcast=广播地址
gateway=网关

[port1]
addr=10.16.20.57
netmask=255.255.255.0
broadcast=10.16.20.255
gateway=10.16.20.254
** lcore list used to handle this port
** the format is same as port_list
*lcore_list= 0

** Packet capture path, this will hurt performance
*pcap=./a.pcap

**Comment by whl739** [comment]
Paste your nginx.conf

**Comment by NicoSpec** [comment]
user  root;

worker_processes  8;

error_log  logs/error.log;
error_log  logs/error.log  notice;
error_log  logs/error.log  info;

pid        logs/nginx.pid;

fstack_conf f-stack.conf;

events {
    worker_connections  102400;
    use kqueue;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    *log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    *                  '$status $body_bytes_sent "$http_referer" '
    *                  '"$http_user_agent" "$http_x_forwarded_for"';

    *access_log  logs/access.log  main;

    sendfile        off;
    *tcp_nopush     on;

    *keepalive_timeout  0;
    keepalive_timeout  65;

    *gzip  on;

    server {
        listen       80;
        server_name  localhost;

        * bulid server on kernel network stack 
        * 
        *kernel_network_stack on;

        *charset koi8-r;

        access_log /dev/null;
        *access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        *error_page  404              /404.html;

        * redirect server error pages to the static page /50x.html
        *
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        * proxy the PHP scripts to Apache listening on 127.0.0.1:80
        *
        *location ~ \.php$ {
        *    proxy_pass   http://127.0.0.1;
        *}

        * pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        *
        *location ~ \.php$ {
        *    root           html;
        *    fastcgi_pass   127.0.0.1:9000;
        *    fastcgi_index  index.php;
        *    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        *    include        fastcgi_params;
        *}

        * deny access to .htaccess files, if Apache's document root
        * concurs with nginx's one
        *
        *location ~ /\.ht {
        *    deny  all;
        *}
    }


    * another virtual host using mix of IP-, name-, and port-based configuration
    *
    *server {
    *    listen       8000;
    *    listen       somename:8080;
    *    server_name  somename  alias  another.alias;

    *    location / {
    *        root   html;
    *        index  index.html index.htm;
    *    }
    *}


    * HTTPS server
    *
    *server {
    *    listen       443 ssl;
    *    server_name  localhost;

    *    ssl_certificate      cert.pem;
    *    ssl_certificate_key  cert.key;

    *    ssl_session_cache    shared:SSL:1m;
    *    ssl_session_timeout  5m;

    *    ssl_ciphers  HIGH:!aNULL:!MD5;
    *    ssl_prefer_server_ciphers  on;

    *    location / {
    *        root   html;
    *        index  index.html index.htm;
    *    }
    *}

}

**Comment by whl739** [comment]
Take a look at nginx's error.log.

**Comment by NicoSpec** [comment]
2018/01/09 20:21:01 [notice] 9972#0: using the "kqueue" event method
2018/01/09 20:21:01 [notice] 9972#0: using the "kqueue" event method
2018/01/09 20:21:01 [notice] 9972#0: nginx/1.11.10
2018/01/09 20:21:01 [notice] 9972#0: nginx/1.11.10
2018/01/09 20:21:01 [notice] 9972#0: built by gcc 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
2018/01/09 20:21:01 [notice] 9972#0: built by gcc 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
2018/01/09 20:21:01 [notice] 9972#0: OS: Linux 3.10.0-327.3.1.el7.x86_64
2018/01/09 20:21:01 [notice] 9972#0: OS: Linux 3.10.0-327.3.1.el7.x86_64
2018/01/09 20:21:01 [notice] 9972#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2018/01/09 20:21:01 [notice] 9972#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2018/01/09 20:21:01 [notice] 9973#0: start worker processes
2018/01/09 20:21:01 [notice] 9973#0: start worker processes
2018/01/09 20:21:01 [notice] 9973#0: start worker process 9974
2018/01/09 20:21:01 [notice] 9973#0: start worker process 9974
2018/01/09 20:21:01 [notice] 9973#0: start worker process 9975
2018/01/09 20:21:01 [notice] 9973#0: start worker process 9975
2018/01/09 20:21:01 [notice] 9973#0: start worker process 9976
2018/01/09 20:21:01 [notice] 9973#0: start worker process 9976
2018/01/09 20:21:01 [notice] 9973#0: start worker process 9977
2018/01/09 20:21:01 [notice] 9973#0: start worker process 9977
2018/01/09 20:21:01 [notice] 9973#0: start worker process 9978

there isn't error.

**Comment by NicoSpec** [comment]
When I use f-stack's ifconfig apearing these IP

**Comment by whl739** [comment]
Enable the packet capture: `port.pcap` to see what it shows.

**Comment by NicoSpec** [comment]
I only saw in the dpdk directory a.pcap file, how to see the output?

**Comment by whl739** [comment]
Open with `wireshark`.

**Comment by NicoSpec** [comment]
![image](https://user-images.githubusercontent.com/19813367/34722964-ddedb54e-f583-11e7-835b-1c1a3cd7673c.png)
there is a lot of package.

**Comment by NicoSpec** [comment]
Hi, @whl739 
Now,I have resolved the problem.
The reason for the inability to ping is that the IP configuration on the private and public NIC is reversed. After adjustment, and then increase the routing can be used
