### ISSUE TITLE
udp stream error

### ISSUE THREAD

**Issue by lazy-wangxl** [F-Stack/f-stack#157]
Compile nginx with --with-stream, and nginx.conf like this:
stream {
   upstream dns {
        server 192.168.1.3:53;
   }
  server {
       listen 53 udp;
       proxy_responses 1;
       proxy_timeout 20s;
       proxy_pass dns;
  }
}

This is the error message(error.log):
[alert] 16834#0 setsockopt(IP_PKTINFO) for 0.0.0.0:53 failed, ignore(9: Bad file descriptor)

**Comment by firesidefox** [comment]
I want to answer your question in two parts. 
1. The configure of nginx automatically detects the features of different platforms. But, for now, *nginx based on fstack*  still detects the features of the platform, and not fstack. It can be subject to inconsistent and incorrect. 

2.  *nginx based on fstack*  delays setting up server on fstack until ```ngx_worker_process_init```.   
```ngx_configure_listening_sockets``` should as well.

This (IP_PKTINFO) simply get a alert,  you can just ignore it.
