### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by phantomgps1** [F-Stack/f-stack#16]
cc -c -O2 -fno-strict-aliasing -frename-registers -pipe -Wno-maybe-uninitialized   -std=c99  -Wall -Wnested-externs -Wstrict-prototypes -Wmissing-proto
types -Wpointer-arith -Wno-inline -Wcast-qual -Wno-pointer-sign -Wmissing-include-dirs -fdiagnostics-show-option -Wno-unused-but-set-variable -fno-comm
on -finline-limit=8000 --param inline-unit-growth=100 --param large-function-growth=1000  -DFSTACK  -fstack-protector -D__FreeBSD__ -D_KERNEL -DHAVE_KE
RNEL_OPTION_HEADERS -include opt_global.h -fno-builtin -I/home/yuwh/fstack/f-stack/lib/include -undef -imacros filtered_predefined_macros.h -nostdinc
-I. -I/home/yuwh/fstack/f-stack/lib/../freebsd -I./machine_include -I./opt -Werror -Wno-unused-variable  ff_compat.c
cc -c -O2 -fno-strict-aliasing -frename-registers -pipe -Wno-maybe-uninitialized   -std=c99  -Wall -Wnested-externs -Wstrict-prototypes -Wmissing-proto
types -Wpointer-arith -Wno-inline -Wcast-qual -Wno-pointer-sign -Wmissing-include-dirs -fdiagnostics-show-option -Wno-unused-but-set-variable -fno-comm
on -finline-limit=8000 --param inline-unit-growth=100 --param large-function-growth=1000  -DFSTACK  -fstack-protector -D__FreeBSD__ -D_KERNEL -DHAVE_KE
RNEL_OPTION_HEADERS -include opt_global.h -fno-builtin -I/home/yuwh/fstack/f-stack/lib/include -undef -imacros filtered_predefined_macros.h -nostdinc
-I. -I/home/yuwh/fstack/f-stack/lib/../freebsd -I./machine_include -I./opt -Werror -Wno-unused-variable  ff_glue.c
cc1: warnings being treated as errors
In file included from ff_glue.c:50:
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/buf.h:130: error: declaration does not declare anything
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/buf.h:131: error: declaration does not declare anything
In file included from ff_glue.c:53:
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h:192: error: declaration does not declare anything
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h:219: error: declaration does not declare anything
...
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h: In function ‘m_free’:
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h:1174: error: ‘struct mbuf’ has no member named ‘m_next’
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h: In function ‘rt_m_getfib’:
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h:1190: error: ‘struct mbuf’ has no member named ‘m_pkthdr’
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h: In function ‘mbufq_drain’:
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h:1249: error: ‘struct mbuf’ has no member named ‘m_stailqpkt’
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h: In function ‘mbufq_last’:
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h:1265: error: ‘struct mbuf’ has no member named ‘m_stailqpkt’
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h:1265: error: type defaults to ‘int’ in declaration of ‘__x’
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h:1265: error: initialization from incompatible pointer type
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h:1265: error: ‘struct mbuf’ has no member named ‘m_stailqpkt’
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h: In function ‘mbufq_enqueue’:
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h:1288: error: ‘struct mbuf’ has no member named ‘m_stailqpkt’
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h:1288: error: ‘struct mbuf’ has no member named ‘m_stailqpkt’
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h: In function ‘mbufq_dequeue’:
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h:1300: error: ‘struct mbuf’ has no member named ‘m_stailqpkt’
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h:1301: error: ‘struct mbuf’ has no member named ‘m_nextpkt’
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h: In function ‘mbufq_prepend’:
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h:1311: error: ‘struct mbuf’ has no member named ‘m_stailqpkt’
/home/yuwh/fstack/f-stack/lib/../freebsd/sys/mbuf.h:1311: error: ‘struct mbuf’ has no member named ‘m_stailqpkt’
At top level:
cc1: error: unrecognized command line option "-Wno-maybe-uninitialized"
make: *** [ff_glue.o] Error 1

[yuwh@localhost lib]$gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)

**Comment by whl739** [comment]
Upgrade gcc to 4.5+.

**Comment by yuwenhua** [comment]
It doesn't look like a compiler problem, how can you close issue in this way

**Comment by yuwenhua** [comment]
It's not the problem of gcc version, 
change CFLAG -std=c99 to gnu99
