### ISSUE TITLE
link_elf_lookup_symbol: missing symbol hash table

### ISSUE THREAD

**Issue by ralequi** [F-Stack/f-stack#162]
Why the error logged as `link_elf_lookup_symbol: missing symbol hash table` is produced?
I've check other issues and happened time to time. Is it important? Why it is caused? Need to link with something statically that we don't have?

Thanks!

**Comment by whl739** [comment]
When freebsd system is initializing, it will load kernel modules, but we havn't any kernel modules, we have already compiled these modules to the f-stack library.
It's not a problem, the `link_elf` is included to make the freebsd to compile successfully.

**Comment by ralequi** [comment]
Understood, Thanks!
