### ISSUE TITLE
Consider provide a ff_run alternative

### ISSUE THREAD

**Issue by ralequi** [F-Stack/f-stack#163]
Hi,

The ff_run method may be appropriate in many scenarios, even in most, but not for all.
I may ask for an alternative, I mean, a ff_run(null,null) that start the threads but allow the user to call the POSIX-like functions without need to be in ff_run context.
Some applications (as some I develop) can not or are hardly difficult to convert to this paradigm.

Thank you for consider this option in the future.

**Comment by whl739** [comment]
You know that DPDK is running in polling mode, every cycle, we send packets, receive packets, and do other things, so `ff_run` with a callback function is a easy way to inject our logics into each cycle. And F-Stack is designed as a server-side library, generally server-side program has an infinite loop. When porting to f-stack, we can extract the logic of cycle, and convert it to a callback function of `ff_run`.

Your suggestion will be considered in the future.
