### ISSUE TITLE
How to start multi Redis instance?

### ISSUE THREAD

**Issue by git-littlezhou** [F-Stack/f-stack#167]
Hello f-stack team, i want to start multi Redis instance on one machine, fox example, one listen on 6379, and one listen on 6380. I use 
${bin} --conf config1.ini --proc-type=primary --proc-id=0 redis-6379.conf 
${bin} --conf config2.ini --proc-type=primary --proc-id=0 redis-6380.conf
to start two instance, but it can not work.

**Comment by whl739** [comment]
F-Stack doesn't support multiple instances, it can only start one primary process, and multi secondary processes.
For now, the redis app only supports one single process.

**Comment by alvyC** [comment]
Hi, Does redis app support multi instances now? I am trying to do the following: 
```
./app/redis-3.2.8/src/redis-server --conf config.ini --proc-type=primary --procid=0 redis-1.conf &
./app/redis-3.2.8/src/redis-server --conf config.ini --proc-type=secondary --procid=1 redis-2.conf &
```
But getting error. Just want to make sure, the problem is not at my end.

**Comment by victorstewart** [comment]
what would be involved in building in this support? I'd be interested in working on it.
