### ISSUE TITLE
EAL: Error reading from file descriptor 8: Input/output error

### ISSUE THREAD

**Issue by arcanique** [F-Stack/f-stack#174]
When I run the helloworld program，it appears 'EAL: Error reading from file descriptor 8: Input/output error'.And I'm sure that I have configured the large page and network card driver correctly. 

This is my NIC : Ethernet controller: Intel Corporation 82599 Ethernet Controller Virtual Function (rev 01)

**Comment by arcanique** [comment]
I found that it was due to a bug in dpdk in the virtual machine. Can F-stack upgrade dpdk version?

**Comment by whl739** [comment]
Do you mean this patch?
http://dpdk.org/dev/patchwork/patch/945/

**Comment by arcanique** [comment]
Yes, can f-stack upgrade dpdk version friendly ？

**Comment by whl739** [comment]
You can use your own dpdk, just export FF_DPDK=/your/dpdk/build/path, see [lib/Makefile](https://github.com/F-Stack/f-stack/blob/master/lib/Makefile#L23).

I will merge this patch, and upgrade dpdk to newest version in the future.

**Comment by whl739** [comment]
I just checked dpdk's updates, and found that this patch is not merged, and is just used for VMware Workstation environment, because INTX is badly emulated in VMWare.
You can apply this patch yourself, this will not be merged.

**Comment by arcanique** [comment]
Thanks very much

**Comment by wtao0221** [comment]
Hi, @I944 

I have the same problem. 

Does this patch solve your problem? However, after I patch it and re-compile DPDK, I still get the same error.
