### ISSUE TITLE
Multi process error!

### ISSUE THREAD

**Issue by arcanique** [F-Stack/f-stack#177]
hi,
    when I use the f-stack mode, the primary process is the example that you provide,and the secondary process is a udp server use f-stack api.
I performed these two programs：
./helloworld -c config.ini -t primary -p 0
./udpserver -c config.ini -t secondary -p 1

The running error is：--》create ring:dispatch_ring_p0_q1 failed!

EAL: Detected 8 lcore(s)
EAL: Probing VFIO support...
EAL: WARNING: Address Space Layout Randomization (ASLR) is enabled in the kernel.
EAL:    This may cause issues with mapping memory into secondary processes
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL:   probe driver: 15ad:7b0 rte_vmxnet3_pmd
EAL: PCI device 0000:0b:00.0 on NUMA socket 0
EAL:   probe driver: 15ad:7b0 rte_vmxnet3_pmd
EAL: PCI device 0000:13:00.0 on NUMA socket 0
EAL:   probe driver: 8086:10ed rte_ixgbevf_pmd
EAL: PCI device 0000:1b:00.0 on NUMA socket 0
EAL:   probe driver: 8086:10ed rte_ixgbevf_pmd
lcore: 1, port: 0, queue: 1
create mbuf pool on socket 0
create ring:dispatch_ring_p0_q0 success, 2047 ring entries are now free!
PANIC in init_dispatch_ring():
create ring:dispatch_ring_p0_q1 failed!
7: [./helloworld() [0x40731e]]
6: [/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f9404746b35]]
5: [./helloworld() [0x407460]]
4: [./helloworld() [0x4aa97d]]
3: [./helloworld() [0x4a7d4a]]
2: [./helloworld() [0x406bd3]]
1: [./helloworld() [0x564b6a]]

**and config.ini is** :

```
## Hexadecimal bitmask of cores to run on.
lcore_mask=7
channel=4
promiscuous=1
numa_on=1
## TCP segment offload, default: disabled.
tso=0
## HW vlan strip, default: enabled.
vlan_strip=1

# enabled port list
#
# EBNF grammar:
#
#    exp      ::= num_list {"," num_list}
#    num_list ::= <num> | <range>
#    range    ::= <num>"-"<num>
#    num      ::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
#
# examples
#    0-3       ports 0, 1,2,3 are enabled
#    1-3,4,7   ports 1,2,3,4,7 are enabled
port_list=0

## Port config section
## Correspond to dpdk.port_list's index: port0, port1...
[port0]
addr=192.168.1.10
netmask=255.255.255.0
broadcast=192.168.1.255
gateway=192.168.1.1
```

Looking forward to your reply

**Comment by whl739** [comment]
1. close ASLR.
```
echo 0 > /proc/sys/kernel/randomize_va_space
```
2. secondary process should start up after that primary is already running.
3. All the processes should deal with the same business, because we use RSS to hash to different processes.

**Comment by arcanique** [comment]
I set it up the way you like. But there are still errors.
I noticed that the primary process is already running ,but it just create dispatch_ring_p0_q0 success. I think this is the key of this question, resulting in the secondary process can not  lookup ring. And make the error

**Comment by arcanique** [comment]
And when I set the lcore_mask=a , the primary process created three rings (q0,q1,q2). But there is a mistake 'Cause: num_procs[3] bigger than max_rx_queues[1]'

**Comment by whl739** [comment]
> And when I set the lcore_mask=a , the primary process created three rings (q0,q1,q2). 

if lcore_mask=a, primary will create q0 and q1, but not q2. The hexadecimal 'A' is '1010' in binary.

> 'Cause: num_procs[3] bigger than max_rx_queues[1]'

It means that your nic has only one rx queue, so we couldn't start more than one process.

**Comment by arcanique** [comment]
thanks, I got it!

**Comment by bgong2005** [comment]
I meet the same problem, how to solve it?
