### ISSUE TITLE
SSL connection refused by fstack-nginx

### ISSUE THREAD

**Issue by mithun-aticara** [F-Stack/f-stack#179]
Hi ,

I am running nginx server provided by f-stack and it works fine for 'http' connection, but refuses the 'https'. I have set the nginx.conf file properly for https server, but fails to connect. The error message in the error log of nginx server is 
2018/04/03 18:25:50 [alert] 90965#0: *2 recv() failed (9: Bad file descriptor) while SSL handshaking, client: 192.168.174.16, server: 0.0.0.0:443

Please let me know.

Regards,
Mithun

**Comment by firesidefox** [comment]
I test with **the latest code**, it works properly with ```https```. Are you using the latest? Give me more information.

**Comment by mithun-aticara** [comment]
Hi,

I have git cloned latest code and the issue 

 persists. I have attached my nginx.conf file. Also, attached 
stripped error log  of nginx.

git clone path: git clone https://github.com/F-Stack/f-stack.git
Attached nginx.conf and error.log file below:
[conf_and_err_log.tar.gz](https://github.com/F-Stack/f-stack/files/1875611/conf_and_err_log.tar.gz)

Error message: 
*1 http check ssl handshake
*1 http recv(): -1
*1 recv() failed (9: Bad file descriptor) while SSL handshaking, client: 192.168.174.231, server: 0.0.0.0:443
*1 close http connection: 104026
*1 event timer del: 104026: 1522842538661

Regards,
Mithun

**Comment by mithun-aticara** [comment]
Also my f-stack.conf file look this:

[dpdk]
## Hexadecimal bitmask of cores to run on.
lcore_mask=1
channel=4
promiscuous=1
numa_on=1
## TCP segment offload, default: disabled.
tso=0
## HW vlan strip, default: enabled.
vlan_strip=1

# enabled port list
#
# EBNF grammar:
#
#    exp      ::= num_list {"," num_list}
#    num_list ::= <num> | <range>
#    range    ::= <num>"-"<num>
#    num      ::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
#
# examples
#    0-3       ports 0, 1,2,3 are enabled
#    1-3,4,7   ports 1,2,3,4,7 are enabled
port_list=0

## Port config section
## Correspond to dpdk.port_list's index: port0, port1...
[port0]
addr=192.168.174.247
netmask=255.255.255.0
broadcast=192.168.1.255
gateway=192.168.1.1

## lcore list used to handle this port
## the format is same as port_list
# lcore_list= 0

## Packet capture path, this will hurt performance
#pcap=./a.pcap

## Kni config: if enabled and method=reject,
## all packets that do not belong to the following tcp_port and udp_port
## will transmit to kernel; if method=accept, all packets that belong to
## the following tcp_port and udp_port will transmit to kernel.
#[kni]
#enable=1
#method=reject
## The format is same as port_list
#tcp_port=80,443
#udp_port=53

## FreeBSD network performance tuning configurations.
## Most native FreeBSD configurations are supported.
[freebsd.boot]
hz=100

## Block out a range of descriptors to avoid overlap
## with the kernel's descriptor space.
## You can increase this value according to your app.
fd_reserve=1024

kern.ipc.maxsockets=262144

net.inet.tcp.syncache.hashsize=4096
net.inet.tcp.syncache.bucketlimit=100

net.inet.tcp.tcbhashsize=65536

kern.ncallout=262144

[freebsd.sysctl]
kern.ipc.somaxconn=32768
kern.ipc.maxsockbuf=16777216

net.link.ether.inet.maxhold=5

net.inet.tcp.fast_finwait2_recycle=1
net.inet.tcp.sendspace=16384
net.inet.tcp.recvspace=8192
net.inet.tcp.nolocaltimewait=1
net.inet.tcp.cc.algorithm=cubic
net.inet.tcp.sendbuf_max=16777216
net.inet.tcp.recvbuf_max=16777216
net.inet.tcp.sendbuf_auto=1
net.inet.tcp.recvbuf_auto=1
net.inet.tcp.sendbuf_inc=16384
net.inet.tcp.recvbuf_inc=524288
net.inet.tcp.sack.enable=1
net.inet.tcp.blackhole=1
net.inet.tcp.msl=2000
net.inet.tcp.delayed_ack=0

net.inet.udp.blackhole=1
net.inet.ip.redirect=0

**Comment by mithun-aticara** [comment]
Also attached f-stack.conf file
[fstack_Conf.tar.gz](https://github.com/F-Stack/f-stack/files/1875705/fstack_Conf.tar.gz)

**Comment by firesidefox** [comment]
It seems that nothing is wrong.
I'm afraid you need to confirm that ***the nginx***  you run was compiled from the latest code.

**Comment by mithun-aticara** [comment]
Hi,

As mentioned in previous comment I  git clone the source code from f-stack repo which I compile and run . Hope it is the latest one. Also I run in Ubuntu version 17 machine which has 8 cores. Can you please tell me the machine you are testing it and also if possible please share nginx.conf file and f-stack.conf file.

Regards
Mithun

**Comment by firesidefox** [comment]
**CentOS-7-x86_64-1611, kernel-3.10.0-514.el7**. The nginx.conf and f-stack.conf are the same with yours.
I will try to replicate it with the same environment as you have. 
Please provide the "ulimit -n" and the value of bad file descriptor.

**Comment by mithun-aticara** [comment]
Thanks for the reply ...

In the attached error log, I can see the logged message for accept () function as below
 
2018/04/04 17:17:58 [debug] 31609#0: *1 accept: 192.168.174.231:56316 fd:104026

The ip above is my client ip. 
fd: 104026, Is it the bad file descriptor you are asking for?

Also, will provide the "ulimit -n" value tomorrow as I am away from my machine. But I take care of setting the 'maximum open file descriptor value' of ulimit to  higher than worker_connections value of nginx.conf. (in my case 102400)

**Comment by mithun-aticara** [comment]
Some information about my system:
ulimit -n
103000


uname -a
Linux REST-API-DEV 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

Sorry, I wrongly mentioned as ubuntu 17 in prevous comment

**Comment by firesidefox** [comment]
```
2018/04/04 17:17:57 [debug] 31609#0: epoll timer: 0
2018/04/04 17:17:57 [debug] 31609#0: epoll timer: 0
```
I noticed that the log entry appeared continuously. Is that the same as the original?

**Comment by firesidefox** [comment]
I cannot replicate it. Sorry to say, but the log indicates that you are using outdated code. Previously, nginx-fstack used two threads to handle the kernel and f-stack, but now nginx-fstack use one. and you can use the new directive ```schedule_timeout``` to verify this.
```  
    Syntax: schedule_timeout time;
    Default: schedule_timeout 30ms;
    Context: main

    Sets a time interval for polling kernel_network_stack. The default value is 30 msec.

```

**Comment by mithun-aticara** [comment]
Sorry to confuse you by giving stripped version of the log. Reattached the original log in the attachment at the end.  Also, with the directive 'schedule_timeout 40ms;' inside ngix.conf file, the nginx is able to parse it . (Initially, when I put this directive inside server context it gave error: [emerg] "schedule_timeout" directive is not allowed here in .... Then put this directive right below the fstack_conf directive and it worked ). 

In the attachment, I have dumped my own log message in the file my_log_ssl.log. Basically I have modified the source file 'ngx_ff_module.c' to log the each of the fstack api calls/system calls with corresponding file descriptor and pids . Then I captured the log by trying to connect one ssl client to our nginx fstack server. The server failed to respond to client hello message. In the log, at the end, we can see ff_accept call, but then there is no ff_recieve.  

Also, attached the modified source file ngx_ff_module.c
[logs.tar.gz](https://github.com/F-Stack/f-stack/files/1889593/logs.tar.gz)




.

**Comment by firesidefox** [comment]
As mentioned above, the context of ```schedule_timeout``` is ```main```. So it shouldnot appear in server context.

What's you configure command line? 
What's your openssl version?
Your fd log file is not easy to read. You can just log the bad fd's infomation.
I got rid of some unuseful logs. You can alse provide a new nginx log.

I may need more time. Thanks for your patience!

**Comment by mithun-aticara** [comment]
1.) Configure command line is: ./configure --prefix=/usr/local/nginx_fstack --with-ff_module --with-http_ssl_module
2.) openssl version is : OpenSSL 1.0.2g
./sbin/nginx -V
nginx version: nginx/1.11.10
built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx_fstack --with-ff_module --with-http_ssl_module

3.) Give me some time for bad fd's log

**Comment by firesidefox** [comment]
It is caused by optimization options of the particular compiler version. But I still need time to fix it.

**Comment by mithun-aticara** [comment]
The ssl issue seems to be resolved with latest code... Thank you ....
