### ISSUE TITLE
epoll_ctl(1,2048) failed(9: Bad file descriptor)

### ISSUE THREAD

**Issue by herono2010** [F-Stack/f-stack#180]
ubuntu 12.04;
gcc 4.6.3

when i use "use kqueue;" in nginx.conf , it's ok ; but when i change "use epoll;", it has error in error.log and worker process does not work well. The error log like this:
"epoll_ctl(1,2048) failed (9: Bad file descriptor);
worker process 51062 exited with fatal code 2 and cannot be repspawned".

Look forward to your reply.

**Comment by whl739** [comment]
You could only use kqueue. We didn't implement  the epoll path.

**Comment by herono2010** [comment]
ok,thanks your reply.
