### ISSUE TITLE
Why use freeBSD stack ?

### ISSUE THREAD

**Issue by shanshanpt** [F-Stack/f-stack#181]
I feel that f-stack is add a dpdk interface in freeBSD, and then wrap a API similar to Linux. Am I right? 
Thanks.

**Comment by whl739** [comment]
Yes. We port FreeBSD's network stack to userspace, and adapt it to dpdk.

> Why use freeBSD stack ? 

FreeBSD's code is more easier to understand and has a looser license.

**Comment by shanshanpt** [comment]
Would you consider to cut down some not important logic in freeBSD kernel? 
I think the user stack should be as simple as possible. :)

**Comment by whl739** [comment]
Stability is more important for us. We developed an user stack, it's more simpler and faster, but in WAN, there are many problems.
