### ISSUE TITLE
DPDK changes

### ISSUE THREAD

**Issue by anandhkrishnan** [F-Stack/f-stack#187]
I was looking to port this to newer version of DPDK. Did you make any change in DPDK to make things work? If so, will you be able to summarise the changes/issues that you faced?

**Comment by whl739** [comment]
No, i din't make any change for dpdk.
But in newer version of dpdk, some APIs are changed.

**Comment by anandhkrishnan** [comment]
Ok. Thanks. I am able to compile things, but 50% of the times, packets just do not make it to the PMD driver (ixgbe) on the rx side. Rest of the 50% , things seem to work. Any issues you remember?

Things work well with the original f-stack and the bundled DPDK  in the same system.

**Comment by whl739** [comment]
I have no idea about this.

**Comment by anandhkrishnan** [comment]
Got it working. The lcore configuration did not match nginx process configuration.
