### ISSUE TITLE
nginx进程发起tcp连接，双向数据包不在同一个进程？

### ISSUE THREAD

**Issue by licko** [F-Stack/f-stack#19]
在测试nginx时，启动了2个nginx进程，进程A对应接收队列0，发送队列0；进程B对应接收队列1，发送队列1.进程A发起tcp 时，有时从外部服务器回的tcp报文被接收队列1收到，进入了进程B，但B没有tcp会话，就会reset这个连接，这个问题怎么解决呢？
      在in_pcb.c 端口分配时执行了ff_rss_check，感觉是要保证回来的数据包进入同一个进程，但我测试没有成功。

**Comment by derness** [comment]
I really suggest you reopen your issue that people all around the world can understand it.
Tips:please provide more details about your system such as configuration，NIC，and so on.
