### ISSUE TITLE
Integrating wrk to f-stack

### ISSUE THREAD

**Issue by linhopa** [F-Stack/f-stack#198]
I wonder if integrating wrk to f-stack is even possible? I've been trying to do it, but no success so far, the connection just hangs. I have one thread to hold all of the connections. I pass the aeEventLoop to the ff_run that calls aeMain(aeEventLoop)

**Comment by whl739** [comment]
F-Stack is multi-process architecture, it may not be well suiltable for wrk, and mostly it is used for server-side.
This is not to say that it couldn't be integrated with wrk, but there will be a lot of works to do.

**Comment by SamuelTames** [comment]
I attempted to port [dpdk-httpperf](https://github.com/ansyun/dpdk-httpperf) to f-stack by utilizing the f-stack wrappers from the redis port at `f-stack/app/redis-3.2.8/src/{ae*,anet*}`, and making wrk single threaded, but was unsuccessful.

With this method, I believe secondary f-stack wrk processes could be spawned to increase connections/load.
