### ISSUE TITLE
which benchmark tool did you use to get the nginx test result you posted in readme.md?

### ISSUE THREAD

**Issue by yuwenhua** [F-Stack/f-stack#20]
Is't reproducible？

**Comment by whl739** [comment]
We use [wrk](https://github.com/wg/wrk). 
To acquire high performance, you should edit config.ini, modify `lcore_mask` to run with more cores. For example, if you want to run with 4,8,16 cores, lcore_mask can be f, ff, ffff.
For `Connection:Keep-Alive` test, only a few machines are needed, but for `Connection:Close` test, you should modify nginx.conf: `keepalive_timeout  0` and use dozens of machines.

**Comment by yuwenhua** [comment]
thanks.
