### ISSUE TITLE
Problems on using ff_connect

### ISSUE THREAD

**Issue by jessica369tt** [F-Stack/f-stack#200]
Hello, I have read some issues on the usage of ff_connect. I know that ff_connect must be used as async I/O and add this socket to epoll/select later.
But, I always tried failed.
My code is below, please help.

int checkconnect(int fd)
{
        int epfd = ff_epoll_create(0);

        struct epoll_event ev;
        struct epoll_event events[MAX_EVENTS];

        ev.data.fd = fd;
        ev.events = EPOLLOUT | EPOLLIN | EPOLLET;

        ff_epoll_ctl(epfd, EPOLL_CTL_ADD, fd, &ev);

        int nevents = ff_epoll_wait(epfd,  events, MAX_EVENTS, 0);
        int i;

        if (nevents == 0){
                printf("nevents: %d\n", nevents);
                return -1;
        }
        for (i=0; i<nevents; i++){
                int err = -1;
                socklen_t len = sizeof(int);

                if (ff_getsockopt(events[i].data.fd, SOL_SOCKET, SO_ERROR, &err, &len) < 0){
                        ff_close(fd);
                        printf("getsockopt errno:%d %s\n", errno, strerror(errno));
                        return -2;
                }
        }

        return 0;
}

int loop()
{
    char *server_ip = "172.16.1.1";
    int server_port = 80;
    char *message = "hello world! hahahahahahahahahahhahahaha";

    int client_socket = ff_socket(AF_INET, SOCK_STREAM, 0);
    if (client_socket < 0){
                printf("ff_socket failed\n");
                exit(1);
        }

    int on = 1;
    ff_ioctl(client_socket, FIONBIO, &on);  /* unblock */

        int ret = 0;

        struct sockaddr_in server_addr;
        bzero(&server_addr, sizeof(server_addr));
        server_addr.sin_family = AF_INET;
        if (inet_aton(server_ip, &server_addr.sin_addr) == 0){
                printf("Server ip address Error\n");
                exit(1);
        }

        server_addr.sin_port = htons(server_port);

if ((ret = ff_connect(client_socket, (struct linux_sockaddr *)&server_addr, sizeof(server_addr))) < 0){
                if (errno == EINPROGRESS) {
                        int check_ret = checkconnect(client_socket);
                        if (check_ret < 0){
                                printf("checkconnect error: %d\n", check_ret);
                                return 0;
                        }
                }else{
                        printf("errno: %d\n", errno);
                        sleep(1);
                }
        }

        ff_send(client_socket, message, strlen(message), 0);

        printf("Already Send!\n");

        ff_close(client_socket);

        return 0;
}

int main(int argc, char * argv[])
{
    ff_init(argc, argv);
    ff_run(loop, NULL);
    return 0;
}

If I change these ff_api to host api, it works well. 
If using ff_api, "nevents" equals to zero forever.
I want to know why.
Please help. 
Thank you very much.

**Comment by firesidefox** [comment]
f-stack is polling-based. `loop`, the callback  of `ff_run`, is invoked each poll. So your client-creating code should not be here, but be between ```ff_init``` and ```ff_run```.

In addition, f-stack is designed for server-side, may not be suitable for client-side.

**Comment by jessica369tt** [comment]
@chadwill 's answer is right. Thanks a lot.

**Comment by liningjie418** [comment]
@jessica369tt Is the example can work correctly ? I use your code but found write error and found connect failed
