### ISSUE TITLE
f-stack nginx as reverse proxy not working 

### ISSUE THREAD

**Issue by mankalamanishkumar** [F-Stack/f-stack#202]
i am observing following packet on kni interface when nginx is configured as reverse proxy.

IP 192.168.xxx.x > 192.168.xxx.x: ICMP 172.xx.xx.xx tcp port 80 unreachable, length 68
i am running f-stack nginx on 192.168.xxx.x(kni) and a web server on 172.xx.xx.xx(bridge on same machine) 

and following is my nginx configuration 

server {
        listen 9090;
        location / {
            proxy_pass "http://172.xx.xx.xx";
        }
    }

Please help me

**Comment by firesidefox** [comment]
Do you want to test reverse proxy of f-stack nginx, and build your test environment mentioned above?
If so,  **KNI** does not work. You can use ```proxy_kernel_network_stack```.
```
    Syntax: proxy_kernel_network_stack on | off;
    Default: proxy_kernel_network_stack off;
    Context: http, stream, mail, server

    Determines whether proxy should go through kernel network stack or fstack.
```

**Comment by mankalamanishkumar** [comment]
Thank you, after enabling proxy_kernel_network_stack directive nginx **reverse proxy** is working.
but i want to use f-stack network stack instead of kernel network stack.
I want to build nginx as reverse proxy on f-stack network stack. Any idea?
setup will look like
client--------------|f-stack(nginx(reverse proxy))|------------server

Please help me

**Comment by firesidefox** [comment]
Tell me more about deployment view.  Are **client** and **proxy** on the same machine? Are you using **VM**? The number of your NICs?

**Comment by mankalamanishkumar** [comment]
Yes i am using 3 VM's and each VM i have two interfaces, one for management and other for f-stack.
VM1 - web client
VM2 - nginx(reverse proxy) running on f-stack
VM3 - web server
management interfaces are 192.122.xxx.xxx
f-stack interfaces are 192.168.xxx.xxx
Note : As we cannot bind management interface with DPDK so i have created f-stack interface for binding.
Issue is when **proxy_kernel_network_stack** is **off(Default)**  and trying to send a request from web client, nginx reverse proxy is failing to forward the packet and i am not observing any packets on VM3 f-stack interface.
Note : i have tried by enabling KNI and also by disabling KNI, observed same issue.

**Comment by firesidefox** [comment]
1. With ```proxy_kernel_network_stack on```, nginx still run on f-stack. it accepts client connections on f-stack, but connects to upstream through kernel.
2. The KNI provides the ability to receive/transmit packets from/to Linux kernel net interfaces. It cannot apply to your situation.
3. You may try to solve it by setting gateway or adding routing.

**Comment by mankalamanishkumar** [comment]
I have tried by adding gateway and route but it is not working.

**Comment by firesidefox** [comment]
Figure out your deployment topology. Find out where the packets go. Then you will really see what's what.

**Comment by mankalamanishkumar** [comment]
Ok
