### ISSUE TITLE
ngx_add_conn/ngx_del_conn will not work in ff_host_event

### ISSUE THREAD

**Issue by mscbg** [F-Stack/f-stack#203]
Hi， I have a question for Fstack/nginx. I see ngx_add_conn/ngx_del_conn is defined as ngx_event_actions.del_conn (kqueue event?)，that may mean ngx_ff_host_event may never called this function. I didn't know why. Events from kernel/ff_host never need to add_conn/del_conn？ But I see epoll events need these two function to bind conn event. If someone can give some directions, I will be very grateful.

**Comment by firesidefox** [comment]
F-stack nginx is drived by kqueue/fstack and epoll/kernel. Kqueue does not have `ngx_add_conn/ngx_del_conn`. If ngx_ff_host_event' `ngx_add_conn/ngx_del_conn` is enabled, f-stack nginx has to deal with them differently. Doing so will get minimal modification.

**Comment by mscbg** [comment]
@chadwill Thanks a lot.
