### ISSUE TITLE
make redis-3.2.8 error

### ISSUE THREAD

**Issue by qwe131829** [F-Stack/f-stack#209]
root@root123:/home/root123/f-stack/f-stack/app/redis-3.2.8# make
cd src && make all
make[1]: Entering directory '/home/root123/f-stack/f-stack/app/redis-3.2.8/src'
    CC adlist.o
    CC quicklist.o
    CC ae.o
In file included from ae.c:50:0:
ae_ff_kqueue.c:36:20: fatal error: ff_api.h: \u6ca1\u6709\u90a3\u4e2a\u6587\u4ef6\u6216\u76ee\u5f55
compilation terminated.
Makefile:226: recipe for target 'ae.o' failed
make[1]: *** [ae.o] Error 1
make[1]: Leaving directory '/home/root123/f-stack/f-stack/app/redis-3.2.8/src'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by whl739** [comment]
Did you export `FF_PATH`?

**Comment by qwe131829** [comment]
Firstly I think wheather it is the problem of path.But,it still come up this problem after setting the path
