### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by anandhkrishnan** [F-Stack/f-stack#210]
Hello,

I see in your roadmap the support for IPv6. All the code that is needed for IPv6 seem to be there, but under a feature IFDEF. Why is it ifdef-ed out and what do you think is needed to enable IPv6 support in the stack?

Thanks,

**Comment by whl739** [comment]
The original code is wrapped by `ifdef`.
You can add `#define INET6 1` in `lib/opt/opt_inet6.h`, and add the ipv6 related source files  
to `NETINET6_SRCS` in `lib/Makefile`.
I remembered that i compiled ipv6 before, but there were some erros, and i didn't resolve it.

**Comment by rperper** [comment]
It seems that there are some hard-coded references to the AF_INET family, particularly in dealing with the config files.  We'd really like to use F-Stack, but IPv6 is quite important to us.

**Comment by xait3207** [comment]
Hello, Is IPv6 now supported? How to do it?

**Comment by wkgcass** [comment]
any updates now?

**Comment by wdjwxh** [comment]
> any updates now?

the latest release says it supported ipv6. But there are some problems when i configure it.

**Comment by hyperxpro** [comment]
Any update?

**Comment by jfb8856606** [comment]
F-stack has support ipv6 and close this issue.
