### ISSUE TITLE
redis in the f-stack can not run

### ISSUE THREAD

**Issue by qwe131829** [F-Stack/f-stack#211]
l use f-stack from the quick start .make redis and make lib do not have but can not start the redis-server .
this is error after making test
[exception]: Executing test client: could not set permissions for file "./tests/tmp/server.rdb-startup-test.30462.6/dump.rdb": no such file or directory.
could not set permissions for file "./tests/tmp/server.rdb-startup-test.30462.6/dump.rdb": no such file or directory
    while executing
"file attributes [file join $server_path dump.rdb] -permissions 0222"
    (file "tests/integration/rdb.tcl" line 54)
    invoked from within
"source $path"
    (procedure "execute_tests" line 4)
    invoked from within
"execute_tests $data"
    (procedure "test_client_main" line 10)
    invoked from within
"test_client_main $::test_server_port "
Makefile:240: recipe for target 'test' failed
make[1]: *** [test] Error 1
make[1]: Leaving directory '/home/root123/f-stack/app/redis-3.2.8/src'
Makefile:6: recipe for target 'test' failed
make: *** [test] Error 2
in src ./redis-server 
root@root123:/home/root123/f-stack/app/redis-3.2.8/src# ./redis-server 
invalid proc-type

**Comment by whl739** [comment]
Run like this:
` ./redis-server --conf=config.ini --proc-type=primary --proc-id=0 /path/to/redis.conf`.

`--conf=config.ini --proc-type=primary --proc-id=0` these three arguments are necessary for f-stack, and the following arguments(for example: `redis.conf  --loglevel verbose`) are prepared for redis.
