### ISSUE TITLE
F-stack/NGINX with asynch ssl

### ISSUE THREAD

**Issue by mscbg** [F-Stack/f-stack#212]
Is there anyone using NGINX as a https server with QAT Acceleration card or other asynchronous SSL(rpc network call)？ I want to know if we can do this by using f-stack/nginx. I have tried this by add 'ngx_add_async_conn' function in  ff_host_event. It worked fine by curl， but if using ab for pressure measurement，nginx will crash. I tried debug this but it is really difficult in asynchronous environment. How did tencent do this? Have you using f-stack in HTTPS? https://blog.csdn.net/suhuaiqiang_janlay/article/details/60962697

**Comment by firesidefox** [comment]
More information about your need. `RPC` through kernel network? How you achieved it?

**Comment by mscbg** [comment]
Using ff-host event to control openssl async fd just like QAT. And rpc is just a new thread with kernel event. Every nginx worker has a rpc thread. Rpc thread is used to call remote rsa calculation by QAT server.

**Comment by firesidefox** [comment]
1. Fstack-nginx is drived by `fstack-event`(fstack-kqueue) and `host-event`(kernel-epoll), without modifying origin architectural mode and business process model. I don't think your *rpc module* should, either. You can add it to `host-event`. In addition, it should be asynchronous.
2. Paste your code, then someone can help you to fix bug.
