### ISSUE TITLE
How does fstack make redis be multicore scalable?

### ISSUE THREAD

**Issue by jianghuiyou** [F-Stack/f-stack#213]
As you know, redis runs in single-thread mode. Even if it can be configured as master-slave mode, its every instance still runs on different port. Fstack didn't show any benchmark related to redis, I'm so curious about that.

**Comment by qwe131829** [comment]
Can you run redis successfully？

**Comment by jianghuiyou** [comment]
Not yet, I'm just curious about this. If fstack make redis multicore scalable, I'will run it and learn the source code if necessary.

**Comment by whl739** [comment]
We havn't support multicore scalable for redis, you can only use one process for redis.
