### ISSUE TITLE
Do we support hooks in f-stack?

### ISSUE THREAD

**Issue by mankalamanishkumar** [F-Stack/f-stack#215]
If I want to provide some additional functionality at each layer, example hooks in Linux. how can I achieve that using f-stack.

**Comment by whl739** [comment]
I think `pfil_hook` is much suitable for your case. for ether packets, you can use `link_pfil_hook`, and for ip packets, you can use `inet_pfil_hook`.
You can add a kernel module and compile it to f-stack.
If you have a `hook.c` like this:
```
static int hook_init(void *);
SYSINIT(hook_init, SI_SUB_PROTO_DOMAIN, SI_ORDER_ANY, hook_init, NULL);

static int
in_hook(void *arg, struct mbuf **mp, struct ifnet *ifp,
    int dir, struct inpcb *inp)
{

}

static int
out_hook(void *arg, struct mbuf **mp, struct ifnet *ifp,
    int dir, struct inpcb *inp)
{

}

static int
hook_init(void *arg)
{
    struct pfil_head *ph_inet;

    ph_inet = pfil_head_get(PFIL_TYPE_AF, AF_INET);
    if (ph_inet != NULL) {
        pfil_add_hook(in_hook, NULL, PFIL_IN, ph_inet);
        pfil_add_hook(out_hook, NULL, PFIL_OUT, ph_inet);
    }

    return (0);
}
```
and compile:
```
cd f-stack/lib
export "KMOD_SRCS=/your/kmod/path/hook.c /your/kmod/path/b.c"
export "CONF_CFLAGS=-I/your/kmod/path"
make
```

**Comment by mankalamanishkumar** [comment]
Thank you for the response, can we use ngctl to create node and communicate with other stack nodes? if yes, then what is the difference between above mention approach(PFIL_HOOKS) and ngctl approach?

**Comment by whl739** [comment]
Yes, they are different. You can google them.
