### ISSUE TITLE
 sudo ./tools/ifconfig/ifconfig -p 0 not diplaying packet statistics 

### ISSUE THREAD

**Issue by mankalamanishkumar** [F-Stack/f-stack#216]
sudo ./tools/ifconfig/ifconfig -p 0 
I am able to see mac and ip on f-stack-0 interface, how can I know the packet statistic which are processed by f-stack?

**Comment by whl739** [comment]
See below:
https://forums.freebsd.org/threads/freebsd-11-not-showing-rx-tx-packets-and-counts-using-ifconfig-getifaddrs.60010/
https://serverfault.com/questions/836079/freebsd-11-not-showing-rx-tx-packets-and-counts?rq=1
