### ISSUE TITLE
EC2 issue

### ISSUE THREAD

**Issue by Luo-Liang** [F-Stack/f-stack#219]
Hi there!

We're following the script provided in https://github.com/F-Stack/f-stack/blob/master/doc/Launch_F-Stack_on_AWS_EC2_in_one_minute.md, but the process hang at 

`ifconfig eth0 down`

And causes the SSH connection to drop. I can no longer connect to the instance.

I noticed the following line in the script:

`ifconfig veth0 ${myaddr}  netmask ${mymask}  broadcast ${mybc} hw ether ${myhw}
route add -net 0.0.0.0 gw ${mygw} dev veth0`

Does this mean F-Stack will take over veth0 and I should use SSH again? If so, do you know why I can no longer connect to it?

Thanks!

**Comment by whl739** [comment]
After set up veth0, f-stack can communicate with kernel through kni, then SSH can be used.
Do the follow steps:
1. check config.ini, see section kni and its items.
2. check the nginx process, see whether it is started successful.
3. Did you execute these commands with a script file or execute each command manually.

**Comment by Luo-Liang** [comment]
This is resolved as suggested. Thanks!
