### ISSUE TITLE
Compiling On Oracle Virtual Box.

### ISSUE THREAD

**Issue by maxiprimo** [F-Stack/f-stack#221]
Building fstack v1.12 with dpkd x86_64-native-linuxapp-gcc successfully, all Libarieries generated, the example build failed, using ubuntu within oracle virtual box via bridged network. 

There Exist Linking Needs Through the Object  "/freebsd/vm/uma_core.c". 

the problem are at the freebsd x64 support includes, that doesnt linked correctly, while build fstack library. there are missing of **smp** and for **counter** and **ppu** implementations, matched by a right target detected of an intel i5 ivy x64 cpu.

some view in at source-tree shows this implementations:

f-stack-1.12\freebsd\kern\subr_smp.c: **void smp_rendezvous(...)**
f-stack-1.12\freebsd\amd64\vmm\vmm.c: **void vm_smp_rendezvous(...)**
f-stack-1.12\freebsd\amd64\include\counter.h: **extern struct pcpu __pcpu[1];**
f-stack-1.12\freebsd\amd64\vmm\amd\svm.c: **extern struct pcpu __pcpu[];**

that partly are in ff_glue.c implemented. 

may that a problem only at building on the oracle virtual box? i cant deactivate 64bit virtual maschine hardware features VT-x and AMD-V.

how can them fixed?

pdx@ubuntu:/data/fstack/example sudo make c -0 -gdwarf-2 -I../lib -o "helloworld" main.c -L../lib -81,--whole-archive,-lfstack,--no-whole-ar hive -L../dpdk/x86_64-native-linuxapp-gcc/lib -81,--whole-archive,-1dpdk,--no-whole-archive -W1,--n .-whole-archive -1rt -lm -1d1 -1crypto -pthread -lnuma **../lib/libfstack.a(libfstack.ro): In function 'counter_u64_zero': uma_core.c:(.text+0x20226): undefined reference to 'smp_no_rendevous_barrier'** ma_core.c:(.text+0x20235): undefined reference to "smp_rendezvous' ../lib/libfstack.a(libfstack.ro): In function 'counter_u64_alloc': ma_core.c:(.text+Ox2029c): undefined reference to 'smp_no_rendevous_barrier' ma_core.c:(.text+Ox202b3): undefined reference to 'smp_rendezvous' ../lib/libfstack.a(libfstack.ro): In function "sysctl_handle_counter_u64': ma_core.c:(.text+0x20355): undefined reference to 'smp_no_rendevous_barrier' ma_core.c:(.text+Ox2036c): undefined reference to 'smp_rendezvous' ../lib/libfstack.a(libfstack.ro): In function "sysctl_handle_counter_u64_array': ma_core.c:(.text+0x20439): undefined reference to "smp_no_rendevous_barrier' ma_core.c:(.text+0x20462): undefined reference to 'smp_rendezvous' ../lib/libfstack.a(libfstack.ro): In function 'if_transmit': if.c:(.text+Ox3df7f): undefined reference to '__pcpu' if.c:(.text+Ox3dfe7): undefined reference to '__pcpu' ../lib/libfstack.a(libfstack.ro): In function 'if_inc_counter': ma_core.c:(.text+Ox3f8e5): undefined reference to '__pcpu' **../lib/libfstack.a(libfstack.ro): In function 'if_handoff': uma_core.c:(.text+0x423c8): undefined reference to '__pcpu'** uma_core.c:(.text+0x42452): undefined reference to "_pcpu' ../lib/libfstack.a(libfstack.ro):ip_reass.c:(.text+0x58467): more undefined references to pcpu' f 'How ollect2: error: Id returned 1 exit status akefile:17: recipe for target 'all' failed ake: mm* Call] Error 1 pdx@ubuntu:/data/fstack/example$ _

**Comment by whl739** [comment]
See #105 , #99 .

**Comment by maxiprimo** [comment]
Thank You!.
