### ISSUE TITLE
Looks like message pool in ff_dpdk_if is redundant 

### ISSUE THREAD

**Issue by chavalev** [F-Stack/f-stack#223]
Hi , 
In init_msg_ring ( ff_dpdk_if.c) there is an allocation for mempool called message_pool, but it does not look like it is used .

**Comment by firesidefox** [comment]
See [f-stack/tools/compat/ff_ipc.c](https://github.com/F-Stack/f-stack/blob/master/tools/compat/ff_ipc.c).
