### ISSUE TITLE
Could not able to run example/helloworld_epoll(main_epoll.c) on multiple core

### ISSUE THREAD

**Issue by mankalamanishkumar** [F-Stack/f-stack#225]
i have changed lcore_mask=7 that means binary(helloworld_epoll) should run on core 0,1,2 but i am observing only one process and it is running on core 0.
12759 pts/0    Rl     9:04 ./example/helloworld_epoll --conf config.ini --proc-type=primary --proc-id=0

please help me here to run helloworld_epoll on multi core

**Comment by mankalamanishkumar** [comment]
Above change are working for nginx and i am able to see multiple nginx instances. But why it is not working for simple example application.

**Comment by mankalamanishkumar** [comment]
when i try to run following command to create one more process i am getting error
**cmd**
sudo ./example/helloworld_epoll --conf config.ini --proc-type=secondary --proc-id=1

**error**
lcore: 1, port: 0, queue: 1
create mbuf pool on socket 0
create ring:dispatch_ring_p0_q0 success, 2047 ring entries are now free!
PANIC in init_dispatch_ring():
create ring:dispatch_ring_p0_q1 failed!
8: [./example/helloworld_epoll() [0x407679]]
7: [/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f69b0036830]]
6: [./example/helloworld_epoll() [0x4078eb]]
5: [./example/helloworld_epoll() [0x51cf98]]
4: [./example/helloworld_epoll() [0x504f6e]]
3: [./example/helloworld_epoll() [0x4feab1]]
2: [./example/helloworld_epoll() [0x40703a]]
1: [./example/helloworld_epoll() [0x5e24fb]]
Aborted (core dumped)

**Comment by mankalamanishkumar** [comment]
how can i make example binary to run on multiple core?

Thanks in advance

**Comment by whl739** [comment]
Run `start.sh` or 
```
./example/helloworld_epoll --conf=config.ini --proc-type=primary --proc-id=0
./example/helloworld_epoll --conf=config.ini --proc-type=secondary --proc-id=1
./example/helloworld_epoll --conf=config.ini --proc-type=secondary --proc-id=2
```

**Comment by mankalamanishkumar** [comment]
Thanks it was my h/w issue. i have tried on new h/w and it's working.
Thanks f-stack team
