### ISSUE TITLE
How to use ipfw in "tools" directory?

### ISSUE THREAD

**Issue by ZhongqiXiao** [F-Stack/f-stack#229]
i need to use ipfw to filter some kind of packet,for example, I want to allow  packets  from any to my ip address and port 80
i just tpyed the command in `tools/ipfw` :
  `./ipfw -P 0 add allow tcp from any to 192.168.10.10 80`
and i got 
`ipfw: getsockopt(IP_FW_XADD): Operation not supported`
other similar command  would be the similar result (xxx...:Operation not supported).
Do I need to complie  the whole freebsd directory?
Please help me to solve this problem.
Thank you!

**Comment by whl739** [comment]
`ipfw` is not compiled by default.
Uncomment `#FF_IPFW=1` in lib/Makefile.

**Comment by ZhongqiXiao** [comment]
It‘s working.Thank you very much!
