### ISSUE TITLE
Is it possible to have a specific listener per process in fstack ?

### ISSUE THREAD

**Issue by rock59** [F-Stack/f-stack#231]
I want to port a project to fstack . The project is : 

1. Multi-process 
2. Based on epoll
3. Incoming TCP connections load balanced between worker processes by SO_REUSEPORT (linux kernel >= 3.9)
4. All worker processes share port 80 for main service
5. For management RPC service , every distinct worker process listens to a process specific port (for example process 1 listens to port 8081 , processes 2 listens to 8082 and so on)

Is it possible to have a specific listener per process in fstack ?

Thanks fstack team for your great project

**Comment by whl739** [comment]
Yes, it's very suitable.
F-Stack is multi-process architecture, every f-stack process is load balanced by RSS, and has its own network stack, so all processes can listen 80 and no need to set SO_REUSEPORT. And also f-stack provides epoll interface.

**Comment by rock59** [comment]
Thansk @whl739 for your quick reply but this is my concern :

If worker process 1 listens on port 8081 and worker process 2 listens on port 8082 and so on , is it guaranteed that every incoming tcp client connected to port 8081 always go to process 1 (lcore 1) and every incoming tcp client connected to port 8082 always go to process 2 (lcore 2) and so on by RSS ?

**Comment by whl739** [comment]
Emm, this is a problem, `rss`  couldn't support this, but `fdir` can.
Unfortunately f-stack hasn't support `fdir` for now.

**Comment by whl739** [comment]
And another solution, dispatch packets by yourself.
F-Stack provides an API `ff_regist_packet_dispatcher`, you can register a callback function to dispatch the 
incoming packets.
```
/*
 * Packet dispatch callback function.
 * Implemented by user.
 *
 * @param data
 *   The data pointer of this packet.
 * @param len
 *   The length of this packet.
 * @param queue_id
 *   Current queue of this packet.
 * @param nb_queues
 *   Number of queues to be dispatched.
 *
 * @return 0 to (nb_queues - 1)
 *   The queue id that the packet will be dispatched to.
 * @return -1
 *   Error occurs or packet is handled by user, packet will be freed.
 *
 */
typedef int (*dispatch_func_t)(void *data, uint16_t len,
    uint16_t queue_id, uint16_t nb_queues);

/* regist a packet dispath function */
void ff_regist_packet_dispatcher(dispatch_func_t func);
```
For example:
```
process-1 8081 --->rx queue 0
process-2 8082 --->rx queue 1

func dispatch_callback(data, len, queue_id, nb_queues)
{
    check packets-->data
    if tcp:
        if port is 8081:
            return 0
        else if port is 8082:
            return 1
    else:
        return queue_id
}
```

**Comment by rock59** [comment]
Great .. thanks .. This solution seems to work for me now
