### ISSUE TITLE
when use FD_SET() function in f-stack network programing, causing core dumped

### ISSUE THREAD

**Issue by SuiBianJun** [F-Stack/f-stack#236]
hello f-stack team.
when i want to achieve I/O multiplexing by ff_select() in socket, but passing the returned value of ff_socket() to FD_SET() function's first parameter causing core dumped.
i print returned value of ff_socket(), finding the value greater than or equal 1024 every call. but FD_SETSIZE is 1024. 
if i passing a parameter which less than 1024, FD_SET() function is ok. so maybe exist funtion to replace FD_SET() ?, or can change initial returned value (and how to do) of ff_socket() because the original socket() function return a small number of descriptor.
expecting your reply, thanks.

**Comment by SuiBianJun** [comment]
oh, i know how to change the initial returned value of ff_socket(). but meeting a new problem. after call ff_select() function, it blocked all the time even a client trying to connect.

**Comment by SuiBianJun** [comment]
oh, after looking code that use ff_select in source code, i have clear my problem.

**Comment by WoolenWang** [comment]
@SuiBianJun pls tell us how you solve this problem or add a pr to make this fix?

i have the same issue

**Comment by liningjie418** [comment]
I met the same issue too, please tell me the way to solve it ?

**Comment by WoolenWang** [comment]
> I met the same issue too, please tell me the way to solve it ?

the best way to solve it is "dont't use select" ..............

use epoll or kqueue...

@linj170309

**Comment by liningjie418** [comment]
@WoolenWang @SuiBianJun Thanks for your reply, but how the thread opener solve the issue ?

**Comment by ghpass** [comment]
resolved? 
who has successed in ff_select?  Please give an example. Thanks a lot!
