### ISSUE TITLE
Observed compilation error

### ISSUE THREAD

**Issue by mankalamanishkumar** [F-Stack/f-stack#237]
i cloned the code and when trying to build the lib, getting following error.

/data/f-stack/lib$ sudo make
cc -c -O2 -frename-registers  -funswitch-loops -fweb -Wall -Werror -include /data/f-stack/lib/../dpdk/x86_64-native-linuxapp-gcc/include/rte_config.h -march=native -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2 -I/data/f-stack/lib/../dpdk/x86_64-native-linuxapp-gcc/include  -I. -Werror -Wno-unused-variable  ff_dpdk_if.c
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:37:0,
                 from /data/f-stack/lib/../dpdk/x86_64-native-linuxapp-gcc/include/rte_vect.h:57,
                 from /data/f-stack/lib/../dpdk/x86_64-native-linuxapp-gcc/include/rte_memcpy.h:46,
                 from ff_dpdk_if.c:32:
/data/f-stack/lib/../dpdk/x86_64-native-linuxapp-gcc/include/rte_memcpy.h: In function ‘rte_memcpy_generic’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
 _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
 ^
In file included from ff_dpdk_if.c:32:0:
/data/f-stack/lib/../dpdk/x86_64-native-linuxapp-gcc/include/rte_memcpy.h:626:9: error: called from here
         _mm_storeu_si128((__m128i *)((uint8_t *)dst + 7 * 16), _mm_alignr_epi8(xmm8, xmm7, offset));        \
         ^
/data/f-stack/lib/../dpdk/x86_64-native-linuxapp-gcc/include/rte_memcpy.h:668:16: note: in expansion of macro ‘MOVEUNALIGNED_LEFT47_IMM’
     case 0x01: MOVEUNALIGNED_LEFT47_IMM(dst, src, n, 0x01); break;    \
                ^
/data/f-stack/lib/../dpdk/x86_64-native-linuxapp-gcc/include/rte_memcpy.h:822:2: note: in expansion of macro ‘MOVEUNALIGNED_LEFT47’
  MOVEUNALIGNED_LEFT47(dst, src, n, srcofs);
  ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:37:0,
                 from /data/f-stack/lib/../dpdk/x86_64-native-linuxapp-gcc/include/rte_vect.h:57,
                 from /data/f-stack/lib/../dpdk/x86_64-native-linuxapp-gcc/include/rte_memcpy.h:46,
                 from ff_dpdk_if.c:32:
/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
 _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
 ^
In file included from ff_dpdk_if.c:32:0:

**on my previous ubuntu 14 it was working and now i have created a new VM(ubuntu 16.04).
what might be the issue, please help me here.**

**Comment by mankalamanishkumar** [comment]
Issue got resolved, there was some VM configuration issue.

**Comment by yancyzhao** [comment]
@mankalamanishkumar I have the same problem, do you remember how to solve it? ths
