### ISSUE TITLE
[Question] set MTU in example (helloworld)

### ISSUE THREAD

**Issue by Luo-Liang** [F-Stack/f-stack#239]
Hi!

Is there an option to enable jumbo frame (MTU=9000) in f-stack?

Many thanks!

**Comment by whl739** [comment]
`tools/ifconfig` can set mtu. But there is a problem here, the mtu value can not be more than 1500 for now.
We will fix it in the near future.

**Comment by Luo-Liang** [comment]
Thanks!

**Comment by jfb8856606** [comment]
Update: F-Stack now supports setting MTU > 1500 (jumbo frames up to 9000) on the `dev` branch. Enable it with `mtu_enable=1` in the `[dpdk]` config section and set `mtu` per port. See #490 and #720 for details.
