### ISSUE TITLE
Performance Tuning on EC2 c5.18xlarge

### ISSUE THREAD

**Issue by Luo-Liang** [F-Stack/f-stack#241]
Hi, 
I'm testing out F-stack on EC2's C5.18xlarge instance, which has 25Gbps NIC, 144GB memory and 72 processor cores.

I'm using a `config.ini` like this:

```
[dpdk]: lcore_mask=0x1
[dpdk]: channel=4
[dpdk]: promiscuous=1
[dpdk]: numa_on=1
[dpdk]: tso=1
[dpdk]: vlan_strip=1
[dpdk]: port_list=0
[port0]: addr=172.31.2.61
[port0]: netmask=255.255.240.0
[port0]: broadcast=172.31.15.255
[port0]: gateway=172.31.0.1
[freebsd.boot]: hz=100
[freebsd.boot]: fd_reserve=1024
[freebsd.boot]: kern.ipc.maxsockets=262144
[freebsd.boot]: net.inet.tcp.syncache.hashsize=4096
[freebsd.boot]: net.inet.tcp.syncache.bucketlimit=100
[freebsd.boot]: net.inet.tcp.tcbhashsize=65536
[freebsd.boot]: kern.ncallout=262144
[freebsd.sysctl]: kern.ipc.somaxconn=32768
[freebsd.sysctl]: kern.ipc.maxsockbuf=167772160
[freebsd.sysctl]: net.link.ether.inet.maxhold=5
[freebsd.sysctl]: net.inet.tcp.fast_finwait2_recycle=1
[freebsd.sysctl]: net.inet.tcp.sendspace=13107200
[freebsd.sysctl]: net.inet.tcp.recvspace=13107200
[freebsd.sysctl]: net.inet.tcp.nolocaltimewait=1
[freebsd.sysctl]: net.inet.tcp.cc.algorithm=cubic
[freebsd.sysctl]: net.inet.tcp.sendbuf_max=167772160
[freebsd.sysctl]: net.inet.tcp.recvbuf_max=167772160
[freebsd.sysctl]: net.inet.tcp.sendbuf_auto=1
[freebsd.sysctl]: net.inet.tcp.recvbuf_auto=1
[freebsd.sysctl]: net.inet.tcp.sendbuf_inc=1048576
[freebsd.sysctl]: net.inet.tcp.recvbuf_inc=1048576
[freebsd.sysctl]: net.inet.tcp.sack.enable=1
[freebsd.sysctl]: net.inet.tcp.blackhole=1
[freebsd.sysctl]: net.inet.tcp.msl=2000
[freebsd.sysctl]: net.inet.tcp.delayed_ack=0
[freebsd.sysctl]: net.inet.udp.blackhole=1
[freebsd.sysctl]: net.inet.ip.redirect=0
```

I'm using `helloworld_epoll` to test performance. The actual code can be found here, https://github.com/luo-liang/f-stack-bw2, which is basically the same as `helloworld_epoll`: the client keeps asking for data of size S, and the server keeps responding. 

Both the client and server has a core mask of 1 (the NIC has only 1 rx queue)

The result i am seeing is:

Packet Payload Size | Baseline Linux | F-Stack
-- | -- | --
1 | 0.000165Gbps | 0.000071Gbps
2 | 0.000334Gbps | 0.000144Gbps
4 | 0.000671Gbps | 0.000298Gbps
8 | 0.001324Gbps | 0.000595Gbps
16 | 0.002637Gbps | 0.001152Gbps
32 | 0.005278Gbps | 0.002381Gbps
64 | 0.010121Gbps | 0.004754Gbps
128 | 0.020959Gbps | 0.009401Gbps
256 | 0.041805Gbps | 0.019053Gbps
512 | 0.080563Gbps | 0.037926Gbps
1024 | 0.158882Gbps | 0.076187Gbps
2048 | 0.302673Gbps | 1.580556Gbps
4096 | 0.580383Gbps | 3.535004Gbps
8192 | 1.074097Gbps | 6.113065Gbps
16384 | 2.456177Gbps | 6.128035Gbps
32768 | 4.871937Gbps | 6.118858Gbps
65536 | 8.899414Gbps | 6.113562Gbps
131072 | 8.941406Gbps | 6.114827Gbps

As you can see, F-stack is only better than Linux's default TCP when the content size is 2048-32768 bytes. 

I would expect F-stack to give much better throughput than Linux, but is not the case. 

Is there any specific tuning I need to do? Does the config.ini file look good?
I'm also suspecting MTU, because the VM default MTU is 9001 -- is there a way to change MTU size?

Many thanks for your support!

**Comment by jfb8856606** [comment]
We will test it and reply later.

**Comment by jfb8856606** [comment]
F-Stack  send packet only when certain conditions are met:
1. m_table is filled by 32 packets
2. or delay 100 us.
So you can modify code to send packet immediately in your test case.
```
diff --git a/lib/ff_dpdk_if.c b/lib/ff_dpdk_if.c
index 21691fc..29063a4 100644
--- a/lib/ff_dpdk_if.c
+++ b/lib/ff_dpdk_if.c
@@ -1276,10 +1276,12 @@ send_single_packet(struct rte_mbuf *m, uint8_t port)
     len++;

     /* enough pkts to be sent */
-    if (unlikely(len == MAX_PKT_BURST)) {
-        send_burst(qconf, MAX_PKT_BURST, port);
-        len = 0;
-    }
+    //if (unlikely(len == MAX_PKT_BURST)) {
+    //    send_burst(qconf, MAX_PKT_BURST, port);
+    //    len = 0;
+    //}
+    send_burst(qconf, len, port);
+    len = 0;

     qconf->tx_mbufs[port].len = len;
     return 0;
```

And you can enable the config delayed ack and test again in this test case to reduce the numbers of packets. 
`net.inet.tcp.delayed_ack=1`

**Comment by Luo-Liang** [comment]
Thanks! Will test again!

**Comment by jfb8856606** [comment]
This patch is applied to little content size, and run “ping-pang” test.
It shouldn't be modified in the actual  service.

**Comment by jfb8856606** [comment]
see 59bb71f
