### ISSUE TITLE
can appoint specific process to specific rx_queue? 

### ISSUE THREAD

**Issue by SuiBianJun** [F-Stack/f-stack#242]
hi, f-stack team.
i have a questions.
if my nic hava two rx_queue(rx_0, rx_1). then, run helloworld in single core like: ./helloworld ../config.ini -p 0 -t primary. 
maybe the process will use rx_0. can i appoint it use rx_1 ?

**Comment by jfb8856606** [comment]
F-Stack start from rx_0 always，and you can try modify the code to appoint it use rx_1 when set the rx queues.
I'm not sure it can work properly.

**Comment by SuiBianJun** [comment]
thanks, I just do some test now. I will try your method.
