### ISSUE TITLE
how many network elements use in RSS compute?

### ISSUE THREAD

**Issue by SuiBianJun** [F-Stack/f-stack#243]
hi, f-stack team.
another question.
in f-stack, maybe RSS compute use: src_ip, dst_ip, src_port, dst_port  or use: src_ip, dst_ip, proto_code, src_port, dst_port  or use 7 tuples?  thanks

**Comment by jfb8856606** [comment]
F-Stack use 4 tuples to do RSS compute, you can find it in func `ff_rss_check` in file `ff_dpdk_if.c`.
