### ISSUE TITLE
Fail to run multiple workers with nginx

### ISSUE THREAD

**Issue by moritzsteiner** [F-Stack/f-stack#244]
I've followed the recipe and successfully managed to run nginx using f-stack. However, the default configuration makes use of one worker thread only. I'd like to increase this to 4 since my test machine has 4 cores (actually two cores with two hyperthreads each) and the NIC used has 4 queues. My setup runs ubuntu 18.04 on ec2 with 2 ena NICs (one for management and one for DPDK). 
When running with 4 workers, the error log is full with message showing dying workers that a restarted immediately:
```
# tail -20 /usr/local/nginx_fstack/logs/error.log 
EAL: No free hugepages reported in hugepages-1048576kB
EAL: FATAL: rte_service_init() failed

EAL: FATAL: rte_service_init() failed

EAL: FATAL: rte_service_init() failed

2018/07/03 18:24:23 [notice] 22592#0: signal 29 (SIGIO) received
2018/07/03 18:24:23 [notice] 22592#0: signal 29 (SIGIO) received
2018/07/03 18:24:23 [notice] 22592#0: signal 17 (SIGCHLD) received
2018/07/03 18:24:23 [notice] 22592#0: worker process 23318 exited with code 1
2018/07/03 18:24:23 [notice] 22592#0: worker process 23319 exited with code 1
2018/07/03 18:24:23 [notice] 22592#0: start worker process 23324
2018/07/03 18:24:23 [notice] 22592#0: start worker process 23325
EAL: Detected 4 lcore(s)
EAL: Detected 4 lcore(s)
2018/07/03 18:24:23 [notice] 22592#0: signal 17 (SIGCHLD) received
2018/07/03 18:24:23 [notice] 22592#0: worker process 23317 exited with code 1
2018/07/03 18:24:23 [notice] 22592#0: start worker process 23326
EAL: Detected 4 lcore(s)

```

Any idea what I'm doing wrong?

Here is my config:
```

# sudo head /usr/local/nginx_fstack/conf/nginx.conf

# root account is necessary.
user  root;
# should be equal to the lcore count of `dpdk.lcore_mask` in f-stack.conf.
worker_processes 4;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
error_log  logs/error.log  debug;


# sudo head /usr/local/nginx_fstack/conf/f-stack.conf 
[dpdk]
## Hexadecimal bitmask of cores to run on.
lcore_mask=0xf
channel=4
promiscuous=1
numa_on=1
## TCP segment offload, default: disabled.
tso=1
## HW vlan strip, default: enabled.
vlan_strip=1
 

# /usr/local/share/dpdk/usertools/cpu_layout.py 
======================================================================
Core and Socket Information (as reported by '/sys/devices/system/cpu')
======================================================================

cores =  [0, 1]
sockets =  [0]

       Socket 0     
       --------     
Core 0 [0, 2]       
Core 1 [1, 3]    

# /usr/local/share/dpdk/usertools/dpdk-devbind.py -s | head

Network devices using DPDK-compatible driver
============================================
0000:00:06.0 'Elastic Network Adapter (ENA) ec20' drv=igb_uio unused=ena

Network devices using kernel driver
===================================
0000:00:05.0 'Elastic Network Adapter (ENA) ec20' if=ens5 drv=ena unused=igb_uio *Active*

# ethtool -S ens5 | grep rx_bytes
     queue_0_rx_bytes: 173149573
     queue_1_rx_bytes: 72148634
     queue_2_rx_bytes: 46515951
     queue_3_rx_bytes: 21579089



```

**Comment by jfb8856606** [comment]
Ubuntu18.04  use hugepages-1048576kB default, our tutorial use hugepages-2048kB.
One way is modify set hugepages like this and reboot the OS.
```
sudo vim /etc/default/grub
GRUB_CMDLINE_LINUX_DEFAULT="...... default_hugepagesz=1G hugepagesz=1G hugepages=2"
sudo updata-grub
```
Or use hugepages-2048kB default

**Comment by moritzsteiner** [comment]
Thanks for the comment. In fact I've been following your tutorial and I make use of 2048kB hugepages. The warning message above is just to say that there are no 1048576kB available (because I've setup 2048kB pages). 
The thing is it's working alright with just one core! How do I get it to work with multiple cores?

**Comment by jfb8856606** [comment]
I will test it in EC2, but there is no AMI of ubuntu 18.04, is your test environment upgrade from ubuntu16.04?

**Comment by jfb8856606** [comment]
reappearCannot get attribute for ena device

**Comment by jfb8856606** [comment]
I have reappear this issue, the secondary processes init the NIC of Amazon ena(Elastic Network Adapter)  failed.
`PMD: Cannot get attribute for ena device rc= -19`
I will find the reason of it.

**Comment by moritzsteiner** [comment]
Thanks for looking into this. I used the marketplace to find an AMI for Ubuntu 18.04:
![image](https://user-images.githubusercontent.com/2161790/42592647-fd0453b0-84fe-11e8-97c8-7ec97cf4d221.png)

**Comment by jfb8856606** [comment]
I had test it, and the reason is: 
The secondary processes call `rte_eal_init` to init ena NIC will memset the ena's `adapter` struct, cause the  primary process crash.
I will report this issue to DPDK, and you can temporarily modify it like this, and F-Stack working properly.
```
diff --git a/dpdk/drivers/net/ena/ena_ethdev.c b/dpdk/drivers/net/ena/ena_ethdev
.c
index aa24ef3..89dff54 100644
--- a/dpdk/drivers/net/ena/ena_ethdev.c
+++ b/dpdk/drivers/net/ena/ena_ethdev.c
@@ -1278,7 +1278,8 @@ static int eth_ena_dev_init(struct rte_eth_dev *eth_dev)

        static int adapters_found;

-       memset(adapter, 0, sizeof(struct ena_adapter));
+       // Temporary modification for multi process
+       //memset(adapter, 0, sizeof(struct ena_adapter));
        ena_dev = &adapter->ena_dev;

        eth_dev->dev_ops = &ena_dev_ops;
```

**Comment by moritzsteiner** [comment]
Thank you! The patch works great, I can run f-stack with nginx on multiple cores now.
