### ISSUE TITLE
Help needed to test the F-Stack performance 

### ISSUE THREAD

**Issue by mankalamanishkumar** [F-Stack/f-stack#246]
Hi f-stack team,

It had been couple of months looking into f-stack and now i got h/w to check the performance
I had gone through www.f-stack.org and f-stack can achieve following performance
Physical limits of NIC, 10M CC, 5M RPS, 1M CPS

Now my question is how to get those values in my setup, topology information etc. and i will use helloworld application to take the performance.

I have seen that you guys have used wrk as client on dozen of machines for testing and please let me know the topology.
Can we use httperf???
Can i use single h/w for both server(PCI passthrough) and clients(multiple VM's and running wrk)??

I want to know your topology??

Thanks in advance

**Comment by mankalamanishkumar** [comment]
Hi f-stack team, please help me.

**Comment by jfb8856606** [comment]
1. httpperf is OK, be suer the clients can provide enough request pressure.
2. It is not recommended to do this using a single hardware for both server and clients.
3. Our testing environment‘s topology is like this:
3.1 A 40GE server support WAN service, and clients on another data center, the RTT is 5ms, and the performance data for public used this environment.
3.2 A switch downlink one server and dozen of clients, all machines is on the same/adjacent racks, the RTT < 0.05ms.
3.3 One server and one client are directly connected through fiber optic jumpers.

**Comment by mankalamanishkumar** [comment]
thank you for your response.
I did a small test by running helloworld binary on one host and wrk client on another host, both are connected back to back. I am using only single core i.e only one helloworld process as server and performed the following test.
1. sudo ./start.sh on host1
2. sudo ./wrk -t 32 -c 100 -d 50s http://<ip>
I got the following output
**Running 50s test @ http://<ip>
  32 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   230.15us  293.28us  46.50ms   93.91%
    Req/Sec    14.14k     3.83k   27.79k    67.21%
  22537261 requests in 50.10s, 13.64GB read
Requests/sec: 449854.23
Transfer/sec:    278.86MB**
 
following is traffic on nic(client side)
**sudo vnstat -i <intereface> -l
Monitoring rename4...    (press CTRL-C to stop)
   rx:     2.54 Gbit/s 832430 p/s          tx:   341.43 Mbit/s 416218 p/s**

My question is client is generating 2.54 Gbit traffic but server(helloworld) responding with 341 Mbit  speed why??

following is the top output
sudo ./top -p 0
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL:   Invalid NUMA socket, default to 0
EAL: Requested device 0000:00:0*.0 cannot be used
EAL:   Invalid NUMA socket, default to 0
|---------|---------|---------|---------------|
|     idle|      sys|      usr|           loop|
|---------|---------|---------|---------------|
|   23.15%|   39.75%|   37.10%|        6876836|
|   23.58%|   39.49%|   36.93%|        6996780|
|   25.87%|   38.31%|   35.81%|        7605737|
|   23.81%|   39.42%|   36.78%|        7053564|
|   27.78%|   37.34%|   34.88%|        8118591|
|   21.60%|   40.49%|   37.91%|        6456704|
|   26.34%|   38.19%|   35.48%|        7713973|
|   28.15%|   37.40%|   34.45%|        8130703|
|   21.32%|   40.86%|   37.82%|        6362579|

**Comment by jfb8856606** [comment]
```
sudo vnstat -i -l
Monitoring rename4... (press CTRL-C to stop)
rx: 2.54 Gbit/s 832430 p/s tx: 341.43 Mbit/s 416218 p/s
```
Rx means received data, tx means sent data. 
So, actually, the client is generating 341 Mbit traffic but server(helloworld) responding with 2.54 Gbit speed.
The avg BW that server respond is : 13.64GB * 8 / 50 = 2.18 Gbit

**Comment by mankalamanishkumar** [comment]
:-) Thank you
