### ISSUE TITLE
apr_poll: The timeout specified has expired (70007)

### ISSUE THREAD

**Issue by alandtsang** [F-Stack/f-stack#25]
Hi f-stack maintainers,

I configured the addr, netmask, broadcast and gateway in config.ini, ping and `curl -v http://x.x.x.x/` is ok(x.x.x.x is my server address), but when I run `ab -n 10000 -c 20 http://x.x.x.x/` on client side, the above error occurred.

server side command as follows:
```
# ./start.sh -b example/helloworld -c config.ini
```
- f-stack is the latest version.
- CentOS 7.2.1511
- gcc version 4.8.5
- Intel Corporation Ethernet Controller 10-Gigabit X540-AT2
- cpu 24 cores

Do I need to configure other fields of config.ini?
Thanks.

**Comment by whl739** [comment]
The default configuration only enabled two cores, if you want use more cores, for example 24 cores,  you should set `lcore_mask` to `ffffff`.
And you can use `wrk`, `wrk` is more modern for http benchmarks.

**Comment by alandtsang** [comment]
Thanks for your reply. wrk test is ok, but why not ab?

**Comment by whl739** [comment]
I don't know more about `ab`, but when i use `ab`, it always interrupted by some errors.

**Comment by alandtsang** [comment]
OK, Thanks a lot.
