### ISSUE TITLE
can fstack transport video file over network？

### ISSUE THREAD

**Issue by theseusyang** [F-Stack/f-stack#252]
Hi team：
can fstack transport video file over LAN/WAN network？like a video file size is 500M~1GB.

**Comment by theseusyang** [comment]
@whl739 @jfb8856606

**Comment by jfb8856606** [comment]
Is there any question?

**Comment by theseusyang** [comment]
Is it possible that if we build a P2P network using fstack to transport big block file like video file ？

**Comment by theseusyang** [comment]
or nignx+fstack

**Comment by theseusyang** [comment]
anybody can response my question？

**Comment by jfb8856606** [comment]
F-Stack is a general application programming framework that can be used in a variety of applications.

If any problem is encountered during the use of F-Stack, you can issue it.
