### ISSUE TITLE
RSS not working

### ISSUE THREAD

**Issue by mankalamanishkumar** [F-Stack/f-stack#253]
Hi Team,

i am running helloclient(using 3 cores) application and using three client(wrk) to generate the traffic, with increase in number of client, there is no performance improvement, after debugging i found that only queue 0 is getting used. I have printed the NIC stats and got the following output
rx_q0packets: 2021006
rx_q0bytes: 211633087
rx_q0errors: 0
rx_q1packets: 0
rx_q1bytes: 0
rx_q1errors: 0
rx_q2packets: 0
rx_q2bytes: 0
rx_q2errors: 0
tx_q0packets: 4024866
tx_q0bytes: 1574109698
tx_q1packets: 0
tx_q1bytes: 0
tx_q2packets: 0
tx_q2bytes: 0

do i need to do any changes in config file? as per my knowledge i think no.
Please help here

**Comment by mankalamanishkumar** [comment]
Did any one faced same issue??
f-stack team please help.

**Comment by jfb8856606** [comment]
Show the config file and wrk client's arguments, i will take a look at it.

**Comment by mankalamanishkumar** [comment]
Attach is my configuration and 
[f-stack_conf.txt](https://github.com/F-Stack/f-stack/files/2217901/f-stack_conf.txt)
Command using at client sides is **sudo ./wrk -t 32 -c 1 -d 10s http://192.168.111.2**

**Comment by jfb8856606** [comment]
`./wrk -t 32 -c 1 -d 10s http://192.168.111.2` means one connection be used, the four-tuple(src-ip, dst-ip, src-port, dst-port) is same, and the same hash value is calculated.
Modify the `-c` argument  of wrk, example `-c 128` or `-c 1024`, and try it again.
Or add `-H "Connection: Close"` for wrk to use short connection.

**Comment by mankalamanishkumar** [comment]
I have tried, with -c 1000 but observed same issue, i.e only queue 0 is receiving all the packets. I have printed the hash value of rte mbuf structure and observed that hash value is different for all tcp connections.

**Comment by jfb8856606** [comment]
What is the NIC's `lspci` infomation and OS info?

**Comment by mankalamanishkumar** [comment]
OS : Ubuntu 16.04.2 LTS
NIC : Ethernet Controller 10-Gigabit X540-AT2 and i am doing PCI Passthrough

**Comment by jfb8856606** [comment]
X540-AT2 is supported, PCI pass-through is need to test.

If you use linux kernel instead of F-Stack, is RSS working properly?

**Comment by mankalamanishkumar** [comment]
Yes RSS is working, i have tested by using testpmd.

**Comment by mankalamanishkumar** [comment]
Understood the isssue. When i am trying to print xstats, it is showing wrong stats.
RSS is working fine so closing this bug
