### ISSUE TITLE
problem with running nginx on VBox

### ISSUE THREAD

**Issue by Nesyan** [F-Stack/f-stack#255]
Hi,
I finished installation F-Stack properly. OS: centos7 on VirtualBox.
when I run nginx, nothing is done and output of error.log is:
`
ERROR: This system does not support "SSE4_2".
Please check that RTE_MACHINE is set correctly.
EAL:FATAL: unsupported cpu type.
EAL:Error - exiting with code: 1
  couse: Error with EAL initialization
2018/07/24 13:53:34 [error] 3703#0: primary worker process failed to initialize (110: connection timed out)
`
please help me, how can I solve this?

**Comment by jfb8856606** [comment]
```
VBoxManage setextradata "VM name" VBoxInternal/CPUM/SSE4.1 1
VBoxManage setextradata "VM name" VBoxInternal/CPUM/SSE4.2 1
```

**Comment by Nesyan** [comment]
Thank you.
now, I'm getting this error:
`EAL: Detected 1 lcore(s)
 EAL: Error - exititng with code : 1
     couse: Cannot create lock on '/var/run/.rte_config'. Is another primary process running?`

**Comment by Nesyan** [comment]
F-Stack team, please help.

**Comment by whl739** [comment]
>  Is another primary process running?

Or is root account?

**Comment by Nesyan** [comment]
yes it is

**Comment by whl739** [comment]
> EAL: Detected 1 lcore(s) EAL: Error - exititng with code : 1 couse: Cannot create lock on '/var/run/.rte_config'. Is another primary process running?

This error occurs when primary coudn't acquire the flock.
Did you reboot and try again?

**Comment by Nesyan** [comment]
it worked. thank you.
