### ISSUE TITLE
Run f-stack in container

### ISSUE THREAD

**Issue by Vikash082** [F-Stack/f-stack#256]
Hello,

    Can we run f-stack in container ? Trying to find out, what all changes are required to run it as container ?

**Comment by jfb8856606** [comment]
Yes, F-Stack can run in container. Points to note:
1. kernel-header/kernel-devel must be install correctly.
2. MTU of F-Stack may need to be reduced with `tools/ifconfig`.

**Comment by jfb8856606** [comment]
F-Stack can run in container use the host NIC of its host, include physical or virtio NIC.
You can run docker like this:
```
yum install -y kernel-devel-$(uname -r)
docker pull centos
kernel_version=`uname -r`
docker run -it -d  --privileged  -v /usr/src/linux-headers-$kernel_version:/usr/src/linux-headers-$kernel_version -v /usr/src/kernels/$kernel_version:/usr/src/kernels/$kernel_version -v /lib/modules/$kernel_version:/lib/modules/$kernel_version -v /sys/bus/pci/devices:/sys/bus/pci/devices -v /sys/kernel/mm/hugepages:/sys/kernel/mm/hugepages -v /sys/devices/system/node:/sys/devices/system/node -v /dev:/dev --name  f-stack-centos centos
docker exec -it f-stack-centos /bin/bash
```
And then follow the [quick start](https://github.com/F-Stack/f-stack/blob/master/doc/F-Stack_Quick_Start_Guide.md)  or [tutorial of EC2](https://github.com/F-Stack/f-stack/blob/master/doc/Launch_F-Stack_on_AWS_EC2_in_one_minute.md)
