### ISSUE TITLE
Compile f-stack lib Issue - Centos7

### ISSUE THREAD

**Issue by lemaitre97** [F-Stack/f-stack#264]
Hi,

I have a problem with the compilation of fstack-lib in CentOs7, can you help me please ?
I have follow this tutorial : https://github.com/F-Stack/f-stack/blob/master/doc/F-Stack_Build_Guide.md
But unfortunately it missing file for compile the f-stack lib

> [root@ip220 lib]# make
> Makefile:32: /mk/rte.vars.mk: No such file or directory
> Makefile:130: /mk/rte.subdir.mk: No such file or directory
> make: *** No rule to make target `/mk/rte.subdir.mk'.  Stop.
>

**Comment by jfb8856606** [comment]
Can you check all the files are downloaded and show the all commands that you have executed?

**Comment by lemaitre97** [comment]
Yes sorry it's a mistake from me I was wrong with all open tutorial. Thanks you very much and sorry yet.
