### ISSUE TITLE
Is f-stack actually GPL 2.0?

### ISSUE THREAD

**Issue by wongfei2009** [F-Stack/f-stack#266]
Hi,

I wonder if I need to disclose the source code for developing a commercial software using f-stack.

Because f-stack is depending on micro-thread framework, which is in GPL 2.0.

Thank your for the advice.

Regards.

**Comment by jfb8856606** [comment]
F-Stack is not based microthread framework, the microthread framework just a separate, optional component , and other  modules in BSD 2-Clause or BSD 3-Clause.

If your softlayer not used  or based microthread framework , you don't need to disclose the source code, if you used  microthread framework, you must follow the GPL2.0 license. Like android.

see [GNU General Public License, version 2](http://www.gnu.org/licenses/old-licenses/gpl-2.0.html)
`These requirements apply to the modified work as a whole. If identifiable sections of that work are not derived from the Program, and can be reasonably considered independent and separate works in themselves, then this License, and its terms, do not apply to those sections when you distribute them as separate works. But when you distribute the same sections as part of a whole which is a work based on the Program, the distribution of the whole must be on the terms of this License, whose permissions for other licensees extend to the entire whole, and thus to each and every part regardless of who wrote it.`

**Comment by wongfei2009** [comment]
That's clear. Thanks a lot.
