### ISSUE TITLE
Can f-stack network stack run as 1 process on multiple cores with multiple threads?

### ISSUE THREAD

**Issue by taoswords** [F-Stack/f-stack#27]
Hi,

Based on start.sh demo, it looks like the f-stack starts a single process on 1 core. 
My understanding is that f-stack can use multiple-process. 
It is ok for every process is running on a specific core and 1 thread to deal with the send/recv.

I tried to run f-stack as 1 process on multiple cores with multiple threads. For example, I could give the parameters with multiple cores by set -c options like:
sudo ./demo ./config.ini -c 0x3 --proc-type=primary --num-procs=1 --proc-id=0

However ,the network stack will fall into segment fault.  I used gdb to debug and found that the parameter 'curthread' passed to the network APIs in ff_syscall_wrapper is zero.  For example, if -c 0x3 is specified, the slave core would call ff_epoll_create -> ff_kqueue -> (segment fault). It is because of the "curthread" on slave core is zero.

It is appreciated if anybody  can give a light on why 'curthread' is zero on the slave cores and where the 'curthread' will be assigned with a valid value in the code.

Thanks,
oceanspark

**Comment by whl739** [comment]
`lcore_mask` in config.ini means hexadecimal bitmask of cores to run on, it can be configured to multi cores, the default `3` means we will start two processes on cpu0 and cpu1. But if you have only one core, it will start one process.

If you start f-stack without start.sh, you should do it like this:
1 process:
 `sudo ./demo ./config.ini -c 0x1 --proc-type=primary --num-procs=1 --proc-id=0`
2 processes:
```
sudo ./demo ./config.ini -c 0x1 --proc-type=primary --num-procs=2 --proc-id=0
sudo ./demo ./config.ini -c 0x2 --proc-type=secondary--num-procs=2 --proc-id=1
```

**Comment by whl739** [comment]
We don't support 1 process on multiple cores with multiple threads for now.
In order to run FreeBSD TCP/IP stack in parallel without lock, we just run one process with one thread on each core.

**Comment by taoswords** [comment]
Yelp. 2 processes will be OK if I start  the 1st process as primary and the 2nd process as secondary. 

My case is to run multiple workers to deal with the tcp sessions on 1 NIC port with 1 IP. The original idea is to run multiple threads to deal with different sessions based on different tcp ports. The beneifit is that the different tcp session will involve different time-consumption phases, and it is not suitable to put all in the single f-stack network stack.

If f-stack do not support 1 process on multiple cores with multiple threads so far, is it possible for me to use f-stack to satisfy my case?How could the primary process to share incoming network packets with the secondary process?

-- Where should I initialize the IP?  On the primary process?  Or both on the primary and secondary?
-- How could I make the different tcp streams to different process even if the IP initialization is resolved?

**Comment by whl739** [comment]
> If f-stack do not support 1 process on multiple cores with multiple threads so far, is it possible for me to use f-stack to satisfy my case?How could the primary process to share incoming network packets with the secondary process?

F-Stack can not fully adapt your case, you must make some changes.In lib/ff_dpdk_if.c:process_packets:
```
enum FilterReturn filter = protocol_filter(data, len);
```
this code will check the incoming packets, if they are ARP packets or KNI packets,  will be transmitted to other processes using rte_ring.You can refer to this, peek the packet, determine that whether this packet is needed for this process, if not, transmit to other process.

> -- Where should I initialize the IP? On the primary process? Or both on the primary and secondary?

Both on the primary and secondary.

> -- How could I make the different tcp streams to different process even if the IP initialization is resolved?

Refer to the ARP processing.

By the way, we'll add some hook functions for custom packet handling, for example, bypass, forward, copy,etc..

**Comment by taoswords** [comment]
Thanks. I will look inside and try to filter the packets.

**Comment by taoswords** [comment]
one more question:

Given the config.ini is configured with 1 port with 1 IP.  I run 2 processes with 1st as primary and 2nd as secondary based on current f-stack. 
I wonder which process will receive the packets. Will the primary process receives all the packets?   Or the traffic is randomly received among these 2 processes? Since these 2 processes all share the same config.ini and will see the same configuration on the same port, the primary process and secondary process will randomly pick up the packets?

**Comment by whl739** [comment]
According to the result of RSS hash, packets will be received to different processes.
Currently the primary and secondary processess will receive packets from all nics.

**Comment by gpstrive** [comment]
@oceanspark  
actually, you can achieved the purpose by run 2 process (or many), and each process has its own rx ring.

**Comment by jlijian3** [comment]
Is it support nginx proxy on multiple processes? How to make the packets from backend server received by the process correctly?
For example，nginx process0 send syn to the backend server，the syn-ack will received by process0 but not process1.

**Comment by taoswords** [comment]
@gpstrive Yeah, different rx ring can do if the transactions are stateless. I want to control all the streams/datagrams for every transaction. Just as @whl739  said, we need to do some custom packet handling. I am trying to add some hook points for purpose. Certainly, if f-stack supports hooks, maybe it is easier ^-^

**Comment by taoswords** [comment]
@jlijian3 I do not quite understand your mentioned proxy-pass. Maybe it is like the flow director. I just know f-stack uses RSS hash to distribute the flows to different process,  and it is up to the users to take actions on the received packets, like dropping, dealing with some extra procedures, or just forwarding, and so on.

**Comment by jlijian3** [comment]
Sorry，I mean  nginx proxy.

**Comment by whl739** [comment]
Proxy is supported by nginx-fstack.
When F-Stack connects to a server, we will choose a port(use toeplitz_hash to calculate the rss result) that packets will be received on the same process.

**Comment by gpstrive** [comment]
@oceanspark  
My case is to run multiple workers to deal with the tcp sessions on 1 NIC port with 1 IP. The original idea is to run multiple threads to deal with different sessions based on different tcp ports.

If you start 2 processes,  different tcp sessions distribute to different process and the same session always go to the same process,  does it satisfy your case ?

**Comment by taoswords** [comment]
@gpstrive I think your approach to start 2 processes to handle tcp sessions is ok in your case. However, my case is different and is required to handle mixed udp and tcp packets, and some time-consuming work to do. So I consider to hook and re-distribute the packets to different processes even if I benefit the high capability of F-stack to receive packets.
