### ISSUE TITLE
ipfw with transparent proxy

### ISSUE THREAD

**Issue by mmprabhu123** [F-Stack/f-stack#272]
Hi,
I am trying to test nginx transparent proxy and I see that the interfaces on my proxy (nginx+f-stack) have been setup. However, I am unable to configure a nat rule to translate the destination to my proxy-ip:3129.

tester@testserver3:~/f-stack/tools/sbin$ sudo ./ipfw -P 0 table 1 list
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
ipfw: failed to request table info: Operation not supported

tester@testserver3:~/f-stack/tools/sbin$ sudo ./ipfw -P 0 -q add 100 fwd 192.168.141.3,3129 tcp from any to any 80
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
ipfw: getsockopt(IP_FW_XADD): Operation not supported

I tried setting this:
tester@testserver3:~/f-stack/tools/sbin$sudo ./sysctl -w net.link.bridge.ipfw=1

Some of the other commands work:
tester@testserver3:~/f-stack/tools/sbin$ sudo ./ifconfig
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
lo0: flags=8008<LOOPBACK,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        groups: lo
f-stack-0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=3<RXCSUM,TXCSUM>
        ether 90:e2:ba:c6:f0:a
        inet 192.168.141.3 netmask 0xffffff00 broadcast 192.168.141.255

Appreciate any help.

Thanks,
M.

**Comment by whl739** [comment]
`ipfw` is not compiled by default. See `lib/Makefile`, uncomment the `FF_IPFW=1` or just export it.

**Comment by mmprabhu123** [comment]
Still get the same error, I re-compiled f-stack and did clean build of tools and nginx. I do see a new sysctl value.

tester@testserver3:~/f-stack/tools/sbin$ sudo ./sysctl -a  | grep  ipfw            
kern.features.ipfw_ctl3: 1
net.link.ether.ipfw: 1
net.link.bridge.ipfw_arp: 0
net.link.bridge.ipfw: 1

tester@testserver3:~/f-stack/tools/sbin$ sudo ./ipfw -P 0 -q add 100 fwd 192.168.141.3,3129 tcp from any to any 80
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
ipfw: getsockopt(IP_FW_XADD): Operation not supported

**Comment by mmprabhu123** [comment]
I did a clean build again and this time with DEBUG flags turned on in the Makefile. This time, it worked. Will close the ticket for now. Thanks for the pointer for FF_IPFW in the Makefile.

tester@testserver3:~/f-stack/tools/sbin$ sudo ./ipfw -P 0 -q add 100 fwd 192.168.141.3,3129 tcp from any to any 80
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0


tester@testserver3:~/f-stack/tools/sbin$ sudo ./ipfw -P 0  list
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
00100 fwd 192.168.141.3,3129 tcp from any to any dst-port 80
65535 allow ip from any to any
