### ISSUE TITLE
compile error： fatal error: opt_vlan.h: No such file or directory

### ISSUE THREAD

**Issue by lewislone** [F-Stack/f-stack#28]
compile f-stack on CentOS7 get an error：

> cc -c -O2 -fno-strict-aliasing -frename-registers -pipe -Wno-maybe-uninitialized   -std=c99  -Wall -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wno-inline -Wcast-qual -Wno-pointer-sign -Wmissing-include-dirs -fdiagnostics-show-option -Wno-unused-but-set-variable -fno-common -finline-limit=8000 --param inline-unit-growth=100 --param large-function-growth=1000  -DFSTACK  -fstack-protector -D__FreeBSD__ -D_KERNEL -DHAVE_KERNEL_OPTION_HEADERS -include opt_global.h -fno-builtin -I/root/f-stack/lib/include -undef -imacros filtered_predefined_macros.h -nostdinc  -I. -I/root/f-stack/lib/../freebsd -I./machine_include -I./opt -Werror -Wno-unused-variable  /root/f-stack/lib/../freebsd/net/if_vlan.c
/root/f-stack/lib/../freebsd/net/if_vlan.c:48:22: fatal error: opt_vlan.h: No such file or directory
 #include "opt_vlan.h"
                      ^
compilation terminated.
make: *** [if_vlan.o] Error 1

**Comment by whl739** [comment]
Sorry, this file is omitted by last commit.I'll fix it right away.
