### ISSUE TITLE
worker crash when using proxy_kernel_network_stack 

### ISSUE THREAD

**Issue by arikachen** [F-Stack/f-stack#286]
**conf:**
    upstream test{
        server y.y.y.y:80;
    }

    server {
        listen          8888;
        location / {
            proxy_kernel_network_stack on;
            proxy_pass      http://test;
        }
    }

**step:**
./wrk -t32 -c1000 -d10s http://x.x.x.x:8888/

**stack:**
Thread 1 "nginx" received signal SIGSEGV, Segmentation fault.
ngx_pfree (pool=0x55555615b1d0, p=0x5555563a8a00) at src/core/ngx_palloc.c:283
283	        if (p == l->alloc) {
(gdb) bt
#0  ngx_pfree (pool=0x55555615b1d0, p=0x5555563a8a00) at src/core/ngx_palloc.c:283
#1  0x000055555560ee51 in ngx_http_set_keepalive (r=0x5555563a8e60) at src/http/ngx_http_request.c:2955
#2  ngx_http_finalize_connection (r=r@entry=0x5555563a8e60) at src/http/ngx_http_request.c:2551
#3  0x000055555560f510 in ngx_http_finalize_request (r=r@entry=0x5555563a8e60, rc=<optimized out>) at src/http/ngx_http_request.c:2447
#4  0x000055555561a5bf in ngx_http_upstream_finalize_request (r=r@entry=0x5555563a8e60, u=u@entry=0x5555563a9e40, rc=<optimized out>) at src/http/ngx_http_upstream.c:4406
#5  0x000055555561ac75 in ngx_http_upstream_process_request (r=r@entry=0x5555563a8e60, u=u@entry=0x5555563a9e40) at src/http/ngx_http_upstream.c:4010
#6  0x000055555561b4c1 in ngx_http_upstream_process_upstream (r=r@entry=0x5555563a8e60, u=u@entry=0x5555563a9e40) at src/http/ngx_http_upstream.c:3903
#7  0x000055555561dbc2 in ngx_http_upstream_send_response (u=0x5555563a9e40, r=0x5555563a8e60) at src/http/ngx_http_upstream.c:3166
#8  ngx_http_upstream_process_header (r=0x5555563a8e60, u=0x5555563a9e40) at src/http/ngx_http_upstream.c:2328
#9  0x000055555561a61f in ngx_http_upstream_handler (ev=<optimized out>) at src/http/ngx_http_upstream.c:1239
#10 0x0000555555605050 in ngx_ff_epoll_process_events (cycle=<optimized out>, timer=<optimized out>, flags=<optimized out>) at src/event/modules/ngx_ff_host_event_module.c:410
#11 0x00005555555fc835 in ngx_process_events_and_timers (cycle=cycle@entry=0x555556156da0) at src/event/ngx_event.c:266
#12 0x00005555556014b4 in ngx_worker_process_cycle_loop (arg=0x555556156da0) at src/os/unix/ngx_process_cycle.c:839
#13 0x00005555556e56f5 in main_loop ()
#14 0x000055555571e72a in rte_eal_mp_remote_launch ()
#15 0x00005555556e8e56 in ff_dpdk_run ()
#16 0x0000555555600aea in ngx_spawn_process (cycle=cycle@entry=0x555556156da0, proc=proc@entry=0x555555601a49 <ngx_worker_process_cycle>, data=data@entry=0x0, name=name@entry=0x5555559fac92 "worker process", respawn=respawn@entry=-3)
    at src/os/unix/ngx_process.c:198
#17 0x0000555555601fbc in ngx_start_worker_processes (cycle=cycle@entry=0x555556156da0, n=8, type=type@entry=-3) at src/os/unix/ngx_process_cycle.c:422
#18 0x0000555555602501 in ngx_master_process_cycle (cycle=0x555556156da0) at src/os/unix/ngx_process_cycle.c:144
#19 0x00005555555e2912 in main (argc=1, argv=<optimized out>) at src/core/nginx.c:388

**Comment by whl739** [comment]
@chadwill

**Comment by firesidefox** [comment]
Investigate!
