### ISSUE TITLE
Why not replace system calls in libfstack.a ?

### ISSUE THREAD

**Issue by amjy** [F-Stack/f-stack#29]
In my opinion,  f-stack should replace syscalls in libfstack.a;
The apps will not care fd bits and call socket/read/write/kqueue the same as the normal network stack;
Developers just add ff_init at app init, and change the processing to ff_run;
I have modified it and test ok by the examples, nginx and redis;
But it dosen‘t work well with micro_thread, because "multiple definition of the system calls".

**Comment by derness** [comment]
Thank you for your advice and thank you for your exploratory work. We will be very happy if you join project and contribute. We will replace the system calls in future. Replace system calls need careful about net fd and virtual file system fd. Micro_thread is already hook some system calls, see mt_sys_hook.h for details，maybe it has conflict with yours?

**Comment by amjy** [comment]
Yes, you're right, it has conflict with mt_sys_hook.h; 
Just micro thread works well maybe easy, But I did not find the best way to solve the similar problems.
