### ISSUE TITLE
Running f-stack in container with OVS-DPDK

### ISSUE THREAD

**Issue by bennybrit** [F-Stack/f-stack#298]
Hello,
I've the current setup:
OVS-DPDK configured with bridge br0 and 2 ports (dpdk0 which is the physical NIC on the host, and vhost0 which is vhost-user port), below is the output of "ovs-vsctl show":

b1073c63-7039-4bf1-b444-ba3f50c7c560
    Bridge "br0"
        Port "br0"
            Interface "br0"
                type: internal
        Port "dpdk0"
            Interface "dpdk0"
                type: dpdk
                options: {dpdk-devargs="0000:21:00.0", n_rxq="4"}
        Port "vhost0"
            Interface "vhost0"
                type: dpdkvhostuser
    ovs_version: "2.9.0"

The vhost-user socket is created under /var/run/openvswitch, and i start the container with the following command:
docker run ... \
-v /var/run/openvswitch/vhost0:/var/run/vhost0 \
-v /mnt/huge/:/dev/hugepages/ \
...

Now the question is how do i bind to the vhost-user socket inside the container? let's assume i'm running the "helloworld" example, in my "config.ini" i have "port_list" parameter but this refers to a port, and i don't have a port inside my container, the only option that i can bind to it is by using virtual device option (vdev) passed as parameter to EAL, below is example from DPDK documentation on how to run testpmd with vdev flag:
$(testpmd) ... --vdev=virtio_user0,path=/var/run/vhost0 ...

Is there an option to run fstack with vdev? any help appreciated

Thanks in advance,
Benny

**Comment by whl739** [comment]
We haven't do any support in container,  maybe should do some changes, i'm not quite sure.

**Comment by bennybrit** [comment]
> We haven't do any support in container, maybe should do some changes, i'm not quite sure.

Thanks for the quick reply.
any plans to add support for containers in the future?
also i found this thread, which says that containers are supported:
https://github.com/F-Stack/f-stack/issues/256

any reason why it's not supported now?

Thanks again,
Benny

**Comment by whl739** [comment]
I don't know wether it works or not, because i dint't do any tests in container.
Maybe @jfb8856606 knows.

**Comment by gechangwei** [comment]
@bennybrit @jfb8856606 
I also want use ovs+dpdk support f-stack, do you solve this problem ? or maybe you can give me some  help?

**Comment by jfb8856606** [comment]
Running F-Stack in container does not support aggregation model yet, it can only use the NIC of its host, include physical or virtio NIC, see #256 to run it.
We will support aggregation model(vdev) with container later.

**Comment by jfb8856606** [comment]
@bennybrit @gechangwei F-Stack always supported it.
Also see http://doc.dpdk.org/guides/howto/virtio_user_for_container_networking.html
