### ISSUE TITLE
helloworld down when it send a lot

### ISSUE THREAD

**Issue by wangchuanguo** [F-Stack/f-stack#30]
wo change the helloworld to let it send very large size file, but it works down after sending 31*1024 chars.
i can not ping or connect again!
can you help me ?
and my hugepage info:
HugePages_Total:     498
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB

**Comment by whl739** [comment]
Can you paste your codes? Or you can just test large files on nginx-fstack.

**Comment by wangchuanguo** [comment]
else if (event.filter == EVFILT_READ) {
            char buf[1024];
            size_t readlen = ff_read(clientfd, buf, sizeof(buf));

            //printf("bytes %zu are available to read...,fd:%d\n", (size_t)event.data, clientfd);

            //ff_write(clientfd, html, sizeof(html));
            FILE* fp = NULL;
            fp = fopen("/wcg/CentOS-7-x86_64-DVD-1611.iso","r");
            if(fp==NULL)
            {
                    perror("file open failed! \n");
                exit(0);
            } else {
                printf("open file ok!\n");
            }
            int iret=-1,send_len=-1,total_size=0, count=0;
            while(count<90  && (iret = fread(buf, sizeof(char), 1024,fp)) > 0)
            {
                //send_len = send(connectfd, buf, iret, 0);
                send_len = ff_write(clientfd, buf, iret);
                printf("send %d byte at %d\n", send_len,count);
                if(send_len<0)
                {
                        perror("send file failed!\n");
                        exit(0);
                }
                total_size += send_len;
                ++count;

                bzero(buf, 1024);
                iret = -1;
                send_len=-1;
        }
        fclose(fp);
        printf("send over, total %d!\n", total_size);

**Comment by whl739** [comment]
This is a wrong way to use ff_write, you need to add an EVFILT_WRITE event to kqueue, and when this event is ready, you can write.
The default example calls ff_write directly because the content is small and can be written successfully at one time.
If you don't know how to write an asynchronous IO program, you can just use nginx-fstack instead.

**Comment by wangchuanguo** [comment]
ok,i got it,thanks

**Comment by wangchuanguo** [comment]
I think some simple examples of asynchronous IO programs will be better!
Thanks
