### ISSUE TITLE
build f-stack with DPDK-18.08

### ISSUE THREAD

**Issue by rmkm** [F-Stack/f-stack#306]
I've committed to my branch in forked repository to enable f-stack to build with DPDK-18.08.

The commit is below:
https://github.com/morishima311/f-stack/commit/2844b699a18a80e56f857771812c6dd7bcff2d6c

I checked that I could build f-stack with the change above, but I'm not sure this was the right change because this was the first time for me to use DPDK KNI API. I think there are better implementation, I'd like to ask your opinion.

**Comment by jfb8856606** [comment]
We will check it and upgrade DPDK to 18.11 while DPDK 18.11 stable release.

**Comment by rmkm** [comment]
I'm looking forward to seeing f-stack with DPDK 18.11. Thank you for your comment!

**Comment by jfb8856606** [comment]
DPDK of f-stack already upgrade to 18.11 LTS 8850115,  and your commit is OK.

And I will continue testing it.

**Comment by rmkm** [comment]
Great... thanks a lot !
