### ISSUE TITLE
helloworld run on multiple cores, forward packet through bridge

### ISSUE THREAD

**Issue by answerwa** [F-Stack/f-stack#309]
Hi f-stack maintainers:smile:,

I try to use helloworld program to set up two ports(add configuration of port1 to the config.ini file), then execute the following command:

```
./ifconfig bridge create
./ifconfig bridge0 addm f-stack-0 addm f-stack-1 up
./ifconfig f-stack-0 up
./ifconfig f-stack-1 up
```

This can create a bridge, then add the two ports in it. After then the helloworld program and bridge can forward  packet between the two ports. But only one core is been used, the performance is too low.

So, i modify the config.ini file like below(only shows the difference):

```
root@f-stack# git diff config.ini 
diff --git a/config.ini b/config.ini
index 0a5a6be..b0465a2 100644
--- a/config.ini
+++ b/config.ini
@@ -1,6 +1,6 @@
 [dpdk]
 # Hexadecimal bitmask of cores to run on.
-lcore_mask=1
+lcore_mask=f
 
 # Number of memory channels.
 channel=4
@@ -34,7 +34,7 @@ idle_sleep=0
 # examples
 #    0-3       ports 0, 1,2,3 are enabled
 #    1-3,4,7   ports 1,2,3,4,7 are enabled
-port_list=0
+port_list=0,1
 
 # Port config section
 # Correspond to dpdk.port_list's index: port0, port1...
@@ -43,6 +43,14 @@ addr=192.168.1.2
 netmask=255.255.225.0
 broadcast=192.168.1.255
 gateway=192.168.1.1
+lcore_list= 0,1
+
+[port1]
+addr=192.168.1.3
+netmask=255.255.225.0
+broadcast=192.168.1.255
+gateway=192.168.1.1
+lcore_list= 2,3
 
 # lcore list used to handle this port
 # the format is same as port_list
```

want to use 4 cores on helloworld.

The startup message shows the program has been run successfully.

```
lcore: 0, port: 0, queue: 0
lcore: 1, port: 0, queue: 1
lcore: 2, port: 1, queue: 0
lcore: 3, port: 1, queue: 1
```

Now, i need to specify the f-stack proc_id when i check the two ports(f-stack-0 and f-stack-1) through `ifconfig`. So, i do not know how to create(create on which core) a bridge to contain the two ports:sweat_smile:.

Is there a way can create a bridge as mentioned above?

Or, I just go a wrong way to use this program. 
Can I run helloworld on multiple cores, but just start one process?

Best wishes!:smile_cat:

**Comment by jfb8856606** [comment]
You can try modify or remove the `lcore_list` argument in section `port0` and `port1`, and every f-stack process can bind the two port's queue, like this:
```
lcore_mask=f
port_list=0,1

[port0]
#lcore_list=0-3 # Comment out it, or modify to 0-3,  just corresponding to lcore_mask

[port1]
#lcore_list=0-3 # Comment out it, or modify to 0-3,  just corresponding to lcore_mask
```

And then use `ifconfig` to create bridge in every process like this
```
./ifconfig -p 0 bridge create
./ifconfig -p 0  bridge0 addm f-stack-0 addm f-stack-1 up
./ifconfig -p 0  f-stack-0 up
./ifconfig -p 0  f-stack-1 up

./ifconfig -p 1 bridge create
./ifconfig -p 1  bridge0 addm f-stack-0 addm f-stack-1 up
./ifconfig -p 1  f-stack-0 up
./ifconfig -p 1  f-stack-1 up

./ifconfig -p 2 bridge create
./ifconfig -p 2  bridge0 addm f-stack-0 addm f-stack-1 up
./ifconfig -p 2  f-stack-0 up
./ifconfig -p 2  f-stack-1 up

./ifconfig -p 3 bridge create
./ifconfig -p 3  bridge0 addm f-stack-0 addm f-stack-1 up
./ifconfig -p 3  f-stack-0 up
./ifconfig -p 3  f-stack-1 up
```

**Comment by answerwa** [comment]
Thanks for your reply.

I have tried the way you mentioned this morning.

I used six cores all on socket 1, then create bridge in each process. But I found the performance is still not satisfied(result as follow).
![six_cores](https://user-images.githubusercontent.com/7703303/49144023-4a4b4d80-f337-11e8-92ba-3d1cd413fae8.png)

I'll keep looking for a higher performance way.

If you can give me some advice, that would be great.

Anyway, thanks again:smile_cat:.

**Comment by jfb8856606** [comment]
Can you show the `tools/sbin/top`  status of all processes, to see the real CPU usage.

Or whether the four tuple (src_ip, dst_ip, src_port, dst_port) of the stream is random.

**Comment by answerwa** [comment]
> whether the four tuple (src_ip, dst_ip, src_port, dst_port) of the stream is random.

Yes, the client ip range is (17.1.2.2-17.1.2.100), and the server ip range is (17.1.2.101-17.1.2.200).

I just use `tools/sbin/top` to check each process, all the status like this:

```
|---------|---------|---------|---------------|
|     idle|      sys|      usr|           loop|
|---------|---------|---------|---------------|
|    0.19%|   98.92%|    0.89%|          82061|
|    0.23%|   98.87%|    0.90%|          87600|
|    0.26%|   98.77%|    0.96%|          95913|
|    0.17%|   99.04%|    0.79%|          70076|
|    0.26%|   98.77%|    0.97%|          97080|
|    0.39%|   98.71%|    0.90%|         107852|
|    0.22%|   98.89%|    0.88%|          86174|
|    0.51%|   98.60%|    0.89%|         120645|
|    0.16%|   98.92%|    0.92%|          79892|
|    0.33%|   98.78%|    0.90%|          97632|
|    0.30%|   98.80%|    0.90%|          96605|
|    0.14%|   99.08%|    0.78%|          65925|
|    0.32%|   98.79%|    0.89%|          98917|
|    0.23%|   98.87%|    0.91%|          87593|
|    0.28%|   98.81%|    0.91%|          94084|
|    0.25%|   98.83%|    0.92%|          92283|
|    0.25%|   98.84%|    0.92%|          90598|
|    0.35%|   98.68%|    0.97%|         107712|
|    0.19%|   98.90%|    0.91%|          83062|
|    0.17%|   99.05%|    0.78%|          69625|
|    0.28%|   98.81%|    0.91%|          94010|
|   57.13%|   41.66%|    1.21%|        6649618|*
|   99.75%|    0.00%|    0.25%|       10818123|*
|   70.84%|   28.11%|    1.04%|        8036860|*
|    0.16%|   99.05%|    0.78%|          66000|
|    0.27%|   98.94%|    0.79%|          79041|
|    0.10%|   99.12%|    0.78%|          58515|
|    0.13%|   99.05%|    0.82%|          64994|
|    0.22%|   98.99%|    0.79%|          72866|
|    0.20%|   99.01%|    0.78%|          70578|
|    0.17%|   99.05%|    0.78%|          66678|
|    0.11%|   99.10%|    0.79%|          58715|
```

The three lines with `*`, i think maybe is the traffic generator has paused and choose another rate.

**Comment by jfb8856606** [comment]
It seems the performance of FreeBSD bridge is low， i will test it.

And another question, whether run helloworld use more cores to increase line speed rate to more than 70%, and how many cores used?

**Comment by answerwa** [comment]
There are 12 cores on my machine, (0-5) on socket0, and (6-11) on socket1. So I just used 6 cores(6-11) for the performance test. The result was pasted as above, line speed rate about 40%. 

I will test by using more cores tomorrow, and I will also use the same numbers of cores to test the l2fwd of dpdk . By the time, I will paste the result.

Thanks for helping 😺

**Comment by jfb8856606** [comment]
Thanks for you reply, i will test it.

**Comment by answerwa** [comment]
hello, me again😹.

I test  by using 10cores, 8cores and 6cores. The results as below(I hope packet loss rate less than 0.01%).

Hugepages shows like this:

```AnonHugePages:         0 kB
ShmemHugePages:        0 kB
HugePages_Total:    8192
HugePages_Free:     8192
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
```


First, I test on l2fwd with the command `./build/l2fwd -l 6-7 -n 4 -- -p 3 --no-mac-updating`, it seems just can use at most one core per port.

| traffic(Gbps) | line speed rate(%) | packet loss rate(%) |
| ------------- | ------------------ | ------------------- |
| 10            | 71.5               | 28                  |
| 5             | 49.7               | 0.2                 |
| 2.5           | 24.9               | 0.0325              |
| 2.335         | 23.34              | 0.0196              |
| 2.179         | 21.79              | 0.0089              |



10 cores(2-5 on socket0, 6-11 on socket1) results:

| traffic(Gbps) | idle(primary core)(%) | line speed rate(%) | packet loss rate(%) |
| ------------- | --------------------- | ------------------ | ------------------- |
| 10            | 1.5                   | 72                 | 28                  |
| 5             | 11                    | 49.75              | 0.16                |
| 3.7           | 25                    | 37                 | 0.123               |
| 3.1           | 33                    | 31                 | 0.028               |
| 2.8           | 38                    | 28                 | 0.0014              |



8 cores(4-5 on socket0, 6-11 on socket1) results:

| traffic(Gbps) | idle(primary core)(%) | line speed rate(%) | packet loss rate(%) |
| ------------- | --------------------- | ------------------ | ------------------- |
| 10            | 0.8                   | 66.7               | 33.04               |
| 5             | 5.6                   | 49.8               | 0.06                |
| 3.7           | 20                    | 37                 | 0.0109              |
| 3.4           | 24                    | 34                 | 0.0177              |
| 3.3           | 38                    | 28                 | 0.0014              |



6 cores(6-11 on socket1) results:

| traffic(Gbps) | idle(primary core)(%) | line speed rate(%) | packet loss rate(%) |
| ------------- | --------------------- | ------------------ | ------------------- |
| 10            | 0.7                   | 46.1               | 53.7                |
| 5             | 0.8                   | 46                 | 7                   |
| 4.33          | 0.8                   | 43.3               | 0.0223              |
| 4.32          | 0.7                   | 43.2               | 0.0078              |


Maybe more cores can handle higher speed, but seems not stable enough.



ps:

I found a situation that if I killall the helloworld, and use the `start.sh` to restart them, there are something wrong:

```
kernel: igb_uio 0000:02:00.0: uio device registered with irq 45
kernel: igb_uio 0000:02:00.1: uio device registered with irq 46
kernel: helloworld[24258]: segfault at 20 ip 0000555555637cc7 sp 00007fffffffe750 error 4 in helloworld[555555554000+52e000]
kernel: helloworld[24260]: segfault at 30 ip 0000555555637cc7 sp 00007fffffffe750 error 4 in helloworld[555555554000+52e000]
kernel: helloworld[24261]: segfault at 38 ip 0000555555637cc7 sp 00007fffffffe750 error 4 in helloworld[555555554000+52e000]
kernel: helloworld[24255]: segfault at 8 ip 0000555555637cc7 sp 00007fffffffe750 error 4 in helloworld[555555554000+52e000]
kernel: helloworld[24256]: segfault at 10 ip 0000555555637cc7 sp 00007fffffffe750 error 4 in helloworld[555555554000+52e000]
kernel: helloworld[24257]: segfault at 18 ip 0000555555637cc7 sp 00007fffffffe750 error 4 in helloworld[555555554000+52e000]
kernel: helloworld[24259]: segfault at 28 ip 0000555555637cc7 sp 00007fffffffe750 error 4 in helloworld[555555554000+52e000]
```

So, I just use `./example/helloworld --conf config.ini --proc-type=secondary --proc-id=1 &` to start each program.

**Comment by jfb8856606** [comment]
Thanks your test result, I think I found some problems that might degrade performance, I will verify them.

The situation of `start.sh` have not encountered before, you can try to increase the value of  `sleep 5` in `start.sh` .

**Comment by answerwa** [comment]
> The situation of start.sh have not encountered before, you can try to increase the value of sleep 5 in start.sh .

OK, I will try this.

Looking forward to your good news👍.

**Comment by answerwa** [comment]
I have made some progress today and want to share it with you.



I checked the results of yesterday, found when run helloworld with 10 cores, it actually can handle about 70% line speed rate, but it just not stable enough. I think maybe the irq and system call disturb the cpu which helloworld used. So, I set the `isolcpus=2,3,4,5,6,7,8,9,10,11` argument in `/boot/grub/grub.conf`(OS:debian), then reboot.



The retest performance results as below.

10 cores(2-5 on socket0, 6-11 on socket1) result(forgot to record idle rate😹):

| traffic(Gbps) | line speed rate(%) | packet loss rate(%) |
| ------------- | ------------------ | ------------------- |
| 10            | 73.27              | 26.53               |
| 7.5           | 73.17              | 2.11                |
| 6.2           | 62.28              | 0.018               |
| 5.8           | 58                 | 0.0038              |



And I also retest the l2fwd with 2cores:

| traffic(Gbps) | line speed rate(%) | packet loss rate(%) |
| ------------- | ------------------ | ------------------- |
| 10            | 72.1               | 27.67               |
| 7.5           | 71.58              | 4.24                |
| 7             | 70                 | 0.0059              |



Feeling the performance has been greatly improved. 

Hoping this information can help you solve the problem of poor performance.



ps:

> The situation of start.sh have not encountered before, you can try to increase the value of sleep 5 in start.sh .

I increase the value of sleep time from 5 to 10, it works.

**Comment by jfb8856606** [comment]
Yes，set `isolcpus` is effective, if possible, it shoule be set always when running.

I will check other problems.

**Comment by WoolenWang** [comment]
learn a lot， thanks .
大家都是中国人，用英文交流那么多，也是666。
