### ISSUE TITLE
How to cooperate f-stack with coroutine?

### ISSUE THREAD

**Issue by j0826** [F-Stack/f-stack#311]
Hi, I read about your article about cooperate f-stack with SPP(tencent coroutine framework). I thought it's an novel idea to adapt to DPDK's thread model limitations(for example, fd write and read should be on the same thread) by coroutines.
My question is , i do have an experimental coroutine  framework that features on networking apps,  could someone give me some ideas on how to cooperate it with F-stack?( like , how a corotine should be scheduled, or how to assign a fd write to its thread)
Thanks!

**Comment by derness67** [comment]
The  DPDK's thread is always run but not give up CPU，you can refer to the SPP  coroutine framework， it manage all fds and judge any one fd is ready for read or write.

**Comment by j0826** [comment]
Thanks for your reply, my main confusion is that DPDK requires fd to create and bind, and subsequent fd reads and writes on the same thread, which will give the existing coroutine scheduling algorithm a big challenge. For example, I can't judge Whether this coroutine task involves  fd read or write ,   Which corresponding thread scheduler should be assigned to this coroutine task. I guess your implementation is to open a set of threads to manage a batch of fd separately, bind these fd operations to the determined thread scheduler?
