### ISSUE TITLE
How do we know which queue or lcore sending packets out?

### ISSUE THREAD

**Issue by ZhongqiXiao** [F-Stack/f-stack#314]
Hi, f-stack!
I need to know each packet is processed by which queue or lcore, so i add some printf information in the function `process_packet`, which is in `lib/ff_dpdk_if.c`,
  `fprintf(fp, "[time: %s] src:%d.%d.%d.%d:%d -->> dst:%d.%d.%d.%d:%d ,queue_id:%d\n",
                        timePointer,
                        src_ip[0], src_ip[1], src_ip[2], src_ip[3], srcPort,
                        dst_ip[0], dst_ip[1], dst_ip[2], dst_ip[3], dstPort,
                        queue_id);`
but this is only for coming packets,
I notes that the function `ff_dpdk_if_send` doesn't have `queue_id` argrument,  how do i fprintf the same information for packets are going to be sending?
I am looking forward to your reply, thanks for your help!

**Comment by jfb8856606** [comment]
See the function `send_burst` in `lib/ff_dpdk_if.c`.
