### ISSUE TITLE
F-Stack based client cannot connect to server

### ISSUE THREAD

**Issue by berinpaul** [F-Stack/f-stack#315]
Hi, I'm trying to write an f-stack based client application. I've read threads on `ff_connect` (#135) but still cannot manage to get a connection. Tried both `ff_poll` and `ff_epoll_wait`.  Posting callback function below. Can someone help.

**Comment by berinpaul** [comment]
int loop(void* args)
{        
      
        int nevents = ff_epoll_wait(epfd,  Events, 10, 0);
        int i;

        if (nevents == 0){
                printf("nevents: %d\n", nevents);
                return -1;
        }
        for (i=0; i<nevents; i++){
                int err = -1; 
                socklen_t len = sizeof(int);

                if (ff_getsockopt(Events[i].data.fd, SOL_SOCKET, SO_ERROR, &err, &len) < 0){
                        ff_close(sock);
                        printf("getsockopt errno:%d %s\n", errno, strerror(errno));
                        return -2;
                }
        }

        ff_send(sock , hello , strlen(hello) , 0 );
        printf("Hello message sent\n"); 
        valread = ff_read( sock , buffer, 1024);
}

**Comment by berinpaul** [comment]
## Rest of the code
int main(int argc, char *argv[])
{

        ff_init(argc, argv);
        if ((sock = ff_socket(AF_INET, SOCK_STREAM, 0)) < 0)
        {
                printf("\n Socket creation error \n");
                return -1;
        }

        memset(&serv_addr, '0', sizeof(serv_addr));

        serv_addr.sin_family = AF_INET;
        serv_addr.sin_port = htons(PORT);

        // Convert IPv4 and IPv6 addresses from text to binary form 
        if(inet_pton(AF_INET, "192.168.1.5", &serv_addr.sin_addr)<=0)
        {
                printf("\nInvalid address/ Address not supported \n");
                return -1;
        }
        ff_ioctl(sock, FIONBIO, &on);

        if (ff_connect(sock, (struct linux_sockaddr *)&serv_addr, sizeof(serv_addr)) < 0)
        {
                printf("ff_connect failed %d: %s\n", errno, strerror(errno));
        }

        epfd = ff_epoll_create(0);

        ev.data.fd = sock;
        ev.events = EPOLLOUT | EPOLLIN;

        ff_epoll_ctl(epfd, EPOLL_CTL_ADD, sock, &ev);
        ff_run(loop, NULL);
        return 0;
}

**Comment by mayank-bhushan** [comment]
Hi, I am facing the same issue. Did you get it to work?
