### ISSUE TITLE
does f-stack support policy based routing and can f-stack support bridge mode like linux brctl?

### ISSUE THREAD

**Issue by ZhongqiXiao** [F-Stack/f-stack#321]
Hi,f-stack:
does f-stack support policy based routing? 
Can f-stack support bridge mode like linux brctl?
Your help will be greatly appreciated! 
Looking forward to your reply.

**Comment by whl739** [comment]
Theoretically, f-stack supports all most feature of freebsd's network stack.

Policy routing can be set by `tool/ipfw`, refer the freebsd's manual: [Policy routing with IPFW](https://lists.freebsd.org/pipermail/freebsd-security/2004-April/001838.html).

A bridge interface can be created by `tool/ifconfig`, refer the freebsd's manual: [Bridging](https://www.freebsd.org/doc/handbook/network-bridging.html).
