### ISSUE TITLE
More clients ff_bind Hang up

### ISSUE THREAD

**Issue by starcity** [F-Stack/f-stack#323]
Hi：
     I use F-stack to create a large number of clients, ff_bind port, and hang up.
     
 This   is my code:

#include <stdio.h>
#include <sys/ioctl.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <strings.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <errno.h>
#include <assert.h>
#include<linux/netfilter_ipv4.h>

#include "ff_config.h"
#include "ff_api.h"
#include "ff_epoll.h"
#include <sys/time.h>
#include <netinet/tcp.h>

void server_connect()
{
    int serverfd = ff_socket(AF_INET, SOCK_STREAM, 0);
    if (serverfd < 0 ) {
        printf("ff_socket failed\n");
        exit(0);
    }

    struct sockaddr_in server;
    bzero(&server, sizeof(server));
    server.sin_family = AF_INET;
    server.sin_port = htons(5432);
    server.sin_addr.s_addr = inet_addr("192.168.60.202");

    int on = 1;
    ff_ioctl(serverfd, FIONBIO, &on);

    struct sockaddr_in local;
    bzero(&local, sizeof(local));
    local.sin_family = AF_INET;
    local.sin_port = htons(INADDR_ANY);
    uint32_t local_ip = inet_addr("192.168.60.201");
    local.sin_addr.s_addr = local_ip;

    int ret = ff_bind(serverfd, (struct linux_sockaddr *)&local, sizeof(local));
    if (ret < 0) {
        printf("pid:%d ff_bind failed :%d\n",getpid(),ntohs(local.sin_port));
        exit(1);
    }
    ff_connect(serverfd, (const struct linux_sockaddr *)&server, sizeof(struct sockaddr_in)); 
}

int index = 0;
int loop(void *arg)
{
        index++;
        if(index < 100){
                usleep(100000);
                return 0;
        }
        if(index > 20000)return 0;
        server_connect();
        usleep(1000);
}

int main(int argc, char * argv[])
{
    ff_init(argc, argv);
    ff_run(loop, NULL);
    return 0;
}

I use pstack to view the stack
![image](https://user-images.githubusercontent.com/6322398/50721256-735dbb80-10f7-11e9-93b9-3032a4919c0b.png)

I use perf to view the stack
![image](https://user-images.githubusercontent.com/6322398/50721267-a607b400-10f7-11e9-94f6-c3c484b60b54.png)

**Hundreds of connections can be built, and they hang up.The problem is ff_bind. Can you modify it?**

**Comment by WoolenWang** [comment]
是不是没人处理这些问题了的?

is that no one handle this problem any more?

**Comment by cxl-ironman** [comment]
应该把socket(),bind(),connect()等操作放在ff_init()和ff_run()之间

**Comment by WoolenWang** [comment]
> 应该把socket(),bind(),connect()等操作放在ff_init()和ff_run()之间

@cxl-ironman 

这样在ff_run 之后就无法发起新的socket了? 那么跑着的时候怎么创建新socket?

if socket bind connect api has to use after ff_init and before ff_run then we can not start a new socket after ff_run ? not all the socket is persistent long socket... how to use client to start new connect when it is running?

**Comment by WoolenWang** [comment]
我试过这样,可以在ff_run中的循环中发起socket:
`
void server_connect()
{
    struct epoll_event ev;
    int ret;
    int serverfd = ff_socket(AF_INET, SOCK_STREAM, 0);
    if (serverfd < 0)
    {
        printf("ff_socket failed\n");
        return;
    }

    struct sockaddr_in server;
    bzero(&server, sizeof(server));
    server.sin_family = AF_INET;
    server.sin_port = htons(80);
    server.sin_addr.s_addr = inet_addr("192.168.2.100");

    int on = 1;
    ff_ioctl(serverfd, FIONBIO, &on);

    // struct sockaddr_in local;
    // bzero(&local, sizeof(local));
    // local.sin_family = AF_INET;
    // local.sin_port = htons(INADDR_ANY);
    // uint32_t local_ip = inet_addr("192.168.1.2");
    // local.sin_addr.s_addr = local_ip;

    // int ret = ff_bind(serverfd, (struct linux_sockaddr *)&local, sizeof(local));
    // if (ret < 0)
    // {
    //     RTDUMP(D_ERROR, "pid:%d ff_bind failed :%d\n", getpid(), ntohs(local.sin_port));
    //     exit(1);
    // }

    ret = ff_connect(serverfd, (const struct linux_sockaddr *)&server, sizeof(struct sockaddr_in));
    if (ret < 0)
    {
        // RTDUMP(D_PACKET, "没有成功connect %d, %d", ret, errno);
        // return;
    }
    // RTDUMP(D_TRACE, "成功connect %d, %d", ret, errno);
    // ret = ff_close(serverfd);
    // if (ret < 0)
    // {
    //     RTDUMP(D_ERROR, "没有成功 close %d, %d", ret, errno);
    //     return;
    // }
    ev.data.fd = serverfd;
    ev.events = EPOLLOUT | EPOLLIN | EPOLLERR;
    ff_epoll_ctl(epfd, EPOLL_CTL_ADD, serverfd, &ev);
}
`
不能bind，需要把socket加到epoll里面,后面再
int nevents = ff_epoll_wait(epfd, events, MAX_EVENTS, 0);

才行.

**Comment by WoolenWang** [comment]
这个Bind的,bsd的内核处理貌似有bug，查了一下，上面出现死循环的问题原因在于 in_pcb.c里面的 in_pcblookup_local 有死循环.

提交了一个pr #343

**Comment by starcity** [comment]
F-stack does not handle FreeBSD protocol stack well.Problems arise when creating a large number of bind
 clients .

**Comment by starcity** [comment]
> 是不是没人处理这些问题了的?
> 
> is that no one handle this problem any more?

F-stack does not correspond

**Comment by jfb8856606** [comment]
You can test it use 944e508

**Comment by WoolenWang** [comment]
Why revert 944e508

**Comment by jfb8856606** [comment]
No extensive stability testing has been performed on it, only reserved it in the dev branch now.

**Comment by WoolenWang** [comment]
> No extensive stability testing has been performed on it, only reserved it in the dev branch now.


you should add some test suite with this project, all great opensource project were well self tested.
add some unittest and single functional testscript for it will be great
@jfb8856606
