### ISSUE TITLE
Why revert "DPDK:upgrade to 18.11.0 LTS." ?

### ISSUE THREAD

**Issue by shuaisilun** [F-Stack/f-stack#333]
I could see that in the lastest commit you reverted the DPDK updates for 18.11. May I ask why did you reverted the updates ? Our team is trying to use f-stack with 100G NIC but we found out that we need to update dpdk to 18.11 to support it.

**Comment by vanlink** [comment]
It seems that hw checksum will not work.

**Comment by jfb8856606** [comment]
DPDK 18.11.0 has been moved to dev branch, becasue it will cause some problems:
1. The kni feature can't use now.
2. There are many changes in DPDK 18.11, such as rte_malloc, mempool, mulit-process, etc. May be they will cause F-Stack work abnormal while running in multi-processes.  
And so F-Stack should do more test, and then merge to master branch.

**Comment by shuaisilun** [comment]
Thx for the clarification !
