### ISSUE TITLE
Nginx so old. Is there any chance of port the newest version of nginx  1.15.9 that support tlsv1.3?

### ISSUE THREAD

**Issue by lmonteiro440** [F-Stack/f-stack#340]
I´d like to use NGINX over F-Stack but the version 1.11.10 doesn´t support TLS1.3.
Is there any chance to port the 1.15.9 version?
Thanks

**Comment by lmonteiro440** [comment]
I´d like to use NGINX over F-Stack but the version 1.11.10 doesn´t support TLS1.3.
Is there any chance to port the 1.15.9 version?
Thanks

**Comment by tsung-li** [comment]
I've port it to 1.13,  it seems works. almost all of changes can merge directly except one timer api changed in nginx

**Comment by jfb8856606** [comment]
We will port nginx 1.14.2 to F-Stack later.

**Comment by lmonteiro440** [comment]
Thank you very much. Since I use it together with Ixia breakingpoint traffic generator in a test bed tlsv1.3 is necessary.
Regards

**Comment by lmonteiro440** [comment]
Dongsheng-LI if it is working could you make it available?
Thanks
