### ISSUE TITLE
中文:f-stack 是否还在不断更新和维护阶段 还是已经停止后续的更新和维护了？English:Is f-stack still in the update and maintenance stage or has it stopped the follow-up update and maintenance?

### ISSUE THREAD

**Issue by fantastic2085** [F-Stack/f-stack#342]

**Comment by WoolenWang** [comment]
貌似都没人理了?
it seems that no one maintain this any more?

**Comment by fantastic2085** [comment]
> 貌似都没人理了?
> it seems that no one maintain this any more?
还不清楚 我看最近递交切换了DPDK的代码，没有修改什么bug的 难道不维护了吗？

**Comment by jfb8856606** [comment]
F-Stack will release next version in June or July.
