### ISSUE TITLE
Can you use blocking calls or need to use kqueue/epoll interface?

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [F-Stack/f-stack#344]
Can you just use blocking calls like ff_recvfrom by themselves with F-stack, or do they have to always be in a kqueue/epoll callback function from ff_run?  Thanks!

**Comment by jfb8856606** [comment]
F-Stack use PMD(Pool Mode Driver of DPDK) to improve performance, so if you use socket API as block mode, it won't recvive the remaining data.

**Comment by NEOAdvancedTechnology** [comment]
Thanks!

**Comment by jfb8856606** [comment]
And you can try to use the [micro_thread framework](https://github.com/F-Stack/f-stack/tree/master/app/micro_thread)

**Comment by WoolenWang** [comment]
> And you can try to use the [micro_thread framework](https://github.com/F-Stack/f-stack/tree/master/app/micro_thread)

any micro_thread usage example?

**Comment by NEOAdvancedTechnology** [comment]
micro_thread usage example would be great!

**Comment by jfb8856606** [comment]
The [echo demo](https://github.com/F-Stack/f-stack/blob/master/app/micro_thread/echo.cpp) of micro_thread.

**Comment by WoolenWang** [comment]
> The [echo demo](https://github.com/F-Stack/f-stack/blob/master/app/micro_thread/echo.cpp) of micro_thread.

Thanks, i will try it , it looks very nice to use.

**Comment by WoolenWang** [comment]
> The [echo demo](https://github.com/F-Stack/f-stack/blob/master/app/micro_thread/echo.cpp) of micro_thread.

@jfb8856606 

btw , using this micro-thread how to debug ? like how to show thread in gdb ? how to bt in gdb show the thread current stack status?

**Comment by jfb8856606** [comment]
Uh, that is a difficult job. 

You can use gdb, but it hard to use in frequent context switches, usually we will add some logs to show some status.

**Comment by WoolenWang** [comment]
@jfb8856606

but this micro-thread should have this abilitity to debug current how many micro thread in wait, and the schedule waiting list. like provide the gdb python tool to dump the related data in memory.
