### ISSUE TITLE
Move to redis 4.0.10 run fail

### ISSUE THREAD

**Issue by fantastic2085** [F-Stack/f-stack#352]
EAL: PCI device 0000:02:01.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:100f net_e1000_em
EAL: PCI device 0000:02:06.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:100f net_e1000_em
EAL: PCI device 0000:02:07.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:100f net_e1000_em
lcore: 0, port: 0, queue: 0
create mbuf pool on socket 0
create ring:dispatch_ring_p0_q0 success, 2047 ring entries are now free!
Port 0 MAC: 00 0c 29 dc a6 d8
RX checksum offload supported
TX ip checksum offload supported
TX TCP&UDP checksum offload supported
TSO is disabled
set port 0 to promiscuous mode ok

Checking link statusdone
Port 0 Link Up - speed 1000 Mbps - full-duplex
link_elf_lookup_symbol: missing symbol hash table
link_elf_lookup_symbol: missing symbol hash table
Timecounters tick every 10.000 msec
Timecounter "ff_clock" frequency 100 Hz quality 1
f-stack-0: Ethernet address: 00:0c:29:dc:a6:d8
28391:C 15 Mar 09:41:12.878 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
28391:C 15 Mar 09:41:12.878 # Redis version=4.0.10, bits=64, commit=77306048, modified=1, pid=28391, just started
28391:C 15 Mar 09:41:12.878 # Configuration loaded
28391:M 15 Mar 09:41:12.878 * Increased maximum number of open files to 10032 (it was originally set to 1024).

=== REDIS BUG REPORT START: Cut & paste starting from here ===
28391:M 15 Mar 09:41:12.878 # ------------------------------------------------
28391:M 15 Mar 09:41:12.878 # !!! Software Failure. Press left mouse button to continue
28391:M 15 Mar 09:41:12.878 # Guru Meditation: Error registering the readable event for the module blocked clients subsystem. #server.c:1949
28391:M 15 Mar 09:41:12.878 # (forcing SIGSEGV in order to print the stack trace)
28391:M 15 Mar 09:41:12.878 # ------------------------------------------------
28391:M 15 Mar 09:41:12.878 # Redis 4.0.10 crashed by signal: 11
28391:M 15 Mar 09:41:12.878 # Crashed running the instruction at: 0x4b2f07
28391:M 15 Mar 09:41:12.878 # Accessing address: 0xffffffffffffffff
28391:M 15 Mar 09:41:12.878 # Failed assertion: <no assertion failed> (<no file>:0)

**I have ported all the changes from redis3.2.8 to redis4.0.10** 

![image](https://user-images.githubusercontent.com/4116773/54402476-1558e000-4707-11e9-981d-14fea21a9a2b.png)

**Comment by fantastic2085** [comment]
Does anyone have a look?

**Comment by zhumyww** [comment]
I have the SAME problem! Have you solved?

**Comment by zhumyww** [comment]
> Does anyone have a look?

The reason why server panic is that F-Stack does not support PIPE / unix domain events.
But even if you remove pipe related code, redis does not work as well. May be some problem still exist.
