### ISSUE TITLE
How do I start redis3.2.8 without start.sh

### ISSUE THREAD

**Issue by fantastic2085** [F-Stack/f-stack#353]

**Comment by jfb8856606** [comment]
[Quict start](https://github.com/F-Stack/f-stack/blob/master/doc/F-Stack_Quick_Start_Guide.md)

**Comment by fantastic2085** [comment]
> [Quict start](https://github.com/F-Stack/f-stack/blob/master/doc/F-Stack_Quick_Start_Guide.md)
thank you!
Could you take a look at it Move to redis 4.0.10 run fail #352?
