### ISSUE TITLE
Send and Receive layer 2 packets

### ISSUE THREAD

**Issue by krishnamurthyvd** [F-Stack/f-stack#361]
Does f-stack support PF_PACKET/SOCK_RAW kind of socket interface to send and receive L2 packets directly from a network interface? FreeBSD's stack supports it via BPF. Does f-stack support this or is there any other API for achieving the same?

**Comment by jfb8856606** [comment]
See #215 or the function `ff_regist_packet_dispatcher` in [ff_api.h](https://github.com/F-Stack/f-stack/blob/master/lib/ff_api.h)
