### ISSUE TITLE
about fstack parameter: fd_reserve in config.ini

### ISSUE THREAD

**Issue by fantastic2085** [F-Stack/f-stack#363]
What does fd_reserve in config.ini do?
Set fd_reserve to 1024 and the ff_socket return value to 1024

**Comment by fantastic2085** [comment]
Can anybody answer that？

**Comment by jfb8856606** [comment]
Yes, F-Stack will use fd from 1024.

**Comment by fantastic2085** [comment]
> Yes, F-Stack will use fd from 1024.

@jfb8856606  If multiple threads create sockets, is the socket fd both 1024

**Comment by jfb8856606** [comment]
It is independent in each F-STACK **process**, shared-nothing.
