### ISSUE TITLE
ff_connect error

### ISSUE THREAD

**Issue by liningjie418** [F-Stack/f-stack#365]
Hi , 

I use the fowlloing code that found error
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
ff_connect failed 106: Transport endpoint is already connected
Is there have any advices ? thanks .

#include <stdio.h>
#include <sys/ioctl.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <strings.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <errno.h>
#include <assert.h>

#include "ff_config.h"
#include "ff_api.h"
#include "ff_epoll.h"

#define MAX_EVENTS 512

struct epoll_event ev;
struct epoll_event events[MAX_EVENTS];

int epfd;
int sockfd;

int loop(void *arg)
{	
    struct sockaddr_in my_addr;
	
    bzero(&my_addr, sizeof(my_addr));
    my_addr.sin_family = AF_INET;
    my_addr.sin_port = htons(80);
    my_addr.sin_addr.s_addr = inet_addr("192.168.31.1");

	int on = 1;
   	ff_ioctl(sockfd, FIONBIO, &on);
	
	if (ff_connect(sockfd, (struct linux_sockaddr *)&my_addr, sizeof(my_addr)) == -1) 
	{
   		 printf("ff_connect failed %d: %s\n", errno, strerror(errno));
	} else 
	{
   	 	printf("ff_connect OK\n");
    	exit(0);
	}
}

int main(int argc, char * argv[])
{
    ff_init(argc, argv);

    sockfd = ff_socket(AF_INET, SOCK_STREAM, 0);

    if (sockfd < 0) {
        printf("ff_socket failed\n");
        exit(1);
    }
	
    assert((epfd = ff_epoll_create(0)) > 0);
    ev.data.fd = sockfd;
    ev.events = EPOLLIN | EPOLLOUT;
    ff_epoll_ctl(epfd, EPOLL_CTL_ADD, sockfd, &ev);
    ff_run(loop, NULL);
    return 0;
}

**Comment by leontian** [comment]
you only have one socket and you are trying to connect multiple times in a loop.

**Comment by liningjie418** [comment]
Thanks for your reply, could you provide a code example of client side ?

**Comment by liningjie418** [comment]
Hi f-stack ,

I use the following code that can not conntect the remote server, and not reply "ACK" to server, is there my code has something wrong ?

tcp        0      0 192.168.31.144:80       192.168.31.139:26493    SYN_RECV    -      


int checkconnect(int fd)
{
	int epfd = ff_epoll_create(1024);

    struct epoll_event ev;
    struct epoll_event events[MAX_EVENTS];

    ev.data.fd = fd;
    ev.events = EPOLLOUT | EPOLLIN | EPOLLET;

    ff_epoll_ctl(epfd, EPOLL_CTL_ADD, fd, &ev);

    int nevents = ff_epoll_wait(epfd,  events, MAX_EVENTS, -1);
    int i;

    if (nevents == 0)
	{
            printf("nevents: %d\n", nevents);
            return -1;
    }
	
    for (i = 0; i < nevents; i++)
	{
		int err = -1;
        socklen_t len = sizeof(int);

		if(events[i].events & EPOLLOUT)
		{
			if (ff_getsockopt(events[i].data.fd, SOL_SOCKET, SO_ERROR, &err, &len) < 0)
			{
				ff_close(fd);
				printf("getsockopt errno:%d %s\n", errno, strerror(errno));
				return -1;
			}

			if(err != 0)
			{
				printf("not access\n");

				return -1;
			}
		}
	}

    return 0;
}

int loop()
{
	char *message = "hello world";
    int ret = 0;

	if(checkconnect(client_socket))
		return -1;

    ret = ff_send(client_socket, message, strlen(message), 0);

    printf("Already Send!, ret: %d\n", ret);

    ff_close(client_socket);

	exit(0);
	
    return 0;
}

int main(int argc, char * argv[])
{
	struct sockaddr_in server_addr;
	
    bzero(&server_addr, sizeof(server_addr));
    server_addr.sin_family = AF_INET;
	
	ff_init(argc, argv);
	
	client_socket = ff_socket(AF_INET, SOCK_STREAM, 0);
	if (client_socket < 0)
	{
		printf("ff_socket failed\n");
        exit(1);
    }

	int on = 1;
	ff_ioctl(client_socket, FIONBIO, &on);  /* unblock */

	if(inet_pton(AF_INET, "192.168.31.144", &server_addr.sin_addr) != 1)
    {
         printf("\nInvalid address/ Address not supported \n");
         return -1;
    }

    server_addr.sin_port = htons(80);

	if (ff_connect(client_socket, (struct linux_sockaddr *)&server_addr, sizeof(server_addr)) < 0)
	{
		printf("connect failed: %s\n", strerror(errno));
	}

	ff_run(loop, NULL);

	return 0;
}

**Comment by liningjie418** [comment]
I am confused about code **ff_getsockopt(events[i].data.fd, SOL_SOCKET, SO_ERROR, &err, &len)**
 ,  it rised write event and call getsockopt get the err value is 0. 

Then I think connection is established,  but I found the connection is not established.

netstat -antp on the server side:
tcp 0 0 192.168.31.144:80 192.168.31.139:26493 SYN_RECV -

And I use tcpdump , find client just send syn and not response server, server is reconnecting client.

**Comment by liningjie418** [comment]
麻烦看一下我的问题吧，多谢了.

Please take a look at my issue, thanks.

**Comment by liningjie418** [comment]
我发现日志中有这样日志， 请问有影响吗？

I found following words in log file , any affected?

Apr  1 15:41:16 linj-virtual-machine f-stack[113656]: TCP: [192.168.31.144]:80 to [192.168.31.139]:55514 tcpflags 0x%b; tcp_do_segment: Timestamp not expected, no action

**Comment by liningjie418** [comment]
On the server side , I run following cmd and still has no effect.

echo 0 > /proc/sys/net/ipv4/tcp_timestamps
echo 0 > /proc/sys/net/ipv4/tcp_tw_recycle

**Comment by liningjie418** [comment]
我把tcp_debug.c 中tcpconsdebug = 1， 
打印如下，希望能有帮助。

invalid proc_id:-1, use default 0
[dpdk]: lcore_mask=1
[dpdk]: channel=4
[dpdk]: promiscuous=1
[dpdk]: numa_on=1
[dpdk]: tso=0
[dpdk]: vlan_strip=1
[dpdk]: idle_sleep=0
[dpdk]: port_list=0
[dpdk]: nb_vdev=0
[port0]: addr=192.168.31.139
[port0]: netmask=255.255.225.0
[port0]: broadcast=192.168.31.255
[port0]: gateway=192.168.31.2
[freebsd.boot]: hz=100
[freebsd.boot]: fd_reserve=1024
[freebsd.boot]: kern.ipc.maxsockets=262144
[freebsd.boot]: net.inet.tcp.syncache.hashsize=4096
[freebsd.boot]: net.inet.tcp.syncache.bucketlimit=100
[freebsd.boot]: net.inet.tcp.tcbhashsize=65536
[freebsd.boot]: kern.ncallout=262144
[freebsd.sysctl]: kern.ipc.somaxconn=32768
[freebsd.sysctl]: kern.ipc.maxsockbuf=16777216
[freebsd.sysctl]: net.link.ether.inet.maxhold=5
[freebsd.sysctl]: net.inet.tcp.fast_finwait2_recycle=1
[freebsd.sysctl]: net.inet.tcp.sendspace=16384
[freebsd.sysctl]: net.inet.tcp.recvspace=8192
[freebsd.sysctl]: net.inet.tcp.nolocaltimewait=1
[freebsd.sysctl]: net.inet.tcp.cc.algorithm=cubic
[freebsd.sysctl]: net.inet.tcp.sendbuf_max=16777216
[freebsd.sysctl]: net.inet.tcp.recvbuf_max=16777216
[freebsd.sysctl]: net.inet.tcp.sendbuf_auto=1
[freebsd.sysctl]: net.inet.tcp.recvbuf_auto=1
[freebsd.sysctl]: net.inet.tcp.sendbuf_inc=16384
[freebsd.sysctl]: net.inet.tcp.recvbuf_inc=524288
[freebsd.sysctl]: net.inet.tcp.sack.enable=1
[freebsd.sysctl]: net.inet.tcp.blackhole=1
[freebsd.sysctl]: net.inet.tcp.msl=2000
[freebsd.sysctl]: net.inet.tcp.delayed_ack=0
[freebsd.sysctl]: net.inet.tcp.log_debug=1
[freebsd.sysctl]: net.inet.udp.blackhole=1
[freebsd.sysctl]: net.inet.ip.redirect=0
EAL: Detected 2 lcore(s)
EAL: Auto-detected process type: PRIMARY
EAL: No free hugepages reported in hugepages-1048576kB
f-stack -c1 -n4 --proc-type=auto EAL: Probing VFIO support...
EAL: PCI device 0000:02:01.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:100f net_e1000_em
EAL: PCI device 0000:02:02.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:100f net_e1000_em
lcore: 0, port: 0, queue: 0
create mbuf pool on socket 0
create ring:dispatch_ring_p0_q0 success, 2047 ring entries are now free!
Port 0 MAC: 00 0c 29 1f 77 96
RX checksum offload supported
TX ip checksum offload supported
TX TCP&UDP checksum offload supported
TSO is disabled
set port 0 to promiscuous mode ok

Checking link statusdone
Port 0 Link Up - speed 1000 Mbps - full-duplex
link_elf_lookup_symbol: missing symbol hash table
link_elf_lookup_symbol: missing symbol hash table
Timecounters tick every 10.000 msec
Timecounter "ff_clock" frequency 100 Hz quality 1
f-stack-0: Ethernet address: 00:0c:29:1f:77:96
0x7ffff7f25000 SYN_SENT:output [b1d73685..b1d73671)@0, urp=0<SYN> -> SYN_SENT
	rcv_(nxt,wnd,up) (0,0,0) snd_(una,nxt,max) (b1d73685,b1d73685,b1d73685)
	snd_(wl1,wl2,wnd) (0,0,0)
0x7ffff7f25000 CLOSED:user CONNECT -> SYN_SENT
	rcv_(nxt,wnd,up) (0,0,0) snd_(una,nxt,max) (b1d73685,b1d73686,b1d73686)
	snd_(wl1,wl2,wnd) (0,0,0)
connect failed: Operation now in progress
0x7ffff7f25000 CLOSED:input 0@f7f55b00, urp=0<SYN,ACK,FIN,RST,PUSH,URG> -> ESTABLISHED
	rcv_(nxt,wnd,up) (4c127403,2238,4c127403) snd_(una,nxt,max) (b1d73686,b1d73686,b1d73686)
	snd_(wl1,wl2,wnd) (4c127403,b1d73686,7210)
0x7ffff7f25000 ESTABLISHED:output [b1d73686..b1d73672)@4c127403, urp=0<ACK> -> ESTABLISHED
	rcv_(nxt,wnd,up) (4c127403,2238,4c127403) snd_(una,nxt,max) (b1d73686,b1d73686,b1d73686)
	snd_(wl1,wl2,wnd) (4c127403,b1d73686,7210)
access, Operation now in progress, 115
0x7ffff7f25000 ESTABLISHED:output [b1d73686..b1d73672)@4c127403, urp=0<ACK,PUSH> -> ESTABLISHED
	rcv_(nxt,wnd,up) (4c127403,2238,4c127403) snd_(una,nxt,max) (b1d73686,b1d73686,b1d73686)
	snd_(wl1,wl2,wnd) (4c127403,b1d73686,7210)
0x7ffff7f25000 ESTABLISHED:user SEND -> ESTABLISHED
	rcv_(nxt,wnd,up) (4c127403,2238,4c127403) snd_(una,nxt,max) (b1d73686,b1d73691,b1d73691)
	snd_(wl1,wl2,wnd) (4c127403,b1d73686,7210)
Already Send!, ret: 11, Operation now in progress
0x7ffff7f25000 FIN_WAIT_1:output [b1d73691..b1d7367d)@4c127403, urp=0<ACK,FIN> -> FIN_WAIT_1
	rcv_(nxt,wnd,up) (4c127403,2238,4c127403) snd_(una,nxt,max) (b1d73686,b1d73691,b1d73691)
	snd_(wl1,wl2,wnd) (4c127403,b1d73686,7210)
0x7ffff7f25000 ESTABLISHED:user DISCONNECT -> FIN_WAIT_1
	rcv_(nxt,wnd,up) (4c127403,2238,4c127403) snd_(una,nxt,max) (b1d73686,b1d73692,b1d73692)
	snd_(wl1,wl2,wnd) (4c127403,b1d73686,7210)
0x7ffff7f25000 FIN_WAIT_1:user CLOSE -> FIN_WAIT_1
	rcv_(nxt,wnd,up) (4c127403,2238,4c127403) snd_(una,nxt,max) (b1d73686,b1d73692,b1d73692)
	snd_(wl1,wl2,wnd) (4c127403,b1d73686,7210)

**Comment by nizibu** [comment]
我对代码稍微修改了下，现在可以运行了，能接受到数据，但是连接的过程十分缓慢。

#include <stdio.h>
#include <sys/ioctl.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <strings.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <errno.h>
#include <assert.h>

#include "ff_config.h"
#include "ff_api.h"
#include "ff_epoll.h"

int epfd;
int  client_socket;
#define MAX_EVENTS 512

int loop()
{
	int ret = 0;
	char recv_buf[4096] = {0};
	char *message = "hello world";
	struct epoll_event events[MAX_EVENTS];

	int nevents = ff_epoll_wait(epfd,  events, MAX_EVENTS, -1);
	int i;

	if (nevents == 0)
	{
	      //  printf("nevents: %d\n", nevents);
	        return -1;
	}

	for (i = 0; i < nevents; i++)
	{
	int err = -1;
	    socklen_t len = sizeof(int);

		if(events[i].events & EPOLLOUT)
		{
			if (ff_getsockopt(events[i].data.fd, SOL_SOCKET, SO_ERROR, &err, &len) < 0)
			{
				ff_close(events[i].data.fd);
				printf("getsockopt errno:%d %s\n", errno, strerror(errno));
				return -1;
			}

			if(err != 0)
			{
				printf("not access\n");
				return -1;
			}

			ret = ff_send(events[i].data.fd, message, strlen(message), 0);
			printf("Already Send!, ret: %d\n", ret);
		}else if(events[i].events & EPOLLIN){
			ret = ff_read(events[i].data.fd, recv_buf, sizeof(recv_buf));
			printf("ret :[%d] recv_buf:[%s]\n", ret, recv_buf);
			ff_close(events[i].data.fd);
		}
	}

	return 0;
}

int main(int argc, char * argv[])
{
	struct sockaddr_in server_addr;

	bzero(&server_addr, sizeof(server_addr));
	server_addr.sin_family = AF_INET;

	ff_init(argc, argv);

	client_socket = ff_socket(AF_INET, SOCK_STREAM, 0);
	if (client_socket < 0)
	{
		printf("ff_socket failed\n");
	    exit(1);
	}

	int on = 1;
	ff_ioctl(client_socket, FIONBIO, &on);  /* unblock */
	
	epfd = ff_epoll_create(1024);

	struct epoll_event ev;
	ev.data.fd = client_socket;
	ev.events = EPOLLOUT | EPOLLIN | EPOLLET;
	ff_epoll_ctl(epfd, EPOLL_CTL_ADD, client_socket, &ev);

	if(inet_pton(AF_INET, "10.0.0.166", &server_addr.sin_addr) != 1)
	{
	     printf("\nInvalid address/ Address not supported \n");
	     return -1;
	}

	server_addr.sin_port = htons(3000);

	if (ff_connect(client_socket, (struct linux_sockaddr *)&server_addr, sizeof(server_addr)) < 0)
	{
		printf("connect failed: %s\n", strerror(errno));
	}

	ff_run(loop, NULL);

	return 0;
}

**Comment by liningjie418** [comment]
非常感谢你的回答，我有点不太明白，当有可写事件的时候我认为当前连接已经建立，直接调用ff_write为什么不可以呢？

**Comment by liningjie418** [comment]
好像我不能调用exit(0)， 不知道为什么

**Comment by nizibu** [comment]
loop那里有epoll重复添加的动作，不确定是否存在问题。正常的操作，是在connect前把socket_fd的写事件加入epoll，等待读事件的返回则表示连接成功，并不需要每次都去添加。

**Comment by nizibu** [comment]
loop那里有epoll重复添加的动作，不确定是否存在问题。正常的操作，是在connect前把socket_fd的写事件加入epoll，等待写事件的返回则表示连接成功，并不需要每次都去添加。

**Comment by liningjie418** [comment]
对的。之前怀疑fstack是基于轮询的，想着接收服务器端的响应是不是需要重回协议栈，在进loop中，我看了一下代码，3次握手实在tcp_input中自动自动完成的，并不会上到上层应用中，好奇怪。

**Comment by nizibu** [comment]
f-stack是基于轮询的，但freebsd协议栈好像还有一个非轮询模式，只是现在f-stack还没有封装。你现在是才开始研究dpdk吗，方便加个联系方式吗，以后好沟通。

**Comment by liningjie418** [comment]
可以啊，我是刚开始学习，菜鸟加小白，哈哈，qq1350445139

**Comment by jfb8856606** [comment]
F-Stack is designed for high cc, high throughput， if you want use for single connection， you should do some modify yourself. see #241

**Comment by zfy3000163** [comment]
> F-Stack专为高CC，高吞吐量而设计，如果要用于单个连接，则应自行进行一些修改。参见[＃241](https://github.com/F-Stack/f-stack/issues/241)

场景：f-stack作为客户端程序，发送f-stack的服务器端，客户端调用ff_write(fd, buf, length)， length 大于1500的时候，ff_write会失败，请问这是什么原因。length < 1500没有问题。谢谢！
如果采用f-stack作为客户端，发送到非f-stack得服务器端， 是没有这个问题的，length可以是66535.
