### ISSUE TITLE
As the number of cores increases, Nginx-fstack performance does not improve？

### ISSUE THREAD

**Issue by ccjinghang** [F-Stack/f-stack#369]
Hello
     I tested f-stack performance with the WRK tool.
     The test environment is as follows：
     client： CPU 8-core  memory ：16G   Network bandwidth：10000M/s
     server： CPU 8-core  memory ：16G   Network bandwidth：10000M/s
     **f-stack.conf**
     [dpdk]

lcore_mask=f
channel=4
promiscuous=1
numa_on=1
tso=0
vlan_strip=1

port_list=0

[port0]
addr=192.168.128.52
netmask=255.255.255.0
broadcast=192.168.128.255
gateway=

#pcap=./a.pcap

#[kni]
#enable=1
#method=reject
#tcp_port=80,443
#udp_port=53

[freebsd.boot]
hz=100

fd_reserve=1024

kern.ipc.maxsockets=262144

net.inet.tcp.syncache.hashsize=4096
net.inet.tcp.syncache.bucketlimit=100

net.inet.tcp.tcbhashsize=65536

kern.ncallout=262144

[freebsd.sysctl]
kern.ipc.somaxconn=32768
kern.ipc.maxsockbuf=16777216

net.link.ether.inet.maxhold=5

net.inet.tcp.fast_finwait2_recycle=1
net.inet.tcp.sendspace=16384
net.inet.tcp.recvspace=8192
net.inet.tcp.nolocaltimewait=1
net.inet.tcp.cc.algorithm=cubic
net.inet.tcp.sendbuf_max=16777216
net.inet.tcp.recvbuf_max=16777216
net.inet.tcp.sendbuf_auto=1
net.inet.tcp.recvbuf_auto=1
net.inet.tcp.sendbuf_inc=16384
net.inet.tcp.recvbuf_inc=524288
net.inet.tcp.sack.enable=1
net.inet.tcp.blackhole=1
net.inet.tcp.msl=2000
net.inet.tcp.delayed_ack=0

net.inet.udp.blackhole=1
net.inet.ip.redirect=0

**nginx.conf**

user  root;

worker_processes  4;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

fstack_conf f-stack.conf;

events {
    worker_connections  102400;
    use kqueue;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        off;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        # bulid server on kernel network stack 
        # 
        #kernel_network_stack on;

        #charset koi8-r;

        access_log /dev/null;
        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }

    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}

**The results are as follows**
The WRK consumes about 40 percent of the CPU.
The idling rate of Nginx-fstack is about 0.1%.
Running 1m test @ http://192.168.128.47:80
  8 threads and 1600 connections
^C  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.11ms    1.64ms  32.03ms   69.79%
    Req/Sec    65.31k    11.06k  161.86k    80.89%
  4386857 requests in 8.50s, 0.98GB read
Requests/sec: 516361.13
Transfer/sec:    117.67MB

I modified the fstack configuration as follows：

lcore_mask=ff
channel=4
promiscuous=1
numa_on=1

I modified the Nginx configuration as follows：

user  root;

worker_processes  8;

**The results are as follows**
The WRK consumes about 38 percent of the CPU.
The idling rate of Nginx-fstack is about 0.04%.
Running 1m test @ http://192.168.128.47:80
  8 threads and 1600 connections
^C  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.49ms    1.73ms  15.94ms   67.87%
    Req/Sec    57.71k     2.66k   67.01k    72.98%
  2848812 requests in 6.20s, 649.19MB read
Requests/sec: 459600.11
Transfer/sec:    104.73MB

**As the number of cores increases, the performance does not improve. Can you tell me the reason？**

**Comment by ccjinghang** [comment]
Hello
   I have solved the problem.The client interrupt is not bound, resulting in the pressure can not go up.

**Comment by Leopold-Sun** [comment]
I came up with the same issue, what does "The client interrupt is not bound" mean?

**Comment by ccjinghang** [comment]
> I came up with the same issue, what does "The client interrupt is not bound" mean?

Generally, the number of network card queues is the same as the number of CPU cores. One queue corresponds to one interrupt, so the interrupt of network card multi-queue can be bound to the CPU one by one.

**Comment by Leopold-Sun** [comment]
> > I came up with the same issue, what does "The client interrupt is not bound" mean?
> 
> Generally, the number of network card queues is the same as the number of CPU cores. One queue corresponds to one interrupt, so the interrupt of network card multi-queue can be bound to the CPU one by one.

That's true. Thanks a lot. The problem is solved.

**Comment by rajeshwarp2002** [comment]
@Leopold-Sun @ccjinghang Hello guys, is this cpu binding for IRQ of dpdk Rx queues or kernel nic interface? I am not able to find how to get IRQ for each Rx/Tx queue for the NIC bound to dpdk, I always thought dpdk doesnt need IRQ because it is running in poll mode and it bypasses kerenl, can you hlep?
