### ISSUE TITLE
Fstack-Nginx cannot run more than 32 worker_processes?

### ISSUE THREAD

**Issue by ccjinghang** [F-Stack/f-stack#373]
I want to run 36worker_processes.The specific configuration is as follows:
**f-stack.conf**
[dpdk]
lcore_mask=fffffffff
channel=4
promiscuous=1
numa_on=1
tso=0
vlan_strip=1
port_list=0
[port0]
addr=192.168.128.52
netmask=255.255.255.0
broadcast=192.168.128.255
gateway=

**nginx.conf**
user root;
worker_processes 36;

The result is that 32 processes are pulled up.I checked the log and found no errors.Can you help me with this problem?

**Comment by ccjinghang** [comment]
Hello！
When I first looked at the results with the htop tool, it showed 32 processes.I used the top tool to look at the results, which showed 36 processes.The htop tool does not map the CPu share of all processes.

**Comment by ccjinghang** [comment]
Hello !
I found that when 36 processes were executed, the CPU share of 28 processes was 100%, and the CPU share of 8 processes was 50%. In the end, the total CPU share was the same as that of 32 processes.Therefore, this is not the htop  tool issue, but rather a CPU binding issue.Can you help me with this problem?

**Comment by jinhao2** [comment]
https://github.com/F-Stack/f-stack/pull/402

**Comment by ccjinghang** [comment]
Thank you for your reply. @
