### ISSUE TITLE
Unable to reduce latency

### ISSUE THREAD

**Issue by ahmednazir85** [F-Stack/f-stack#375]
I'm trying to get low latency using DPDK and F-stack. I have disabled vector mode and enabled TSO. I'm using PMD i40e on x722 NIC.

I have also applied this patch from #241

`diff --git a/lib/ff_dpdk_if.c b/lib/ff_dpdk_if.c
index 21691fc..29063a4 100644
--- a/lib/ff_dpdk_if.c
+++ b/lib/ff_dpdk_if.c
@@ -1276,10 +1276,12 @@ send_single_packet(struct rte_mbuf *m, uint8_t port)
     len++;

     /* enough pkts to be sent */
-    if (unlikely(len == MAX_PKT_BURST)) {
-        send_burst(qconf, MAX_PKT_BURST, port);
-        len = 0;
-    }
+    //if (unlikely(len == MAX_PKT_BURST)) {
+    //    send_burst(qconf, MAX_PKT_BURST, port);
+    //    len = 0;
+    //}
+    send_burst(qconf, len, port);
+    len = 0;

     qconf->tx_mbufs[port].len = len;
     return 0;`

But there is no significant difference in latency. Is there is something I'm missing?

**Comment by jfb8856606** [comment]
see 59bb71f

**Comment by ahmednazir85** [comment]
Thanks let me check

**Comment by ahmednazir85** [comment]
I'm now able to get 6us round trip by setting pkt_tx_delay=0.
Thanks for update.

**Comment by renzibei** [comment]
@ahmednazir85 Hello, may I know how did you disable vector mode of i40e? I couldn't find the related resources on the internet. Thank you!

**Comment by ahmednazir85** [comment]
You can use --force-max-simd-bitwidth=64 flag.

**Comment by renzibei** [comment]
> You can use --force-max-simd-bitwidth=64 flag.

Thanks for reply. I have modified the driver code to force DPDK to use non-vec code for rx and tx. However, I found that this seems to have very little impacts on latency. The original rtt latency is about 12 us. And disabling vector got the similar result. Do you have any experience about this? @ahmednazir85
