### ISSUE TITLE
./start.sh print No probed ethernet devices

### ISSUE THREAD

**Issue by dongbin1024** [F-Stack/f-stack#379]
1、my problem:
[root@localhost f-stack]# ./start.sh
./example/helloworld --conf config.ini --proc-type=primary --proc-id=0
[dpdk]: lcore_mask=1
[dpdk]: channel=4
[dpdk]: promiscuous=1
[dpdk]: numa_on=1
[dpdk]: tso=0
[dpdk]: vlan_strip=1
[dpdk]: port_list=0
[port0]: addr=108.80.25.123
[port0]: netmask=255.255.255.0
[port0]: broadcast=108.80.25.255
[port0]: gateway=
[freebsd.boot]: hz=100
[freebsd.boot]: fd_reserve=1024
[freebsd.boot]: kern.ipc.maxsockets=262144
[freebsd.boot]: net.inet.tcp.syncache.hashsize=4096
[freebsd.boot]: net.inet.tcp.syncache.bucketlimit=100
[freebsd.boot]: net.inet.tcp.tcbhashsize=65536
[freebsd.boot]: kern.ncallout=262144
[freebsd.sysctl]: kern.ipc.somaxconn=32768
[freebsd.sysctl]: kern.ipc.maxsockbuf=16777216
[freebsd.sysctl]: net.link.ether.inet.maxhold=5
[freebsd.sysctl]: net.inet.tcp.fast_finwait2_recycle=1
[freebsd.sysctl]: net.inet.tcp.sendspace=16384
[freebsd.sysctl]: net.inet.tcp.recvspace=8192
[freebsd.sysctl]: net.inet.tcp.nolocaltimewait=1
[freebsd.sysctl]: net.inet.tcp.cc.algorithm=cubic
[freebsd.sysctl]: net.inet.tcp.sendbuf_max=16777216
[freebsd.sysctl]: net.inet.tcp.recvbuf_max=16777216
[freebsd.sysctl]: net.inet.tcp.sendbuf_auto=1
[freebsd.sysctl]: net.inet.tcp.recvbuf_auto=1
[freebsd.sysctl]: net.inet.tcp.sendbuf_inc=16384
[freebsd.sysctl]: net.inet.tcp.recvbuf_inc=524288
[freebsd.sysctl]: net.inet.tcp.sack.enable=1
[freebsd.sysctl]: net.inet.tcp.blackhole=1
[freebsd.sysctl]: net.inet.tcp.msl=2000
[freebsd.sysctl]: net.inet.tcp.delayed_ack=0
[freebsd.sysctl]: net.inet.udp.blackhole=1
[freebsd.sysctl]: net.inet.ip.redirect=0
EAL: Detected 32 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:02:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:02:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:02:00.2 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:02:00.3 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:09:00.0 on NUMA socket 0
EAL:   probe driver: 8086:10fb net_ixgbe
EAL: PCI device 0000:09:00.1 on NUMA socket 0
EAL:   probe driver: 8086:10fb net_ixgbe
EAL: Error - exiting with code: 1
  **Cause: No probed ethernet devices**

2、below is devbind -s list，i have two nic port with dpdk;
[root@localhost dpdk]# ./usertools/dpdk-devbind.py -s
Network devices using DPDK-compatible driver

0000:05:00.0 xxxxxx drv=igb_uio unused=hinic
0000:06:00.0 xxxxxx drv=igb_uio unused=hinic

3、I have tried dpdk testpmd, it seems work normally;

**Comment by dongbin1024** [comment]
i have resolved this issue, my fault, i add my owm nic code to dpdk for support my nic, and complie all dpdk code and get my librte_pmd_xxx.a file
but  i did not link the .a file to f-stack/example/helloworld, so it can't see the nic device

**Comment by garlicup** [comment]
> i have resolved this issue, my fault, i add my owm nic code to dpdk for support my nic, and complie all dpdk code and get my librte_pmd_xxx.a file
> but i did not link the .a file to f-stack/example/helloworld, so it can't see the nic device

how to link the .a file to the f-stack code?
