### ISSUE TITLE
how to avoid the same local port in the case of multiple threads

### ISSUE THREAD

**Issue by zhanghaisen** [F-Stack/f-stack#391]
When nginx works as reverse proxy,  multiple workers are isolated in network stack. So the source port of Tcp client from different worker may be same if the source port is assigned by isolated network stack , though in little probability. But it would cause issue when connecting to same back end server.

**Comment by firesidefox** [comment]
See [ff_check_rss](https://github.com/F-Stack/f-stack/blob/13940a4962c6903fcc8d036d769ad96ad6910c3b/lib/ff_dpdk_if.c#L1629)  !

**Comment by zhanghaisen** [comment]
> See [ff_check_rss](https://github.com/F-Stack/f-stack/blob/13940a4962c6903fcc8d036d769ad96ad6910c3b/lib/ff_dpdk_if.c#L1629) !

Thanks, but I do not find where to call this routine ff_rss_check( ).

**Comment by zhanghaisen** [comment]
Thanks @c5i  very much. I will investigate this routine ff_check_rss.
