### ISSUE TITLE
I can't find f-stack benchmark tools

### ISSUE THREAD

**Issue by theseusyang** [F-Stack/f-stack#40]
I can't find f-stack benchmark tools, does f-stack have a test performance tools?

**Comment by whl739** [comment]
We use `wrk` to test nginx_fstack.

**Comment by theseusyang** [comment]
OK, Thanks . 
If I push small binary files e.g. jpg  into f-stack, Is wrk also suitable for this test scenario?

**Comment by whl739** [comment]
`wrk` is a http benchmark tool, if your app is a http server, it is suitable.
But if a tcp server,  it doesn't fit.

**Comment by theseusyang** [comment]
got it!

**Comment by loonyma** [comment]
Does wrk become a bottleneck to test nginx_fstack? because wrk running with linux kernel, but nginx_fstack
base on DPDK.

**Comment by whl739** [comment]
Then you can use more than one machine.

**Comment by kreuzerkrieg** [comment]
Is there any TCP client/server benchmark tool? I just want to test what performance I can get using f-stack with simple REQ/REP over TCP in user-space
