### ISSUE TITLE
Does F-stack support zero-copy?

### ISSUE THREAD

**Issue by hongjil** [F-Stack/f-stack#407]
I am trying to understand how f-stack works in general.

Based on my understanding, f-stack still does the copy:
1. It receives the data from NIC to the hugepages.
2. When users call `ff_read()` in a loop, it copies data from FreeBSD TCP to the users' specified buffer.

Is my understanding correct? 

Looking forward to your replies.

**Comment by jfb8856606** [comment]
1. It's zero-copy.
2. It's do copy.
