### ISSUE TITLE
endian编译错误是哪里的问题

### ISSUE THREAD

**Issue by laiyongGit** [F-Stack/f-stack#417]
![image](https://user-images.githubusercontent.com/18278341/62358362-233cbf80-b547-11e9-81e1-e6faa07fe201.png)
centos 7 3.10.0 kernel version

**Comment by jfb8856606** [comment]
x86?
Is 32 bits OS, show the `uname -a`, and F-Stack has do any test with 32 bits platform, maybe you need do some modify.
