### ISSUE TITLE
You shall keep the license statement in your ngx_ff_module.c file

### ISSUE THREAD

**Issue by bluenet13** [F-Stack/f-stack#42]
Your socket hook way was copied from our project(https://github.com/opendp/dpdk-nginx/blob/master/src/event/modules/ans_module.c), you shall keep the license statement.

Our license is here.
/*-

BSD LICENSE
Copyright(c) 2015-2017 Ansyun anssupport@163.com. All rights reserved.
All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
* Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in
  the documentation and/or other materials provided with the
  distribution.
* Neither the name of Ansyun <anssupport@163.com> nor the names of its
  contributors may be used to endorse or promote products derived
  from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Author: JiaKai (jiakai1000@gmail.com) and Bluestar (anssupport@163.com)
*/

**Comment by jlijian3** [comment]
copy from https://github.com/OpenFastPath/nginx_ofp, wtf!

**Comment by whl739** [comment]
@bluenet13 
This file was derived from https://github.com/OpenFastPath/nginx_ofp,  i don't know the relationship between your project and nginx_ofp, since nginx_ofp didn't add a license, so i only added a note at the begin of this file, and didn't add license for this file.
```
/*
 * Inspired by nginx_ofp's ngx_ofp_module.c.
 * https://github.com/OpenFastPath/nginx_ofp.
 */
```

If you are sure this moudle is your original, i'll add your license, please tell me about that.

**Comment by bluenet13** [comment]
Yes, nginx_ofp copy it from original ans_module.c.

**Comment by whl739** [comment]
OK, got it. I'll add it later.

**Comment by bluenet13** [comment]
for your redis app shall add the license statement too.

**Comment by whl739** [comment]
I  forgot this, will add it later.
Look at this repo: https://github.com/F-Stack/hijack-syscall, this is pushed by a developer, it's similar, does it need a license too?

**Comment by bluenet13** [comment]
Yes.

**Comment by whl739** [comment]
The hook way of dlsym is so general,  look at our coroutine api, it also has a hook api and it's similar too, but it was implemented by Tencent many years ago.
https://github.com/F-Stack/f-stack/blob/master/app/micro_thread/mt_sys_hook.h.
I don't think they all need your license.
