### ISSUE TITLE
how to configure multi ip on one port ?

### ISSUE THREAD

**Issue by kwjjyn** [F-Stack/f-stack#421]
Hi, f-stack team,

When running f-stack nginx , I see  there is one port named **f-stack-0**  using the tool in `/f-stack/tools/sbin/ifconfig` . And there is one ip address which is configured by `f-stack.conf` in `/path-to-fstack-nginx/conf` . 

What if I want to add more IP on this port ? How to configure it ? It seems the `port_list` in `f-stack.conf` means different nic . And it seems no use to configure it . 

But when I use `/f-stack/tools/sbin/ifconfig` to add ip address on **f-stack-0** , it will only show the new ip added on this dev . It seems new ip will overwrite old ip . 

Is it possible to add different ip on one port ? And the process on this port can use all these ip ?

**Comment by jfb8856606** [comment]
You can use `/f-stack/tools/sbin/ifconfig` to add multi ip, you must use `add` or `alias` parameter, see [ifconfig](https://www.freebsd.org/cgi/man.cgi?ifconfig)

**Comment by kwjjyn** [comment]
Thanks for your reply . However , after I add the new ip on the port , I still can't ping it . the output of ./ifconfig is :
```bash
[...]
f-stack-0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether 0:16:3e:10:32:e7
	inet 192.168.0.123 netmask 0xffffe100
	inet 192.168.0.101 netmask 0xffffffff broadcast 192.168.0.101
```
the broadcast seems to be added automatically.
Do you have any advices?   Thanks a lot.

**Comment by jfb8856606** [comment]
Just like linux, you can't ping it by default if the multi ips are in the same scope.

**Comment by jfb8856606** [comment]
I do a test, and it work correctly.
```
ff_ifconfig f-stack-0 <x.x.x.249> netmask 255.255.255.255 alias
ff_ifconfig f-stack-0 <x.x.x.250> netmask 255.255.255.255 alias
```

The info of `f-stack-0`:
```
#ff_ifconfig 
lo0: flags=8008<LOOPBACK,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        groups: lo 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
f-stack-0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=3<RXCSUM,TXCSUM>
        ether 48:7b:6b:74:fb:59
        inet x.x.x.164 netmask 0xffffe180 broadcast x.x.x.255 
        inet x.x.x.249 netmask 0xffffffff broadcast x.x.x.249 
        inet x.x.x.250 netmask 0xffffffff broadcast x.x.x.250 
        inet6 fe80::4a7b:6bff:fe74:fb59 prefixlen 64 scopeid 0x2 
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
```

All these three IPs can be ping.

**Comment by ratnadeepb** [comment]
@jfb8856606 could you point me to some documentation that allows to build the f-stack tools properly. Because when I run make, it returns the successfully but does not build the executables

**Comment by jfb8856606** [comment]
@ratnadeepb you can see the binary tools in the `tools/sbin` directory.

Or run `make install` after `make`, and then use `ff_*`, such as `ff_ifconfig`,`ff_route`.

**Comment by ygm521** [comment]
@jfb8856606 What is your open source positioning? Why not do a load balancing product, you can proxy tcp, http, https business. Configuration can be delivered by restapi.

**Comment by ratnadeepb** [comment]
> @ratnadeepb you can see the binary tools in the `tools/sbin` directory.
> 
> Or run `make install` after `make`, and then use `ff_*`, such as `ff_ifconfig`,`ff_route`.

My apologies for the late turn around. I got this going. However, I am having to change the IPs manually. For example: `sudo ff_ifconfig f-stack-0 192.168.56.119/24`.
Changes made to `config.ini` or `app/nginx-1.16.1/conf/f-stack.conf` take effect.

**Comment by DKCopy** [comment]
with multiple worker (process) mode, the ff_ifconfig  can't config alias address to all worker.

**Comment by jfb8856606** [comment]
> with multiple worker (process) mode, the ff_ifconfig can't config alias address to all worker.

You can use `-p <proc id>` to config it.

And it will support config vip automatic soon.
