### ISSUE TITLE
NodeJS Compatibility

### ISSUE THREAD

**Issue by incapdns** [F-Stack/f-stack#428]
Is it possible to configure NodeJS to work with F-Stack? I don't understand C, but after checking the code a lot: I suppose (I'm not sure) that just modify the file "tcp_wrap.c" to use in this distribution as described in the API (F-Stack_API_Reference.md), if my alternative is correct or not, I await return. Thanks.

I'm leaving a pastebin of the tcp_wrap file: https://pastebin.com/1VuVd38k
Note: I think (I'm not sure) we only need to modify the following references: "Bind", "Listen", "Connect"

Thanks in advance.

**Comment by jfb8856606** [comment]
You can try modify the event loop of the `libuv` in  the file `tcp_wrap.c`, Similar to the modification of nginx.

**Comment by incapdns** [comment]
Ok, thanks. I will do this and I will return with the news (if there is any error).

**Comment by incapdns** [comment]
It worked correctly, thanks  (hijack)

**Comment by xujuntwt95329** [comment]
Hi @incapdns 
I'm also considering such kind of usage. Did you observe significant performance improvement by using f-stack in nodejs?
