### ISSUE TITLE
SOCK_STREAM [Solved] + Multi Thread (Pthread)

### ISSUE THREAD

**Issue by incapdns** [F-Stack/f-stack#430]
I'm sorry for my bad english.
I'm using ff_syscall.c in libuv, but all sockets are falling under this rule:
__WEAK int socket -> (SOCK_STREAM != type && SOCK_DGRAM != type) -> return socket_raw(domain, type, protocol); "f_syscall.c line 165".
My doubt:
Are sockets with the following flags: "SOCK_STREAM | SOCK_NONBLOCK | SOCK_CLOEXEC" supported?

**Comment by incapdns** [comment]
Second error: "Aborted" on node (i force SOCK_STREAM to test)

**Comment by incapdns** [comment]
gdb:
in kern_kqueue()
in ff_kqueue() at ff_ssycall.c
...

I found the problem: pthread_create.
Any predictions to work with multiple threads?

**Comment by jfb8856606** [comment]
All ff POSIX like API **MUST** be called in the main thread.

**Comment by incapdns** [comment]
Got it :(, is there any possibility of adding this functionality in the future? (Or really there is no way?)
Note: I'm sorry for my bad english.

**Comment by incapdns** [comment]
I can solve (work with multi threads -> without mutex).
For all concerned:
1. Expose the * pcurthread variable (located in ff_compat.c) and include in #include ff_api.h and ff_api.symlist
2. Create a void with the parameter: "struct thread * pthread", with the following value:
pcurthread = & (* pthread)
3. Expose the void ff_set_thread (any name, note: created in step 2) and do the same procedure as step 1.
4. Create a project with the following content:
dpthread.c (note: replace the name: ff_set_thread with the name defined in step 2):
```
#define _GNU_SOURCE
#include <dlfcn.h>
#include <stdio.h>
#include <pthread.h>
#include "ff_api.h"

int (* original_pthread_create) (pthread_t * thread, const pthread_attr_t * attr, void * (* start_routine) (void *), void * arg) = NULL;

void load_original_pthread_create () {
    original_pthread_create = dlsym (RTLD_NEXT, "pthread_create");
}
int pthread_create (pthread_t * thread, const pthread_attr_t * attr, void * (* start_routine) (void *), void * arg) {
    if (original_pthread_create == NULL) {
        load_original_pthread_create ();
    }
    void start_thread (struct thread * pthread) {
       ff_set_thread (pthread);
       start_routine (arg);
    };
    return original_pthread_create (thread, attr, start_thread, pcurthread);
}
```

5. Compile the dpthread.c file with ending ".a" (using makefile or your preferred).
6. Add this file to your Makefile (f-stack project using pthread_create). -L/data/dpthread-dir -ldpthread (or the chosen name)

Note: If needed you can comment the line: "//rte_timer_manage" in ff_dpdk_if.c (Somecases is required to work)

**Comment by hongjil** [comment]
@incapdns How about the performance benchmark between multi-threading and multi-process in f-stack?

**Comment by cwlgit687** [comment]
> 我可以解决（使用多线程->不使用互斥锁）。
> 对于所有相关人员：
> 
> 1. 公开* pcurthread变量（位于ff_compat.c中）并包含在#include ff_api.h和ff_api.symlist中
> 2. 使用参数“ struct thread * pthread”创建一个具有以下值的
>    void ：pcurthread =＆（* pthread）
> 3. 暴露空的ff_set_thread（任何名称，请注意：在步骤2中创建），并执行与步骤1相同的过程。
> 4. 创建一个具有以下内容的项目：
>    dpthread.c（注意：将名称：ff_set_thread替换为步骤2中定义的名称）：
> 
> ```
> #define _GNU_SOURCE
> #include <dlfcn.h>
> #include <stdio.h>
> #include <pthread.h>
> #include "ff_api.h"
> 
> int (* original_pthread_create) (pthread_t * thread, const pthread_attr_t * attr, void * (* start_routine) (void *), void * arg) = NULL;
> 
> void load_original_pthread_create () {
>     original_pthread_create = dlsym (RTLD_NEXT, "pthread_create");
> }
> int pthread_create (pthread_t * thread, const pthread_attr_t * attr, void * (* start_routine) (void *), void * arg) {
>     if (original_pthread_create == NULL) {
>         load_original_pthread_create ();
>     }
>     void start_thread (struct thread * pthread) {
>        ff_set_thread (pthread);
>        start_routine (arg);
>     };
>     return original_pthread_create (thread, attr, start_thread, pcurthread);
> }
> ```
> 
> 1. 编译以“ .a”结尾的dpthread.c文件（使用makefile或您喜欢的文件）。
> 2. 将此文件添加到您的Makefile（使用pthread_create的f-stack项目）中。-L / data / dpthread-dir -ldpthread（或所选名称）
> 
> 注意：如果需要，您可以注释以下行：ff_dpdk_if.c中的“ // rte_timer_manage”（某些情况下需要工作）



> I can solve (work with multi threads -> without mutex).
> For all concerned:
> 
> 1. Expose the * pcurthread variable (located in ff_compat.c) and include in #include ff_api.h and ff_api.symlist
> 2. Create a void with the parameter: "struct thread * pthread", with the following value:
>    pcurthread = & (* pthread)
> 3. Expose the void ff_set_thread (any name, note: created in step 2) and do the same procedure as step 1.
> 4. Create a project with the following content:
>    dpthread.c (note: replace the name: ff_set_thread with the name defined in step 2):
> 
> ```
> #define _GNU_SOURCE
> #include <dlfcn.h>
> #include <stdio.h>
> #include <pthread.h>
> #include "ff_api.h"
> 
> int (* original_pthread_create) (pthread_t * thread, const pthread_attr_t * attr, void * (* start_routine) (void *), void * arg) = NULL;
> 
> void load_original_pthread_create () {
>     original_pthread_create = dlsym (RTLD_NEXT, "pthread_create");
> }
> int pthread_create (pthread_t * thread, const pthread_attr_t * attr, void * (* start_routine) (void *), void * arg) {
>     if (original_pthread_create == NULL) {
>         load_original_pthread_create ();
>     }
>     void start_thread (struct thread * pthread) {
>        ff_set_thread (pthread);
>        start_routine (arg);
>     };
>     return original_pthread_create (thread, attr, start_thread, pcurthread);
> }
> ```
> 
> 1. Compile the dpthread.c file with ending ".a" (using makefile or your preferred).
> 2. Add this file to your Makefile (f-stack project using pthread_create). -L/data/dpthread-dir -ldpthread (or the chosen name)
> 
> Note: If needed you can comment the line: "//rte_timer_manage" in ff_dpdk_if.c (Somecases is required to work)



> 我可以解决（使用多线程->不使用互斥锁）。
> 对于所有相关人员：
> 
> 1. 公开* pcurthread变量（位于ff_compat.c中）并包含在#include ff_api.h和ff_api.symlist中
> 2. 使用参数“ struct thread * pthread”创建一个具有以下值的
>    void ：pcurthread =＆（* pthread）
> 3. 暴露空的ff_set_thread（任何名称，请注意：在步骤2中创建），并执行与步骤1相同的过程。
> 4. 创建一个具有以下内容的项目：
>    dpthread.c（注意：将名称：ff_set_thread替换为步骤2中定义的名称）：
> 
> ```
> #define _GNU_SOURCE
> #include <dlfcn.h>
> #include <stdio.h>
> #include <pthread.h>
> #include "ff_api.h"
> 
> int (* original_pthread_create) (pthread_t * thread, const pthread_attr_t * attr, void * (* start_routine) (void *), void * arg) = NULL;
> 
> void load_original_pthread_create () {
>     original_pthread_create = dlsym (RTLD_NEXT, "pthread_create");
> }
> int pthread_create (pthread_t * thread, const pthread_attr_t * attr, void * (* start_routine) (void *), void * arg) {
>     if (original_pthread_create == NULL) {
>         load_original_pthread_create ();
>     }
>     void start_thread (struct thread * pthread) {
>        ff_set_thread (pthread);
>        start_routine (arg);
>     };
>     return original_pthread_create (thread, attr, start_thread, pcurthread);
> }
> ```
> 
> 1. 编译以“ .a”结尾的dpthread.c文件（使用makefile或您喜欢的文件）。
> 2. 将此文件添加到您的Makefile（使用pthread_create的f-stack项目）中。-L / data / dpthread-dir -ldpthread（或所选名称）
> 
> 注意：如果需要，您可以注释以下行：ff_dpdk_if.c中的“ // rte_timer_manage”（某些情况下需要工作）

May I create several sub threads in this multithread. Can I use FF API

**Comment by peifengsi** [comment]
Does f-stack have a plan to support multi-threading officially?

**Comment by wesleyEPS5GC** [comment]
> I can solve (work with multi threads -> without mutex). For all concerned:
> 
> 1. Expose the * pcurthread variable (located in ff_compat.c) and include in #include ff_api.h and ff_api.symlist
> 2. Create a void with the parameter: "struct thread * pthread", with the following value:
>    pcurthread = & (* pthread)
> 3. Expose the void ff_set_thread (any name, note: created in step 2) and do the same procedure as step 1.
> 4. Create a project with the following content:
>    dpthread.c (note: replace the name: ff_set_thread with the name defined in step 2):
> 
> ```
> #define _GNU_SOURCE
> #include <dlfcn.h>
> #include <stdio.h>
> #include <pthread.h>
> #include "ff_api.h"
> 
> int (* original_pthread_create) (pthread_t * thread, const pthread_attr_t * attr, void * (* start_routine) (void *), void * arg) = NULL;
> 
> void load_original_pthread_create () {
>     original_pthread_create = dlsym (RTLD_NEXT, "pthread_create");
> }
> int pthread_create (pthread_t * thread, const pthread_attr_t * attr, void * (* start_routine) (void *), void * arg) {
>     if (original_pthread_create == NULL) {
>         load_original_pthread_create ();
>     }
>     void start_thread (struct thread * pthread) {
>        ff_set_thread (pthread);
>        start_routine (arg);
>     };
>     return original_pthread_create (thread, attr, start_thread, pcurthread);
> }
> ```
> 
> 5. Compile the dpthread.c file with ending ".a" (using makefile or your preferred).
> 6. Add this file to your Makefile (f-stack project using pthread_create). -L/data/dpthread-dir -ldpthread (or the chosen name)
> 
> Note: If needed you can comment the line: "//rte_timer_manage" in ff_dpdk_if.c (Somecases is required to work)

Can you post all the code? Ask for help

**Comment by Chithesus** [comment]
what he did is replace the pthread_create function to self-defined pthread_create,  and in the self-defined pthread_create, pcurthread was set; but i dont think it can work;

**Comment by Chithesus** [comment]
@jfb8856606     i tried his solution, but crushed;  can u give a direction about how to use it as multithread program; it is really sad such good fstack cann't be use as multithread api;
