### ISSUE TITLE
如何使用 nginx_fstack 向本机非 fstack server 转发报文

### ISSUE THREAD

**Issue by LiangqinRen** [F-Stack/f-stack#431]
# 背景

我有一台具有多个光、电网卡的服务器，其上运行了一个可以进行密码运算服务的 Server，鉴于其与客户端通信使用 openssl 加密，所以使用了 Nginx 的 stream、openssl 进行代理转发，为了提高整体服务速度，我想使用 nginx_fstack 代替原有 Nginx。  

## 1.描述

目前我不知道如何实现我的需求，我将服务器某一个网卡转交给 fstack 管理，并设置其地址为 10.10.10.10，除此之外服务器还有一个远程访问的网卡地址为 192.168.0.199。目前我使用 stream 模块向 192.168.0.199 或 127.0.0.1 进行了如下尝试，均无法成功转发，报错会在下面说明：  

1. 开启 KNI 选项
2. 参照 #202 开启 proxy_kernel_network_stack 选项。但是文档中要求前提 NGX_HAVE_FSTACK 存在，但是目前其并不存在且我没有找到如何设置这个参数。同时其说明的语法（如下）似乎与 /usr/local/nginx_fstack/conf/f-stack.conf 中其他配置项语法不同，我直接使用 `proxy_kernel_network_stack on;` 的语法 nginx 无法运行，我参照其余选项使用 `proxy_kernel_network_stack=on` 可以运行 nginx，但是没有效果。我不清楚 `Context: http, stream, mail, server` 具体语法是什么样子
3. 设置第二个 fstack 网卡，并尝试是否可以将报文转向 fstack demo helloworld，由于无法同时运行两个基于 fstack 的应用，所以也没有成功

```shell
Syntax: proxy_kernel_network_stack on | off;
Default: kernel_network_stack off;
Context: http, stream, mail, server
```

目前报错都是 `2019/08/28 08:26:11 [error] 17193#0: *14 upstream timed out (110: Connection timed out) while connecting to upst    ream, client: 10.10.20.11, server: 0.0.0.0:9999, upstream: "192.168.0.199:10000", bytes from/to client:0/0, byte    s from/to upstream:0/0` 这种超时。同时还会出现大量 `2019/08/28 08:31:28 [alert] 8516#0: close() channel failed (9: Bad file descriptor)` 和 `2019/08/28 08:31:29 [alert] 8516#0: recvmsg() truncated data` 、 `2019/08/28 08:31:29 [alert] 8516#0: recvmsg() returned invalid ancillary data level 678007725 or type 0` 等。

## 2.问题

我想知道如何使用 nginx_fstack 完成我的目标，即使用其向本机非 fstack server 转发请求。如果可能，相对于普通 nginx 是否在收包时有性能提升。如果可能，我具体该如何配置，例如使用 KNI 或者是 使用 `proxy_kernel_network_stack` 选项，转发地址为 127.0.0.1 还是普通电口地址 192.168.0.199，该选项设置的具体语法是什么尤其是 `Context: http, stream, mail, server` 作用域部分。

**Comment by jfb8856606** [comment]
You should study how to use and config Nginx.

`proxy_kernel_network_stack on` should set on `nginx.conf`, not `f-stack.conf`.

**Comment by suyuexin** [comment]
600171370
我创建了一个qq交流群，不知道有没有人有兴趣进来交流呢
