### ISSUE TITLE
Nginx transparent problem with fstack

### ISSUE THREAD

**Issue by rolfliu** [F-Stack/f-stack#434]
Hi,
I want to use nginx transparent proxy with f-stack, but it doesn't work.
When I start nginx with transparent config(NGX_HAVE_TRANSPARENT_PROXY is defined) , I found a setsockopt error in the error.log,   as follows:
 "[alert] 39022#0: *1 setsockopt(IP_BINDANY) failed (22: Invalid argument) while connecting to upstream, client: 192.168.1.246, server: 0.0.0.0:10022, upstream: "192.168.0.87:23", bytes from/to client:0/0, bytes from/to upstream:0/0"

What's the problem?

Thank you

**Comment by jfb8856606** [comment]
Is Nginx-1.11.10 or Nginx-1.16.0?
And you can show the config info of nginx and f-stack

**Comment by rolfliu** [comment]
I make a new test environment, the result is the same.
I use Nginx-1.16.0.
####The test network topology is as follows:
![fstack nginx test](https://user-images.githubusercontent.com/54878317/65210094-9fc23800-dacc-11e9-9c76-7ffa6d98ef7f.png)


####Attach the f-stack.conf/nginx.conf/error.log.

[f-stack.conf.txt](https://github.com/F-Stack/f-stack/files/3629134/f-stack.conf.txt)
[nginx.conf.txt](https://github.com/F-Stack/f-stack/files/3629135/nginx.conf.txt)

####error.log info:
2019/09/19 10:36:43 [info] 15100#0: *1 client 192.168.0.246:23726 connected to 0.0.0.0:10022
2019/09/19 10:36:43 [alert] 15100#0: *1 setsockopt(IP_BINDANY) failed (22: Invalid argument) while connecting to upstream, client: 192.168.0.246, server: 0.0.0.0:10022, upstream: "192.168.1.87:22", bytes from/to client:0/0, bytes from/to upstream:0/0
2019/09/19 10:36:43 [alert] 15100#0: *1 setsockopt(IP_BINDANY) failed (22: Invalid argument) while connecting to upstream, client: 192.168.0.246, server: 0.0.0.0:10022, upstream: "192.168.1.87:22", bytes from/to client:0/0, bytes from/to upstream:0/0
2019/09/19 10:36:43 [alert] 15100#0: *1 setsockopt(IP_BINDANY) failed (22: Invalid argument) while connecting to upstream, client: 192.168.0.246, server: 0.0.0.0:10022, upstream: "192.168.1.87:22", bytes from/to client:0/0, bytes from/to upstream:0/0


Best regards!

**Comment by GuoM65** [comment]
看了一下代码，貌似是这个地方返回的错误；
int
ff_setsockopt(int s, int level, int optname, const void *optval,
    socklen_t optlen)
{
    int rc;

    if (level == LINUX_SOL_SOCKET)
        level = SOL_SOCKET;

    optname = linux2freebsd_opt(level, optname);
    if (optname < 0) {
        rc = EINVAL;
        goto kern_fail;
    }

    if ((rc = kern_setsockopt(curthread, s, level, optname,
            __DECONST(void *, optval), UIO_USERSPACE, optlen)))
        goto kern_fail;

    return (rc);

kern_fail:
    ff_os_errno(rc);
    return (-1);
}
如果是的话，看样子是不支持IP_BINDANY这个类型

**Comment by rolfliu** [comment]
透明代理已支持，可以setsockopt IP_BINDANY，新的代码已合并
