### ISSUE TITLE
你好，我想用f-stack+redis来测试性能，但是现在客户端压测显示连接失败如何解决？

### ISSUE THREAD

**Issue by ericgong1993** [F-Stack/f-stack#444]
服务端那里启动redis-server完全正常，但是客户端用redis-benchmark来压测服务端，显示Could not connect to Redis，ERROR: failed to fetch CONFIG from.....，请问我是遗漏了什么吗

**Comment by ericgong1993** [comment]
@jfb8856606

**Comment by ericgong1993** [comment]
难道服务端和客户端都要使用同一版本redis3？

**Comment by jfb8856606** [comment]
F-Stack don't support redis-benchmark, you need use normal client to do test.

**Comment by suyuexin** [comment]
600171370
我创建了一个qq交流群，不知道有没有人有兴趣进来交流呢

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/1374800/97186441-40a91980-17dc-11eb-94d3-a879310ac24f.png)
请问启动完redis，怎么连接上。redis-cli也连不上啊！

**Comment by suyuexin** [comment]
去微信搜索f-stack，在公众号里能找到交流群------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;millerliu&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月26日(星期一) 晚上10:41
收件人:&nbsp;&quot;F-Stack/f-stack&quot;<f-stack@noreply.github.com&gt;;
抄送:&nbsp;&quot;suyuexin&quot;<1076020341@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [F-Stack/f-stack] 你好，我想用f-stack+redis来测试性能，但是现在客户端压测显示连接失败如何解决？ (#444)

**Comment by cjavaphp** [comment]
我看issue已经关闭，请问这个问题最后怎么解决的

**Comment by jfb8856606** [comment]
@cjavaphp  redis这里没有问题，注意一些事项即可
1. 需要从其他机器访问，不要从本机访问
2. 放开相关防火墙
3. 不支持f-stack版本的redis-benchmark，只能使用源生版本的redis-cli和redis-benchmark.
