### ISSUE TITLE
Does f-stack support SO_REUSEPORT option?

### ISSUE THREAD

**Issue by hubblezzhu** [F-Stack/f-stack#447]
Hello, we now have a case that needs using SO_REUSEPORT option like kernel TCP/IP stack to do some load balancing. Does f-stack support now?

**Comment by jfb8856606** [comment]
F-Stack is shared-nothing, `SO_REUSEPORT ` is useless.

**Comment by xiaofan8421** [comment]
What does it mean about useless SO_REUSEPORT? Can't the multi-process receive packets by using SO_REUSEPORT for high performance?

**Comment by xiaofan8421** [comment]
> F-Stack is shared-nothing, `SO_REUSEPORT ` is useless.
What does it mean about useless SO_REUSEPORT? Can't the multi-process receive packets by using SO_REUSEPORT for high performance
