### ISSUE TITLE
enable sctp in fstack

### ISSUE THREAD

**Issue by chanwai1219** [F-Stack/f-stack#45]
hi, all, I am doing some work to enable sctp. But sctp create some kproc working thread.
Is there any suggestion about how to port this part?
Thanks in advance!

**Comment by whl739** [comment]
At the beginning of F-Stack, i wanted to implement kernel thread with coroutine, but i found that kernel thread is not necessary for tcp/ip stack, so i removed all kernel threads instead of implementing it.
I don't know much about SCTP, could you tell me that if kernel thread is necessary for SCTP?
If it's necessary, maybe coroutine is a good way to simulate kernel thread.
And a pull/request is welcomed.

**Comment by chanwai1219** [comment]
As the sctp worker thread will be blocked until other thread wake it up, we can do a workaround that call sctp_iterator_worker directly in sctp_wakeup_iterator instead of wakeup.

**Comment by fengyongning** [comment]
Hello, whl739
     At this stage in f-stack, what protocols are supported by f-stack,  whether or not including the sctp and http2? Thinks.

**Comment by whl739** [comment]
F-Stack does not support sctp, you can contact with @chanwai1219.
http2 is a 7 layer protocol, it is implemeted by nginx.

**Comment by fengyongning** [comment]
Hi, chanwai1219 
Excuse me,  Finally, did you implement the SCTP protocol based on F-Stack?

**Comment by chanwai1219** [comment]
> Hi, chanwai1219
> Excuse me, Finally, did you implement the SCTP protocol based on F-Stack?

Yes, we use SCTP on f-stack almost 2 years. Feel free to open an issue, I will help.

**Comment by fengyongning** [comment]
Thinks chanwai1219, How is your implenment? based on kni, or others? if possible, contact me with email fengyongning@yeah.net, thinks.

**Comment by chanwai1219** [comment]
> Thinks chanwai1219, How is your implenment? based on kni, or others? if possible, contact me with email [fengyongning@yeah.net](mailto:fengyongning@yeah.net), thinks.

There are full sctp stack in freebsd kernel, just compile these files to f-stack.

**Comment by fengyongning** [comment]
> 
> 
> > Thinks chanwai1219, How is your implenment? based on kni, or others? if possible, contact me with email [fengyongning@yeah.net](mailto:fengyongning@yeah.net), thinks.
> 
> There are full sctp stack in freebsd kernel, just compile these files to f-stack.

Hi, chanwai1219
    I have complete sctp function throught kni, but failed to modify fstack lib and freebsd kernel. I add all freebsd/netinet/sctp_*.c except sctp_auth.c in lib/Makefile, such as :
ifdef FF_SCTP
NETINET_SRCS+=		\
	sctp_asconf.c	\
	sctp_bsd_addr.c	\
	sctp_cc_functions.c	\
	sctp_crc32.c	\
	sctp_indata.c	\
	sctp_input.c	\
	sctp_output.c	\
	sctp_pcb.c		\
	sctp_peeloff.c	\
	sctp_ss_functions.c	\
	sctp_syscalls.c	\
	sctp_sysctl.c	\
	sctp_timer.c	\
	sctp_usrreq.c	\
	sctputil.c
endif
It's ok to build libfstack.a, but build example app with libfstack.a, there ars erros such as:
cc -O -gdwarf-2  -I../lib -o "helloworld" main.c -L/home/ours/fengyn/f-stack/20190521/f-stack-master/lib -Wl,--whole-archive,-lfstack,--no-whole-archive -L../dpdk/x86_64-native-linuxapp-gcc/lib -Wl,--whole-archive,-ldpdk,--no-whole-archive -Wl,--no-whole-archive -lrt -lm -ldl -lcrypto -pthread -lnuma -lsctp
/home/ours/fengyn/f-stack/20190521/f-stack-master/lib/libfstack.a(libfstack.ro)：in function ‘sctp_startup_iterator’：
uma_core.c:(.text+0x98e07)：‘kproc_create’ undefined references
So, I want to know how you modified it. where is the main point of change?  
Think you very much!

**Comment by chanwai1219** [comment]
overwrite the kproc_create with 
`
int
kproc_create(void (*func)(void *), void *arg,
    struct proc **newpp, int flags, int pages, const char *fmt, ...)
{
    return 0;
}
`
when this proc needs to be invoked, call the worker directly
`
void
sctp_wakeup_iterator(void)
{
#if 0
	wakeup(&sctp_it_ctl.iterator_running);
#else
    sctp_iterator_worker();
#endif
}
`

**Comment by fengyongning** [comment]
Thanks chanwai1219, I find if add all freebsd sctp*.c to build, there are some problems about auth and syscall etc. happend. So I want to know  which sctp*.c should be build and others not, in orde to avoid that introduction of other problems.

**Comment by jackie-lee** [comment]
Hi, @chanwai1219
可以创建一个移植了SCTP的github仓库吗？这样也方便后面的人参考

**Comment by markman76** [comment]
Although this issue is closed, can I refer how to compile SCTP related files of FreeBSD to F-Stack?
(Documents, Web site or github)

**Comment by wangchong2023** [comment]
> > Hi, chanwai1219
> > Excuse me, Finally, did you implement the SCTP protocol based on F-Stack?
> 
> Yes, we use SCTP on f-stack almost 2 years. Feel free to open an issue, I will help.

@chanwai1219 
Do you have any plans to enable SCTP and submit PR code? Thanks very much.
