### ISSUE TITLE
compare with mtcp and TAS?

### ISSUE THREAD

**Issue by ryuxin** [F-Stack/f-stack#450]
What is the difference between f-stack and modern TCP stack, such mtcp (https://www.usenix.org/system/files/conference/nsdi14/nsdi14-paper-jeong.pdf) and TAS (https://people.mpi-sws.org/~antoinek/documents/19eurosys_tas.pdf)?

Does f-stack has better design?

Is there any performance comparison with mtcp and TAS?

**Comment by jfb8856606** [comment]
F-Stack has more complete TCP/IP stack, can compatible more abnormal network requests without problems，and  F-Stack support more system tools like `ifconfig`,`route` etc.

The performance of F-Stack slightly lower than simple TCP/IP stack， but on the same order of magnitude.

[More information](https://www.zhihu.com/question/59779624/answer/172519441)
