### ISSUE TITLE
我在centos7 安装步骤编译f-stack-1.12.tar.gz，lib目录编译失败，麻烦问下有没有遇到相同问题的？

### ISSUE THREAD

**Issue by wyao51** [F-Stack/f-stack#451]
[root@localhost lib]# uname -a
Linux localhost.localdomain 3.10.0-957.10.1.el7.x86_64 #1 SMP Wed Oct 9 06:07:10 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost lib]# make
cc -c -O2 -frename-registers  -funswitch-loops -fweb -Wall -Werror -include /data/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_config.h -march=native -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2 -I/data/f-stack/dpdk/x86_64-native-linuxapp-gcc/include  -I. -Werror -Wno-unused-variable  ff_host_interface.c
ff_host_interface.c:42:26: fatal error: openssl/rand.h: No such file or directory
 #include <openssl/rand.h>
                          ^
compilation terminated.
make: *** [ff_host_interface.o] Error 1

**Comment by wyao51** [comment]
安装yum install openssl-devel 即可

**Comment by ericgong1993** [comment]
yum install openssl-devel

**Comment by suyuexin** [comment]
600171370
我创建了一个qq交流群，不知道有没有人有兴趣进来交流呢
