### ISSUE TITLE
f-stack failed with more than 64 core

### ISSUE THREAD

**Issue by beard-627** [F-Stack/f-stack#452]
hello,
    When I ran helloworld with 80 core, I found the 80 processes was assigned to 64 cores, so I analyzed the cause of the problem, modified some code and push a solution. Can you check the request and tell me if changes can be merge into the code? thanks

**Comment by jfb8856606** [comment]
I don't have the dev more 60 cores, and i will test the pr with less 64 cores later, and merge it

**Comment by jfb8856606** [comment]
done
