### ISSUE TITLE
如何让其他程序测试F-stack的接口函数?

### ISSUE THREAD

**Issue by suyuexin** [F-Stack/f-stack#453]
想在Ubuntu下给F-stack进行兼容性测试，目前环境已搭好，但是不知道怎么让测试程序在跑有关网络的测试时调用F-stack的接口函数？是有什么对外使用的库文件之类的吗？

**Comment by jfb8856606** [comment]
See [helloworld](https://github.com/F-Stack/f-stack/blob/dev/example/main.c)
