### ISSUE TITLE
Is there have f-stack for online business? What is the f-stack advantages? Can proxy tcp business? Can I configure routing? Have a port bond?

### ISSUE THREAD

**Issue by ygm521** [F-Stack/f-stack#454]

**Comment by jfb8856606** [comment]
F-Stack supported many online businesses， such as [HttpDNS](https://cloud.tencent.com/product/hd)

Nginx work well except transparent proxy.

Dev branch has supported bonding, but if it can work well dependent on the DPDK bonding dirver. For example, bonding mode 4 driver can't work correctly with multi-processes.

**Comment by ghpass** [comment]
> F-Stack supported many online businesses， such as [HttpDNS](https://cloud.tencent.com/product/hd)
> 
> Nginx work well except transparent proxy.
> 
> Dev branch has supported bonding, but if it can work well dependent on the DPDK bonding dirver. For example, bonding mode 4 driver can't work correctly with multi-processes.
Dear sir,
How to set the mode 4 bonding? Pls give an example. Thanks!
I'm using version 1.21.
