### ISSUE TITLE
现在有python接口的f-stack吗

### ISSUE THREAD

**Issue by cwlgit687** [F-Stack/f-stack#458]
pyfstack那个编译总有问题

**Comment by ygm521** [comment]
敢用吗？

**Comment by jfb8856606** [comment]
Show your compile environment and error info.

Very old version of f-stack is used in the repo of pyfstack.

**Comment by cwlgit687** [comment]
![image](https://user-images.githubusercontent.com/56579268/69114254-dcf07980-0abf-11ea-9373-e9c54a7439f5.png)
这些错误已经改了或者注释了
![image](https://user-images.githubusercontent.com/56579268/69114373-204ae800-0ac0-11ea-9f89-01cd9838fc31.png)
现在是这个问题
pyfstack里用的是f-stack-1.11

**Comment by jfb8856606** [comment]
You should try compile pyfstack use CentOS 7.0, not CentOS 7.6.

**Comment by ygm521** [comment]
@jfb8856606  Why not directly released v1.20？

**Comment by suyuexin** [comment]
600171370
我创建了一个qq交流群，不知道有没有人有兴趣进来交流呢
