### ISSUE TITLE
Rx queue configuration

### ISSUE THREAD

**Issue by pkking** [F-Stack/f-stack#46]
Hi all,
Im using f-stack in an 10c16G kvm box.
When i started Nginx it seems dpdk's NIC driver in a vm only init with ONE rx/tx queue(tried both e1000 and virtio model in qemu) and the start scripts complains:
```bash
create mbuf pool on socket 0
create ring:arp_ring_0_0 success, 2047 ring entries are now free!
create ring:arp_ring_1_0 success, 2047 ring entries are now free!
create ring:arp_ring_2_0 success, 2047 ring entries are now free!
create ring:arp_ring_3_0 success, 2047 ring entries are now free!
create ring:arp_ring_4_0 success, 2047 ring entries are now free!
create ring:arp_ring_5_0 success, 2047 ring entries are now free!
create ring:arp_ring_6_0 success, 2047 ring entries are now free!
create ring:arp_ring_7_0 success, 2047 ring entries are now free!
EAL: Error - exiting with code: 1
  Cause: num_procs[8] bigger than max_rx_queues[1]
```
Be a totally newbie and not fimilar with the NIC drivers configurations in dpdk, my question is:
Is it possible to take advantage of multi-processes in a vm for f-stack, or what i missed?

**Comment by whl739** [comment]
F-Stack couldn't run with multi processes with only one queue.
You should set `lcore_mask=1`.

**Comment by pkking** [comment]
@whl739 Your setting works for me, however, be more straightforwardly, it's more valuable for me to know can i set up a multi rx/tx queue NIC with DPDK on a vm?

**Comment by whl739** [comment]
Try `ethtool -l eth0`, see the `Current hardware settings` section and key `Combined`.
And http://www.linux-kvm.org/page/Multiqueue may be helpful.

**Comment by pkking** [comment]
Big thank you @whl739 :)
