### ISSUE TITLE
kni 

### ISSUE THREAD

**Issue by jeckypei** [F-Stack/f-stack#465]
does the ff kni support the following rule to filter packet ?
#clone|forward l2proto  l3proto src-ip dst-ip l4-sport l4-dport
clone    0x0806   *     *    *     *           *
forward 0x86dd   *     *     *     *          *
forward 0x0800  17    *     *    *          2000

**Comment by jeckypei** [comment]
oh, read more code , has such feature, arp and ND is hard coded .

**Comment by jfb8856606** [comment]
Yes，if you want to process more protocols or packets，you need to modify the code.
