### ISSUE TITLE
The meaning of core in performance picture.

### ISSUE THREAD

**Issue by yuyang0** [F-Stack/f-stack#47]
In order to do benchmark, I want to know the meaning of "core", physical core or hyperthread? thx

**Comment by whl739** [comment]
physical core

**Comment by yuyang0** [comment]
so your test machine has two  E5-2670 v3 cpu?

**Comment by whl739** [comment]
yes

**Comment by yuyang0** [comment]
thx, Could you pls add these information to readme?

**Comment by whl739** [comment]
OK.
