### ISSUE TITLE
外包招聘

### ISSUE THREAD

**Issue by threecoins** [F-Stack/f-stack#470]
工作内容：在f-stack框架的FreeBSD协议层中按甲方设计实现一个传输层协议以及对软路由作部分修改
要求：需熟悉linux内核协议层实现和dpdk接口调用
联系邮箱（附上个人简历）：baixiyue6@163.com
薪酬面议

**Comment by ygm521** [comment]
咋这么优秀呢，f-stack有公司线上用，可能除了腾讯？
