### ISSUE TITLE
ff_kqueue return zero

### ISSUE THREAD

**Issue by soroshsabz** [F-Stack/f-stack#471]
ITNOA

I try to run f-stack example 

after I run helloworld, the process stop with assertion like below

`main.c:114: main: Assertion (kq= ff_kqueue())> 0 failed`

what is my problem? or where we found some meaningful information to debugging it?

thanks

**Comment by soroshsabz** [comment]
how to validate `curthread` is valid state?

**Comment by jfb8856606** [comment]
All ff api must called in main thread.

**Comment by soroshsabz** [comment]
thanks
