### ISSUE TITLE
Port new freebsd stack stable release 12.x

### ISSUE THREAD

**Issue by soroshsabz** [F-Stack/f-stack#472]
ITNOA

I think it is good to port to new FreeBSD release 12.1 for minor improvement in `tcp/ip` stack

**Comment by suyuexin** [comment]
600171370
我创建了一个qq交流群，不知道有没有人有兴趣进来交流呢

**Comment by soroshsabz** [comment]
@suyuexin ?

**Comment by jfb8856606** [comment]
Currently we won't to port FreeBD 12.x, unless there are more changes to the `tcp/ip` stack, such as `BBR`.
And we will follow the improvements in new versions, such as  critical vulnerability or others, but  F-Stack not follow the modified of `IPFW` and `RACK` currently.

**Comment by Retia-Adolf** [comment]
Actually, they had already added `BBR` several months ago: https://reviews.freebsd.org/D21582

**Comment by jfb8856606** [comment]
Yes, i has seen this differential before, but we still need to wait for it to release, then we will update F-Stack in branch `dev`.

**Comment by jeff-lv-github** [comment]
> Currently we won't to port FreeBD 12.x, unless there are more changes to the `tcp/ip` stack, such as `BBR`. And we will follow the improvements in new versions, such as critical vulnerability or others, but F-Stack not follow the modified of `IPFW` and `RACK` currently.

I am trying to porting the f-stack to arm64 and met some problems in ff_freebsd_init().
Could you share the experience of poring freebsd to x86?

**Comment by jfb8856606** [comment]
F-Stack has support FreeBSD-13.0, and RACK/BBR, close this issue.
