### ISSUE TITLE
Performance bottleneck

### ISSUE THREAD

**Issue by pkking** [F-Stack/f-stack#48]
Dear team,
I ran f-stack and nginx on a vm(non NUMA) which has 8c10G and a 10G NIC.
With ONE queue and ONE lcore `wrk` got
```bash
# ./wrk -c 200 -t 6 -d 30s http://192.1.1.3:8080
//sth nosiy
Requests/sec:  53773.02
Transfer/sec:     43.64MB
```
When i start nginx and f-stack with 2 cores and 2 queues, the result became
```bash
# ./wrk -c 200 -t 6 -d 30s http://192.1.1.3:8080
//sth nosiy
Requests/sec:  96035.38
Transfer/sec:     77.94MB
```
But more than 2 cores and 2 queues still got about 10k RPS, is there any way to figure out the bottleneck?

**Comment by whl739** [comment]
Try `wrk -c 1024 -t 8`?

**Comment by pkking** [comment]
```bash
# ./wrk -c 1024 -t 8 -d 30s http://192.1.1.3:8080
Running 30s test @ http://192.1.1.3:8080
  8 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     9.56ms    4.88ms  83.55ms   77.21%
    Req/Sec    11.89k     4.10k   43.16k    72.25%
  2831833 requests in 30.09s, 2.24GB read
Requests/sec:  94120.63
Transfer/sec:     76.38MB
```
Tried connections from 200 to 2000, got the same results :(

**Comment by whl739** [comment]
How many f-stack processes did you start with the above result?

**Comment by pkking** [comment]
I set `lcore_mask=3` and nginx worker with `1`

**Comment by whl739** [comment]
> But more than 2 cores and 2 queues still got about 10k RPS, is there any way to figure out the bottleneck?

Do you mean that when start with more than 2 cores, the result is same with 2 cores?
What's the result if setting lcore_mask up to f and ff?

**Comment by pkking** [comment]
Yep, as mentioned above, setting `lcore_mask=ff`, still got about 10k RPS
Here's the start log:
[start.txt](https://github.com/F-Stack/f-stack/files/1182310/start.txt)
and try `wrk` again, got
```bash
# ./wrk  -c 1024 -t 8 -d 30s --timeout 3s http://192.1.1.3:8080
Running 30s test @ http://192.1.1.3:8080
  8 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    12.69ms   27.52ms 831.18ms   90.98%
    Req/Sec    13.24k     6.57k   50.48k    73.60%
  3142765 requests in 30.10s, 2.49GB read
Requests/sec: 104421.08
Transfer/sec:     84.74MB
```

**Comment by whl739** [comment]
Is the nic of  your client  1Gb or 10Gb?

**Comment by pkking** [comment]
Sry for the misspelling, the NIC is 10Gb
```
Checking link statusdone
Port 0 Link Up - speed 10000 Mbps - full-duplex
```

**Comment by pkking** [comment]
Sry, the client NIC info is:
```
# ethtool  ens12f0
Settings for ens12f0:
	Supported ports: [ FIBRE ]
	Supported link modes:   1000baseT/Full 
	                        10000baseT/Full 
	Supported pause frame use: No
	Supports auto-negotiation: Yes
	Advertised link modes:  1000baseT/Full 
	                        10000baseT/Full 
	Advertised pause frame use: No
	Advertised auto-negotiation: Yes
	Speed: 10000Mb/s
	Duplex: Full
	Port: Other
	PHYAD: 0
	Transceiver: external
	Auto-negotiation: on
	Supports Wake-on: umbg
	Wake-on: g
	Current message level: 0x00000007 (7)
			       drv probe link
	Link detected: yes
```

**Comment by whl739** [comment]
Look at this: http://dpdk.org/ml/archives/dev/2015-July/021863.html. 
It's similar with your issuse.
Maybe it's the reason.

> The default Linux bridge (and OVS) switch are your bottleneck.
It is not DPDK virtio issue in general. There are some small performance
gains still possible with virtio enhancements (like offloading).

**Comment by pkking** [comment]
Thanks for the link, network passthrough is a nice suggestion.
So, is that means if i decide to deploy my APP in a IaaS or Paas cloud infra with f-stack, this performance bottleneck will probably happen as ovs/virtio are so widely used in these circumstances?

**Comment by whl739** [comment]
Yes.But if the host runs with dpdk-ovs,  the performance will be better.
We only deploy f-stack with physical machine.

**Comment by pkking** [comment]
@whl739 Thanks for your help!
I'll close this thread.
