### ISSUE TITLE
Setup multi services, each use an exclusive nic

### ISSUE THREAD

**Issue by nizibu** [F-Stack/f-stack#486]
Hi, f-stack team!
I will build two services with two nics，this receive only the data of the corresponding nic.
test with f-stack/example/helloword_epoll, what configuration should do in config.ini?

**Comment by jfb8856606** [comment]
You can modify `lcore_list=x` in `[portx]` sec, to set which port run in which lcore.
You can run different services in specified lcore.

**Comment by nizibu** [comment]
Thanks!
according to your instructions, I have successfully tested it.
this is my config.ini:
`port_list=0,1
# Port config section
# Correspond to dpdk.port_list's index: port0, port1...
[port0]
addr=172.16.1.71
netmask=255.255.225.0
broadcast=172.16.1.255
gateway=172.16.1.1
# lcore list used to handle this port
# the format is same as port_list
lcore_list=0,2
[port1]
addr=172.168.1.71
netmask=255.255.225.0
broadcast=172.168.1.255
gateway=172.168.1.1

# lcore list used to handle this port
# the format is same as port_list
lcore_list=1,3
`

**Comment by nizibu** [comment]
Thanks!
according to your instructions, I have successfully tested it.
this is my config.ini:
`port_list=0,1

[port0]
addr=172.16.1.71
netmask=255.255.225.0
broadcast=172.16.1.255
gateway=172.16.1.1

lcore_list=0,2

[port1]
addr=172.168.1.71
netmask=255.255.225.0
broadcast=172.168.1.255
gateway=172.168.1.1

lcore_list=1,3
`
