### ISSUE TITLE
F-Stack mutli-process rx pkts by using SO_REUSEPORT

### ISSUE THREAD

**Issue by xiaofan8421** [F-Stack/f-stack#487]
F-Stack is shared-nothing, `SO_REUSEPORT ` is useless.

_Originally posted by @jfb8856606 in https://github.com/F-Stack/f-stack/issues/447#issuecomment-536294513_

**Comment by xiaofan8421** [comment]
What does it mean about useless SO_REUSEPORT? Can't the multi-process receive packets by using SO_REUSEPORT for high performance?

**Comment by jfb8856606** [comment]
F-Stack is shared-nothing, there is a separate stack in every process, can bind same IP:Port in mulit-processes by itself, same to `SO_REUSEPORT` , so  `SO_REUSEPORT` is useless, although release v1.20 compatible it.
