### ISSUE TITLE
F-stack in VM: Ethdev port_id=0 invalid rss_hf: 0x28, valid value: 0x0

### ISSUE THREAD

**Issue by vincentmli** [F-Stack/f-stack#489]
Hi,

I am trying to run F-stack with the ported Nginx in KVM Ubuntu virtual machine, I tried to provision either virtio through OpenvSwitch bridge or SR-IOV VF to the VM and bind the virtio or VF to dpdk for f-stack, but I got same error when starting up F-stack Nginx as below:

root@ubuntu1804:/usr/src/f-stack/app/nginx-1.16.1# lspci

<pre>
00:03.0 Ethernet controller: Red Hat, Inc. Virtio network device
00:04.0 Ethernet controller: Red Hat, Inc. Virtio network device
</pre>

root@ubuntu1804:/usr/src/f-stack# dpdk/usertools/dpdk-devbind.py --status

<pre>
Network devices using DPDK-compatible driver
============================================
0000:00:04.0 'Virtio network device 1000' drv=igb_uio unused=

Network devices using kernel driver
===================================
0000:00:03.0 'Virtio network device 1000' if=ens3 drv=virtio-pci unused=igb_uio *Active*

</pre>

start nginx and got error, provision SR-IOV VF to the VM, same error, is this caused by the invalid rss_hf or something else?

<pre>
Mar 18 22:11:39 ubuntu1804 f-stack[13739]: EAL: PCI device 0000:00:03.0 on NUMA socket -1
Mar 18 22:11:39 ubuntu1804 f-stack[13739]: EAL:   Invalid NUMA socket, default to 0
Mar 18 22:11:39 ubuntu1804 f-stack[13739]: EAL:   probe driver: 1af4:1000 net_virtio
Mar 18 22:11:39 ubuntu1804 f-stack[13739]: EAL: PCI device 0000:00:04.0 on NUMA socket -1
Mar 18 22:11:39 ubuntu1804 f-stack[13739]: EAL:   Invalid NUMA socket, default to 0
Mar 18 22:11:39 ubuntu1804 f-stack[13739]: EAL:   probe driver: 1af4:1000 net_virtio
Mar 18 22:11:39 ubuntu1804 kernel: igb_uio 0000:00:04.0: uio device registered with irq 27
Mar 18 22:11:39 ubuntu1804 f-stack[13739]: Ethdev port_id=0 invalid rss_hf: 0x28, valid value: 0x0
Mar 18 22:11:39 ubuntu1804 f-stack[13739]: EAL: Error - exiting with code: 1
                                             Cause:
Mar 18 22:11:39 ubuntu1804 f-stack[13739]: init_port_start failed
</pre>

**Comment by vincentmli** [comment]
here is error with EAL exiting code  1#012
<pre>
Mar 18 22:38:40 ubuntu1804 f-stack[13817]: EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
Mar 18 22:38:40 ubuntu1804 f-stack[13817]: EAL: PCI device 0000:00:03.0 on NUMA socket -1
Mar 18 22:38:40 ubuntu1804 f-stack[13817]: EAL:   Invalid NUMA socket, default to 0
Mar 18 22:38:40 ubuntu1804 f-stack[13817]: EAL:   probe driver: 1af4:1000 net_virtio
Mar 18 22:38:40 ubuntu1804 f-stack[13817]: EAL: PCI device 0000:00:04.0 on NUMA socket -1
Mar 18 22:38:40 ubuntu1804 f-stack[13817]: EAL:   Invalid NUMA socket, default to 0
Mar 18 22:38:40 ubuntu1804 f-stack[13817]: EAL:   probe driver: 1af4:1000 net_virtio
Mar 18 22:38:40 ubuntu1804 kernel: [19199.301568] igb_uio 0000:00:04.0: uio device registered with irq 27
Mar 18 22:38:40 ubuntu1804 f-stack[13817]: Ethdev port_id=0 invalid rss_hf: 0x28, valid value: 0x0
Mar 18 22:38:40 ubuntu1804 f-stack[13817]: EAL: Error - exiting with code: 1#012  Cause:
Mar 18 22:38:40 ubuntu1804 f-stack[13817]: init_port_start failed
</pre>

**Comment by vincentmli** [comment]
run strace when starting nginx, here is more information. it looks the error is indeed caused by RSS, note the modified RSS hash "requested:0x3ffffc configured:0"

13827 write(1, "lcore: 0, port: 0, queue: 0\ncreate mbuf pool on socket 0\ncreate ring:dispatch_ring_p0_q0 success, 2047 ring entries are now free!\nPort 0 MAC: 00 00 00 00 00 01\nPort 0 modified RSS hash function based on hardware support,requested:0x3ffffc configured:0\nTSO is disabled\nEthdev port_id=0 invalid rss_hf: 0x28, valid value: 0x0\n", 324) = 324
13827 getpid()                          = 13827
13827 sendto(13, "<27>Mar 18 22:46:27 f-stack[13827]: Ethdev port_id=0 invalid rss_hf: 0x28, valid value: 0x0\n", 92, MSG_NOSIGNAL, NULL, 0) = 92
13827 write(1, "EAL: Error - exiting with code: 1\n  Cause: ", 43) = 43
13827 getpid()                          = 13827
13827 sendto(13, "<26>Mar 18 22:46:27 f-stack[13827]: EAL: Error - exiting with code: 1\n  Cause: ", 79, MSG_NOSIGNAL, NULL, 0) = 79
13827 write(1, "init_port_start failed\n", 23) = 23
13827 getpid()                          = 13827
13827 sendto(13, "<26>Mar 18 22:46:27 f-stack[13827]: init_port_start failed\n", 59, MSG_NOSIGNAL, NULL, 0) = 59
13827 close(14)                         = 0

**Comment by jfb8856606** [comment]
F-Stack not tested run in VM with OpenvSwitch, just tested use vdev on docker and OVS-DPDK run in host.
You can try run DPDK demo in your envirment to see if it work well, if it work well, i will to test it.

**Comment by vincentmli** [comment]
thanks for responding, my test is running OVS-DPDK in host, here is my OVS-DPDK config:

<pre>
root@vli-lab:~# ovs-vsctl show
f7569f8c-2118-4fec-8197-2affe5dc581b
    Bridge ovs-br0
        datapath_type: netdev
        Port dpdkvhostuserclient0
            Interface dpdkvhostuserclient0
                type: dpdkvhostuserclient
                options: {vhost-server-path="/tmp/dpdkvhostuserclient0"}
        Port dpdk-p0
            Interface dpdk-p0
                type: dpdk
                options: {dpdk-devargs="0000:04:00.0", n_rxq="16", n_txq="16"}
        Port ovs-br0
            Interface ovs-br0
                type: internal
    Bridge ovs-vhostnet-br
        Port enp4s0f1
            Interface enp4s0f1
        Port ovs-vhostnet-br
            Interface ovs-vhostnet-br
                type: internal
    ovs_version: "2.12.90"
</pre>

libvirt xml for the VM:

    <interface type='vhostuser'>
      <mac address='00:00:00:00:00:01'/>
      <source type='unix' path='/tmp/dpdkvhostuserclient0' mode='server'/>
      <target dev='dpdkvhostuserclient0'/>
      <model type='virtio'/>
      <driver queues='2'>
        <host mrg_rxbuf='on'/>
      </driver>
      <alias name='net1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </interface>

**Comment by vincentmli** [comment]
traced through the error and code, here is suspect:
according to the message  requested:0x3ffffc configured:0, the port_conf.rx_adv_conf.rss_conf.rss_hf should be 0 and passed on to rte_eth_dev_configure, but in rte_eth_dev_configure dev_conf->rx_adv_conf.rss_conf.rss_hf is changed to 0x28, why from 0 to 0x28 ?

<pre>
lib/ff_dpdk_if.c
static int
init_port_start(void)
{
……..
          port_conf.rx_adv_conf.rss_conf.rss_hf &= dev_info.flow_type_rss_offloads;
            if (port_conf.rx_adv_conf.rss_conf.rss_hf !=
                    ETH_RSS_PROTO_MASK) {
                printf("Port %u modified RSS hash function based on hardware support,"
                        "requested:%#"PRIx64" configured:%#"PRIx64"\n",
                        port_id, default_rss_hf,
                        port_conf.rx_adv_conf.rss_conf.rss_hf); <===HERE IT IS VALUE 0
            }

           int ret = rte_eth_dev_configure(port_id, nb_queues, nb_queues, &port_conf);
            if (ret != 0) {
                return ret;
            }

……….
}
</pre>


Ethdev port_id=0 invalid rss_hf: 0x28, valid value: 0x0

dpdk/lib/librte_ethdev/rte_ethdev.c

<pre>
int
rte_eth_dev_configure(uint16_t port_id, uint16_t nb_rx_q, uint16_t nb_tx_q,
                      const struct rte_eth_conf *dev_conf)
{

…………
       /* Check that device supports requested rss hash functions. */
        if ((dev_info.flow_type_rss_offloads |
             dev_conf->rx_adv_conf.rss_conf.rss_hf) !=
            dev_info.flow_type_rss_offloads) {
                RTE_ETHDEV_LOG(ERR,
                        "Ethdev port_id=%u invalid rss_hf: 0x%"PRIx64", valid value: 0x%"PRIx64"\n",
                        port_id, dev_conf->rx_adv_conf.rss_conf.rss_hf, <=== FROM 0 TO 0x28 ?
                        dev_info.flow_type_rss_offloads);
                ret = -EINVAL;
                goto rollback;
        }
……………
}

</pre>

**Comment by vincentmli** [comment]
I suspect f-stack nginx fail to run might because virtio-pmd in DPDK does not support RSS offload
<pre>
# git show 13b3137f3b7c8
commit 13b3137f3b7c8f866947a9b34e06a8aec0d084f7
Author: Dilshod Urazov 
Date:   Wed Oct 9 13:32:07 2019 +0100

    net/virtio: reject unsupported Rx multi-queue modes
    
    This driver supports none of DCB, RSS or VMDQ modes, therefore must
    check and return error if configured incorrectly.
    
    Virtio can distribute Rx packets across multi-queue, but there is
    no controls (algorithm, redirection table, hash function) except
    number of Rx queues and ETH_MQ_RX_NONE is the best fit meaning
    no method is enforced on how to route packets to MQs.
    
    Fixes: c1f86306a026 ("virtio: add new driver")
    Cc: stable@dpdk.org
    
    Signed-off-by: Dilshod Urazov 
    Signed-off-by: Andrew Rybchenko 
    Reviewed-by: Maxime Coquelin 

diff --git a/drivers/net/virtio/virtio_ethdev.c b/drivers/net/virtio/virtio_ethdev.c
index 0a2ed2e50..76bd40a3e 100644
--- a/drivers/net/virtio/virtio_ethdev.c
+++ b/drivers/net/virtio/virtio_ethdev.c
@@ -2066,6 +2066,13 @@ virtio_dev_configure(struct rte_eth_dev *dev)
        PMD_INIT_LOG(DEBUG, "configure");
        req_features = VIRTIO_PMD_DEFAULT_GUEST_FEATURES;
 
+       if (rxmode->mq_mode != ETH_MQ_RX_NONE) {
+               PMD_DRV_LOG(ERR,
+                       "Unsupported Rx multi queue mode %d",
+                       rxmode->mq_mode);
+               return -EINVAL;
+       }
+
        if (dev->data->dev_conf.intr_conf.rxq) {
                ret = virtio_init_device(dev, hw->req_guest_features);
                if (ret < 0)
</pre>

but I am curious why the error "Ethdev port_id=0 invalid rss_hf: 0x28, valid value: 0x0" occurs ?

**Comment by ygm521** [comment]
i also :
Port 0 modified RSS hash function based on hardware support,requested:0x3ffffc configured:0
TSO is disabled
virtio_dev_configure(): Unsupported Rx multi queue mode 1

**Comment by jfb8856606** [comment]
> I suspect f-stack nginx fail to run might because virtio-pmd in DPDK does not support RSS offload
> 
> # git show 13b3137f3b7c8
> commit 13b3137f3b7c8f866947a9b34e06a8aec0d084f7
> Author: Dilshod Urazov 
> Date:   Wed Oct 9 13:32:07 2019 +0100
> 
>     net/virtio: reject unsupported Rx multi-queue modes
>     
>     This driver supports none of DCB, RSS or VMDQ modes, therefore must
>     check and return error if configured incorrectly.
>     
>     Virtio can distribute Rx packets across multi-queue, but there is
>     no controls (algorithm, redirection table, hash function) except
>     number of Rx queues and ETH_MQ_RX_NONE is the best fit meaning
>     no method is enforced on how to route packets to MQs.
>     
>     Fixes: c1f86306a026 ("virtio: add new driver")
>     Cc: stable@dpdk.org
>     
>     Signed-off-by: Dilshod Urazov 
>     Signed-off-by: Andrew Rybchenko 
>     Reviewed-by: Maxime Coquelin 
> 
> diff --git a/drivers/net/virtio/virtio_ethdev.c b/drivers/net/virtio/virtio_ethdev.c
> index 0a2ed2e50..76bd40a3e 100644
> --- a/drivers/net/virtio/virtio_ethdev.c
> +++ b/drivers/net/virtio/virtio_ethdev.c
> @@ -2066,6 +2066,13 @@ virtio_dev_configure(struct rte_eth_dev *dev)
>         PMD_INIT_LOG(DEBUG, "configure");
>         req_features = VIRTIO_PMD_DEFAULT_GUEST_FEATURES;
>  
> +       if (rxmode->mq_mode != ETH_MQ_RX_NONE) {
> +               PMD_DRV_LOG(ERR,
> +                       "Unsupported Rx multi queue mode %d",
> +                       rxmode->mq_mode);
> +               return -EINVAL;
> +       }
> +
>         if (dev->data->dev_conf.intr_conf.rxq) {
>                 ret = virtio_init_device(dev, hw->req_guest_features);
>                 if (ret < 0)
> but I am curious why the error "Ethdev port_id=0 invalid rss_hf: 0x28, valid value: 0x0" occurs ?

If you use F-Stack with DPDK 19.11 (dev branch), you can see this and do some rollback yourself, and F-Stack will work.

But you should know run RSS with vitrio has some issues, such as you MUST init the same rx and tx queues num .
