### ISSUE TITLE
only support FreeBSD?

### ISSUE THREAD

**Issue by lijk8890** [F-Stack/f-stack#49]
Hi:
Can F-Stack support CentOS/RedHat system? or only support FreeBSD?
thx

**Comment by whl739** [comment]
We only support Linux but not FreeBSD.We port FreeBSD network stack to Linux userspace.

**Comment by lijk8890** [comment]
but, follow the "Quick Start", i can't build it succeed,
the **errors** just like this:
cc -c -O2 -fno-strict-aliasing -frename-registers -pipe -Wno-maybe-uninitialized   -std=c99  -Wall -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wno-inline -Wcast-qual -Wno-pointer-sign -Wmissing-include-dirs -fdiagnostics-show-option -Wno-unused-but-set-variable -fno-common -finline-limit=8000 --param inline-unit-growth=100 --param large-function-growth=1000  -DFSTACK  -fstack-protector -D__FreeBSD__ -D_KERNEL -DHAVE_KERNEL_OPTION_HEADERS -include opt_global.h -fno-builtin -I/data/f-stack/lib/include -undef -imacros filtered_predefined_macros.h -nostdinc  -I. -I/data/f-stack/lib/../freebsd -I./machine_include -I./opt -Werror -Wno-unused-variable  ff_glue.c
cc1: warnings being treated as errors
In file included from ff_glue.c:50:
/data/f-stack/lib/../freebsd/sys/buf.h:130: error: declaration does not declare anything
/data/f-stack/lib/../freebsd/sys/buf.h:131: error: declaration does not declare anything
In file included from ff_glue.c:53:
/data/f-stack/lib/../freebsd/sys/mbuf.h:192: error: declaration does not declare anything
/data/f-stack/lib/../freebsd/sys/mbuf.h:219: error: declaration does not declare anything
/data/f-stack/lib/../freebsd/sys/mbuf.h:224: error: declaration does not declare anything
/data/f-stack/lib/../freebsd/sys/mbuf.h:246: error: declaration does not declare anything
/data/f-stack/lib/../freebsd/sys/mbuf.h:247: error: declaration does not declare anything
/data/f-stack/lib/../freebsd/sys/mbuf.h:249: error: declaration does not declare anything
/data/f-stack/lib/../freebsd/sys/mbuf.h: In function ‘m_extaddref’:
/data/f-stack/lib/../freebsd/sys/mbuf.h:659: error: ‘struct mbuf’ has no member named ‘m_ext’
/data/f-stack/lib/../freebsd/sys/mbuf.h:660: error: ‘struct mbuf’ has no member named ‘m_ext’
/data/f-stack/lib/../freebsd/sys/mbuf.h:661: error: ‘struct mbuf’ has no member named ‘m_ext’
/data/f-stack/lib/../freebsd/sys/mbuf.h:662: error: ‘struct mbuf’ has no member named ‘m_ext’
/data/f-stack/lib/../freebsd/sys/mbuf.h:663: error: ‘struct mbuf’ has no member named ‘m_ext’
/data/f-stack/lib/../freebsd/sys/mbuf.h:664: error: ‘struct mbuf’ has no member named ‘m_ext’
/data/f-stack/lib/../freebsd/sys/mbuf.h:665: error: ‘struct mbuf’ has no member named ‘m_ext’
/data/f-stack/lib/../freebsd/sys/mbuf.h:666: error: ‘struct mbuf’ has no member named ‘m_ext’
/data/f-stack/lib/../freebsd/sys/mbuf.h:667: error: ‘struct mbuf’ has no member named ‘m_ext’

when i check the source code , i found it:
vim /data/f-stack/lib/../freebsd/sys/**buf.h**
124         union {
125                 TAILQ_ENTRY(buf) b_freelist; /* (Q) */
126                 struct {
127                         void    (*b_pgiodone)(void *, vm_page_t *, int, int);
128                         int     b_pgbefore;
129                         int     b_pgafter;
130                 };
131         };
is there a bug? or something i did wrong?
wish your reply, thank you.
@whl739

**Comment by whl739** [comment]
Use gcc 4.8+.

**Comment by lijk8890** [comment]
my **environment**:
CentOS 6.5 64bit x86_64 arch
gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC)
@whl739

**Comment by lijk8890** [comment]
ok, i will try it.
@whl739
