### ISSUE TITLE
I am in china, Why I can't download the f-stack ?

### ISSUE THREAD

**Issue by chquan** [F-Stack/f-stack#492]
I am in china, Why I can't download the f-stack ?
If you can help me , Please send email to me: quanchunhui@163.com.

thanks!

**Comment by vincentmli** [comment]
> I am in china, Why I can't download the f-stack ?

could you download any other github project?  , I can't imagine this is f-stack problem :)

**Comment by jfb8856606** [comment]
You need check your network or search F-Stack in coding.
