### ISSUE TITLE
KNI link status is not correctly updated

### ISSUE THREAD

**Issue by freak82** [F-Stack/f-stack#493]
Hi there,

I'm playing/testing the KNI support of the f-stack and found two issues there:
1. The status of the KNI interface (veth0) is not correctly set to `UP` even after the `kni_config_network_interface` function return success. I mean that executing `ip link set up veth0` causes the above function to be called and it returns success but the `ip a a` still shows the interface as `DOWN`.
2. Packets sent from the Linux kernel never reach the KNI interface (veth0). Here is my scenario:
- I run the f-stack application with KNI support which brings the KNI interface `veth0`
- I setup the ip on this interface, setup routing and static ARP table entry
- I start a TCP server (nc -4tl <ip> <port>) on the `veth0` ip.
- I setup iptables rules which log to dmesg the packets going through `PREROUTING`, `INPUT`, `OUTPUT` and `POSTROUTING` chains.
- I start tcpdump on the `veth0` interface.
- I start TCP client on a different machine which tries to connect to the above TCP server.
The result is that I see SYN packet(s) coming on the KNI interface `veth0`, I see them with the tcpdump and I see the same packet(s) in the `PREROUTING` and `INPUT` chains. Then I see the SYN-ACK packet in the `OUTPUT` and the `POSTROUTING` chains but I don't see the packet with tcpdump on the KNI interface. The packet is lost after the `POSTROUTING` and the KNI interface TX queue.

It turned out that the cause for both of the above issues is the mssing link status update. The KNI interface is not set to UP and thus the kernel doesn't queue to it any outbound packets to it. I added functionality which updates the KNI link status in a way similar to the one shown in the `dpdk/example/kni/main.c`.

I can provide patch for this if you want it?

Regards,
Pavel.

**Comment by nizibu** [comment]
You can configure 'echo 1 > /sys/class/net/veth0/carrier'  to activate the interface.
