### ISSUE TITLE
Can I use f-stack without enabling DPDK?

### ISSUE THREAD

**Issue by choleraehyq** [F-Stack/f-stack#5]
The DPDK support is optional in seastar. We can compile seastar with DPDK `./configure --enable-dpdk`.
Can I use f-stack without DPDK? I just want to use the user space stack.

**Comment by whl739** [comment]
No, we don't support it currently.
But you can do it yourself.  In ff_veth.c:ff_veth_setup_interface, set ifp->if_transmit = your_transmit_func, and 
call ifp->if_input(ifp, mb) when recv packets.

**Comment by choleraehyq** [comment]
OK, thanks.
