### ISSUE TITLE
Cannot set socket fd to be nonblocking

### ISSUE THREAD

**Issue by Zhiyi-Zhang** [F-Stack/f-stack#50]
Hi F-stack team, I recently got blocked when playing with f-stack. I found I cannot set the file descriptor to be nonblocking.
I am trying to use UDP in epoll mode. When a new event whose mask is EPOLLIN come, I then call the function `ff_recvmsg()` to read from the fd. However, `ff_recvmsg` is always blocking my program.
Even though I tried the following code, I still got blocked.
```
int flags = ff_fcntl(fd, F_GETFL, 0);
exit_if(flags<0, "fcntl failed");
int r = ff_fcntl(fd, F_SETFL, flags | O_NONBLOCK);
exit_if(r<0, "fcntl failed");
```
Do you have any idea about it?

**Comment by whl739** [comment]
There's a bug in `ff_fcntl`. `O_NONBLOCK`'s value is different between Linux and FreeBSD.
Use `int on = 1;ff_ioctl(sockfd, FIONBIO, &on);` instead.

**Comment by Zhiyi-Zhang** [comment]
Thank you so much. It works perfectly. A further question is: can f-stack support adding pipe fd to epoll fd? As far as I know, there is no ff_pipe() in f-stack.

**Comment by whl739** [comment]
No, we didn't support.

**Comment by zouyonghao** [comment]
> There's a bug in `ff_fcntl`. `O_NONBLOCK`'s value is different between Linux and FreeBSD.
> Use `int on = 1;ff_ioctl(sockfd, FIONBIO, &on);` instead.

Will this bug be fixed later?
