### ISSUE TITLE
ubuntu 16.04 compile f-stack/dpdk error

### ISSUE THREAD

**Issue by jackie-lee** [F-Stack/f-stack#502]
run f-stack/dpdk/usertools/dpdk-setup.sh
select [15] x86_64-native-linuxapp-gcc

error message:
In file included from /home/dpdk/f-stack/dpdk/lib/librte_eal/linuxapp/eal/eal.c:32:0:
/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_memory.h:51:5: warning: "RTE_CACHE_LINE_SIZE" is not defined [-Wundef]
 #if RTE_CACHE_LINE_SIZE == 64
     ^
/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_memory.h:53:7: warning: "RTE_CACHE_LINE_SIZE" is not defined [-Wundef]
 #elif RTE_CACHE_LINE_SIZE == 128
       ^
**/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_memory.h:56:2: error: #error "Unsupported cache line size"
 #error "Unsupported cache line size"
  ^
In file included from /home/dpdk/f-stack/dpdk/lib/librte_eal/linuxapp/eal/eal.c:34:0:
/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_eal.h:61:22: error: ‘RTE_MAX_NUMA_NODES’ undeclared here (not in a function)
  uint32_t numa_nodes[RTE_MAX_NUMA_NODES]; /**< List of detected NUMA nodes. */
                      ^
/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_eal.h:63:35: error: ‘RTE_MAX_LCORE’ undeclared here (not in a function)
  enum rte_lcore_role_t lcore_role[RTE_MAX_LCORE]; /**< State of cores. */
                                   ^
In file included from /home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/generic/rte_spinlock.h:21:0,
                 from /home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_spinlock.h:12,
                 from /home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_malloc_heap.h:10,
                 from /home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_eal_memconfig.h:1,
                 from /home/dpdk/f-stack/dpdk/lib/librte_eal/linuxapp/eal/eal.c:35:
/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_lcore.h: In function ‘rte_lcore_to_socket_id’:**
/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_lcore.h:210:33: warning: parameter ‘lcore_id’ set but not used [-Wunused-but-set-parameter]
 rte_lcore_to_socket_id(unsigned lcore_id)
                                 ^
In file included from /home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/generic/rte_cycles.h:18:0,
                 from /home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_cycles.h:13,
                 from /home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_spinlock.h:18,
                 from /home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_malloc_heap.h:10,
                 from /home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_eal_memconfig.h:1,
                 from /home/dpdk/f-stack/dpdk/lib/librte_eal/linuxapp/eal/eal.c:35:
/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_atomic.h: At top level:
/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_atomic.h:18:5: warning: "RTE_MAX_LCORE" is not defined [-Wundef]
 #if RTE_MAX_LCORE == 1
     ^
In file included from /home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_compat.h:8:0,
                 from /home/dpdk/f-stack/dpdk/lib/librte_eal/linuxapp/eal/eal.c:29:
**/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_memory.h:64:43: error: ‘RTE_CACHE_LINE_SIZE’ undeclared here (not in a function)
 #define __rte_cache_aligned __rte_aligned(RTE_CACHE_LINE_SIZE)
                                           ^**
/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_common.h:61:53: note: in definition of macro ‘__rte_aligned’
 #define __rte_aligned(a) __attribute__((__aligned__(a)))
                                                     ^
/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_malloc_heap.h:33:3: note: in expansion of macro ‘__rte_cache_aligned’
 } __rte_cache_aligned;
   ^
**In file included from /home/dpdk/f-stack/dpdk/lib/librte_eal/linuxapp/eal/eal.c:35:0:
/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_eal_memconfig.h:70:33: error: ‘RTE_MAX_MEMSEG_LISTS’ undeclared here (not in a function)
  struct rte_memseg_list memsegs[RTE_MAX_MEMSEG_LISTS];
                                 ^
/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_eal_memconfig.h:73:35: error: ‘RTE_MAX_TAILQ’ undeclared here (not in a function)
  struct rte_tailq_head tailq_head[RTE_MAX_TAILQ]; /**< Tailqs for objects */
                                   ^
/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_eal_memconfig.h:76:34: error: ‘RTE_MAX_HEAPS’ undeclared here (not in a function)
  struct malloc_heap malloc_heaps[RTE_MAX_HEAPS];**
                                  ^
/home/dpdk/f-stack/dpdk/lib/librte_eal/linuxapp/eal/eal.c: In function ‘eal_parse_socket_arg’:
/home/dpdk/f-stack/dpdk/lib/librte_eal/linuxapp/eal/eal.c:546:9: warning: unused variable ‘arg’ [-Wunused-variable]
  char * arg[RTE_MAX_NUMA_NODES];
         ^
/home/dpdk/f-stack/dpdk/lib/librte_eal/linuxapp/eal/eal.c: In function ‘rte_eal_lcore_role’:
/home/dpdk/f-stack/dpdk/lib/librte_eal/linuxapp/eal/eal.c:1268:29: warning: parameter ‘lcore_id’ set but not used [-Wunused-but-set-parameter]
 rte_eal_lcore_role(unsigned lcore_id)
                             ^
In file included from /home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/generic/rte_spinlock.h:21:0,
                 from /home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_spinlock.h:12,
                 from /home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_malloc_heap.h:10,
                 from /home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_eal_memconfig.h:1,
                 from /home/dpdk/f-stack/dpdk/lib/librte_eal/linuxapp/eal/eal.c:35:
/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_lcore.h: In function ‘rte_lcore_to_socket_id’:
/home/dpdk/f-stack/dpdk/x86_64-native-linuxapp-gcc/include/rte_lcore.h:213:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/dpdk/f-stack/dpdk/lib/librte_eal/linuxapp/eal/eal.c: In function ‘rte_eal_lcore_role’:
/home/dpdk/f-stack/dpdk/lib/librte_eal/linuxapp/eal/eal.c:1271:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/dpdk/f-stack/dpdk/lib/librte_eal/linuxapp/eal/eal.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-address-of-packed-member’
/home/dpdk/f-stack/dpdk/mk/internal/rte.compile-pre.mk:114: recipe for target 'eal.o' failed
make[7]: *** [eal.o] Error 1
/home/dpdk/f-stack/dpdk/mk/rte.subdir.mk:35: recipe for target 'eal' failed
make[6]: *** [eal] Error 2
/home/dpdk/f-stack/dpdk/mk/rte.subdir.mk:35: recipe for target 'linuxapp' failed
make[5]: *** [linuxapp] Error 2
/home/dpdk/f-stack/dpdk/mk/rte.subdir.mk:35: recipe for target 'librte_eal' failed
make[4]: *** [librte_eal] Error 2
/home/dpdk/f-stack/dpdk/mk/rte.sdkbuild.mk:49: recipe for target 'lib' failed
make[3]: *** [lib] Error 2
/home/dpdk/f-stack/dpdk/mk/rte.sdkroot.mk:100: recipe for target 'all' failed
make[2]: *** [all] Error 2
/home/dpdk/f-stack/dpdk/mk/rte.sdkinstall.mk:57: recipe for target 'pre_install' failed
make[1]: *** [pre_install] Error 2
/home/dpdk/f-stack/dpdk/mk/rte.sdkroot.mk:79: recipe for target 'install' failed

Does anyone encountered this issue, how to fix it?

**Comment by jfb8856606** [comment]
Maybe some of your DPDK's file has no executable permissions, you can directly git clone F-STACK OR download f-stack.tar.gz or f-stack.zip from github, but not copy from Windows, and re-compile it.
