### ISSUE TITLE
proxy_kernel_network_stack 卡死没响应

### ISSUE THREAD

**Issue by longyoudong** [F-Stack/f-stack#504]
**1. nginx.conf配置**
proxy_kernel_network_stack on;
 location / {
		 proxy_pass http://127.0.0.1:9000;           
           
        }
2. 压力测试
 ./wrk -t32 -c1000 -d10s http://192.168.200.30/

3. curl http://192.168.200.30/ 一直卡死不动

补充：
   不进行压力测试，单次访问 http://192.168.200.30/ 正常

**Comment by jfb8856606** [comment]
You should do more check by yourself, such as enable log or disable proxy_pass or check `http://127.0.0.1:9000`'s performance, etc.
