### ISSUE TITLE
nginx readv errors

### ISSUE THREAD

**Issue by pkking** [F-Stack/f-stack#51]
Dear team,
Today i config nignx as a proxy before my static pages server.
But nginx complain some errors and i have no idea about that.
My nginx.conf is:
```bash
#user  nobody;
worker_processes  1;
daemon off;
events {
    worker_connections  1024000;
    use kqueue;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  logs/access.log  main;
    error_log logs/nginx_error.log  debug;

    sendfile        off;
    keepalive_timeout  65;
    gzip  on;
    server {
        listen       8080;
        server_name  localhost;

        location / {
            proxy_pass   http://192.1.1.4:80;
        }
    }
}
```
As the configuration above, i have web server at 192.1.1.4:80 and proxy is running on 192.1.1.3:8080
When i run `lynx  192.1.1.3:8080`, i can see nothing on the screen and the web server log shows:
```
192.1.1.3 - - [02/Aug/2017:15:15:57 +0800] "GET / HTTP/1.0" 200 612 "-" "Lynx/2.8.8dev.15 libwww-FM/2.14 SSL-MM/1.4.1 OpenSSL/1.0.1e-fips"
```
But the nginx listen on 192.1.1.3:8080 report:
```
2017/08/02 15:01:16 [alert] 17447#0: *1 readv() failed (9: Bad file descriptor) while reading upstream, client: 192.1.1.4, server: localhost, request: "GET / HTTP/1.0", upstream: "http://192.1.1.4:80/", host: "192.1.1.3:8080"
```
Any suggestions?
PS: The config.ini is origin from this repo without any modifications, 
PS1: I started another nginx without f-stack and it works nicely with the same configurations

**Comment by whl739** [comment]
It seemed that the http response was received by another f-stack process.
When connect to a peer, f-stack will choose a port that can be received by itself, maybe there's bug here.
It's similar with #22.
Enable packet capture, and take a look at it, paste your nic info.

**Comment by pkking** [comment]
[a.zip](https://github.com/F-Stack/f-stack/files/1193292/a.zip)
The packet capture seems nothing goes wrong.
The nic is a virtio device which bridged to an Intel Corporation 82599 10G nic.
```
lspci -v|grep -i eth
00:03.0 Ethernet controller: Red Hat, Inc Virtio network device
	Subsystem: Red Hat, Inc Device 0001
	Physical Slot: 3
	Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR+ FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Interrupt: pin A routed to IRQ 11
	Region 0: I/O ports at c000 [size=64]
	Region 1: Memory at febf1000 (32-bit, non-prefetchable) [size=4K]
	Expansion ROM at feb40000 [disabled] [size=256K]
	Capabilities: [40] MSI-X: Enable+ Count=18 Masked-
		Vector table: BAR=1 offset=00000000
		PBA: BAR=1 offset=00000800
	Kernel driver in use: igb_uio
	Kernel modules: virtio_pci
```
And the f-stack start log:
```
Checking link statusdone
Port 0 Link Up - speed 10000 Mbps - full-duplex
link_elf_lookup_symbol: missing symbol hash table
link_elf_lookup_symbol: missing symbol hash table
netisr_init: forcing maxthreads from 1 to 0
Timecounters tick every 10.000 msec
Timecounter "ff_clock" frequency 100 Hz quality 1
f-stack-0: Ethernet address: 52:54:00:c6:1e:18
```

**Comment by whl739** [comment]
I tried the same configurations and it worked fine.
Any more infos?

**Comment by pkking** [comment]
[nginx_errors.txt](https://github.com/F-Stack/f-stack/files/1195725/nginx_errors.txt)
@whl739 Here's the nginx debug log, notice there are two connect() return NGX_AGAIN error at line 72 and 235,
Seems the connect() syscall return -1 but nginx does not take care of it gracefully?

**Comment by whl739** [comment]
Maybe this issuse is introduced by my previous commits.
Could you test it again with this patch?
[readv.txt](https://github.com/F-Stack/f-stack/files/1195876/readv.txt)
