### ISSUE TITLE
Basic questions about F-stack

### ISSUE THREAD

**Issue by ecofriendlygeek** [F-Stack/f-stack#516]
Hi,
We are evaluating F-stack + DPDK to speed up our networking applications.
1. Do we need to re-write our apps which currently based on Linux socket interface to use the F-stack socket interface ?
2. Can we plug in different TCP congestion algorithms like in Linux ?
3. Can we port in a new TCP congestion algorithm if one is not available ?
4. Does it support multiple DPDK network interfaces (eth0,eth1,eth2) at the same time bound to different IP addresses ?
5. If answer to (4) is yes, can we port our own IP forwarding engine over F-Stack on DPDK ?
Thanks.

**Comment by ecofriendlygeek** [comment]
I am trying to find the answers to the above myself.
I could compile and run dpdk, f-stack and nginx (see below)
I have 2 DPDK cards (see below); 
1. how do I configure the interfaces for these 2 cards with the IP addresses I want ?
2. how do I test it from another system with a browser or any other application ? 
3. apache is already running on port 80; how do I  bind nginx to another port ?

Network devices using DPDK-compatible driver
0000:01:00.0 'I350 Gigabit Network Connection 1521' drv=igb_uio unused=igb
0000:01:00.1 'I350 Gigabit Network Connection 1521' drv=igb_uio unused=igb

~/f-stack/f-stack$ /bin/ps -ef | grep nginx
root     18494     1  0 13:47 ?        00:00:00 nginx: master process /usr/local/nginx_fstack/sbin/nginx
root     18495 18494 99 13:47 ?        00:46:08 nginx: worker process

~/f-stack/f-stack$ cat /usr/local/nginx_fstack/logs/error.log                        
EAL: Detected 16 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket

**Comment by vincentmli** [comment]
> I am trying to find the answers to the above myself.
> I could compile and run dpdk, f-stack and nginx (see below)
> I have 2 DPDK cards (see below);
> 
> 1. how do I configure the interfaces for these 2 cards with the IP addresses I want ?

for F-Stack Nginx, configure the [port0] and [port1] section in /usr/local/nginx_fstack/conf/f-stack.conf, for example I have:
<pre>
port_list=0-1
[port0]
addr=10.1.0.168
netmask=255.255.0.0
broadcast=10.1.255.255
gateway=10.1.0.1
lcore_list= 0-3

[port1]
addr=10.2.0.168
netmask=255.255.0.0
broadcast=10.2.255.255
gateway=10.2.0.1
lcore_list= 0-3
</pre>

> 2. how do I test it from another system with a browser or any other application ?

curl, browser from another machine should  work fine.

> 3. apache is already running on port 80; how do I  bind nginx to another port ?
> 
the apache runs in Linux kernel stack, f-stack nginx runs in dpdk/freebsd stack, should have no conflict, you can also just configure f-stack nginx to listen to different port  in /usr/local/nginx_fstack/conf/nginx.conf just in case it conflicts with Apache

> Network devices using DPDK-compatible driver
> 0000:01:00.0 'I350 Gigabit Network Connection 1521' drv=igb_uio unused=igb
> 0000:01:00.1 'I350 Gigabit Network Connection 1521' drv=igb_uio unused=igb
> 
> ~/f-stack/f-stack$ /bin/ps -ef | grep nginx
> root 18494 1 0 13:47 ? 00:00:00 nginx: master process /usr/local/nginx_fstack/sbin/nginx
> root 18495 18494 99 13:47 ? 00:46:08 nginx: worker process
> 
> ~/f-stack/f-stack$ cat /usr/local/nginx_fstack/logs/error.log
> EAL: Detected 16 lcore(s)
> EAL: Detected 1 NUMA nodes
> EAL: Multi-process socket /var/run/dpdk/rte/mp_socket

it looks it started ok.  by the way, I have youtube video here about F-Stack Nginx:
https://youtu.be/d0vPUwJT1mw

**Comment by ecofriendlygeek** [comment]
Hi,
Thanks for the response.I could get it running : Apache on Linux with 2 ports and nginx on F-stack with 2 other ports.
Few other observations : 
The helloworld with f-stack crashes and leaves the hugepages locked. Need to reboot the system in this case.
The generic scripts with f-stack are a bit buggy; I hard coded my scripts based on the given scripts.
There are 3 parts:1. Get DPDK driver running with hard coded script
2. Manually edit config for f-stack and nginx : Get application + stack running
3. configure the IP interfaces with a hard coded script

    On Saturday, 6 June, 2020, 5:57:51 am IST, Vincent Li <notifications@github.com> wrote:  
 

I am trying to find the answers to the above myself.
I could compile and run dpdk, f-stack and nginx (see below)
I have 2 DPDK cards (see below);
   
   - how do I configure the interfaces for these 2 cards with the IP addresses I want ?


for F-Stack Nginx, configure the [port0] and [port1] section in /usr/local/nginx_fstack/conf/f-stack.conf, for example I have:
port_list=0-1
[port0]
addr=10.1.0.168
netmask=255.255.0.0
broadcast=10.1.255.255
gateway=10.1.0.1
lcore_list= 0-3

[port1]
addr=10.2.0.168
netmask=255.255.0.0
broadcast=10.2.255.255
gateway=10.2.0.1
lcore_list= 0-3

   
   - how do I test it from another system with a browser or any other application ?


curl, browser from another machine should work fine.

   
   - apache is already running on port 80; how do I bind nginx to another port ?


the apache runs in Linux kernel stack, f-stack nginx runs in dpdk/freebsd stack, should have no conflict, you can also just configure f-stack nginx to listen to different port in /usr/local/nginx_fstack/conf/nginx.conf just in case it conflicts with Apache


Network devices using DPDK-compatible driver
0000:01:00.0 'I350 Gigabit Network Connection 1521' drv=igb_uio unused=igb
0000:01:00.1 'I350 Gigabit Network Connection 1521' drv=igb_uio unused=igb

~/f-stack/f-stack$ /bin/ps -ef | grep nginx
root 18494 1 0 13:47 ? 00:00:00 nginx: master process /usr/local/nginx_fstack/sbin/nginx
root 18495 18494 99 13:47 ? 00:46:08 nginx: worker process

~/f-stack/f-stack$ cat /usr/local/nginx_fstack/logs/error.log
EAL: Detected 16 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket


it looks it started ok. by the way, I have youtube video here about F-Stack Nginx:
https://youtu.be/d0vPUwJT1mw

**Comment by ecofriendlygeek** [comment]
Vincent, Thanks for your help.
