### ISSUE TITLE
How to gdb example/helloworld?

### ISSUE THREAD

**Issue by QinLongFei** [F-Stack/f-stack#521]
Hi, f-stack team,

I'm learning f-stack and want to gdb helloworld example. But I found I cannot gdb DPDK function. For example I cannot next in rte_eal_init. F-Stack function is OK.

I have enabled DPDK debug mode by executing export EXTRA_CFLAGS='-O0 -g' and enable F-Stack debug mode in lib/Makefile. 

![image](https://user-images.githubusercontent.com/14818295/84381007-ea677f80-ac1a-11ea-9583-4574052edffb.png)

Need your help!!!

**Comment by jfb8856606** [comment]
`export EXTRA_CFLAGS='-O0 -g'` and recompile DPDK/F-Fstack lib and  helloworld example is work correct for me.
Wehter you exec `make install` instead `export FF_PATH=/data/f-stack` and `export FF_DPDK=/data/f-stack/dpdk/x86_64-native-linuxapp-gcc`, or whether to recompile  DPDK/F-Stack lib and helloworld completely.

**Comment by QinLongFei** [comment]
Thanks.

I write a shell script to run. I use export FF_PATH/FF_DPDK instead make install.


#!/bin/bash

cd dpdk
make config T=x86_64-native-linuxapp-gcc EXTRA_CFLAGS='-O0 -g' && make
cd ..


echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
mount -t hugetlbfs nodev /mnt/huge
modprobe uio
insmod /root/f-stack/dpdk/x86_64-native-linuxapp-gcc/kmod/igb_uio.ko
insmod /root/f-stack/dpdk/x86_64-native-linuxapp-gcc/kmod/rte_kni.ko carrier=on
ifconfig ens37  down
python /root/f-stack/dpdk/usertools/dpdk-devbind.py --bind=igb_uio ens37

export FF_PATH=/root/f-stack
export FF_DPDK=/root/f-stack/dpdk/x86_64-native-linuxapp-gcc
cd lib
make clean
make -j8

**Comment by QinLongFei** [comment]
Before run this script, I always reboot my centOS.

**Comment by jfb8856606** [comment]
You may try use `export FF_DPDK=/root/f-stack/dpdk/build` instead `export FF_DPDK=/root/f-stack/dpdk/x86_64-native-linuxapp-gcc`

**Comment by jfb8856606** [comment]
or 
```
rm -rf /root/f-stack/dpdk/x86_64-native-linuxapp-gcc
ln -s /root/f-stack/dpdk/build /root/f-stack/dpdk/x86_64-native-linuxapp-gcc
```

**Comment by QinLongFei** [comment]
I try use export FF_DPDK=/root/f-stack/dpdk/build. But I still cannot gdb rte_eal_init.

#!/bin/bash

cd dpdk
make config T=x86_64-native-linuxapp-gcc EXTRA_CFLAGS='-O0 -g' && make 
cd ..


echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
mount -t hugetlbfs nodev /mnt/huge
modprobe uio
insmod /root/f-stack/dpdk/x86_64-native-linuxapp-gcc/kmod/igb_uio.ko
insmod /root/f-stack/dpdk/x86_64-native-linuxapp-gcc/kmod/rte_kni.ko carrier=on
ifconfig ens37  down
python /root/f-stack/dpdk/usertools/dpdk-devbind.py --bind=igb_uio ens37 

export FF_PATH=/root/f-stack
export FF_DPDK=/root/f-stack/dpdk/build
cd lib
make clean
make -j8

**Comment by QinLongFei** [comment]
@jfb8856606 , Can you gdb dpdk function?(for example, rte_eal_init)

**Comment by jfb8856606** [comment]
I try `make config T=x86_64-native-linuxapp-gcc EXTRA_CFLAGS='-O0 -g' && make` and it may not work.
Usually， I run
```
export EXTRA_CFLAGS='-O0 -g'
cd /root/f-stack/dpdk/x86_64-native-linuxapp-gcc  # if there is't the dir, shoud run cd /root/f-stack/dpdk/usertools/;python ./dpdk-setup.sh and select 15
make clean
make
```
and need reuse `export FF_DPDK=/root/f-stack/dpdk/x86_64-native-linuxapp-gcc`

**Comment by QinLongFei** [comment]
@jfb8856606 , 

I have tried your way but it still cannot work.

I think maybe it caused by "LIBS+= -L${FF_DPDK}/lib -Wl,--whole-archive,-ldpdk,--no-whole-archive" in **example/Makefile**

I don't know why use "whole-archive" .**This is normally used to turn an  archive file into a shared library, forcing every object to be included in the resulting shared library**.

I think the reason why I cannot gdb dpdk function is dpdk is linked as shared library. Right?

**Comment by QinLongFei** [comment]
My question is not helloworld cannot work but I cannot gdb helloworld.

**Comment by QinLongFei** [comment]
Do you try gdb the helloworld and set a breakpoint in rte_eal_init? What will happen when you input "next"? Following is my result.

![image](https://user-images.githubusercontent.com/14818295/84654630-1a2bc580-af42-11ea-95fa-30ca21afa6b3.png)

**Comment by jfb8856606** [comment]
Sure, i can do it. The helloworld not recompile in your script, you will recompile helloworld manual?

**Comment by QinLongFei** [comment]
Yes, I recompile helleworld manually every time.

**Comment by QinLongFei** [comment]
Update script to compile helloworld each time.


#!/bin/bash
  
#DPDK_PATH=/root/dpdk-stable-18.11.6

DPDK_PATH=/home/fqin/f-stack/dpdk
FSTACK_PATH=/home/fqin/f-stack
cd $DPDK_PATH
make config T=x86_64-native-linuxapp-gcc EXTRA_CFLAGS='-O0 -g -Wno-address-of-packed-member' && make -j8
cd $FSTACK_PATH

echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
mount -t hugetlbfs nodev /mnt/huge
modprobe uio
insmod $DPDK_PATH/build/kmod/igb_uio.ko
insmod $DPDK_PATH/build/kmod/rte_kni.ko carrier=on
#ifconfig ens33  down
#python $DPDK_PATH/usertools/dpdk-devbind.py --bind=igb_uio ens33 

export FF_PATH=$FSTACK_PATH
export FF_DPDK=$DPDK_PATH/build

cd $FSTACK_PATH/lib
make clean
make -j8


cd $FSTACK_PATH/example
make
cd $FSTACK_PATH

**Comment by jfb8856606** [comment]
Run `cat $DPDK_PATH/build/build/lib/librte_eal/linuxapp/eal/.eal.o.cmd` or  `cat $DPDK_PATH/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/eal/.eal.o.cmd`

And check `-O0 -g` whether be added. If not, it's means `export EXTRA_CFLAGS='-O0 -g'`  not set correctly.

**Comment by jfb8856606** [comment]
You must add `export EXTRA_CFLAGS='-O0 -g'` before `make config T=x86_64-native-linuxapp-gcc EXTRA_CFLAGS='-O0 -g' && make` in your script.

If you just run `make config T=x86_64-native-linuxapp-gcc EXTRA_CFLAGS='-O0 -g' && make`, it will not work.

**Comment by QinLongFei** [comment]
@jfb8856606 , Thanks very much!!!

Yes, It works when "export EXTRA_CFLAGS='-O0 -g' " before  "make config T=x86_64-native-linuxapp-gcc"

Thank you again! Have a good day!

Thanks

**Comment by QinLongFei** [comment]
Thanks @jfb8856606
