### ISSUE TITLE
How to add debug logging msgs in f-stack code

### ISSUE THREAD

**Issue by ecofriendlygeek** [F-Stack/f-stack#525]
I want to add printf messages in congestion control module (freebsd/netinet/cc/ ) to debug some performance / loss issue.
What is the standard method to add printf style statements and which file does this get logged to ?

**Comment by vincentmli** [comment]
I used log as example in https://github.com/F-Stack/f-stack/issues/515#issuecomment-633732109

**Comment by ecofriendlygeek** [comment]
Hello Vincent,
I checked #515 
I compiled my code with the log function; but I can't find the messages in /usr/local/nginx_fstack/logs/error.log .
Do they go to some other log file ? Or something else is missing ?

Also you mentioned in the #515 that SR-IOV is not supported.

But refer #414 and #419 
https://github.com/F-Stack/f-stack/issues/419 and https://github.com/F-Stack/f-stack/issues/414
it seems SR-IOV is supported.
Thanks.

**Comment by ecofriendlygeek** [comment]
I used syslog and could get the messages in /var/log/syslog. Thanks.
Do you have any more info about SR-IOV ?

**Comment by ecofriendlygeek** [comment]
Closing this as Vincent's reply could resolve the logging issue.
For SR-IOV will log separate issue in case needed.
