### ISSUE TITLE
vlan can not used

### ISSUE THREAD

**Issue by xg-king** [F-Stack/f-stack#53]
hi, when  i use  f-stack in vlan.  i create vlan interface and set route ,but i can't ping the ip.  also the  pkt->vlan_tci is correct. can you tel me how to do in vlan?

**Comment by whl739** [comment]
Plz paste your configurations, for example: config.ini, ifconfig -a, routing tables, etc..
And f-stack strips the vlan tci by default, maybe it's the reason.
Could you modify the lib/ff_dpdk_if.c:616, set `port_conf.rxmode.hw_vlan_strip = 0`? Test it again.

**Comment by xg-king** [comment]
my vlan config:
./tools/ifconfig/ifconfig vlan2020 vlan 2020 vlandev f-stack-0
./tools/ifconfig/ifconfig vlan2020 20.0.123.123/16
./tools/ifconfig/ifconfig vlan2020 mtu 1500
./tools/ifconfig/ifconfig vlan2020 up

route:
[root@localhost nginx_user]# ./tools/route/route -p 0 show 20.0.0.122
   route to: 20.0.0.122
destination: 20.0.0.0
	   mask: 255.255.0.0
		fib: 0
  interface: f-stack-0
	  flags: <UP,DONE,PINNED>
 recvpipe  sendpipe  ssthresh  rtt,msec    mtu        weight    expire
       0         0         0         0      1500         1         0 
ifconfig:
[root@localhost nginx_user]# ./tools/ifconfig/ifconfig -a
lo0: flags=8008<LOOPBACK,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	groups: lo 
f-stack-0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=3<RXCSUM,TXCSUM>
	ether c0:bf:c0:30:69:57
	inet 20.0.0.123 netmask 0xffff0000 broadcast 20.0.255.255 
vlan2020: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1460
	ether c0:bf:c0:30:69:57
	inet 20.0.123.123 netmask 0xffff0000 broadcast 20.0.255.255 
	groups: vlan 
	vlan: 2020 vlanpcp: 0 parent interface: f-stack-0
when i set  port_conf.rxmode.hw_vlan_strip = 0, i'm sure data is go into vlan_input(struct ifnet *ifp, struct mbuf *m).

**Comment by whl739** [comment]
When set port_conf.rxmode.hw_vlan_strip = 0, it didn't work too?

**Comment by xg-king** [comment]
yes,when i set  port_conf.rxmode.hw_vlan_strip = 0 ,also can't ping 20.0.123.123.
 tomorrow i will add print to if_vlan.c to ensure out data 's vlan_flag and it's data.
because i'm sure in data's flag and vlan_header is right.

another why i set default gateway to 0.0.0.0 in port0, and start the start.sh .the programe print set default gateway fault.

**Comment by xg-king** [comment]
i know why i have this problem，because my secondary core‘s arp table is empty！
 i debug the code , primary has sync arp to secondary, but the data is changed when secondary core get .
primary  put:
ff ff ff ff ff ff c0 bf     c0 30 69 45 81 0 7 e4
8 6 0 1 8 0 6 4     0 1 69 bf c0 30 69 45
14 0 0 7a 0 0 0 0     0 0 69 0 7b 7b 0 0
0 0 0 0 0 0 0 0     0 0 69 0 0 0 0 0
secondary get:
ff ff ff ff ff ff ff ff     ff ff c0 bf c0 30 69 45
8 6 0 1 8 0 6 4     0 1 c0 bf c0 30 69 45
14 0 0 7a 0 0 0 0     0 0 14 0 0 7b 0 0
0 0 0 0 0 0 0 0     0 0 0 0 0 0 0 0

**Comment by xg-king** [comment]
i know why i have this problem，because my secondary core‘s arp table is empty！
i debug the code , primary has sync arp to secondary, but the data is changed when secondary core get .
sometimes  primary core put ring  != secondary core get ring.

**Comment by whl739** [comment]
> my vlan config:
./tools/ifconfig/ifconfig vlan2020 vlan 2020 vlandev f-stack-0
./tools/ifconfig/ifconfig vlan2020 20.0.123.123/16
./tools/ifconfig/ifconfig vlan2020 mtu 1500
./tools/ifconfig/ifconfig vlan2020 up

Is VLAN only configured on primary process? If it is, arps that synced to secondary cores will be dropped.

**Comment by xg-king** [comment]
-p 0 and -p 1  all configed.

**Comment by whl739** [comment]
> sometimes primary core put ring != secondary core get ring.

When enqueue ring, we will clone a mbuf, theire data addresses are pointed to the same buf_addr. This maybe the inequality you thought.
There must be other reasons for this issuse.

**Comment by xg-king** [comment]
i'm sure data has been modify.
when data in  "process_arp_ring" function in secondary core ,before "process_packets" i print data and in "process_packets" i also print data
as you last reply buf_addr is the same ,but data modified.
1、before "process_packets" print:
ifp=0xafbb40,data=0x7fffe1461fc0
c0 bf c0 30 69 57 c0 bf     c0 30 69 45 81 0 7 e4
8 6 0 1 8 0 6 4     0 2 c0 bf c0 30 69 45
14 0 0 7a c0 bf c0 30     69 57 14 0 0 7b 0 0
0 0 0 0 0 0 0 0     0 0 0 0 0 0 0 0
2、in "process_packets" print:
ifp=0x9fbb10,data=0x7fffe1461fc0
c0 bf c0 30 c0 bf c0 30     69 57 c0 bf c0 30 69 45
8 6 0 1 8 0 6 4     0 2 c0 bf c0 30 69 45
14 0 0 7a c0 bf c0 30     69 57 14 0 0 7b 0 0
0 0 0 0 0 0 0 0     0 0 0 0 0 0 0 0
from the print we can see the secondary and primary process have different ifp pointer and have the same data pointer . but same data ponter's content is not same !

**Comment by whl739** [comment]
Could you please continue to debug the primary process, and maybe it is modified by the primary process because of the same buf_addr.

**Comment by xg-king** [comment]
first i expand  MEMPOOL_CACHE_SIZE to 512 the result is the same .

sencond i only allow vlan 2020's packet can do arp process,and filter other packet . so there is no one to change buf_addr'data ,but the result is the same .

so i think maybe arp_ring's buf is different. and i add print like this in "process_packets" 
 if(mbuf_clone) {
	printf("primary:cons tail =%d, prod tail=%d,arp_ring=%p i=%d,port_id=%d\n",arp_ring[i][port_id]->cons.tail,arp_ring[i][port_id]->prod.tail,arp_ring[i][port_id],i,port_id);
          int ret = rte_ring_enqueue(arp_ring[i][port_id], mbuf_clone);
          if (ret < 0)
             rte_pktmbuf_free(mbuf_clone);
	printf("primary:cons tail =%d, prod tail=%d,arp_ring=%p i=%d,port_id=%d\n",arp_ring[i][port_id]->cons.tail,arp_ring[i][port_id]->prod.tail,arp_ring[i][port_id],i,port_id);
}
and add pint in “process_arp_ring”：
if(nb_rb > 0) {
        if (queue_id ==1){
        printf("secondary:cons tail =%d, prod tail=%d,arp_ring=%p\n,queue_id=%d,port_id=%d\n",arp_ring[i][port_id]->cons.tail,arp_ring[i][port_id]->prod.tail,arp_ring[queue_id][port_id],queue_id,port_id);
        }
        process_packets(port_id, queue_id, pkts_burst, nb_rb, ctx, 1);
    }

the result is：
primary:cons tail =13, prod tail=13,arp_ring=0x7fffd681c140 i=1,port_id=0
primary:cons tail =13, prod tail=14,arp_ring=0x7fffd681c140 i=1,port_id=0
secondary:cons tail =0, prod tail=0,arp_ring=0x7fffd681c140,queue_id=1,port_id=0
......
primary:cons tail =14, prod tail=14,arp_ring=0x7fffd681c140 i=1,port_id=0
primary:cons tail =14, prod tail=15,arp_ring=0x7fffd681c140 i=1,port_id=0
secondary:cons tail =0, prod tail=0,arp_ring=0x7fffd681c140,queue_id=1,port_id=0

why secondary’s arp_ring'add is the same, buf the add's producer tail is different,and secondary core's tail always be 0 ?

**Comment by xg-king** [comment]
i think   primary and sencodary must have different  buf_addr, but  must have the same  buf_physaddr.
so in sencodary  core we need to do map buf_physaddr to new addr ?
because now in anytime primary and sencodary core print the same  buf_addr data always different.

**Comment by xg-king** [comment]
i have get the reason, beacuse "rte_pktmbuf_clone" is same as "skb_clone",so the sencodary and primary has the same  buf_addr pointer , do not copy data .so when the primary code process data ,  buf_addr pointer's data can be changed  ,so when secondary get the buf_addr pointer'data and offset is changed . 
we set "port_conf.rxmode.hw_vlan_strip = 0".
