### ISSUE TITLE
How to reproduce RPS tests on cover page

### ISSUE THREAD

**Issue by ecofriendlygeek** [F-Stack/f-stack#539]
I am trying to reproduce the RPS tests on cover page.

1. Memory cached 600 bytes : Using return statement in nginx.conf gives a syntax error about unexpected statement. How to fix this ?
2. What is the client used ? Please give the scripts etc.

**Comment by jfb8856606** [comment]
Wether you set `FF_PATH` and `FF_DPDK` to correctly directly.

**Comment by ecofriendlygeek** [comment]
1. The error was due to wrong compilation option; I fixed it.
2. I have found some clients to run as benchmarks.

Closing the issue.
