### ISSUE TITLE
Is F-stack support reload without any packet dropped?

### ISSUE THREAD

**Issue by orange30** [F-Stack/f-stack#547]
https://github.com/F-Stack/f-stack/issues/12
 The url said the reload has been supported, but it drop a lot packets when reload!
 In production, the packet drop is not vary good. 
Is there a method which support reload without any packet dropped?
@whl739

**Comment by jfb8856606** [comment]
There is currently no good way to achieve it.

Unless you use soft distribution, all secondary worker don't bind the queue of NIC.

**Comment by orange30** [comment]
I am writing one version to support nginx reload.
1,It can work well on f-stack-1.20, and we can assign which cores is used to be rcv cores in f-stack.conf and nginx.conf.
2,When two processs is attached to the same core, it can renice the priority dynamically according the numbers of connections.
3,Because of the timer lib is changed in dpdk 19, my version cann't be work in new f-stack version. In dpdk 19, timer lib uses rte_memzone_reserve to apply global memory; in 18, it just be a static global variable in process.
4, There is also some other problems to solve and to discuss,  for example wrk has a little read errors.   If anyone has interest, we can discuss the problems together.
5,By the way, is there a WeChat Group  to discuss problems of f-stack? @jfb8856606 


There is some photos  to show the version：

Configure：4 cores as rcv core, 26 cores as nginx core.
![image](https://user-images.githubusercontent.com/44566632/97828245-7d57a200-1d01-11eb-8ad0-df80cdbd4c0f.png)
![image](https://user-images.githubusercontent.com/44566632/97828270-8f394500-1d01-11eb-8a5e-6fbff2abb869.png)

Before reload:
![image](https://user-images.githubusercontent.com/44566632/97828340-d0c9f000-1d01-11eb-8519-6998825abe19.png)

Make some HTTP persistent connections .

After reload:
![image](https://user-images.githubusercontent.com/44566632/97828375-e808dd80-1d01-11eb-95f2-129b322b8d7c.png)


The wrk's read error problem when reload:
![image](https://user-images.githubusercontent.com/44566632/97828728-eab80280-1d02-11eb-98f2-319d96111e3d.png)

**Comment by jfb8856606** [comment]
@orange30 Good job. You can search 'johnjfb' in WeChat, and I will add you to F-Stack's WeChat Group.

**Comment by orange30** [comment]
After solve some bugs，the changed version has support nginx reload without any packet dropped.

**Comment by ygm521** [comment]
@orange30 hello， f-stack reload，some questions asked,thanks! WeChat ygmdream

**Comment by RockGo** [comment]
@orange30 can you share the idea, WeChat RockGo56

**Comment by orange30** [comment]
<img width="1497" alt="1" src="https://user-images.githubusercontent.com/44566632/192769437-eeaf906c-bfb4-4bde-9243-ddb46d899ee9.png">
<img width="1474" alt="2" src="https://user-images.githubusercontent.com/44566632/192769455-a4dc0a02-75df-48fe-b8b4-89a16f96ed87.png">
<img width="1477" alt="3" src="https://user-images.githubusercontent.com/44566632/192769479-a21c057c-cd88-4dc8-a989-a6f02e520f03.png">
<img width="1468" alt="4" src="https://user-images.githubusercontent.com/44566632/192769506-171fad6b-3087-4f5d-917a-c33ff9d23610.png">
<img width="1473" alt="5" src="https://user-images.githubusercontent.com/44566632/192769546-23560f16-de15-4586-a559-d7a1a7cb9af3.png">
<img width="1474" alt="6" src="https://user-images.githubusercontent.com/44566632/192769562-672757a3-22c0-40ca-a5ce-f551b41a2cfa.png">
<img width="1472" alt="7" src="https://user-images.githubusercontent.com/44566632/192769577-0a007179-fb32-44a7-9139-bbb1d31800da.png">

**Comment by orange30** [comment]
@ygm521  @RockGo   for reference only.

<img width="1497" alt="1" src="https://user-images.githubusercontent.com/44566632/192770677-e8133078-a20c-44b7-9d3f-658e958e5970.png">
<img width="1474" alt="2" src="https://user-images.githubusercontent.com/44566632/192770687-fcf2df3b-72a2-4f33-bcd2-6c46a4b74b14.png">
<img width="1477" alt="3" src="https://user-images.githubusercontent.com/44566632/192770707-6d30b241-518f-478d-815c-7f6cd101314a.png">
<img width="1468" alt="4" src="https://user-images.githubusercontent.com/44566632/192770727-fe7e18d4-abc0-4c43-a882-5d4950c266c2.png">
<img width="1479" alt="5" src="https://user-images.githubusercontent.com/44566632/192770744-0de8fa99-9ffc-4e5f-8f79-89417128bef4.png">
<img width="1474" alt="6" src="https://user-images.githubusercontent.com/44566632/192770760-cc8c47eb-3e0c-4c8b-8b73-4585c916b8d0.png">
<img width="1472" alt="7" src="https://user-images.githubusercontent.com/44566632/192770772-06207d3b-e1f6-49a8-a077-99a082a47bc1.png">
