### ISSUE TITLE
Freebsd NAT can not run right!

### ISSUE THREAD

**Issue by yayays** [F-Stack/f-stack#557]
Hi, 
F-stack team. I try to use NAT fuction, but can not run. I bind two NICs, where one is connected to the Internet and the other is connected to the internal LAN. The IPFW configue is:
fstack-1 is internal LAN
fstack-0 is WAN

#!/bin/sh
ipfw -q -f flush
cmd="ipfw -q add"
skip="skipto 1000"
pif="fstack-0"
ks="keep-state"
good_tcpo="22,25,37,53,80,443,110"
$cmd 005 allow all from any to any via f-stack-1 # exclude LAN traffic
$cmd 010 allow all from any to any via lo0  # exclude loopback traffic
$cmd 099 reass all from any to any in       # reassemble inbound packets
$cmd 100 nat 1 ip from any to any in via $pif # NAT any inbound packets
$cmd 101 check-state

$cmd 125 $skip tcp from any to any $good_tcpo out via $pif setup $ks
$cmd 130 $skip all from any to any out via $pif $ks
$cmd 1000 nat 1 ip from any to any out via $pif # skipto location for outbound stateful rules
$cmd 1001 allow ip from any to any

In official handbook, the FreeBSD machine must act as a gateway ('gateway_enable="YES"' in rc.conf). How to configure "gateway_enable"?
Thanks!
![IN-KERNAL NAT](https://user-images.githubusercontent.com/11452640/98318545-c5d0d180-2019-11eb-94a7-503c082b3a24.png)

**Comment by jfb8856606** [comment]
see [IPFW](https://docs.freebsd.org/doc/11.0-RELEASE/usr/local/share/doc/freebsd/en/books/handbook/firewalls-ipfw.html) and [Gateways and Routes](https://docs.freebsd.org/doc/11.0-RELEASE/usr/local/share/doc/freebsd/en/books/handbook/network-routing.html)
To enable `net.inet.ip.forwarding` with `ff_sysctl` or config it in `config.ini`.

**Comment by yayays** [comment]
Thanks！

**Comment by lqVincent** [comment]
how to set `firewall_nat_enable="YES"` in f-stack, thanks!
