### ISSUE TITLE
Bug："set_rss_table" will failed when using 'rte_flow_isolate' for Flow Bifurcation

### ISSUE THREAD

**Issue by hawkxiang** [F-Stack/f-stack#561]
Flow Bifurcation：https://doc.dpdk.org/guides/howto/flow_bifurcation.html
背景：某些网卡(MLX5)支持分流模式，相比KNI来说，硬件驱动支持的分流性能高，并且不依赖DPDK进程本身进行流量转发。使用Flow Bifurcation需要使用'rte_flow_isolate'函数。

![image](https://user-images.githubusercontent.com/10736359/100094804-88cb6280-2e94-11eb-900c-1abf69836cf2.png)
Bug：f-stack启动DPDK的函数ff_dpdk_init，在多进程/多线程场景下，调用rte_flow_isolate时；init_port_start函数后续set_rss_table将会失败。其原因：rte_flow_isolate将会导致RSS失效；源码上分析设置RSS reta相关的函数指针被rte_flow_isolate置为NULL，set_rss_table调用出现失败。
![image](https://user-images.githubusercontent.com/10736359/100094841-97197e80-2e94-11eb-8bee-668857bc1cc4.png)

复现： 
1. 类似上图在ff_dpdk_init中开启rte_flow_isolate（需要在init_port_start前面）
2. 编译example
3. config.ini中的lcore_mask=3，开启多核
4. 运行example：`./example/helloworld --conf config.ini --proc-type=primary --proc-id=0`

标准输出将出现如下错误
![image](https://user-images.githubusercontent.com/10736359/100095007-d8119300-2e94-11eb-954f-51bf284a6681.png)

fix: #562

**Comment by jfb8856606** [comment]
F-Stack doesn't support other flow rules except RSS now. But we will support FDIR later.

I will merge the #562, but i can't test it on Mellanox ConnectX.

**Comment by hawkxiang** [comment]
> F-Stack doesn't support other flow rules except RSS now. But we will support FDIR later.
> 
> I will merge the #562, but i can't test it on Mellanox ConnectX.

I have implemented a RSS rule for all NIC devices. And test it in Intel NIC & Mellanox ConnectX. #563 is more general than the current **set_rss_table&rte_eth_dev_filter_supported**
你可以帮忙确认：
1. 这是否符合f-stack需要的FDIR。我觉得它可以代替目前的RSS table实现方面，并且使用了更通用的flow api进行实现。我测试了Intel、Mellanox ConnectX等网卡表现正常，CPU核心负载也均衡。
2. 这种实现方面，在Mellanox ConnectX网卡下，自动具备Flow Bifurcation特性。DPDK的tcp_port正常接收流量，其他数据包自动分流到内核协议栈，例如telnet 22正常；相比KNI方式性能更好。

**Comment by beef9999** [comment]
@hawkxiang @jfb8856606 

请问现在f-stack支持DPDK的Flow Bifurcation功能了吗？有没有例子

**Comment by jfb8856606** [comment]
You can enable the build argument in `lib/Makefile` and see code in `lib/ff_dpdk_if.c`
```
#FF_FLOW_ISOLATE=1
#FF_FDIR=1
```

发件人: Bob Chen ***@***.***>
发送时间: 2023年3月21日 14:58
收件人: F-Stack/f-stack ***@***.***>
抄送: fengbojiang(姜凤波) ***@***.***>; Mention ***@***.***>
主题: [Internet]Re: [F-Stack/f-stack] Bug："set_rss_table" will failed when using 'rte_flow_isolate' for Flow Bifurcation (#561)


@hawkxiang<https://github.com/hawkxiang> @jfb8856606<https://github.com/jfb8856606>

请问现在f-stack支持DPDK的Flow Bifurcation功能了吗？有没有例子
