### ISSUE TITLE
Running Hello World has some problems

### ISSUE THREAD

**Issue by strNewBee** [F-Stack/f-stack#573]
My OS is Ubuntu 16.04.3 running on a Intel Xeno Phi 7210 CPU with a 82599es NIC. I compiled the code and tried to run the hello world example with a following output.

```
syk@slave1:~/fstack/f-stack/example$ sudo ./helloworld --conf=../config.ini 
invalid proc_id:-1, use default 0
[dpdk]: lcore_mask=1
[dpdk]: channel=4
[dpdk]: promiscuous=1
[dpdk]: numa_on=1
[dpdk]: tx_csum_offoad_skip=0
[dpdk]: tso=0
[dpdk]: vlan_strip=1
[dpdk]: idle_sleep=0
[dpdk]: pkt_tx_delay=100
[dpdk]: symmetric_rss=0
[dpdk]: port_list=0
[dpdk]: nb_vdev=0
[dpdk]: nb_bond=0
[pcap]: enable=0
[pcap]: snaplen=96
[pcap]: savelen=16777216
[port0]: addr=192.168.1.2
[port0]: netmask=255.255.225.0
[port0]: broadcast=192.168.1.255
[port0]: gateway=192.168.1.1
[freebsd.boot]: hz=100
[freebsd.boot]: fd_reserve=1024
[freebsd.boot]: kern.ipc.maxsockets=262144
[freebsd.boot]: net.inet.tcp.syncache.hashsize=4096
[freebsd.boot]: net.inet.tcp.syncache.bucketlimit=100
[freebsd.boot]: net.inet.tcp.tcbhashsize=65536
[freebsd.boot]: kern.ncallout=262144
[freebsd.boot]: kern.features.inet6=1
[freebsd.boot]: net.inet6.ip6.auto_linklocal=1
[freebsd.boot]: net.inet6.ip6.accept_rtadv=2
[freebsd.boot]: net.inet6.icmp6.rediraccept=1
[freebsd.boot]: net.inet6.ip6.forwarding=0
[freebsd.sysctl]: kern.ipc.somaxconn=32768
[freebsd.sysctl]: kern.ipc.maxsockbuf=16777216
[freebsd.sysctl]: net.link.ether.inet.maxhold=5
[freebsd.sysctl]: net.inet.tcp.fast_finwait2_recycle=1
[freebsd.sysctl]: net.inet.tcp.sendspace=16384
[freebsd.sysctl]: net.inet.tcp.recvspace=8192
[freebsd.sysctl]: net.inet.tcp.cc.algorithm=cubic
[freebsd.sysctl]: net.inet.tcp.sendbuf_max=16777216
[freebsd.sysctl]: net.inet.tcp.recvbuf_max=16777216
[freebsd.sysctl]: net.inet.tcp.sendbuf_auto=1
[freebsd.sysctl]: net.inet.tcp.recvbuf_auto=1
[freebsd.sysctl]: net.inet.tcp.sendbuf_inc=16384
[freebsd.sysctl]: net.inet.tcp.recvbuf_inc=524288
[freebsd.sysctl]: net.inet.tcp.sack.enable=1
[freebsd.sysctl]: net.inet.tcp.blackhole=1
[freebsd.sysctl]: net.inet.tcp.msl=2000
[freebsd.sysctl]: net.inet.tcp.delayed_ack=0
[freebsd.sysctl]: net.inet.udp.blackhole=1
[freebsd.sysctl]: net.inet.ip.redirect=0
[freebsd.sysctl]: net.inet.ip.forwarding=0
EAL: Detected 128 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Auto-detected process type: PRIMARY
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
f-stack -c1 -n4 --proc-type=auto EAL: Probing VFIO support...
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:10fb net_ixgbe
EAL: PCI device 0000:01:00.1 on NUMA socket 0
EAL:   probe driver: 8086:10fb net_ixgbe
EAL: PCI device 0000:05:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1533 net_e1000_igb
EAL: PCI device 0000:06:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1533 net_e1000_igb
lcore: 0, port: 0, queue: 0
create mbuf pool on socket 0
create ring:dispatch_ring_p0_q0 success, 2047 ring entries are now free!
Port 0 MAC: 90 e2 ba 63 3d ec
Port 0 modified RSS hash function based on hardware support,requested:0x3ffffc configured:0x38d34
RX checksum offload supported
TX ip checksum offload supported
TX TCP&UDP checksum offload supported
TSO is disabled
port[0]: rss table size: 128
set port 0 to promiscuous mode ok

Checking link statusdone
Port 0 Link Up - speed 10000 Mbps - full-duplex
link_elf_lookup_symbol: missing symbol hash table
link_elf_lookup_symbol: missing symbol hash table
Timecounters tick every 10.000 msec
Timecounter "ff_clock" frequency 100 Hz quality 1
f-stack-0: No addr6 config found.
f-stack-0: Ethernet address: 90:e2:ba:63:3d:ec
Illegal instruction 
```
The ** Illegal instruction ** thing happened in testpmd of the dpdk coming with this project but fine with dpdk 20.08. Is it the old version of dpdk causing it? I'm new to DPDK, sorry if I'm bothering you with some silly question. Any help will be grateful.

**Comment by VitalHex** [comment]
I recompiled the dpdk but it's not working

**Comment by vipinpv85** [comment]
> My OS is Ubuntu 16.04.3 running on a Intel Xeno Phi 7210 CPU with a 82599es NIC. I compiled the code and tried to run the hello world example with a following output.
> 
> ```
> syk@slave1:~/fstack/f-stack/example$ sudo ./helloworld --conf=../config.ini 
> invalid proc_id:-1, use default 0
> [dpdk]: lcore_mask=1
> [dpdk]: channel=4
> [dpdk]: promiscuous=1
> [dpdk]: numa_on=1
> [dpdk]: tx_csum_offoad_skip=0
> [dpdk]: tso=0
> [dpdk]: vlan_strip=1
> [dpdk]: idle_sleep=0
> [dpdk]: pkt_tx_delay=100
> [dpdk]: symmetric_rss=0
> [dpdk]: port_list=0
> [dpdk]: nb_vdev=0
> [dpdk]: nb_bond=0
> [pcap]: enable=0
> [pcap]: snaplen=96
> [pcap]: savelen=16777216
> [port0]: addr=192.168.1.2
> [port0]: netmask=255.255.225.0
> [port0]: broadcast=192.168.1.255
> [port0]: gateway=192.168.1.1
> [freebsd.boot]: hz=100
> [freebsd.boot]: fd_reserve=1024
> [freebsd.boot]: kern.ipc.maxsockets=262144
> [freebsd.boot]: net.inet.tcp.syncache.hashsize=4096
> [freebsd.boot]: net.inet.tcp.syncache.bucketlimit=100
> [freebsd.boot]: net.inet.tcp.tcbhashsize=65536
> [freebsd.boot]: kern.ncallout=262144
> [freebsd.boot]: kern.features.inet6=1
> [freebsd.boot]: net.inet6.ip6.auto_linklocal=1
> [freebsd.boot]: net.inet6.ip6.accept_rtadv=2
> [freebsd.boot]: net.inet6.icmp6.rediraccept=1
> [freebsd.boot]: net.inet6.ip6.forwarding=0
> [freebsd.sysctl]: kern.ipc.somaxconn=32768
> [freebsd.sysctl]: kern.ipc.maxsockbuf=16777216
> [freebsd.sysctl]: net.link.ether.inet.maxhold=5
> [freebsd.sysctl]: net.inet.tcp.fast_finwait2_recycle=1
> [freebsd.sysctl]: net.inet.tcp.sendspace=16384
> [freebsd.sysctl]: net.inet.tcp.recvspace=8192
> [freebsd.sysctl]: net.inet.tcp.cc.algorithm=cubic
> [freebsd.sysctl]: net.inet.tcp.sendbuf_max=16777216
> [freebsd.sysctl]: net.inet.tcp.recvbuf_max=16777216
> [freebsd.sysctl]: net.inet.tcp.sendbuf_auto=1
> [freebsd.sysctl]: net.inet.tcp.recvbuf_auto=1
> [freebsd.sysctl]: net.inet.tcp.sendbuf_inc=16384
> [freebsd.sysctl]: net.inet.tcp.recvbuf_inc=524288
> [freebsd.sysctl]: net.inet.tcp.sack.enable=1
> [freebsd.sysctl]: net.inet.tcp.blackhole=1
> [freebsd.sysctl]: net.inet.tcp.msl=2000
> [freebsd.sysctl]: net.inet.tcp.delayed_ack=0
> [freebsd.sysctl]: net.inet.udp.blackhole=1
> [freebsd.sysctl]: net.inet.ip.redirect=0
> [freebsd.sysctl]: net.inet.ip.forwarding=0
> EAL: Detected 128 lcore(s)
> EAL: Detected 1 NUMA nodes
> EAL: Auto-detected process type: PRIMARY
> EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
> EAL: Selected IOVA mode 'PA'
> EAL: No available hugepages reported in hugepages-1048576kB
> f-stack -c1 -n4 --proc-type=auto EAL: Probing VFIO support...
> EAL: PCI device 0000:01:00.0 on NUMA socket 0
> EAL:   probe driver: 8086:10fb net_ixgbe
> EAL: PCI device 0000:01:00.1 on NUMA socket 0
> EAL:   probe driver: 8086:10fb net_ixgbe
> EAL: PCI device 0000:05:00.0 on NUMA socket 0
> EAL:   probe driver: 8086:1533 net_e1000_igb
> EAL: PCI device 0000:06:00.0 on NUMA socket 0
> EAL:   probe driver: 8086:1533 net_e1000_igb
> lcore: 0, port: 0, queue: 0
> create mbuf pool on socket 0
> create ring:dispatch_ring_p0_q0 success, 2047 ring entries are now free!
> Port 0 MAC: 90 e2 ba 63 3d ec
> Port 0 modified RSS hash function based on hardware support,requested:0x3ffffc configured:0x38d34
> RX checksum offload supported
> TX ip checksum offload supported
> TX TCP&UDP checksum offload supported
> TSO is disabled
> port[0]: rss table size: 128
> set port 0 to promiscuous mode ok
> 
> Checking link statusdone
> Port 0 Link Up - speed 10000 Mbps - full-duplex
> link_elf_lookup_symbol: missing symbol hash table
> link_elf_lookup_symbol: missing symbol hash table
> Timecounters tick every 10.000 msec
> Timecounter "ff_clock" frequency 100 Hz quality 1
> f-stack-0: No addr6 config found.
> f-stack-0: Ethernet address: 90:e2:ba:63:3d:ec
> Illegal instruction 
> ```
> 
> The ** Illegal instruction ** thing happened in testpmd of the dpdk coming with this project but fine with dpdk 20.08. Is it the old version of dpdk causing it? I'm new to DPDK, sorry if I'm bothering you with some silly question. Any help will be grateful.

I noticed similar question in stackoverflow (which is removed now). Did you get a chance to run GDB to figure out which instruction is causing the issue?

**Comment by VitalHex** [comment]
> > My OS is Ubuntu 16.04.3 running on a Intel Xeno Phi 7210 CPU with a 82599es NIC. I compiled the code and tried to run the hello world example with a following output.
> > ```
> > syk@slave1:~/fstack/f-stack/example$ sudo ./helloworld --conf=../config.ini 
> > invalid proc_id:-1, use default 0
> > [dpdk]: lcore_mask=1
> > [dpdk]: channel=4
> > [dpdk]: promiscuous=1
> > [dpdk]: numa_on=1
> > [dpdk]: tx_csum_offoad_skip=0
> > [dpdk]: tso=0
> > [dpdk]: vlan_strip=1
> > [dpdk]: idle_sleep=0
> > [dpdk]: pkt_tx_delay=100
> > [dpdk]: symmetric_rss=0
> > [dpdk]: port_list=0
> > [dpdk]: nb_vdev=0
> > [dpdk]: nb_bond=0
> > [pcap]: enable=0
> > [pcap]: snaplen=96
> > [pcap]: savelen=16777216
> > [port0]: addr=192.168.1.2
> > [port0]: netmask=255.255.225.0
> > [port0]: broadcast=192.168.1.255
> > [port0]: gateway=192.168.1.1
> > [freebsd.boot]: hz=100
> > [freebsd.boot]: fd_reserve=1024
> > [freebsd.boot]: kern.ipc.maxsockets=262144
> > [freebsd.boot]: net.inet.tcp.syncache.hashsize=4096
> > [freebsd.boot]: net.inet.tcp.syncache.bucketlimit=100
> > [freebsd.boot]: net.inet.tcp.tcbhashsize=65536
> > [freebsd.boot]: kern.ncallout=262144
> > [freebsd.boot]: kern.features.inet6=1
> > [freebsd.boot]: net.inet6.ip6.auto_linklocal=1
> > [freebsd.boot]: net.inet6.ip6.accept_rtadv=2
> > [freebsd.boot]: net.inet6.icmp6.rediraccept=1
> > [freebsd.boot]: net.inet6.ip6.forwarding=0
> > [freebsd.sysctl]: kern.ipc.somaxconn=32768
> > [freebsd.sysctl]: kern.ipc.maxsockbuf=16777216
> > [freebsd.sysctl]: net.link.ether.inet.maxhold=5
> > [freebsd.sysctl]: net.inet.tcp.fast_finwait2_recycle=1
> > [freebsd.sysctl]: net.inet.tcp.sendspace=16384
> > [freebsd.sysctl]: net.inet.tcp.recvspace=8192
> > [freebsd.sysctl]: net.inet.tcp.cc.algorithm=cubic
> > [freebsd.sysctl]: net.inet.tcp.sendbuf_max=16777216
> > [freebsd.sysctl]: net.inet.tcp.recvbuf_max=16777216
> > [freebsd.sysctl]: net.inet.tcp.sendbuf_auto=1
> > [freebsd.sysctl]: net.inet.tcp.recvbuf_auto=1
> > [freebsd.sysctl]: net.inet.tcp.sendbuf_inc=16384
> > [freebsd.sysctl]: net.inet.tcp.recvbuf_inc=524288
> > [freebsd.sysctl]: net.inet.tcp.sack.enable=1
> > [freebsd.sysctl]: net.inet.tcp.blackhole=1
> > [freebsd.sysctl]: net.inet.tcp.msl=2000
> > [freebsd.sysctl]: net.inet.tcp.delayed_ack=0
> > [freebsd.sysctl]: net.inet.udp.blackhole=1
> > [freebsd.sysctl]: net.inet.ip.redirect=0
> > [freebsd.sysctl]: net.inet.ip.forwarding=0
> > EAL: Detected 128 lcore(s)
> > EAL: Detected 1 NUMA nodes
> > EAL: Auto-detected process type: PRIMARY
> > EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
> > EAL: Selected IOVA mode 'PA'
> > EAL: No available hugepages reported in hugepages-1048576kB
> > f-stack -c1 -n4 --proc-type=auto EAL: Probing VFIO support...
> > EAL: PCI device 0000:01:00.0 on NUMA socket 0
> > EAL:   probe driver: 8086:10fb net_ixgbe
> > EAL: PCI device 0000:01:00.1 on NUMA socket 0
> > EAL:   probe driver: 8086:10fb net_ixgbe
> > EAL: PCI device 0000:05:00.0 on NUMA socket 0
> > EAL:   probe driver: 8086:1533 net_e1000_igb
> > EAL: PCI device 0000:06:00.0 on NUMA socket 0
> > EAL:   probe driver: 8086:1533 net_e1000_igb
> > lcore: 0, port: 0, queue: 0
> > create mbuf pool on socket 0
> > create ring:dispatch_ring_p0_q0 success, 2047 ring entries are now free!
> > Port 0 MAC: 90 e2 ba 63 3d ec
> > Port 0 modified RSS hash function based on hardware support,requested:0x3ffffc configured:0x38d34
> > RX checksum offload supported
> > TX ip checksum offload supported
> > TX TCP&UDP checksum offload supported
> > TSO is disabled
> > port[0]: rss table size: 128
> > set port 0 to promiscuous mode ok
> > 
> > Checking link statusdone
> > Port 0 Link Up - speed 10000 Mbps - full-duplex
> > link_elf_lookup_symbol: missing symbol hash table
> > link_elf_lookup_symbol: missing symbol hash table
> > Timecounters tick every 10.000 msec
> > Timecounter "ff_clock" frequency 100 Hz quality 1
> > f-stack-0: No addr6 config found.
> > f-stack-0: Ethernet address: 90:e2:ba:63:3d:ec
> > Illegal instruction 
> > ```
> > 
> > 
> > The ** Illegal instruction ** thing happened in testpmd of the dpdk coming with this project but fine with dpdk 20.08. Is it the old version of dpdk causing it? I'm new to DPDK, sorry if I'm bothering you with some silly question. Any help will be grateful.
> 
> I noticed similar question in stackoverflow (which is removed now). Did you get a chance to run GDB to figure out which instruction is causing the issue?

Yeah, that was me. I removed the question because it was caused by someone else who shared the same platform with me due to wrong configuration. I'll close this issue since it has been solved. Sorry for this late reply.

**Comment by vipinpv85** [comment]
thanks for the updae, can you share what was the configuration issue?
