### ISSUE TITLE
nox86_64-native-linuxapp-gcc after compiling dpdk by meson

### ISSUE THREAD

**Issue by tresaresa** [F-Stack/f-stack#576]
just as mentioned in the title, i cannot execute following commands without /data/f-stack/dpdk/x86_64-native-linuxapp-gcc
```
insmod /data/f-stack/dpdk/x86_64-native-linuxapp-gcc/kmod/igb_uio.ko
insmod /data/f-stack/dpdk/x86_64-native-linuxapp-gcc/kmod/rte_kni.ko carrier=on # carrier=on is necessary, otherwise need to be up `veth0` via `echo 1 > /sys/class/net/veth0/carrier
```

**Comment by jfb8856606** [comment]
It will be fixed within 2 days, and before it, see [Test DPDK based on igb_uio](http://doc.dpdk.org/dts/gsg/support_igb_uio.html)
