### ISSUE TITLE
Low performance (Throughput) for reverse Iperf 

### ISSUE THREAD

**Issue by daneshzg** [F-Stack/f-stack#580]
Hi,
I am trying to use F-stack+Nginx on two VMs. Topology is as below:
Iperf Server on VM1 running F-Stack(192.168.1.2) + Nginx to proxy between Kernel localhost and the F-stack
Iperf Client on VM2 (192.168.1.10)

{Iperf Server(127.0.0.1)}<-----Nginx----->{F-stack(192.168.1.2)}<------->{Iperf Client(192.168.1.10)}

Nginx Configuration:

```
fstack_conf f-stack.conf;

events {
worker_connections 768;
use kqueue;

}

stream 
{
	upstream iperf_Forward
	      {
	      server 127.0.0.1:10002;
	      }
	server 
	      {
	      listen 10001;
	      proxy_kernel_network_stack on;
	      proxy_pass iperf_Forward;
	      }

	upstream iperf_Reverse
	        {
	        server 192.168.1.10:10005;
	        }
	server 
	        {
	        listen 10005;
	        kernel_network_stack on;
	        proxy_pass iperf_Reverse;
	        }
}
```

F-stack config:
```
[port0]
addr=192.168.1.2
netmask=255.255.255.0
broadcast=192.168.1.255
gateway=0.0.0.0
```

when the Server downloads from the client the throughput is around **3Gbps**
but in **_Reverse_** mode (Client downloads from the Server) the throughput is less than **10Mbps**

Server Snapshot:
![image](https://user-images.githubusercontent.com/78939253/107716080-e4a5ca80-6cd0-11eb-876c-aa970f615338.png)

Client Snapshot:
![image](https://user-images.githubusercontent.com/78939253/107750285-1db75c80-6d1c-11eb-9187-4c3b99e259bc.png)

Do you have any ideas regarding this issue?
Thanks.

**Comment by daneshzg** [comment]
It was the problem of the default interval for polling kernel_network_stack. 
The default value is 30 msec. Changed it to 0 and problem solved.
    Syntax: schedule_timeout time;
    Default: schedule_timeout 30ms;
    Context: main

**Comment by mulhome-com** [comment]
@daneshzg Your environment is great. 
I run the iperf which installed by yum tool in the local host with command : iperf -s
and start fstack nginx with configure
stream {
  upstream iperf_forward {
    server 127.0.0.1:5001;
  }
  server {
    listen 5001;
    proxy_pass iperf_forward;
    proxy_kernel_network_stack on;
  }
}

But in the client console, get the error message **connect failed** after running command:  iperf -c 192.168.1.2
So  how to fix this situation ? Thanks.

**Comment by mulhome-com** [comment]
After annoationing kni in f-stack.conf it worked.
thank you all.
