### ISSUE TITLE
example/helloworld doesn't work:No probed ethernet devices

### ISSUE THREAD

**Issue by yeliauk** [F-Stack/f-stack#581]
运行helloworld，情况如下：
root@ubuntu:/data/f-stack/example# ./helloworld --conf /etc/f-stack.conf --proc-type=primary --proc-id=0
[dpdk]: lcore_mask=1
[dpdk]: channel=4
[dpdk]: promiscuous=1
[dpdk]: numa_on=1
[dpdk]: tso=0
[dpdk]: vlan_strip=1
[dpdk]: idle_sleep=0
[dpdk]: pkt_tx_delay=100
[dpdk]: port_list=0
[dpdk]: nb_vdev=0
[port0]: addr=192.168.88.129
[port0]: netmask=255.255.255.0
[port0]: broadcast=192.168.88.255
[port0]: gateway=192.168.88.1
[freebsd.boot]: hz=100
[freebsd.boot]: fd_reserve=1024
[freebsd.boot]: kern.ipc.maxsockets=262144
[freebsd.boot]: net.inet.tcp.syncache.hashsize=4096
[freebsd.boot]: net.inet.tcp.syncache.bucketlimit=100
[freebsd.boot]: net.inet.tcp.tcbhashsize=65536
[freebsd.boot]: kern.ncallout=262144
[freebsd.sysctl]: kern.ipc.somaxconn=32768
[freebsd.sysctl]: kern.ipc.maxsockbuf=16777216
[freebsd.sysctl]: net.link.ether.inet.maxhold=5
[freebsd.sysctl]: net.inet.tcp.fast_finwait2_recycle=1
[freebsd.sysctl]: net.inet.tcp.sendspace=16384
[freebsd.sysctl]: net.inet.tcp.recvspace=8192
[freebsd.sysctl]: net.inet.tcp.nolocaltimewait=1
[freebsd.sysctl]: net.inet.tcp.cc.algorithm=cubic
[freebsd.sysctl]: net.inet.tcp.sendbuf_max=16777216
[freebsd.sysctl]: net.inet.tcp.recvbuf_max=16777216
[freebsd.sysctl]: net.inet.tcp.sendbuf_auto=1
[freebsd.sysctl]: net.inet.tcp.recvbuf_auto=1
[freebsd.sysctl]: net.inet.tcp.sendbuf_inc=16384
[freebsd.sysctl]: net.inet.tcp.recvbuf_inc=524288
[freebsd.sysctl]: net.inet.tcp.sack.enable=1
[freebsd.sysctl]: net.inet.tcp.blackhole=1
[freebsd.sysctl]: net.inet.tcp.msl=2000
[freebsd.sysctl]: net.inet.tcp.delayed_ack=0
[freebsd.sysctl]: net.inet.udp.blackhole=1
[freebsd.sysctl]: net.inet.ip.redirect=0
EAL: Detected 1 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
f-stack -c1 -n4 --proc-type=primary EAL: Probing VFIO support...
EAL: PCI device 0000:02:01.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:100f net_e1000_em
EAL: PCI device 0000:02:06.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:100f net_e1000_em
em_hw_init(): PHY Initialization Error
eth_em_dev_init(): port_id 0 vendorID=0x8086 deviceID=0x100f: failed to init HW
EAL: Requested device 0000:02:06.0 cannot be used
EAL: Error - exiting with code: 1
  Cause: No probed ethernet devices

查看网卡信息，如下：
root@ubuntu:/data/f-stack/dpdk# python usertools/dpdk-devbind.py --status

Network devices using DPDK-compatible driver
0000:02:06.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' drv=igb_uio unused=e1000

Network devices using kernel driver
0000:02:01.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' if=ens33 drv=e1000 unused=igb_uio *Active*

No 'Crypto' devices detected

No 'Eventdev' devices detected

No 'Mempool' devices detected

No 'Compress' devices detected

不知道如何解决这个问题，特来请教

**Comment by jfb8856606** [comment]
See `Upgrade pkg-config while version < 0.28`  and [Compile dpdk in virtual machine](https://github.com/F-Stack/f-stack/blob/dev/doc/F-Stack_Build_Guide.md#compile-dpdk-in-virtual-machine) sections in [build guide](https://github.com/F-Stack/f-stack/blob/dev/doc/F-Stack_Build_Guide.md) doc.
