### ISSUE TITLE
how to fix "recompile with -fPIC" while linking fstack to other projects?

### ISSUE THREAD

**Issue by liangchen527** [F-Stack/f-stack#582]
Hi all

I'm using fstack to modify an existing project. One building step of the existing project is to make a .so library which is dependent on fstack.a. Unfortunately, I got **ERROR MSG 1**. I tried to execute ```export CFLAGS="-fPIC $CFLAGS"``` and ```export CXXFLAGS=" -fPIC $CXXFLAGS"``` before recompiling both dpdk and fstack libraries but things didn't work correctly. I don't know whether I added the option in a right way. 
By the way, it comes to me that maybe I could link the object files to my project directly. But I'm not sure if this could solve the "recompile with -fPIC" problem and how to  link these objs with cmake (my project uses cmake).

PS: my fstack code is the master branch

Appreciate for any help!

**ERROR MSG 1**
```
/usr/bin/ld: /usr/local/lib/libfstack/libfstack.a.1.21(libfstack.ro): relocation R_X86_64_TPOFF32 against `pcurthread' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_bus_dpaa.a(dpaa_bus.o): relocation R_X86_64_TPOFF32 against symbol `per_lcore_dpaa_io' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_bus_dpaa.a(bman.o): relocation R_X86_64_TPOFF32 against `per_lcore_bman_affine_portal' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_bus_dpaa.a(bman_driver.o): relocation R_X86_64_TPOFF32 against `bmfd' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_bus_dpaa.a(qman.o): relocation R_X86_64_TPOFF32 against `per_lcore_qman_affine_portal' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_bus_dpaa.a(qman_driver.o): relocation R_X86_64_TPOFF32 against `qmfd' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_bus_fslmc.a(dpaa2_hw_dpio.o): relocation R_X86_64_TPOFF32 against symbol `per_lcore__dpaa2_io' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_bus_vdev.a(vdev.o): relocation R_X86_64_TPOFF32 against `per_lcore__thread_id.5396' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_eal.a(eal_thread.o): relocation R_X86_64_TPOFF32 against `per_lcore__thread_id.8400' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_eal.a(eal_vfio.o): relocation R_X86_64_TPOFF32 against `per_lcore__thread_id.8947' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_eal.a(eal_interrupts.o): relocation R_X86_64_TPOFF32 against `per_lcore__epfd' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_eal.a(eal_common_log.o): relocation R_X86_64_TPOFF32 against `per_lcore_log_cur_msg' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_eal.a(eal_common_errno.o): relocation R_X86_64_TPOFF32 against `per_lcore_retval.4583' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_pmd_dpaa_sec.a(dpaa_sec.o): relocation R_X86_64_TPOFF32 against `dpaa_sec_op_nb' can not be used when making a shared object; recompile with -fPIC
```

update:
I tried to add the option in the Makefile of fstack, and now the error message comes to be as follows. dpdk is still not built with -fPIC successfully, since I don't know which file to modify.
```
/usr/bin/ld: /usr/local/lib/librte_bus_dpaa.a(dpaa_bus.o): relocation R_X86_64_TPOFF32 against symbol `per_lcore_dpaa_io' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_bus_dpaa.a(bman.o): relocation R_X86_64_TPOFF32 against `per_lcore_bman_affine_portal' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_bus_dpaa.a(bman_driver.o): relocation R_X86_64_TPOFF32 against `bmfd' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_bus_dpaa.a(qman.o): relocation R_X86_64_TPOFF32 against `per_lcore_qman_affine_portal' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_bus_dpaa.a(qman_driver.o): relocation R_X86_64_TPOFF32 against `qmfd' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_bus_fslmc.a(dpaa2_hw_dpio.o): relocation R_X86_64_TPOFF32 against symbol `per_lcore__dpaa2_io' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_bus_vdev.a(vdev.o): relocation R_X86_64_TPOFF32 against `per_lcore__thread_id.5396' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_eal.a(eal_thread.o): relocation R_X86_64_TPOFF32 against `per_lcore__thread_id.8400' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_eal.a(eal_vfio.o): relocation R_X86_64_TPOFF32 against `per_lcore__thread_id.8947' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_eal.a(eal_interrupts.o): relocation R_X86_64_TPOFF32 against `per_lcore__epfd' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_eal.a(eal_common_log.o): relocation R_X86_64_TPOFF32 against `per_lcore_log_cur_msg' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_eal.a(eal_common_errno.o): relocation R_X86_64_TPOFF32 against `per_lcore_retval.4583' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/librte_pmd_dpaa_sec.a(dpaa_sec.o): relocation R_X86_64_TPOFF32 against `dpaa_sec_op_nb' can not be used when making a shared object; recompile with -fPIC
```

**Comment by jfb8856606** [comment]
F-Stack does not provide a way to compile dynamic libraries, and you need to solve the problem yourself.

About DPDK compilation issues, you can find documentation in dpdk.org, or just search `DPDK .so` use Google.

**Comment by rasaoskuei** [comment]
Hi all!
I have the same issue with using f-stack. but I have got the error message "recompile with -fPIC" only for `libfstack.a`.

Error message:
```
/usr/bin/ld: //usr/local/lib/libfstack.a(libfstack.ro): relocation R_X86_64_TPOFF32 against `pcurthread' can not be used when making a shared object; recompile with -fPIC
```

@liangchen527 how did you solve the problem for `libfstack.a`? I added `-fPIC -fpic` flags to `CFLAGS` and `HOST_CFLAGS`  in fstack Makefile (fstack/lib/Makefile) but the same error was produced.

**Comment by zhaoqikun321** [comment]
Hi all!
I have the same issue with using f-stack. 

How did you solve this problem in the end?

**Comment by rasaoskuei** [comment]
Hi everyone!
You couldn't dynamically link fstack, it should be linked statically.
The main point is `--whole-archive` flag. You should add all `.a` files as a `whole-archive` in one parameter to linker arguments:

link_args = [ `arg_1`, `arg_2`, ... , `-Wl,--whole-archive,-l:librte_common_cpt.a,-l:librte_common_dpaax.a,...,--no-whole-archive`, `arg_k` ]

**Comment by segment11** [comment]
I compile so, change Makefile three contents: 

INCLUDES+= -I./opt -fPIC

HOST_C= ${CC} -c -fPIC $(HOST_CFLAGS)

        #ar -cqs $@ $*.ro ${HOST_OBJS}
        ${CC} -shared -o libfstack.so $*.ro -fPIC ${HOST_OBJS} $(shell $(PKGCONF) --libs libdpdk) -lrte_net_bond -lcrypto

**Comment by stl0601** [comment]
Has the problem been resolved? How to solve it

**Comment by heatheart3** [comment]
> I compile so, change Makefile three contents:
> 
> INCLUDES+= -I./opt -fPIC
> 
> HOST_C= C C − c − f P I C (HOST_CFLAGS)
> 
> ```
>     #ar -cqs $@ $*.ro ${HOST_OBJS}
>     ${CC} -shared -o libfstack.so $*.ro -fPIC ${HOST_OBJS} $(shell $(PKGCONF) --libs libdpdk) -lrte_net_bond -lcrypto
> ```

Thanks a lot, it works! Please allow me to show more details of this solution for others needs help. 
Three lines in f-stack/lib/Makefile should be modifed. 
 ```
HOST_C= ${CC} -c $(HOST_CFLAGS) ${HOST_INCLUDES} ${WERROR} ${PROF} $<
...
INCLUDES+= -I./opt
...
ar -cqs $@ $*.ro ${HOST_OBJS}
```
Find these line and change them into below lines.
```
HOST_C= ${CC} -c -fPIC $(HOST_CFLAGS) ${HOST_INCLUDES} ${WERROR} ${PROF} $<
...
INCLUDES+= -I./opt -fPIC
...
# ar -cqs $@ $*.ro ${HOST_OBJS}
${CC} -shared -o libfstack.so $*.ro -fPIC ${HOST_OBJS} $(shell $(PKGCONF) --libs libdpdk) -lrte_net_bond -lcrypto
```
The line "ar -cqs \$@ \$\*.ro ${HOST_OBJS}" should be deleted and add a line "\${CC} -shared -o libfstack.so \$\*ro -fPIC 
 \$ {HOST_OBJS} \$ (shell \$(PKGCONF) --libs libdpdk) -lrte_net_bond -lcrypto" to compile a .so file.

**Comment by wkgcass** [comment]
If anyone wants a solution,  
Simply adding these lines would be enough I think:

```
HOST_CFLAGS+= -fPIC
CFLAGS+= -fPIC
```

**Comment by wkgcass** [comment]
> If anyone wants a solution, Simply adding these lines would be enough I think:
> 
> ```
> HOST_CFLAGS+= -fPIC
> CFLAGS+= -fPIC
> ```

add them anywhere before `HOST_C= ${CC} -c $(HOST_CFLAGS) ${HOST_INCLUDES} ${WERROR} ${PROF} $<` would be enough
