### ISSUE TITLE
how to run server and client on same machine

### ISSUE THREAD

**Issue by tresaresa** [F-Stack/f-stack#584]
Hi all

I want to run server and client (both developed with f-stack) on the same machine, but got the following error when starting the client program. Is there any way to configure fstack to use different dpdk config file for different programs?

```
EAL: Detected 8 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Cannot create lock on '/var/run/dpdk/rte/config'. Is another primary process running?
EAL: FATAL: Cannot init config
EAL: Cannot init config
EAL: Error - exiting with code: 1
  Cause: Error with EAL initialization
```

Besides, I called ff_init() in the following way in both of server and client. And I didn't edit anything in /etc/f-stack.conf.

```
char arg1_str[] = "/usr/local/mysql/bin/mysqld";
  char * const arg1 = arg1_str;
  char arg2_str[] = "--conf";
  char * const arg2 = arg2_str;
  char arg3_str[] = "/etc/f-stack.conf";
  char * const arg3 = arg3_str;
  char arg4_str[] = "--proc-type=primary";
  char * const arg4 = arg4_str;
  char arg5_str[] = "--proc-id=0";
  char * const arg5 = arg5_str;
  char * const my_argv[5] = {arg1, arg2, arg3, arg4, arg5};
  ff_init(5, my_argv);
```

Thanks a lot!!!

**Comment by jfb8856606** [comment]
No, you can't run F-Stack app like this, You should run server and client in different machine use default code and config.ini.

Or you can find some information from dpdk.org, such as https://doc.dpdk.org/guides/prog_guide/multi_proc_support.html or http://doc.dpdk.org/guides/sample_app_ug/multi_process.html, and do some modify in F-Stack's config.ini or/and code yourself.
