### ISSUE TITLE
SIFTR integration 

### ISSUE THREAD

**Issue by daneshzg** [F-Stack/f-stack#590]
Dears,
I tried the[ patch in here](https://github.com/F-Stack/f-stack/issues/193), and configured F-Stack to report into a file. The file is being created, but it's always empty.
I tried the hello world as well, it prints that it's going to report SIFTR, again the file is empty.
Do you have any updates in this regard or any other solution to collect the TCP stats like ss_thresh, window size,... without affecting the performance?

Your help is really appreciated.
Many thanks.

![image](https://user-images.githubusercontent.com/78939253/113271749-23243280-92db-11eb-8076-89404dab94aa.png)

![image](https://user-images.githubusercontent.com/78939253/113271672-10a9f900-92db-11eb-9dd5-8d23ae96e850.png)

**Comment by kmacy** [comment]
The original author of SIFTR was surprised to hear that anyone is trying to use it still. The general consensus is to use ebpf / dtrace. I doubt it would be difficult to add new macros around the networking stack's dtrace probes to convert them to standard USDT probes.

**Comment by daneshzg** [comment]
@kmacy Thanks for your suggestion. I'll give it a try.
BTW, I could solve the issue with SIFTR, this line of the patch is not necessary, so keep `siftr_enabled = 0`

`-static unsigned int siftr_enabled = 0;`
`+static unsigned int siftr_enabled = 1;`
