### ISSUE TITLE
Potential error(e.g., resource leak, deadlock) due to the unreleased lock pdata->i2c_mutex

### ISSUE THREAD

**Issue by jenny-cheung** [F-Stack/f-stack#605]
Hi, developers, thank you for your checking. The lock &pdata->i2c_mutex may not be correctly released if the ret==1 and control flow goes to these two branches listed below.  Finally, the method returns with the unreleased lock.  The fix is to insert pthread_mutex_unlock(&pdata->i2c_mutex); before returning.

https://github.com/F-Stack/f-stack/blob/39f53b9b66e00fb9a794fb368b4856e6634b8729/dpdk/drivers/net/axgbe/axgbe_i2c.c#L232

https://github.com/F-Stack/f-stack/blob/39f53b9b66e00fb9a794fb368b4856e6634b8729/dpdk/drivers/net/axgbe/axgbe_i2c.c#L234

https://github.com/F-Stack/f-stack/blob/39f53b9b66e00fb9a794fb368b4856e6634b8729/dpdk/drivers/net/axgbe/axgbe_i2c.c#L250

```
static int axgbe_i2c_xfer(struct axgbe_port *pdata, struct axgbe_i2c_op *op)
{
	...;
	pthread_mutex_lock(&pdata->i2c_mutex);
	ret = axgbe_i2c_disable(pdata);
	if (ret) {
		PMD_DRV_LOG(ERR, "failed to disable i2c master\n");
		return ret; // the method returns with unreleased lock
	}

	...;
	ret = axgbe_i2c_enable(pdata);
	if (ret) {
		PMD_DRV_LOG(ERR, "failed to enable i2c master\n");
		return ret; // the method returns with unreleased lock
	}

	...;
}
```

Best,

**Comment by freak82** [comment]
It seems to me that these issues are in the DPDK code.
Maybe they should be reported to the [DPDK developpers](https://www.dpdk.org/contribute/#mailing-lists)?

**Comment by jenny-cheung** [comment]
@freak82 OK, I will report these to DPDK. Could you also check for these? Thank you for the help!!!

**Comment by jfb8856606** [comment]
F-Stack will follow the DPDK's version, If anyone has encountered this problem, they can fix it in advance.

**Comment by jenny-cheung** [comment]
It has been confirmed by the upstream as a true bug. Would be fixed soon.
