### ISSUE TITLE
Potential error(e.g., resource leak, deadlock) due to the unreleased lock sh->txpp.mutex

### ISSUE THREAD

**Issue by jenny-cheung** [F-Stack/f-stack#606]
Hi, developers, thank you for your checking. The lock `sh->txpp.mutex` may not be correctly released if the` !sh->txpp.refcnt || --sh->txpp.refcnt` is true and control flow goes to the branch listed below.  Finally, the method returns with the unreleased lock.   The fix is to insert pthread_mutex_unlock(&sh->txpp.mutex);  before returning.

https://github.com/F-Stack/f-stack/blob/39f53b9b66e00fb9a794fb368b4856e6634b8729/dpdk/drivers/net/mlx5/mlx5_txpp.c#L1101

https://github.com/F-Stack/f-stack/blob/39f53b9b66e00fb9a794fb368b4856e6634b8729/dpdk/drivers/net/mlx5/mlx5_txpp.c#L1105

```
void
mlx5_txpp_stop(struct rte_eth_dev *dev)
{
	struct mlx5_priv *priv = dev->data->dev_private;
	struct mlx5_dev_ctx_shared *sh = priv->sh;
	int ret;

	if (!priv->txpp_en) {
		/* Packet pacing is already disabled for the device. */
		return;
	}
	priv->txpp_en = 0;
	ret = pthread_mutex_lock(&sh->txpp.mutex);
	MLX5_ASSERT(!ret);
	RTE_SET_USED(ret);
	MLX5_ASSERT(sh->txpp.refcnt);
	if (!sh->txpp.refcnt || --sh->txpp.refcnt)
		return; // the method returns with unreleased lock
	/* No references any more, do actual destroy. */
	mlx5_txpp_destroy(sh);
	ret = pthread_mutex_unlock(&sh->txpp.mutex);
	MLX5_ASSERT(!ret);
	RTE_SET_USED(ret);
}
```

Best,

**Comment by jfb8856606** [comment]
See #605.

**Comment by jenny-cheung** [comment]
It has been confirmed by the upstream as a true bug. Would be fixed soon.
