### ISSUE TITLE
Potential error(e.g., resource leak, deadlock) due to the unreleased lock pdata->phy_mutex

### ISSUE THREAD

**Issue by jenny-cheung** [F-Stack/f-stack#607]
Hi, developers, thank you for your checking. The lock `pdata->phy_mutex` may not be correctly released if the phy_data->comm_owned is true and the control flow goes to the branch listed below. Finally, the method returns with the unreleased lock. The fix is to insert `pthread_mutex_unlock(&pdata->phy_mutex)`;  before returning.

https://github.com/F-Stack/f-stack/blob/39f53b9b66e00fb9a794fb368b4856e6634b8729/dpdk/drivers/net/axgbe/axgbe_phy_impl.c#L419

```
static int axgbe_phy_get_comm_ownership(struct axgbe_port *pdata)
{
	struct axgbe_phy_data *phy_data = pdata->phy_data;
	uint64_t timeout;
	unsigned int mutex_id;

	/* The I2C and MDIO/GPIO bus is multiplexed between multiple devices,
	 * the driver needs to take the software mutex and then the hardware
	 * mutexes before being able to use the busses.
	 */
	pthread_mutex_lock(&pdata->phy_mutex);

	if (phy_data->comm_owned)
		return 0;  // the method returns with the unreleased lock

	...;
	return -ETIMEDOUT;
}
```

Best,

**Comment by jfb8856606** [comment]
See #605

**Comment by jenny-cheung** [comment]
It is a false positive.
