### ISSUE TITLE
Test the UDP performance 

### ISSUE THREAD

**Issue by GYL-cloud** [F-Stack/f-stack#612]
When I test the UDP performance,  how to resolve “63583585 dropped due to full socket buffers”。

[root@servier-1-vm my_example]# ff_netstat -s -p udp
EAL:   Invalid NUMA socket, default to 0
EAL:   Invalid NUMA socket, default to 0
Device 0000:00:04.0 is not driven by the primary process
EAL: Requested device 0000:00:04.0 cannot be used
udp:
        65635420 datagrams received
        0 with incomplete header
        0 with bad data length field
        0 with bad checksum
        0 with no checksum
        0 dropped due to no socket
        0 broadcast/multicast datagrams undelivered
        63583585 dropped due to full socket buffers
        0 not for hashed pcb
        2051835 delivered
        0 datagrams output
        0 times multicast source filter matched

My test code:

#include <stdio.h>
#include <sys/ioctl.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <strings.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <errno.h>
#include <assert.h>

#include "ff_config.h"
#include "ff_api.h"
#include "ff_epoll.h"

#define MAX_EVENTS 512
#define MAX_BUF_LEN 1500

struct epoll_event ev;
struct epoll_event events[MAX_EVENTS];
int epfd;
int sockfd;
char buf[MAX_BUF_LEN] = {0};

int loop(void *arg)
{
    /* Wait for events to happen */

    int ret;
    struct sockaddr_in tmpaddr;
    socklen_t len;
    len = sizeof(tmpaddr);
    bzero(&tmpaddr, sizeof(tmpaddr));
    tmpaddr.sin_family = AF_INET;    
    tmpaddr.sin_addr.s_addr = htonl(INADDR_ANY);
    tmpaddr.sin_port = htons(53);

    memset(buf, 0, MAX_BUF_LEN);

    int nevents = ff_epoll_wait(epfd,  events, MAX_EVENTS, 0);
    int i;

    for (i = 0; i < nevents; ++i) {
        /* Handle new connect */
        if (events[i].data.fd == sockfd) {
            memset(buf, 0, MAX_BUF_LEN);
            if((ret = ff_recvfrom(sockfd, buf, MAX_BUF_LEN, 0,  (struct linux_sockaddr *)&tmpaddr, &len)) < 0) {
                continue;
            }
        }
    }

}

int main(int argc, char * argv[])
{
    ff_init(argc, argv);

    if((sockfd = ff_socket(AF_INET, SOCK_DGRAM, 0)) < 0) {
        printf("ff_socket failed\n");
        exit(1);
    }

    int on = 1;
    ff_ioctl(sockfd, FIONBIO, &on);

    struct sockaddr_in servaddr;
    bzero(&servaddr, sizeof(servaddr));
    servaddr.sin_family = AF_INET;
    servaddr.sin_port = htons(53);
    servaddr.sin_addr.s_addr = htonl(INADDR_ANY);

    if(ff_bind(sockfd, (struct linux_sockaddr *)&servaddr, sizeof(servaddr)) < 0) {
        printf("ff_bind failed\n");
        exit(1);
    }

    assert((epfd = ff_epoll_create(0)) > 0);
    ev.data.fd = sockfd;
    ev.events = EPOLLIN;
    ff_epoll_ctl(epfd, EPOLL_CTL_ADD, sockfd, &ev);
    ff_run(loop, NULL);

    return 0;
}

**Comment by freak82** [comment]
Make sure that `idle_sleep=0` is set to 0 in `config.ini`.

You can also try setting `net.inet.udp.recvspace = 8388608` (8MB) or more in the `config.ini` `[freebsd.sysctl]` section.

The default value for UDP receive buffer is very low, around 40KB, as you can see it in `freebsd/netinet/udp_usrreq.c` - `udp_recvspace`.

**Comment by GYL-cloud** [comment]
> Make sure that `idle_sleep=0` is set to 0 in `config.ini`.
> 
> You can also try setting `net.inet.udp.recvspace = 8388608` (8MB) or more in the `config.ini` `[freebsd.sysctl]` section.
> 
> The default value for UDP receive buffer is very low, around 40KB, as you can see it in `freebsd/netinet/udp_usrreq.c` - `udp_recvspace`.

Thank you! The socket receives all udp packets.
