### ISSUE TITLE
lcore 8 has nothing to do

### ISSUE THREAD

**Issue by mincymathew** [F-Stack/f-stack#619]
My application is exiting with the following error

[dpdk]: lcore_mask=0xff00
[dpdk]: channel=4
[dpdk]: promiscuous=1
[dpdk]: numa_on=1
[dpdk]: tx_csum_offoad_skip=0
[dpdk]: tso=0
[dpdk]: vlan_strip=1
[dpdk]: idle_sleep=0
[dpdk]: pkt_tx_delay=100
[dpdk]: symmetric_rss=0
[dpdk]: port_list=0
[dpdk]: nb_vdev=0
[dpdk]: nb_bond=0
[pcap]: enable=0
[pcap]: snaplen=96
[pcap]: savelen=16777216
[pcap]: savepath=.
[port0]: addr=192.168.1.2
[port0]: netmask=255.255.225.0
[port0]: broadcast=192.168.1.255
[port0]: gateway=192.168.1.1
[port0]: lcore_list=14,15
[freebsd.boot]: hz=100
[freebsd.boot]: fd_reserve=1024
[freebsd.boot]: kern.ipc.maxsockets=262144
[freebsd.boot]: net.inet.tcp.syncache.hashsize=4096
[freebsd.boot]: net.inet.tcp.syncache.bucketlimit=100
[freebsd.boot]: net.inet.tcp.tcbhashsize=65536
[freebsd.boot]: kern.ncallout=262144
[freebsd.boot]: kern.features.inet6=1
[freebsd.boot]: net.inet6.ip6.auto_linklocal=1
[freebsd.boot]: net.inet6.ip6.accept_rtadv=2
[freebsd.boot]: net.inet6.icmp6.rediraccept
[freebsd.sysctl]: kern.ipc.somaxconn=32768
[freebsd.sysctl]: kern.ipc.maxsockbuf=16777216
[freebsd.sysctl]: net.link.ether.inet.maxhold=5
[freebsd.sysctl]: net.inet.tcp.fast_finwait2_recycle=1
[freebsd.sysctl]: net.inet.tcp.sendspace=16384
[freebsd.sysctl]: net.inet.tcp.recvspace=8192
[freebsd.sysctl]: net.inet.tcp.cc.algorithm=cubic
[freebsd.sysctl]: net.inet.tcp.sendbuf_max=16777216
[freebsd.sysctl]: net.inet.tcp.recvbuf_max=16777216
[freebsd.sysctl]: net.inet.tcp.sendbuf_auto=1
[freebsd.sysctl]: net.inet.tcp.recvbuf_auto=1
[freebsd.sysctl]: net.inet.tcp.sendbuf_inc=16384
[freebsd.sysctl]: net.inet.tcp.recvbuf_inc=524288
[freebsd.sysctl]: net.inet.tcp.sack.enable=1
[freebsd.sysctl]: net.inet.tcp.blackhole=1
[freebsd.sysctl]: net.inet.tcp.msl=2000
[freebsd.sysctl]: net.inet.tcp.delayed_ack=0
[freebsd.sysctl]: net.inet.udp.blackhole=1
[freebsd.sysctl]: net.inet.ip.redirect=0
[freebsd.sysctl]: net.inet.ip.forwarding=0
EAL: Detected 72 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: 4096 hugepages of size 2097152 reserved, but no mounted hugetlbfs found for that size
f-stack -c100 -n4 --proc-type=primary EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: Cannot open /dev/vfio/28: Device or resource busy
EAL: Failed to open group 28
EAL: Requested device 0000:19:00.0 cannot be used
EAL: Cannot open /dev/vfio/29: Device or resource busy
EAL: Failed to open group 29
EAL: Requested device 0000:19:00.1 cannot be used
EAL: Probe PCI driver: net_i40e (8086:1583) device: 0000:5e:00.0 (socket 0)
EAL: Probe PCI driver: net_i40e (8086:1583) device: 0000:5e:00.1 (socket 0)
EAL: Probe PCI driver: net_i40e (8086:1572) device: 0000:d8:00.0 (socket 1)
EAL: Probe PCI driver: net_i40e (8086:1572) device: 0000:d8:00.1 (socket 1)
EAL: Probe PCI driver: net_i40e (8086:1572) device: 0000:d8:00.2 (socket 1)
EAL: Probe PCI driver: net_i40e (8086:1572) device: 0000:d8:00.3 (socket 1)
EAL: No legacy callbacks, legacy socket not created
EAL: Error - exiting with code: 1
  Cause: lcore 8 has nothing to do
Child pid 1156440 exited with status 1

Would you know why this is?

**Comment by mincymathew** [comment]
Fixed by changing lcore_mask

**Comment by mayank-bhushan** [comment]
Hi, what was your core mask? Can you elaborate more on the changes you did to fix this?
