### ISSUE TITLE
f-stack nginx as a reverse proxy

### ISSUE THREAD

**Issue by Mrbuffoon** [F-Stack/f-stack#62]
Hi，
When f-stack runs as multi-core, multi-queue, and nginx acts as a  web server, different IP will be assigned to different queues for processing and will be fixed. If nginx acts as a reverse proxy, will all requests from all IP be sent centrally to the same queue of the web server? How can this situation be solved?

**Comment by whl739** [comment]
F-Stack will choose a port according to the rss hash result which will be received by the same core/queue  when connect to a server.

**Comment by Mrbuffoon** [comment]
Yes, I  know that "F-Stack will choose a port according to the rss hash result which will be received by the same core/queue when connect to a server" . 

OK, Let me illustrate my problem with an example. 

For example, when nginx as a web server, according to the rss hash, the IP 192.168.0.2'request will be received by the lcore0 and queue0, and the IP 192.168.1.5'request will be received by the lcore1 and queue1. Then, the  multi-core and multi-queue will give full play to his ability.

But, when as a proxy, the request has been relayed by proxy so the web server will assume that all requests come from the same IP（the proxy IP）. According to the rss hash, all request will be received by only one lcore and one queue. In this way, f-stack nginx multi-core and multi-queue performance can not be played out.

Has anyway to solve it?

**Comment by whl739** [comment]
The rss hash is calculated by four tuples (src_ip, src_port, dst_ip, dst_port).
You don't have to worry about it.

**Comment by Mrbuffoon** [comment]
Recently, I'd like to test the forwarding capabilities of f-stack nginx as a reverse proxy. I set one computer as a proxy and the IP is 192.168.0.5. The proxy bind 8 cores and 8 queues. Another computer as a web server and the IP is 192.168.0.6. the web server bind  8 cores and 8 queues too.  All request to the proxy(192.168.0.5) will be relayed to the web server(192.168.0.6). when different clients sent request to the proxy, because the client'IP is different, the request will hash to different cores to handle. But,when relay to webserver,the tuples is (192.168.0.5, 80, 192.168.0.6, 80), isn't it? So,it will be hashed to only one core on webserver,isn't it?

Also,  I noticed that the 16 core f-stack RPS can reach 80W. Can you tell me what tools you use for stress testing? And what is the parameter?

**Comment by whl739** [comment]
> But,when relay to webserver,the tuples is (192.168.0.5, 80, 192.168.0.6, 80), isn't it? So,it will be hashed to only one core on webserver,isn't it?

You made something wrong, let me give you an example:
A client(192.168.1.2) connects to nginx_fstack(192.168.1.5), their four tuple (192.168.1.2, 32576, 192.168.1.5, 80), and nginx_fstack will connect to your web server(192.168.1.6), their four tuple (192.168.1.5, 45121, 192.168.1.6, 80). All these will be hashed to different queues.

> Also, I noticed that the 16 core f-stack RPS can reach 80W. Can you tell me what tools you use for stress testing? And what is the parameter?

We use `wrk` and multiple clients. 

Edit config.ini/f-stack.conf:
```
#This means we use 16 cores on cpu0-cpu15.
lcore_mask=ffff
```
Edit nginx.conf:
```
access_log /dev/null;
location / {
    return 200 "xxxxxxx"; // in readme.md, we returned 600 bytes' body.
}
```
For `Connection-Closed` test, edit nginx.conf:
```
keepalive_timeout  0;
```

**Comment by Mrbuffoon** [comment]
May I know the relevant parameters of wrk? How many machines, -t, -c, -d, -T and so on?

**Comment by whl739** [comment]
It's based on your configurations(hardware and software), you can try it from small to large.
