### ISSUE TITLE
f-stack fails to open udp socket with ICMP protocol

### ISSUE THREAD

**Issue by sarosharif** [F-Stack/f-stack#629]
I am writing a ping-like application using f-stack

I use the following command to make a socket: `ff_socket(AF_INET, SOCK_DGRAM, IPPROTO_ICMP) `
ff_socket() returns -1 with the errno 93(Protocol not supported)

`socket(AF_INET, SOCK_DGRAM, IPPROTO_ICMP)` works fine using kernel's stack. 

Any suggestions on how to solve this?
Thanks.

**Comment by freak82** [comment]
I believe that the Linux and FreeBSD/F-stack implementation differ in this case.
It [seems to me](https://www.freebsd.org/cgi/man.cgi?query=icmp&sektion=4) that on FreeBSD you can use `IPPROTO_ICMP` only with raw sockets - `socket(AF_INET, SOCK_RAW, IPPROTO_ICMP)`.

**Comment by sarosharif** [comment]
Thanks,
Working with raw socket.
