### ISSUE TITLE
how to create a shared library base on libfstack.a?

### ISSUE THREAD

**Issue by yuyang0** [F-Stack/f-stack#63]
gcc reports error, because the objects in libfstack.a need recompile with `-fPIC`, since f-stack depends on DPDK, so I'm not sure if it's enough to just recompile f-stack with `-fPIC`. Any advice on how to solve this problem? thx

**Comment by tresaresa** [comment]
hi, i got the same problem. did you fix it finally?

**Comment by tresaresa** [comment]
hi, i got the same problem. did you fix it finally?
