### ISSUE TITLE
how compile  libfstack.so and work?

### ISSUE THREAD

**Issue by jeff-lv-github** [F-Stack/f-stack#632]
I compile a  libfstack.so

the way:
add CFLAGSS with -fPIC

share_lib: ${ASM_OBJS} ${OBJS} ${HOST_OBJS}
	$(CC) -shared  $^ -o libfstack.so

but when I run helloworld, it's core dump, the error is:
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./helloworld'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f36f8932ea3 in preload_search_info (mod=0x726f705f746e6576 <error: Cannot access memory at address 0x726f705f746e6576>, inf=32771)
    at /home/bx/rtia-net/lib/../freebsd/kern/subr_module.c:178

**Comment by jfb8856606** [comment]
See #582.
