### ISSUE TITLE
Does not work on big-endian devices

### ISSUE THREAD

**Issue by agerguo** [F-Stack/f-stack#642]
https://github.com/F-Stack/f-stack/blob/22ce4aff4f62d7d78df35f4804fcae848cdb310f/freebsd/net/if_vxlan.c#L2779
vxh->vxlh_vni & ~htonl(VXLAN_VNI_MASK << VXLAN_HDR_VNI_SHIFT)

**Comment by jfb8856606** [comment]
Yes，it is.
But Linux and Freebsd are Little Endian, so F-Stack won't modify it now, and you can try open an issue to FreeBSD.
