### ISSUE TITLE
The bad RSS key - symmetric_rsskey

### ISSUE THREAD

**Issue by tinboxw** [F-Stack/f-stack#644]
错误的对称密钥，会极少几率下出现无法同源同遡的情况。

#if 0
  /**
   * 此为 网上的中文博客中描述的对称加密密钥 ，存在严重bug
   * 此密钥，是中文博主抄作业，抄错了！！！，字节序不对
   * 影响：会造成部分同一会话的上下行被分到不同的网卡队列中
   */
  __rte_unused uint8_t rss_sym_key[40] = {
      0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A,
      0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A,
      0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A,
      0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A,
  };
#else
  /**
   * 外网论文地址：
   * https://www.ndsl.kaist.edu/~kyoungsoo/papers/TR-symRSS.pdf
   * 原论文中使用uint16_t存储的密钥
   * 0x6d5a 0x6d5a 0x6d5a 0x6d5a
   * 0x6d5a 0x6d5a 0x6d5a 0x6d5a
   * 0x6d5a 0x6d5a 0x6d5a 0x6d5a
   * 0x6d5a 0x6d5a 0x6d5a 0x6d5a
   * 0x6d5a 0x6d5a 0x6d5a 0x6d5a
   */

  __rte_unused static uint8_t rss_sym_key[40] = {
      0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D,
      0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D,
      0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D,
      0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D,
      0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D, 0x5A, 0x6D
   };
#endif

**Comment by jfb8856606** [comment]
I will test it.

**Comment by jfb8856606** [comment]
I has re-tested `0x6d,0x5a ……0x6d,0x5a` , and it work correctly.

Or you can provide a counter example and reopen this issue.

**Comment by flowwill** [comment]
Fixed my issue. while at first  I can't use multi core for Nginx and with RSS enabled. Thank you!
