### ISSUE TITLE
Dynamic load a, failed, said   gcc: symbol lookup error: ./../lib/libfstack.so: undefined symbol: rte_cycles_vmware_tsc_map

### ISSUE THREAD

**Issue by HREOLIN** [F-Stack/f-stack#657]
/bin/bash: symbol lookup error: /home/lin/f-stack-master/lib/libfstack.so: undefined symbol: rte_cycles_vmware_tsc_map

Why is there such a situation and how to solve it。

**Comment by jfb8856606** [comment]
F-Stack don't support dynamic library, and there are also no plans to support in the short term.

So may be you need to debug it yourself, and we welcome pr.
