### ISSUE TITLE
compile problem porting f-stack to linux kernel

### ISSUE THREAD

**Issue by nsoft-cloud** [F-Stack/f-stack#66]
I thought the f-stack was divided into 2 parts.
The first part was freebsd kernel + f-stack compatible layer. This part was compiled inter libfstack.a.
The second part was host part which is used to initialize freebsd kernel and feed packet to freebsd network stack.
Based on the idea above, the makefile is adjust like below:

	obj-m += f-stack.o
	f-stack-objs := ${HOST_OBJS} libfstack.a
	all: libfstack.a
		$(MAKE) -C /lib/modules/`uname -r`/build M=$(PWD) modules

But there are several symbol can not be found:

	WARNING: "__start_set_pcpu" [/home/ubuntu/f-stack/lib/f-stack.ko] undefined!
	WARNING: "__start_set_sysuninit_set" [/home/ubuntu/f-stack/lib/f-stack.ko] undefined!
	WARNING: "__stop_set_sysuninit_set" [/home/ubuntu/f-stack/lib/f-stack.ko] undefined!
	WARNING: "__stop_set_pcpu" [/home/ubuntu/f-stack/lib/f-stack.ko] undefined!
	WARNING: "_DYNAMIC" [/home/ubuntu/f-stack/lib/f-stack.ko] undefined!

Is there any suggestions for this ? thx a lot

**Comment by whl739** [comment]
Sorry, i couldn't figure out what is the problem with these infomations. Any other changes?

**Comment by amjy** [comment]
@jesseai Could you show  more about the environment and informations?
Or push a branch to your github repositories.

**Comment by chanwai1219** [comment]
hi, what I have done can be found on this commit 
[try to build f-stack in kernel](https://github.com/chanwai1219/f-stack/commit/5fc15f5d025842697c25692d9b52368e84f93b9a)
what I concern about is that where can I found those 5 symbol above

**Comment by amjy** [comment]
__start_set_pcpu in the ".globl" section

maybe you can do it like this:
---
[root@localhost kfs]# ls
ff_kernel_if.c  libfstack.a  Makefile

Makefile:
--
obj-m += f-stack.o
f-stack-objs := ${HOST_OBJS} libfstack.a
f-stack-objs += ff_kernel_if.o

all: libfstack.a
	$(MAKE) -C /lib/modules/`uname -r`/build M=$(PWD) modules


But Where is ff_hardclock
--

**Comment by whl739** [comment]
These symbols are all defined as __GLOBL(.global symbol), it means the symbol is globally visible.
It works at the link stage, and if you `nm` the app, you will find that they are not undefined any more.

**Comment by chanwai1219** [comment]
It seems that when compile a user space application, these symbol will be automatically linked into the program. However, kbuild will NOT do the same thing. The difference of user space and kernel space is that kbuild used the customized link script.  The default gcc linker script of user space can be shown by add **-Wl,-verbose** option. But I didn't tell the difference between user space and kernel space linker script. Why kbuild system doesn't link these symbol?

`
  ld -r -m elf_x86_64 -T ./scripts/module-common.lds --build-id  -o /home/ubuntu/f-stack-new/lib/f-stack.ko /home/ubuntu/f-stack-new/lib/f-stack.o /home/ubuntu/f-stack-new/lib/f-stack.mod.o
`

And among these symbols, _GLOBAL_OFFSET_TABLE_ and _DYNAMIC is the GOT related stuff.  Should I build module using -fno-pic option?

>-fpic
Generate position-independent code (PIC) suitable for use in a shared library, if supported for the target machine. Such code accesses all constant addresses through a global offset table (GOT). The dynamic loader resolves the GOT entries when the program starts (the dynamic loader is not part of GCC; it is part of the operating system). If the GOT size for the linked executable exceeds a machine-specific maximum size, you get an error message from the linker indicating that -fpic does not work; in that case, recompile with -fPIC instead.

**Comment by whl739** [comment]
Sorry, i don't know more about kbuild.
Maybe you should find a way to export these symbols to ko, like `-Wl,--whole-archive`.
