### ISSUE TITLE
Using F-Stack to decode Tunneled Packet ?

### ISSUE THREAD

**Issue by bnnk** [F-Stack/f-stack#677]
Hi All,

  We have a following use case. We don't want to use DPDK since we are not using PMD's but we are receiving a IP/UDP in IP as UDP payload tunneled packet and once we take the inner payload we want to give it to f-stack to decode the IP/UDP and give the UDP payload. I see that the DPDK initialization is as a part of ff_init and it fails. Please let us know if there is anyway to use the UDP stack without DPDK Initialization ?.

rgds
Balaji

**Comment by jfb8856606** [comment]
Now, F-Stack strongly depends on DPDK， you can't use the UDP stack whithout DPDK Initialization.
