### ISSUE TITLE
Add VIP for a NIC

### ISSUE THREAD

**Issue by Mrbuffoon** [F-Stack/f-stack#68]
Hi, I want to set up multiple virtual IP for the DPDK bound NIC, and then the client can access the web service through the virtual IP.

I set it by tools/ifconfig/ifconfig.
    cd tools/ifconfig
    ./ifconfig f-stack-0 192.168.0.6 netmask 255.255.0.0 alias

Then "./ifconfig" ,shows thst:
   lo0: flags=8008<LOOPBACK,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	groups: lo 
   f-stack-0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=3<RXCSUM,TXCSUM>
	ether 48:7b:6b:79:dc:cc
	inet 192.168.0.3 netmask 0xffff0000 broadcast 192.168.255.255 
	inet 192.168.0.6 netmask 0xffff0000 broadcast 192.168.255.255  

Now, I can ping 192.168.0.3 but can't ping 192.168.0.6.

**Comment by whl739** [comment]
Have you configured on every f-stack processes?Because every f-stack process has its own stack.
You can do it like this:
```
./ifconfig -p 0  f-stack-0 192.168.0.6 netmask 255.255.0.0 alias
./ifconfig -p 1  f-stack-0 192.168.0.6 netmask 255.255.0.0 alias
...
```

**Comment by Mrbuffoon** [comment]
Yes, you are right. After set for per process, it can work currently. Thank you!
