### ISSUE TITLE
can I install external application software?

### ISSUE THREAD

**Issue by wangweibee** [F-Stack/f-stack#684]
Can I install external application software in f-stack through source code or software package?  For example, dnsmasq.
fstack能安装外部程序吗，比如dnsmasq？
还是只能用版本中已经移植好的Nginx和redis。

**Comment by jfb8856606** [comment]
Now if other application want to use F-Stack, you need port them to use F-Stack's socket API,  you can diff between the original version of Redis and F-Stack's Redis for reference, or Nginx.
