### ISSUE TITLE
multiple processes

### ISSUE THREAD

**Issue by wrfeewrtgaqwfrwaq** [F-Stack/f-stack#695]
So I want to independently turn on and off multiple applications that need kernel stack offloading. As far as I understand f-stack supports it as long as first turned on instance is primary and all next ones are secondary.

So I tried running simple hello world example where one instance is set to port 80 and another to port 81. It kind of works. Sometimes I can connect to server and exchange packets and sometimes I can't. It seems to me as if sessions are randomly assigned to one instance or another independently of open ports.

**Comment by MrSonicMaster** [comment]
As I understand it, each f-stack process is fully isolated and traffic is directed to a specific rx queue by hardware offloaded RSS. in order to have deterministic traffic flow you must [calculate](https://doc.dpdk.org/guides/prog_guide/toeplitz_hash_lib.html) which local port to bind to for traffic to hit the process you want

**Comment by wrfeewrtgaqwfrwaq** [comment]
What if I disable hardware offload for RSS? I guess software Topelitz gets applied?

But if that's the case why my testing non deterministically worked?

**Comment by MrSonicMaster** [comment]
you can disable hardware rss, and all traffic will go to queue some default queue, very likely queue 0. i do not believe dpdk will not emulate it in software for you.

set in ff_dpdk_if.c
```
port_conf.rxmode.mq_mode = ETH_MQ_RX_NONE;
port_conf.rx_adv_conf.rss_conf.rss_hf = 0;
```
but then you get less scalability from f-stack, other process wont get any traffic unless you route it with ff_regist_packet_dispatcher callback, but that has disadvantage of added latency and extra cpu cycles for 'master' process to get around to routing it, vs hardware doing such work for you. *some* nics support dpdk rte_flow api and/or flow_isolate mode, which can let you do more complex hardware-accelerated flow control, f-stack has some example rte_flow code which can be enabled in makefile, FF_FLOW_ISOLATE.

for layer-4 traffic, rss hash is applied to src/dest ip and src/dest port, so it will route traffic on each 'session (which keep same src/dest tcp ports)' to the same queue, but different sessions will bind to diff local ports and flow to a new queue. try binding to deterministic local address and port and see if it becomes predictable.

**Comment by wrfeewrtgaqwfrwaq** [comment]
well hashing by source & destination ip&port means I can't set up 2 independent applications using f-stack. My goal is to get 2 totally independent applications to have lower latency networking than kernel stack.

**Comment by MrSonicMaster** [comment]
Other hardware flow-control solutions may exist depending on what features your NICs supports, you will need to research it more. Start by looking at feature list on dpdk page for your nics PMD.  But of course, if your nic simply cannot do the flow control you want, then the cpu must do it. in that case you must use ff_regist_packet_dispatcher() to do your flow control logic, it can redirect packet to another f-stack process (internally using spsc dispatch ring).

check [#418](https://github.com/F-Stack/f-stack/issues/231#issuecomment-396201683)

**Comment by jfb8856606** [comment]
And #698
