### ISSUE TITLE
f-stack multi-core not working on aws instances

### ISSUE THREAD

**Issue by yangsuli-netapp** [F-Stack/f-stack#703]
Hi, 

I am trying to run f-stack with the multi-process mode, to utilize multi-core for better performance. 

To do this I simply run ./start.sh -b ./ff_client.

However, even though such method works well on physical machines with Intel NIC cards, when I am doing the same on AWS instances (c5.xlarge to be specific), which uses ENA NIC drivers, I can rarely establish connections successfully.  Most only the time of the primary process success, while the second processes timeout when connecting. 

In Seastar we had the similar problem, and it was due to Seastar not using the correct RSS key for AWS instances, which caused the connection to be assigned to the wrong core (not the core that receives the packet). 

I am wondering, could f-stack have the same issue as well?

**Comment by jfb8856606** [comment]
Yes, if  the RSS key is incorrect, it will have the same issue.

You can find the RSS key that F-Stack used in [ff_dpdk_if.c](https://github.com/F-Stack/f-stack/blob/dev/lib/ff_dpdk_if.c#L85) and try to midify it.

Or you can use [ff_regist_packet_dispatcher](https://github.com/F-Stack/f-stack/blob/dev/lib/ff_api.h#L156) to do packets dispatch in CPU to “RSS bypass”， but performance will decrease.

**Comment by yangsuli-netapp** [comment]
But one question here:

why don't we check and configure the rss_key (using, e.g., rte_eth_dev_rss_hash_update), before we actually start using it to avoid this rss key mismatch problem? 

In both Seastar and f-stack, the rss_key is defined as a constant. I can't seem to understand why. 

Thanks.

Suli

**Comment by jfb8856606** [comment]
Many NIC drivers in DPDK do not implement the interface `rte_eth_dev_rss_hash_update`, and the compatibility of the NIC that has already implemented this interface is better.

ENA drivers implemented after DPDK 21.11, now the last F-Stack release 1.22 use DPDK 20.11, ENA drivers don't support the API,.

You can modify the code of dev branch (use DPDK 21.11)  to support `rte_eth_dev_rss_hash_update` and create a pull request.

**Comment by yangsuli-netapp** [comment]
Okay, it seems like even though ENA drivers start to support rss_key configuration after DPDK 21.08, the underlying hardware still does not support it, and rte_eth_dev_rss_hash_update() fails with unsupported error. 

So my follow-up question is: in f-stack, can I disable RSS to avoid such multi-core problems?

**Comment by jfb8856606** [comment]
> So my follow-up question is: in f-stack, can I disable RSS to avoid such multi-core problems?

You can see this API.

> Or you can use [ff_regist_packet_dispatcher](https://github.com/F-Stack/f-stack/blob/dev/lib/ff_api.h#L156) to do packets dispatch in CPU to “RSS bypass”， but performance will decrease.
