### ISSUE TITLE
Error when starting nginx with F-stack

### ISSUE THREAD

**Issue by thanhdat9526** [F-Stack/f-stack#704]
I get the following error when starting nginx, I have f-stack test installed on my virtual host.
Can you tell me which hardware will be supported by F-Stack and launch perfectly?
**Info-Error:**
ERROR: This system does not support "SSSE3".
Please check that RTE_MACHINE is set correctly.
EAL: FATAL: unsupported cpu type.
EAL: unsupported cpu type.
EAL: Error - exiting with code: 1
  Cause: Error with EAL initialization
2022/10/20 14:59:11 [error] 9811#0: primary worker process failed to initialize (110: Connection timed out)

**Comment by jfb8856606** [comment]
You can try disable SSE3 via set CFLAG `-mno-sse3`.

Or enable sse3 in virtual host.

**Comment by thanhdat9526** [comment]
You mean i need to set FLAG disable SSE3 while compiling Nginx?
eg: ./configure --prefix = ... --with-cc-opt = "-mno-sse3"

**Comment by jfb8856606** [comment]
Yes, you can add  `--with-cc-opt="-mno-sse3"` while do configure.
