### ISSUE TITLE
Adding -DNDEBUG flag will cause the helloworld example to crash

### ISSUE THREAD

**Issue by renzibei** [F-Stack/f-stack#705]
Hello, I find that if `-DNDEBUG` flag is added to the compile-options, the helloworld example will crash. After the modification, the `CFLAGS` line in the Makefile file becomes 
```
CFLAGS += -O -DNDEBUG -gdwarf-2 $(shell $(PKGCONF) --cflags libdpdk)
```
And when I running the `helloworld` program, it will crashes or print many lines of `unknown event: 00000000`.

Can you help look into the reason of it?

**Comment by renzibei** [comment]
I used the compiled static library of f-stack. Maybe the status of NDEBUG macro in the header files of f-stack codes will affect the ABI stability?

**Comment by jfb8856606** [comment]
Fixed.  
Because `assert((kq = ff_kqueue()) > 0);` was be ignored and nevents used usigned type.
