### ISSUE TITLE
Is it necessary to use ff_run and event based programming pattern?

### ISSUE THREAD

**Issue by renzibei** [F-Stack/f-stack#707]
According to my observation, the vast majority of programming examples currently use `ff_run` to start an event-based programming mode (eg kqueue, epoll). Although there are also examples of socket operations performed on the main thread before ff_run starts, they will almost all enter ff_run at the end. Is it possible to only perform socket basic operations (such as recv, send) in the main thread without entering ff_run? Is there a performance penalty for this?

**Comment by MrSonicMaster** [comment]
f-stack is based around dpdk poll-mode driver, which basically operates as infinite loop in main thread polling the nic for data. f-stack does not support multiple threads, so logic must be called to from the main loop, in the loop callback routine passed to ff_fun. it is called when a packet is received (also on timer if nothing is received), after freebsd has processed it, so calls to ex. kevent() can return pending events pertaining to the data.
