### ISSUE TITLE
Why the file descriptors ff_kqueue and ff_socket return start from 1024?

### ISSUE THREAD

**Issue by renzibei** [F-Stack/f-stack#713]
In linux, most APIs returning a new fd will return a smallest non-negative number, for example 4, 5, ..., to make the fd as small as possible, which is easy for the developers to use the fd as the index of array. 

Why does f-stack choose to make the fd start from 1024, this will make the easy mapping solution not portable.

**Comment by hailongeric** [comment]
You can config it in config.ini with fd_reserve arg. You need to ensure the file descriptor's correct usage.

**Comment by renzibei** [comment]
> You can config it in config.ini with fd_reserve arg. You need to ensure the file descriptor's correct usage.

Got it, thanks.
