### ISSUE TITLE
Redis-6.2.6 multi io-threads ?

### ISSUE THREAD

**Issue by hailongeric** [F-Stack/f-stack#717]
Redis-6.2.6 support multi io-threads to improve performance, Does redis-6.2.6 with F-stack version support multi io-threads?

**Comment by jfb8856606** [comment]
I will test it later.

**Comment by jfb8856606** [comment]
Because F-Stack not support multi threads, so Redis-6.2.6 with F-stack also not support multi threads.

While call `write()` in `anet_ff.c`,  `ff_fdisused(sockfd)` unable to judge fd belongs to F-Stack，then cal system real write(), and error.

See also #430

**Comment by Chithesus** [comment]
> Because F-Stack not support multi threads, so Redis-6.2.6 with F-stack also not support multi threads.
> 
> While call `write()` in `anet_ff.c`, `ff_fdisused(sockfd)` unable to judge fd belongs to F-Stack，then cal system real write(), and error.
> 
> See also #430

if i am sure that call as write/read/socket... belongs to F-Stack, can i use multithread?
