### ISSUE TITLE
Is there a clean way to stop the loop?

### ISSUE THREAD

**Issue by renzibei** [F-Stack/f-stack#719]
It is useful in some situations.

**Comment by aengusjiang** [comment]
current implement doesn't.

**Comment by aengusjiang** [comment]
it is better to add ff_stop to exit the ff_run loop

**Comment by jfb8856606** [comment]
No plan yet, but welcome pull request.

**Comment by Chithesus** [comment]
> it is better to add ff_stop to exit the ff_run loop
> No plan yet, but welcome pull request.

suggest interface:
1. ff_stop
2. ff_run_once

**Comment by renzibei** [comment]
Close as the pull request has been merged.
