### ISSUE TITLE
Why should tx checksum offload be closed in bonding mode?

### ISSUE THREAD

**Issue by ghpass** [F-Stack/f-stack#733]
Bonding mode 4 is adpoted in my testing(two Interl 82599ES 10GE NIC ). The version of f-stack is 1.22. 
Everything is ok when "tx_csum_offoad_skip" is set as 1 . 
But if "tx_csum_offoad_skip" is set as **0**, each package sent from f-stack will be dropped by peer.  The IP checksum is incorrect (zero). So the tx checksum offload is not valid.
 I look through the code about 'TX ip checksum offload' in init_port_start(void) and can't find anything wrong.  
 If 'TX ip checksum offload' is disabled, the usage of cpu will be higher. 
Any suggestion is appreciated.

**Comment by jfb8856606** [comment]
F-Stack 1.22 use DPDK 20.11, which not support tx checksum offload.

See https://patches.dpdk.org/project/dpdk/patch/1619171202-28486-2-git-send-email-tangchengchang@huawei.com/

**Comment by ghpass** [comment]
Thanks!
