### ISSUE TITLE
how can fstack uses sr-iov(vf)

### ISSUE THREAD

**Issue by CHRIS123540** [F-Stack/f-stack#734]
Hello, I want to modify config.ini so that f-stack can use vf. Is there any case?

**Comment by uvletter** [comment]
just set `pci_whitelist` to the pci address of VF

**Comment by CHRIS123540** [comment]
Thank you for your answer, I did not use `pci_whitelist`, I directly set the `port_list` parameters and correctly obtained the MAC address of VFs, but I can only ping the address of the PF that created VFs.
![20230213203646](https://user-images.githubusercontent.com/64949823/218460651-7f4db7db-fb09-4117-83bb-0692e9b25785.png)
![20230213204554](https://user-images.githubusercontent.com/64949823/218461194-a076dd7e-08c7-40e4-b4ef-4583a74e4137.png)
![ZOLY098}V235AQNE4I}78V8](https://user-images.githubusercontent.com/64949823/218460822-5d9c934c-d8c2-4b39-b782-63fa3778abf9.png)
![20230213205511](https://user-images.githubusercontent.com/64949823/218463891-a47d0991-a1a0-4a8d-847d-b3f13f78ed1e.png)
I would appreciate it if you could give me some advice

**Comment by uvletter** [comment]
Use the command lspci to find out the pci address of the VF, and then replace pci_whitelist with it, if not I guess fstack would bind to the first available pci device, i.e. the PF.

**Comment by jfb8856606** [comment]
If you use multi port in one subnet, maybe  you should use ff_ipfw to set some policy routing.

Or  you can try set every port to different subnet and retry it.

**Comment by CHRIS123540** [comment]
Setting different subnets works, could you tell me why?

**Comment by jfb8856606** [comment]
May be you can get some info with google search rp_filter.

发件人: Hu Carl ***@***.***>
发送时间: 2023年2月15日 17:43
收件人: F-Stack/f-stack ***@***.***>
抄送: fengbojiang(姜凤波) ***@***.***>; Comment ***@***.***>
主题: [Internet]Re: [F-Stack/f-stack] how can fstack uses sr-iov(vf) (Issue #734)


Setting different subnets works, could you tell me why?
