### ISSUE TITLE
how to make config.ini in f-stack?

### ISSUE THREAD

**Issue by venusgalstar** [F-Stack/f-stack#738]
I have a physical computer has public ip.

But I used default config.ini file when I run ./start.sh

ff_ifconfig shows
IP: 192.168.1.2
Broadcast: 192.168.1.255

ff_netstat -an shows
tcp4 hold 80 port

How could I test for 80 port?

Is it possible to access to internet if I add my original public ip by using ff_ifconfig?

And, I've remoed all installed file and dpdk including .ko files

After reinstall, ./start.sh failed because of "is another primary process running already?".

I need help.

**Comment by jfb8856606** [comment]
Modify [port0]'s addr/netmask/broadcast/gateway argument according to the actual IP information of your server.

> Is it possible to access to internet if I add my original public ip by using ff_ifconfig?
Of course it is possible.

> And, I've remoed all installed file and dpdk including .ko files
May be you need recompile DPDK and get back .ko files, and copy them to other directory for later use.

> After reinstall, ./start.sh failed because of "is another primary process running already?".
You need kill previously running process first.

**Comment by venusgalstar** [comment]
Thanks for your reply.

But how to kill dpdk primary process?

https://stackoverflow.com/questions/74602244/dpdk-multi-process-kill-a-primary-process-and-restart-as-a-secondary-doesnt-wo

From this article, it's not possible to kill primary process of dpdk.

So, I tried to remove dpdk totally including ko files

But as I said before, still same error, "is another primary process running already?"
