### ISSUE TITLE
how to kill dpdk primary process?

### ISSUE THREAD

**Issue by venusgalstar** [F-Stack/f-stack#739]
Thanks for your reply, [jfb8856606](https://github.com/jfb8856606).

But how to kill dpdk primary process?

I need this for new f-stack app with updated config.ini

https://stackoverflow.com/questions/74602244/dpdk-multi-process-kill-a-primary-process-and-restart-as-a-secondary-doesnt-wo

From this article, it's not possible to kill primary process of dpdk.

So, I tried to remove dpdk totally including ko files

But as I said before, still same error, "is another primary process running already?"

**Comment by jfb8856606** [comment]
Don't hesitate, just kill it.

Your own application can set the normal exit process.
