### ISSUE TITLE
Nginx reported error: Invalid options "-" 

### ISSUE THREAD

**Issue by leoncola** [F-Stack/f-stack#74]
Looks like something wrong when parsing cmd args, I checked git logs and reset git back to commit f7ca998abbd24a9713e884a0c05c2cb37f927292, then this error gone.
Maybe this commit f7ca998abbd24a9713e884a0c05c2cb37f927292 "Fix the bug which parsing arg ERRO" caused some new problem.

**Comment by whl739** [comment]
f7ca998abbd24a9713e884a0c05c2cb37f927292 is redis related not nginx.
And the latest nginx has supported the original command args.

**Comment by leoncola** [comment]
This is run under latest commit a67457ae8ad2a4b2c2cc02ea8253c01dd07365d5:
[root@localhost f-stack]# ./start.sh -b /usr/local/nginx_fstack/sbin/nginx -c config.ini
/usr/local/nginx_fstack/sbin/nginx --conf config.ini --proc-type=primary --proc-id=0 
nginx: invalid option: "-"
[root@localhost f-stack]#

**Comment by whl739** [comment]
The latest nginx no longer needs to start like this.
You can just run `/usr/local/nginx_fstack/sbin/nginx` or with original nginx commands.

**Comment by leoncola** [comment]
Thanks, I got it.
BTW, this description maybe a bit missleading: "./start.sh -b /usr/local/nginx_fstack/sbin/nginx -c config.ini"

**Comment by whl739** [comment]
Thank you for your reminding. 
I've noticed that, and fixed it.
