### ISSUE TITLE
how to kill dpdk primary process

### ISSUE THREAD

**Issue by venusgalstar** [F-Stack/f-stack#740]
Could you comment in detail about these?

You said "don't hesitate", Yes I did.

But I am not succeed in it.

I will be very appreciate if you provide me shell command on ubuntu to kill dpdk primay process.

**Comment by jfb8856606** [comment]
`pkill helloworld` or `pkill -9 helloworld`.
`helloword` means your APP name.

**Comment by jfb8856606** [comment]
If you want to "gracefully" exit the process, you need to analyze your own application logic and develop it yourself.

**Comment by venusgalstar** [comment]
it could be done by killall -9 process name
