### ISSUE TITLE
Is there a plan to support mult-threads?

### ISSUE THREAD

**Issue by saffraan** [F-Stack/f-stack#748]
I build a golang project to wrap f-stack in [usnet](git@github.com:saffraan/usnet.git), but It's limited by single thread mode, so that the tps of usnet is less than the tps of golang.net when the clients is less than 100.  

So, Is there a plan to support mult-threads? Because, all network calls are processed in single thread, so I use a sync.Cond to sync goroutines, the signal notify delay 60 us. If F-stack supports mult-threads, I can call api directly.

**Comment by saffraan** [comment]
this is my project: https://github.com/saffraan/usnet.git

**Comment by playXE** [comment]
Would also love to see multi-thread support in ff_* APIs. It is quite hard to write async runtime for Rust using f-stack at the moment

**Comment by saffraan** [comment]
> Would also love to see multi-thread support in ff_* APIs. It is quite hard to write async runtime for Rust using f-stack at the moment

OK，I will try to optimize network syncing function in my project, Thankyou.
