### ISSUE TITLE
How to deal with bonding NICs? Just offload both?

### ISSUE THREAD

**Issue by beef9999** [F-Stack/f-stack#749]
And after binding to igb_uio, will my NICs still have network access, and keep the old IP?

-------

绑定到igb_uio以后，网卡还能访问外网吗？并且保留原IP？

**Comment by saffraan** [comment]
> 绑定到igb_uio以后，网卡还能访问外网吗？

我觉得准确的说是“其他应用能通网卡访问外网”嘛？以我的使用经验来看，绑定 igb_uio 后只有使用了用户态网络栈的应用能通过该网卡访问外网。
> 并且保留原IP？
我在虚拟机中虚拟网卡绑定 igb_uio 驱动后，之前分配的ip还是可以使用的

**Comment by beef9999** [comment]
@saffraan 我是在物理机测试，不打算用KNI。打算用Mellanox网卡和DPDK的Flow Bifurcation功能进行硬件分流，也挺方便。

http://doc.dpdk.org/guides/howto/flow_bifurcation.html
