### ISSUE TITLE
Use port 53 while F-stack is running

### ISSUE THREAD

**Issue by h-farrukh** [F-Stack/f-stack#764]
I have a Ubuntu 20.04 VM with 2 NICs, dpdk, f-stack and BIND on it

In config.ini for F-stack , in the KNI portion I have specified

```
# Kni config: if enabled and method=reject,
# all packets that do not belong to the following tcp_port and udp_port
# will transmit to kernel; if method=accept, all packets that belong to
# the following tcp_port and udp_port will transmit to kernel.
[kni]
enable=1
method=reject
# The format is same as port_list
tcp_port=80,8080,443
udp_port=53 
```

This means that packets at these ports will go through the KNI instead of the kernel right?

Now I'm also running Bind DNS on this VM. Which cannot access port 53 now. Does F-stack monopolize these ports? How can packet processing be accelerated if no other process can access these ports?

**Comment by jfb8856606** [comment]
This config means that packets of udp port 53 will process by F-Stack APP, not transmit to linux kernel via kni.

You can comment out this configuration item `udp_port=53`, and it will transmit to linux kernel via kni.
