### ISSUE TITLE
does F-stack supports Stream Control Transmission Protocol(SCTP) in user space?

### ISSUE THREAD

**Issue by DR-NEGATIVE** [F-Stack/f-stack#770]
Hi F-Stack Team,

First of all great work Team, you have done awesome work :-)

Query:
does current f-stack supports SCPT in user space? as I was looking into code I have seen  some SCTP related files but when I went deep into files I haven't seen anything related to dpdk's mbuf mempool etc.

Thanks

**Comment by markman76** [comment]
Hi,
I already posted the "[How to compile SCTP source code files of FreeBSD to F-Stack?](https://github.com/F-Stack/f-stack/issues/730)"
I will continue to analyze the FreeBSD source code for using SCTP.
