### ISSUE TITLE
Failed during "f-stack/lib" make

### ISSUE THREAD

**Issue by idicrc** [F-Stack/f-stack#777]
Using F-Stack v1.23, Ubuntu Host Linux, v22.04 and DPDK v21.11.4
The ../dpdk directory builds just fine...no errors.
When entering ../lib , I run a make and it runs for a while and then exits with an error:
     'opt_atpic.h' ... no such file
     when compiling the freebsd module: machdep.c   ( in .../freebsd/amd64/amd64 )

Has any one seen this?  I checked the entire system and there's no file called "opt_atpic.h".
Is this file supposed to be created by the F-Stack build itself?

Thanks...

**Comment by jfb8856606** [comment]
I will test it in ubuntu 22.04.

**Comment by jfb8856606** [comment]
I did not encounter this build error like you on ubuntu 22.04 (kernel:5.19.0-1025, gcc:11.4.0), but I has fixed some other build errors on ubuntu 22.04 .

Whether it is directly from the github clone code and compiled according to the guidelines, or whether there are other modifications

**Comment by idicrc** [comment]
Mr. Jiang:

 

   Thanks for the information.  I’ve already figured out a way around the problem and have F-Stack working just fine on Ubuntu.

 

   Question: Do you guys have any employment/contract openings?  I’d love to work with you guys!

 

    Cheers, Robert Moore  719-640-4920 (Colorado, US)

**Comment by jfb8856606** [comment]
Hi Robert:

Glad to hear you've solved the problem.

We don't have employment/contract opening at the moment, but community communication and contributions are welcome at any time

Best Regards,
Fengbo Jiang

发件人: Robert Moore ***@***.***>
发送时间: 2023年8月16日 0:11
收件人: F-Stack/f-stack ***@***.***>
抄送: fengbojiang(姜凤波) ***@***.***>; Comment ***@***.***>
主题: [Internet]Re: [F-Stack/f-stack] Failed during "f-stack/lib" make (Issue #777)

Mr. Jiang:



Thanks for the information. I’ve already figured out a way around the problem and have F-Stack working just fine on Ubuntu.



Question: Do you guys have any employment/contract openings? I’d love to work with you guys!



Cheers, Robert Moore 719-640-4920 (Colorado, US)
