### ISSUE TITLE
make error in f-stack/lib

### ISSUE THREAD

**Issue by zuoriqiufeng** [F-Stack/f-stack#778]
when i `sudo make` in f-task/lib, there an error in `ff_sysctl_wrapper.c` file，it showed " error: ‘modoptval’ undeclared (first use in this function) ", and " error: too many arguments to function ‘linux2freebsd_opt’ ", the details refer to the following figure：
![企业微信截图_16899103846451](https://github.com/F-Stack/f-stack/assets/57280161/94c06ba2-97e7-4122-8db8-726816298ee1)

**Comment by hexclover** [comment]
It seems https://github.com/F-Stack/f-stack/pull/775 introduced these errors, but I don't know how to fix it as I have no idea what a cmsg is...
Maybe @jfb8856606 can revert that commit for the time being?

**Comment by Jamlee** [comment]
checkout version from: cbcadd4435e13a4ac778b8ecf32e59aae7aef679. it will be ok
