### ISSUE TITLE
Cannot ping config.ini ip after run helloword

### ISSUE THREAD

**Issue by segment11** [F-Stack/f-stack#783]
tools/sbin/ifconfig

there is a network interface named f-stack-0, show ip configured in config.ini

but I cannot ping the ip

**Comment by jfb8856606** [comment]
1. Check if you config corrected addr/netmask/broadcast in config.ini.
2. Check if you enable kni in config.ini, if enabled kni, Check  if you config corrected addr/netmask/broadcast/MAC, route, carrier=on, etc.
3. Make sure your client is in another machine.

**Comment by segment11** [comment]
Thanks a lot.
It works.
