### ISSUE TITLE
param num_procs[0] or proc_id[0] error!

### ISSUE THREAD

**Issue by alandtsang** [F-Stack/f-stack#8]
I successfully compiled the f-stack and set FF_PATH and FF_DPDK OK. After running the example code, 

./helloworld ../config.ini 

and the following error occurred:
[dpdk]: lcore_mask=3
[dpdk]: channel=4
[dpdk]: nb_ports=1
[dpdk]: promiscuous=1
[dpdk]: numa_on=1
[dpdk]: tso=0
[port0]: addr=192.168.44.129
[port0]: netmask=255.255.255.0
[port0]: broadcast=192.168.44.255
[port0]: gateway=192.168.44.2
[port0]: enable=1
[port0]: udp_port=53
[freebsd.boot]: hz=100
[freebsd.boot]: kern.ipc.maxsockets=262144
[freebsd.boot]: net.inet.tcp.syncache.hashsize=4096
[freebsd.boot]: net.inet.tcp.syncache.bucketlimit=100
[freebsd.boot]: net.inet.tcp.tcbhashsize=65536
[freebsd.sysctl]: kern.ipc.somaxconn=32768
[freebsd.sysctl]: kern.ipc.maxsockbuf=16777216
[freebsd.sysctl]: net.inet.tcp.fast_finwait2_recycle=1
[freebsd.sysctl]: net.inet.tcp.sendspace=16384
[freebsd.sysctl]: net.inet.tcp.recvspace=8192
[freebsd.sysctl]: net.inet.tcp.nolocaltimewait=1
[freebsd.sysctl]: net.inet.tcp.cc.algorithm=htcp
[freebsd.sysctl]: net.inet.tcp.sendbuf_max=16777216
[freebsd.sysctl]: net.inet.tcp.recvbuf_max=16777216
[freebsd.sysctl]: net.inet.tcp.sendbuf_auto=1
[freebsd.sysctl]: net.inet.tcp.recvbuf_auto=1
[freebsd.sysctl]: net.inet.tcp.sendbuf_inc=16384
[freebsd.sysctl]: net.inet.tcp.recvbuf_inc=524288
[freebsd.sysctl]: net.inet.tcp.inflight.enable=0
[freebsd.sysctl]: net.inet.tcp.sack=1
[freebsd.sysctl]: net.inet.tcp.blackhole=1
[freebsd.sysctl]: net.inet.tcp.msl=2000
[freebsd.sysctl]: net.inet.tcp.delayed_ack=0
[freebsd.sysctl]: net.inet.udp.blackhole=1
[freebsd.sysctl]: net.inet.ip.redirect=0
param num_procs[0] or proc_id[0] error!

I debug found getopt_long function return -1, is there any error in my usage? Thanks
```
static void
ff_load_arg(struct ff_config *cfg, int argc, char *const argv[])
{
    dpdk_argc_arg = 0;
    int c;
    int index = 0;
    while((c = getopt_long(argc, argv, short_options, long_options, &index)) != -1) {
        switch (c) {
            case 'c':
                cfg->dpdk.proc_mask = strdup(optarg);
                break;
```

**Comment by whl739** [comment]
Use `./start.sh -b example/helloworld -c config.ini`.

**Comment by alandtsang** [comment]
OK, I see. Thank you
