### ISSUE TITLE
[bug]Run nginx  Wrong

### ISSUE THREAD

**Issue by tigerjibo** [F-Stack/f-stack#81]
Hi : 
   When I update the new code and compile. Run the /usr/local/nginx_fstack/sbin/nginx has wrong!
   Reade the log:
   ```
  port_cfg_handler:muster config dpdk.port_list first 
  ```
  I modify the /usr/local/nginx_fstack/conf/f-stack.conf
 Add the follow config:
 ```
 vlan_strip=1
**+port_list=0**
 ```
then,run the nginx well.

Please fix this bug about  configure file

**Comment by whl739** [comment]
The nginx configuration is out of date. You can copy `config.ini` from the root directory to $NGX_CONF.
And `app/nginx-1.11.10/conf/f-stack.conf` is out of date too, i'll fix it later.

**Comment by tigerjibo** [comment]
It is so good that you response very fast!
