### ISSUE TITLE
Compile Problem about f-stack

### ISSUE THREAD

**Issue by shenjingGitHub** [F-Stack/f-stack#82]
when i make in lib，i met the  error that no openssl/rand.h this file.Has anyone ever had this problem?？？

**Comment by whl739** [comment]
You should install `openssl-devel` first.

**Comment by shenjingGitHub** [comment]
ok!After then,there're another compiling errores.It said that 'struct mbuf' has no member named 'm_ext'' and so on~

**Comment by whl739** [comment]
It is probably due to that your gcc version is too old, upgrade your gcc to 4.8+.
Related to #41.

**Comment by shenjingGitHub** [comment]
I have updated gcc to 4.8.2,but the errores still exist.Are there any other possibilities？Thank u

**Comment by whl739** [comment]
Paste your error informations.

**Comment by shenjingGitHub** [comment]
cc -c -O2 -fno-strict-aliasing -frename-registers -pipe -Wno-maybe-uninitialized   -std=c99  -Wall -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wno-inline -Wcast-qual -Wno-pointer-sign -Wmissing-include-dirs -fdiagnostics-show-option -Wno-unused-but-set-variable -fno-common -finline-limit=8000 --param inline-unit-growth=100 --param large-function-growth=1000  -DFSTACK  -fstack-protector -D__FreeBSD__ -D_KERNEL -DHAVE_KERNEL_OPTION_HEADERS -include opt_global.h -fno-builtin -I/home/shenjing/f-stack-master/lib/include -undef -imacros filtered_predefined_macros.h -nostdinc  -I. -I/home/shenjing/f-stack-master/lib/../freebsd -I./machine_include -I./opt -Werror -Wno-unused-variable  ff_glue.c
cc1: warnings being treated as errors
In file included from ff_glue.c:50:
/home/shenjing/f-stack-master/lib/../freebsd/sys/buf.h:130: error: declaration does not declare anything
/home/shenjing/f-stack-master/lib/../freebsd/sys/buf.h:131: error: declaration does not declare anything
In file included from ff_glue.c:53:
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:192: error: declaration does not declare anything
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:219: error: declaration does not declare anything
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:224: error: declaration does not declare anything
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:246: error: declaration does not declare anything
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:247: error: declaration does not declare anything
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:249: error: declaration does not declare anything
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'm_extaddref':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:659: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:660: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:661: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:662: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:663: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:664: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:665: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:666: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:667: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'm_init':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:709: error: 'struct mbuf' has no member named 'm_next'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:710: error: 'struct mbuf' has no member named 'm_nextpkt'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:711: error: 'struct mbuf' has no member named 'm_dat'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'm_cljset':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:793: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:794: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:794: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:794: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:795: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:796: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:797: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:798: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'm_clrprotoflags':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:816: error: 'struct mbuf' has no member named 'm_next'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'm_last':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:824: error: 'struct mbuf' has no member named 'm_next'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:825: error: 'struct mbuf' has no member named 'm_next'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'm_extrefcnt':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:835: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:835: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:836: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'm_align':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:914: error: 'struct mbuf' has no member named 'm_ext'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:914: error: 'struct mbuf' has no member named 'm_pktdat'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:914: error: 'struct mbuf' has no member named 'm_dat'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'm_tag_init':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1087: error: 'struct mbuf' has no member named 'm_pkthdr'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'm_tag_first':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1122: error: 'struct mbuf' has no member named 'm_pkthdr'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'm_tag_prepend':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1142: error: 'struct mbuf' has no member named 'm_pkthdr'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1142: error: 'struct mbuf' has no member named 'm_pkthdr'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'm_tag_unlink':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1152: error: 'struct mbuf' has no member named 'm_pkthdr'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1152: error: 'struct mbuf' has no member named 'm_pkthdr'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1152: error: 'struct mbuf' has no member named 'm_pkthdr'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1152: error: 'struct mbuf' has no member named 'm_pkthdr'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'm_tag_find':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1167: error: 'struct mbuf' has no member named 'm_pkthdr'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'm_free':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1174: error: 'struct mbuf' has no member named 'm_next'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'rt_m_getfib':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1190: error: 'struct mbuf' has no member named 'm_pkthdr'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'mbufq_drain':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1249: error: 'struct mbuf' has no member named 'm_stailqpkt'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'mbufq_last':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1265: error: 'struct mbuf' has no member named 'm_stailqpkt'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1265: error: type defaults to 'int' in declaration of '__x'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1265: error: initialization from incompatible pointer type
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1265: error: 'struct mbuf' has no member named 'm_stailqpkt'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'mbufq_enqueue':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1288: error: 'struct mbuf' has no member named 'm_stailqpkt'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1288: error: 'struct mbuf' has no member named 'm_stailqpkt'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'mbufq_dequeue':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1300: error: 'struct mbuf' has no member named 'm_stailqpkt'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1301: error: 'struct mbuf' has no member named 'm_nextpkt'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h: In function 'mbufq_prepend':
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1311: error: 'struct mbuf' has no member named 'm_stailqpkt'
/home/shenjing/f-stack-master/lib/../freebsd/sys/mbuf.h:1311: error: 'struct mbuf' has no member named 'm_stailqpkt'
At top level:
cc1: error: unrecognized command line option "-Wno-maybe-uninitialized"

**Comment by whl739** [comment]
Obviously, this is the old version of gcc.

**Comment by shenjingGitHub** [comment]
So strange！when i use the command gcc -v,it said that the gcc version is 4.8.2.Should I update the version?

**Comment by whl739** [comment]
What does `cc -v` output?

**Comment by shenjingGitHub** [comment]
oh no! it's old version

**Comment by whl739** [comment]
It's a soft link, you can just link to the newer version.

**Comment by shenjingGitHub** [comment]
ok i know!thank u very much!

**Comment by shenjingGitHub** [comment]
Another compling error! Wish to hear from you~
cc -c -O2 -frename-registers  -funswitch-loops -fweb -Wall -Werror -include /home/shenjing/f-stack-master/dpdk/x86_64-native-linuxapp-gcc//include/rte_config.h -march=native -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2 -I/home/shenjing/f-stack-master/dpdk/x86_64-native-linuxapp-gcc//include  -I. -Werror -Wno-unused-variable  ff_config.c
/tmp/ccBuZ6h4.s: Assembler messages:
/tmp/ccBuZ6h4.s:1175: Error: no such instruction: `shlx %ebp,%esi,%edx'
make: *** [ff_config.o] Error 1

**Comment by whl739** [comment]
Try to upgrade `binutils`.
