### ISSUE TITLE
Does it support multi-core operation?

### ISSUE THREAD

**Issue by tianxuanhong** [F-Stack/f-stack#840]
I found that no matter how many cores are configured in lcore_mask, ff_dpdk_init will be started with the first lcore in dpdk_args_setup. I modified it to -cf, that is, it starts with 4 cores. I found that the following error was reported, which seems to be an error in the driver code of the NVIDIA chip.
  mlx5_net: Cannot change Tx QP state to RTR Invalid argument
  mlx5_net: Cannot change Tx QP state to INIT Invalid argument
        May I ask, do we support the operation of multiple lcores? How should I use it? Thank you very much

**Comment by mayank-bhushan** [comment]
@tianxuanhong Hi, how did you solve the multiple lcores issue?
