### ISSUE TITLE
What's the necessary requirement before installing f-stack

### ISSUE THREAD

**Issue by crazy-william** [F-Stack/f-stack#85]
1.system(os,memory)
2.library
3.network driver

Expect for your answer, thanks!

**Comment by whl739** [comment]
1. Linux kernel 3.10+, gcc 4.8+, maybe the older version works fine, but we didn't test on it.
support hugepage and better support numa.
2. Libraries: openssl-devel, kernel-devel-$(uname -r)
3. Supported Nics: http://dpdk.org/doc/nics

**Comment by crazy-william** [comment]
I compile it at CentOS 7.3 in VMWARE hosted on MacOS, compile failed.
```
kernel:3.10.0-693.2.2
gcc:4.8.5
```
I don't know the reason.
I will make it again.
Thanks a lot.

**Comment by whl739** [comment]
You can paste your error information here.
