### ISSUE TITLE
 ./start.sh -b /usr/local/nginx_fstack/sbin/nginx -c ./config.ini get nginx: invalid option: "-"

### ISSUE THREAD

**Issue by vincentmli** [F-Stack/f-stack#87]
Hi

I cloned the most recent f-stack, compile and installed on Ubuntu 16.04.3 following the instruction, but I got error when starting nginx', the config.ini is default coming from f-stack, nothing changed

root@compute1:/home/vincent/f-stack#  ./start.sh -b /usr/local/nginx_fstack/sbin/nginx -c config.ini
/usr/local/nginx_fstack/sbin/nginx --conf config.ini --proc-type=primary --proc-id=0
nginx: invalid option: "-"

**Comment by vincentmli** [comment]
it looks  ./start.sh -b /usr/local/nginx_fstack/sbin/nginx -c config.ini is the wrong way to start nginx, the start.sh will give nginx --conf argument that nginx does not recognize. I could startup ngnix by just run /usr/local/nginx_fstack/sbin/nginx, the journal log has log below:

Oct 09 18:02:38 compute1 f-stack[31218]: EAL: PCI device 0000:01:00.0 on NUMA socket 0
Oct 09 18:02:38 compute1 f-stack[31218]: EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
Oct 09 18:02:38 compute1 f-stack[31218]: EAL: PCI device 0000:01:00.1 on NUMA socket 0
Oct 09 18:02:38 compute1 f-stack[31218]: EAL:   probe driver: 8086:10fb rte_ixgbe_pmd

I assume nginx is attached DPDK port properly, correct?

root@compute1:/home/vincent/f-stack/app/nginx-1.11.10# ps -ef | grep nginx
root     31714     1  0 18:11 ?        00:00:00 nginx: master process /usr/local/nginx_fstack/sbin/nginx
root     31715 31714 81 18:11 ?        00:00:02 nginx: worker process

the linux utility like netstat would not tell if nginx is listening on ip 192.168.1.2, which I guess is normal because netstat only has visibility to the linux socket, not the f-stack socket, is there any plan to port linux utility like netstat to f-stack ?

**Comment by vincentmli** [comment]
sorry, just found netstat under tools directory 

root@compute1:/home/vincent/f-stack/tools# ./netstat/netstat -an
EAL: WARNING: Address Space Layout Randomization (ASLR) is enabled in the kernel.
EAL:    This may cause issues with mapping memory into secondary processes
Active Internet connections (including servers)
Proto Recv-Q Send-Q Local Address          Foreign Address        (state)
tcp4       0      0 *.80                   *.*                    LISTEN
udp4       0      0 *.*                    *.*

**Comment by whl739** [comment]
`nginx` no longer needs to start with `start.sh`, just use `/usr/local/nginx_fstack/sbin/nginx`.

**Comment by vincentmli** [comment]
thank you! I tested the nginx, it works great!
