### ISSUE TITLE
add trace or debug facility in ff-stack lib?

### ISSUE THREAD

**Issue by vincentmli** [F-Stack/f-stack#88]
Hi

I am running on Ubuntu 16.04.3. when nginx is started, the only log I can see is:

Oct 10 11:54:32 compute1 f-stack[1550]: EAL: PCI device 0000:01:00.0 on NUMA socket 0
Oct 10 11:54:32 compute1 f-stack[1550]: EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
Oct 10 11:54:32 compute1 f-stack[1550]: EAL: PCI device 0000:01:00.1 on NUMA socket 0
Oct 10 11:54:32 compute1 f-stack[1550]: EAL:   probe driver: 8086:10fb rte_ixgbe_pmd

I could not see the printf messages in lib/ff_dpdk_init() and init_port_start()/check_all_ports_link_status()...

maybe I am missing something, I would like to see these messages either logged in syslog or console so I get rough idea about the DPDK port informations. could DPDK rte_log facilities used or separate log/debug utilities used for these printf messages for tracing/debugging purpose?

**Comment by whl739** [comment]
Since nginx starts with daemon, it will close stdout, these messages coudn't be printed, so you can start nginx with `daemon off;`.

**Comment by vincentmli** [comment]
great, thanks!
