### ISSUE TITLE
Any plan to create a network daemon based on DPDK?

### ISSUE THREAD

**Issue by leon-shi** [F-Stack/f-stack#90]
The F-Stack is still target to be a library for 2nd development, but the disadvantage is the function comes with the application start and lost after the application exit.
For example, if I want to use the keepalived via kni to create a HA system, but keepalived cannot works with the application well if the application exit, since the nic is lost.

So why not create a userspace network-deamon based on DPDK, and which may using ring to communicate with application, the API can be provided to be Linux socket like. This daemon may starts with OS boots, which takeover the network management instead of Linux.

Any thoughts?

Thanks!

**Comment by whl739** [comment]
We also thought about this,  but there's no much time to do it. 
Pull requests are wanted.

**Comment by gocamero** [comment]
You may want to check out fd.io/vpp from cisco. Its tcpip stack is still
experimental though.

Jin
