### ISSUE TITLE
Compile error in centos 7.4, may be dpdk version is too low.

### ISSUE THREAD

**Issue by jlijian3** [F-Stack/f-stack#91]
librte_eal/linuxapp/kni/igb_main.c:2316:2: error: unknown field ‘ndo_set_vf_vlan’ specified in initializer

centos 7.4 kernel 3.10.0-693.el7.x86_64 has ported some features from official kernel 4.x.

**Comment by whl739** [comment]
Well, the version of dpdk used by F-Stack is 16.07, there may be some bugs with newer kernels.
This may be related to your issuse: http://dpdk.org/dev/patchwork/patch/16651/, you can apply this patch, and try again.
