### ISSUE TITLE
About the nginx cps test

### ISSUE THREAD

**Issue by leon-shi** [F-Stack/f-stack#93]
I am trying to test the f-stack nginx, but only got 400000/s CPS with following setups:
- X540 AT2 NIC
- E5-2670 v1
- 1 test client running multiple wrk instance
- 16 cores configured on server side

I have couples of question:
1. I found if I configure more than 16 cpu cores in f-stack.conf, the CPS
drop down, since X540 NIC RSS only support 16 queues, it makes sense to have maximum 16 cpu cores assigned(RunToComplete Mode), but strange thing is why the CPS drops down if have more than 16 cores configured? 
2. I saw the nginx test result in the README, there is a 20 core test scenario, is it because XL710 NIC
have more queues for RSS?
3. How is the test bed setup in your test for nginx to reach the 1millon/s CPS? I am not going further on the test, but now with 1 test client(wrk with Connection: close header set), I only got 400000/s CPS.

Thanks in advance!

**Comment by whl739** [comment]
1. As i know, if configured more than RSS limit, there may be a problem. As for the reason of the decrease of permance, i'm not quiet sure.
2. Yes, XL710 has 64 RSS queues.
3. Only one test client coudn't get best performance, because only 65536 ports can be used for tcp connections at most and the PCB locks in kernel will harm the performance. So you should use multiple machines.

**Comment by leon-shi** [comment]
I see, thanks! I will try more clients machines, reason I am strange is even I give 2,4 cores to nginx workers(still with 1 client machine), still have big gap compare with the number in the README...with 2 cores, 1 client should be fine, since if I give 4 cores, the CPS is double in my test.
Anyway I will try more clients and post my number then.

Thanks.

**Comment by whl739** [comment]
The performance(connection:close) in README is tested with the following configurations:
```
error_log /dev/null;
access_log off;
keepalive_timeout  0;
location / {
    return 200 'xxxxxxxx'; #600 bytes;
}
```
