### ISSUE TITLE
Performance decreased on a simple DNS server.

### ISSUE THREAD

**Issue by zhuyuhui97** [F-Stack/f-stack#96]
Hi f-stack team. I'm working on porting a simple DNS server to the f-stack platform and hoping to get a better performance on f-stack than Linux network stack. 
The original simple DNS server responds UDP DNS requests using a blocking `recvfrom` and `sendto` function in a while loop. But we found that if we use a blocked `ff_recvfrom` in the `ff_run` callback function, the F-Stack will not respond to any protocols which is necessary for the network such as ARP and ICMP, so we used `ff_fcntl` to set the socket fd nonblocking. If the app found that `ff_recvfrom` didn't receive anything, it will continue and go to the next while loop. 
I used queryperf in bind to test the performance, and I found that the performance decreased a lot.

test result of F-Stack app
> ./queryperf -d test.txt -s 192.168.2.250 -p 9000
>
>DNS Query Performance Testing Tool
>Version: $Id: queryperf.c,v 1.12 2007/09/05 07:36:04 marka Exp $
>
>[Status] Processing input data
>[Status] Sending queries (beginning with 192.168.2.250)
>[Status] Testing complete
>
>Statistics:
>
>  Parse input file:     once
>  Ended due to:         reaching end of file
>
>  Queries sent:         569216 queries
>  Queries completed:    569216 queries
>  Queries lost:         0 queries
>  Queries delayed(?):   0 queries
>
>  RTT max:         	0.008111 sec
>  RTT min:              0.000050 sec
>  RTT average:          0.000299 sec
>  RTT std deviation:    0.000195 sec
>  RTT out of range:     0 queries
>
>  Percentage completed: 100.00%
>  Percentage lost:        0.00%
>
>  Started at:           Sat Oct 28 18:15:27 2017
>  Finished at:          Sat Oct 28 18:15:37 2017
>  Ran for:              9.788022 seconds
>
>  Queries per second:   58154.344157 qps

test result of Linux socket app

> ./queryperf -d test.txt -s 192.168.3.250 -p 9000 
>
>DNS Query Performance Testing Tool
>Version: $Id: queryperf.c,v 1.12 2007/09/05 07:36:04 marka Exp $
>
>[Status] Processing input data
>[Status] Sending queries (beginning with 192.168.3.250)
>[Status] Testing complete
>
>Statistics:
>
>  Parse input file:     once
>  Ended due to:         reaching end of file
>
>  Queries sent:         569216 queries
>  Queries completed:    569216 queries
>  Queries lost:         0 queries
>  Queries delayed(?):   0 queries
>
>  RTT max:         	0.000751 sec
>  RTT min:              0.000022 sec
>  RTT average:          0.000077 sec
>  RTT std deviation:    0.000032 sec
>  RTT out of range:     0 queries
>
>  Percentage completed: 100.00%
>  Percentage lost:        0.00%
>
>  Started at:           Sat Oct 28 19:25:48 2017
>  Finished at:          Sat Oct 28 19:25:50 2017
>  Ran for:              2.884685 seconds
>
>  Queries per second:   197323.451261 qps

So why the performance decreased? What can be the bottleneck? Do you have any idea?

**Comment by zhuyuhui97** [comment]
This is my config.ini, nearly same as the one provided with the source code.

> [dpdk]
>lcore_mask=2
>channel=4
>promiscuous=0
>numa_on=1
>tso=0
>vlan_strip=0
>
>port_list=0
>
>[port0]
>addr=192.168.2.250
>netmask=255.255.255.0
>broadcast=192.168.2.255
>gateway=192.168.2.1
>
>[freebsd.boot]
>hz=100
>
>fd_reserve=1024
>
>kern.ipc.maxsockets=262144
>
>net.inet.tcp.syncache.hashsize=4096
>net.inet.tcp.syncache.bucketlimit=100
>
>net.inet.tcp.tcbhashsize=65536
>
>[freebsd.sysctl]
>kern.ipc.somaxconn=32768
>kern.ipc.maxsockbuf=16777216
>
>net.inet.tcp.fast_finwait2_recycle=1
>net.inet.tcp.sendspace=16384
>net.inet.tcp.recvspace=8192
>net.inet.tcp.nolocaltimewait=1
>net.inet.tcp.cc.algorithm=cubic
>net.inet.tcp.sendbuf_max=16777216
>net.inet.tcp.recvbuf_max=16777216
>net.inet.tcp.sendbuf_auto=1
>net.inet.tcp.recvbuf_auto=1
>net.inet.tcp.sendbuf_inc=16384
>net.inet.tcp.recvbuf_inc=524288
>net.inet.tcp.sack.enable=1
>net.inet.tcp.blackhole=1
>net.inet.tcp.msl=2000
>net.inet.tcp.delayed_ack=0
>
>net.inet.udp.blackhole=1
>net.inet.ip.redirect=0

**Comment by whl739** [comment]
There's  a bug of `ff_fcntl`, use `int on = 1;ff_ioctl(sockfd, FIONBIO, &on);` instead.
I didn't do any UDP performance test, so i'm not sure about the performance of UDP.

**Comment by zhuyuhui97** [comment]
Thanks for your reply.
I know the bug and I use `ff_fcntl(sock, F_SETFL, 4)` to set the socket to be nonblocking, and the issue is not about the bug of `ff_fcntl`.
My code call `recvfrom` for only one time in callback function, which retrieves only one packet from the UDP socket and may not drain receive queue. And the outer `mainloop()` defined in `ff_dpdk_if.c` will process many other things about the network stack which takes too much time. So the right solution is use a while loop in the loop callback to drain rx queue. I finally got 163806.422965 qps using new code. It is much better but still not good enough, so I will keep working on this.

**Comment by whl739** [comment]
For DNS server,  we usually recommend to process `rte_mbuf` directly, and do not enter network stack.
This will get the best performance.

**Comment by zhuyuhui97** [comment]
I see.
And I have another two questions.

1.  F-stack drain tx queue, read packets from rx queue, process arp ring and run user's callback serially in `main_loop()`, Will f-stack support running network stack on a single thread and run user's code on another thread launched on separate lcores?
2.  I found that if I use more than 1 lcores, the start script launch mutiple processes but only one of them will reply to requests in a time period. Is it ok?
My config file is
>[dpdk]
>lcore_mask=2
>channel=4
>promiscuous=0
>numa_on=1
>tso=0
>vlan_strip=0
>port_list=0
>[port0]
>addr=192.168.2.250
>netmask=255.255.255.0
>broadcast=192.168.2.255
>gateway=192.168.2.1

Other parts are the same as the default one.

**Comment by whl739** [comment]
We didn't support yet.
Your idea is similar with #90(run f-stack as a network daemon).
We'd like to do it in the future.

**Comment by zhuyuhui97** [comment]
Do you have any idea about the second question?

**Comment by whl739** [comment]
`lcore_mask=2` means run one process on CPU 1.
If you want to run 2/4/8 processes, you can set it to 3/f/fff.

**Comment by zhuyuhui97** [comment]
Oh I posted the wrong one. I set `lcore_mask` to 3 and ran `queryperf`. I printed PID in loop callback and I found it printed all the same number. Then I reran `queryperf` , sometimes the printed PID became another one, and sometimes it kept unchanged.

**Comment by whl739** [comment]
It seems that `queryperf` used specific ports, then RSS hashes were always same, packets were sent to the fixed process. 
You can use `netstat` to figure out how many ports does `queryperf` use in the client side.

**Comment by asadal12** [comment]
@zhuyuhui97 hello, i am interested to know, which DNS server are you using to port it to f-stack?
