### ISSUE TITLE
can not use more than 4 cores for nginx

### ISSUE THREAD

**Issue by imamandacerny** [F-Stack/f-stack#97]
can not use more than 4 cores for nginx
i try lcore_mask to 0xfff and 0xff, but nginx can't be work normally .
but set lcore_mask to 0xf, nginx can work normally.

nginx error.log

Tailq 25: qname:<>, tqh_first:(nil), tqh_last:(nil)
Tailq 26: qname:<>, tqh_first:(nil), tqh_last:(nil)
Tailq 27: qname:<>, tqh_first:(nil), tqh_last:(nil)
Tailq 28: qname:<>, tqh_first:(nil), tqh_last:(nil)
Tailq 29: qname:<>, tqh_first:(nil), tqh_last:(nil)
Tailq 30: qname:<>, tqh_first:(nil), tqh_last:(nil)
Tailq 31: qname:<>, tqh_first:(nil), tqh_last:(nil)
2017/11/08 06:32:25 [alert] 26026#0: worker process 26106 exited on signal 6
2017/11/08 06:32:25 [alert] 26026#0: worker process 26108 exited on signal 6
2017/11/08 06:32:25 [alert] 26026#0: worker process 26107 exited on signal 6

**Comment by whl739** [comment]
Are there any coredump files? Try gdb to see where it exited on.
Possible reasons:
- You have only 4 cores.
- Nic's max rx queue is 4.

**Comment by imamandacerny** [comment]
no any coredump files find
can send me your mail address to my maill?
i can send you my server ssh login info
you can debug in my server
