### ISSUE TITLE
link error 

### ISSUE THREAD

**Issue by power4** [F-Stack/f-stack#99]
我使用的是虚拟机，环境如下:

[root@localhost lib]# gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
[root@localhost lib]# uname -a
Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

编译都正常，连接redis，或者exmaple的时，出现如下错误，

cc -O -gdwarf-2  -I../lib -o "helloworld" main.c -L/work/f-stack/lib -L/work/f-stack/dpdk/x86_64-native-linuxapp-gcc/lib -Wl,--whole-archive,-lfstack,--no-whole-archive -Wl,--whole-archive -lrte_pmd_vmxnet3_uio -lrte_pmd_i40e -lrte_pmd_ixgbe -lrte_pmd_e1000 -lrte_pmd_ring -Wl,--whole-archive -lrte_hash -lrte_kvargs -Wl,-lrte_mbuf -lethdev -lrte_eal -Wl,-lrte_mempool -lrte_ring -lrte_cmdline -lrte_cfgfile -lrte_kni -lrte_timer -Wl,-lrte_pmd_virtio -Wl,--no-whole-archive -lrt -lm -ldl -lcrypto -pthread
/work/f-stack/lib/libfstack.a(libfstack.ro)：在函数‘counter_u64_zero’中：
uma_core.c:(.text+0x1fa41)：对‘smp_no_rendevous_barrier’未定义的引用
uma_core.c:(.text+0x1fa51)：对‘smp_rendezvous’未定义的引用
/work/f-stack/lib/libfstack.a(libfstack.ro)：在函数‘counter_u64_alloc’中：
uma_core.c:(.text+0x1faba)：对‘smp_no_rendevous_barrier’未定义的引用
uma_core.c:(.text+0x1faca)：对‘smp_rendezvous’未定义的引用
/work/f-stack/lib/libfstack.a(libfstack.ro)：在函数‘sysctl_handle_counter_u64’中：
uma_core.c:(.text+0x1fb65)：对‘smp_no_rendevous_barrier’未定义的引用
uma_core.c:(.text+0x1fb76)：对‘smp_rendezvous’未定义的引用
/work/f-stack/lib/libfstack.a(libfstack.ro)：在函数‘sysctl_handle_counter_u64_array’中：
uma_core.c:(.text+0x1fc56)：对‘smp_no_rendevous_barrier’未定义的引用
uma_core.c:(.text+0x1fc67)：对‘smp_rendezvous’未定义的引用
/work/f-stack/lib/libfstack.a(libfstack.ro)：在函数‘if_transmit’中：
if.c:(.text+0x3d134)：对‘__pcpu’未定义的引用
if.c:(.text+0x3d14b)：对‘__pcpu’未定义的引用
if.c:(.text+0x3d17f)：对‘__pcpu’未定义的引用
/work/f-stack/lib/libfstack.a(libfstack.ro)：在函数‘if_inc_counter’中：
uma_core.c:(.text+0x3e50c)：对‘__pcpu’未定义的引用
/work/f-stack/lib/libfstack.a(libfstack.ro)：在函数‘if_handoff’中：
uma_core.c:(.text+0x40ea6)：对‘__pcpu’未定义的引用
/work/f-stack/lib/libfstack.a(libfstack.ro):uma_core.c:(.text+0x40f0a): more undefined references to `__pcpu' follow
collect2: 错误：ld 返回 1
make: *** [all] 错误 1

请问这个应该如何着手解决

**Comment by whl739** [comment]
You must have copied the codes from windows, `lib/include/machine` is a soft link, but when on windows, it will become a file. Rebuild the soft link.
```
cd lib/include
ln -s amd64/include machine
```

By the way, i really suggest you create your issue with english, that  people all around the world can understand it.

**Comment by power4** [comment]
oh，it's fail miserably in a very easy task. thank u!
